// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLc-TQhQo1BXkycLaAiy7kS_l05HDotXs',
    appId: '1:1037354312933:web:971ad83cd8ae0c8b28200c',
    messagingSenderId: '1037354312933',
    projectId: 'nova-acedemy',
    authDomain: 'nova-acedemy.firebaseapp.com',
    storageBucket: 'nova-acedemy.firebasestorage.app',
    measurementId: 'G-BEHNC3YYN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ3SesmK2qEBwOTBvLAn6yBAv5Qmie9LI',
    appId: '1:1037354312933:android:481477e6d4721e3128200c',
    messagingSenderId: '1037354312933',
    projectId: 'nova-acedemy',
    storageBucket: 'nova-acedemy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbrXpaVKd9MmW6mn9swAqMkrrB4_AsI38',
    appId: '1:1037354312933:ios:82269362f0dcc54328200c',
    messagingSenderId: '1037354312933',
    projectId: 'nova-acedemy',
    storageBucket: 'nova-acedemy.firebasestorage.app',
    iosBundleId: 'com.novaacademy.novaAcademy',
  );
}
