import '../../models/child_model.dart';
import 'nursery_activity_kind.dart';

/// One concept in a Memory Challenge deck. At render time each pair becomes
/// two face-down cards sharing this same [id]; matching them together wins
/// the pair. Plain Dart, same hand-authored-content convention as
/// `MatchPairItem` in `nursery_kg_activity_bank.dart`.
class MemoryPairItem {
  const MemoryPairItem({
    required this.id,
    required this.emoji,
    required this.colorValue,
    required this.labelEn,
    required this.labelMy,
  });

  final String id;
  final String emoji;
  final int colorValue;
  final String labelEn;
  final String labelMy;

  String label(String languageCode) => languageCode == 'my' ? labelMy : labelEn;
}

class NurseryMemoryDef {
  const NurseryMemoryDef({
    required this.id,
    required this.subject,
    required this.grade,
    required this.titleEn,
    required this.titleMy,
    required this.descriptionEn,
    required this.descriptionMy,
    required this.starsReward,
    required this.emoji,
    required this.pairs,
  });

  final String id;
  final String subject;
  final Grade grade;
  final String titleEn;
  final String titleMy;
  final String descriptionEn;
  final String descriptionMy;
  final int starsReward;
  final String emoji;
  final List<MemoryPairItem> pairs;

  static const kind = NurseryActivityKind.memory;
}

const List<MemoryPairItem> fallbackMemoryPairs = [
  MemoryPairItem(
    id: 'sun',
    emoji: '☀️',
    colorValue: 0xFFFFC93C,
    labelEn: 'Sun',
    labelMy: 'နေ',
  ),
  MemoryPairItem(
    id: 'moon',
    emoji: '🌙',
    colorValue: 0xFF7271F7,
    labelEn: 'Moon',
    labelMy: 'လ',
  ),
  MemoryPairItem(
    id: 'star',
    emoji: '⭐',
    colorValue: 0xFFFF8A3D,
    labelEn: 'Star',
    labelMy: 'ကြယ်',
  ),
  MemoryPairItem(
    id: 'cloud',
    emoji: '☁️',
    colorValue: 0xFF4CB6FF,
    labelEn: 'Cloud',
    labelMy: 'မိုးတိမ်',
  ),
];

NurseryMemoryDef? memoryDefForModule(String moduleId) {
  for (final def in nurseryKgMemoryBank) {
    if (def.id == moduleId) return def;
  }
  return null;
}

const List<NurseryMemoryDef> nurseryKgMemoryBank = [
  NurseryMemoryDef(
    id: 'mock-nursery-memory-numbers-1',
    subject: 'math',
    grade: Grade.nursery,
    titleEn: 'Number Match',
    titleMy: 'ဂဏန်း တွဲစုံရှာဂိမ်း',
    descriptionEn: 'Flip cards to find matching number pairs from 1 to 4.',
    descriptionMy: '၁ မှ ၄ အထိ ဂဏန်းတွဲစုံများကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 8,
    emoji: '🔢',
    pairs: [
      MemoryPairItem(
        id: 'num-1',
        emoji: '1️⃣',
        colorValue: 0xFFFF7F91,
        labelEn: 'One',
        labelMy: 'တစ်',
      ),
      MemoryPairItem(
        id: 'num-2',
        emoji: '2️⃣',
        colorValue: 0xFF7271F7,
        labelEn: 'Two',
        labelMy: 'နှစ်',
      ),
      MemoryPairItem(
        id: 'num-3',
        emoji: '3️⃣',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Three',
        labelMy: 'သုံး',
      ),
      MemoryPairItem(
        id: 'num-4',
        emoji: '4️⃣',
        colorValue: 0xFF4CB963,
        labelEn: 'Four',
        labelMy: 'လေး',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-phonics-1',
    subject: 'phonics',
    grade: Grade.nursery,
    titleEn: 'Letter Friends',
    titleMy: 'အက္ခရာ မိတ်ဆွေများ',
    descriptionEn: 'Flip cards to find matching letter-sound picture pairs.',
    descriptionMy: 'အက္ခရာအသံ ပုံစံတွဲစုံများကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 8,
    emoji: '🔤',
    pairs: [
      MemoryPairItem(
        id: 'letter-a',
        emoji: '🍎',
        colorValue: 0xFFE64545,
        labelEn: 'Apple',
        labelMy: 'ပန်းသီး',
      ),
      MemoryPairItem(
        id: 'letter-b',
        emoji: '⚽',
        colorValue: 0xFF7271F7,
        labelEn: 'Ball',
        labelMy: 'ဘောလုံး',
      ),
      MemoryPairItem(
        id: 'letter-c',
        emoji: '🐱',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Cat',
        labelMy: 'ကြောင်',
      ),
      MemoryPairItem(
        id: 'letter-d',
        emoji: '🐶',
        colorValue: 0xFFB5B557,
        labelEn: 'Dog',
        labelMy: 'ခွေး',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-numbers-1',
    subject: 'math',
    grade: Grade.kg,
    titleEn: 'Counting Pairs',
    titleMy: 'ရေတွက် တွဲစုံများ',
    descriptionEn: 'Flip cards to find matching number pairs from 1 to 6.',
    descriptionMy: '၁ မှ ၆ အထိ ဂဏန်းတွဲစုံများကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 10,
    emoji: '🔢',
    pairs: [
      MemoryPairItem(
        id: 'num-1',
        emoji: '1️⃣',
        colorValue: 0xFFFF7F91,
        labelEn: 'One',
        labelMy: 'တစ်',
      ),
      MemoryPairItem(
        id: 'num-2',
        emoji: '2️⃣',
        colorValue: 0xFF7271F7,
        labelEn: 'Two',
        labelMy: 'နှစ်',
      ),
      MemoryPairItem(
        id: 'num-3',
        emoji: '3️⃣',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Three',
        labelMy: 'သုံး',
      ),
      MemoryPairItem(
        id: 'num-4',
        emoji: '4️⃣',
        colorValue: 0xFF4CB963,
        labelEn: 'Four',
        labelMy: 'လေး',
      ),
      MemoryPairItem(
        id: 'num-5',
        emoji: '5️⃣',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Five',
        labelMy: 'ငါး',
      ),
      MemoryPairItem(
        id: 'num-6',
        emoji: '6️⃣',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Six',
        labelMy: 'ခြောက်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-phonics-1',
    subject: 'phonics',
    grade: Grade.kg,
    titleEn: 'Animal Sound Pairs',
    titleMy: 'တိရစ္ဆာန် အသံ တွဲစုံများ',
    descriptionEn: 'Flip cards to find each animal\'s matching pair.',
    descriptionMy: 'တိရစ္ဆာန်တစ်ကောင်စီ၏ တွဲစုံကတ်ကို ရှာပါ။',
    starsReward: 10,
    emoji: '🐾',
    pairs: [
      MemoryPairItem(
        id: 'animal-elephant',
        emoji: '🐘',
        colorValue: 0xFF94BDFF,
        labelEn: 'Elephant',
        labelMy: 'ဆင်',
      ),
      MemoryPairItem(
        id: 'animal-fish',
        emoji: '🐟',
        colorValue: 0xFFFF6A65,
        labelEn: 'Fish',
        labelMy: 'ငါး',
      ),
      MemoryPairItem(
        id: 'animal-lion',
        emoji: '🦁',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Lion',
        labelMy: 'ခြင်္သေ့',
      ),
      MemoryPairItem(
        id: 'animal-monkey',
        emoji: '🐵',
        colorValue: 0xFFB5734A,
        labelEn: 'Monkey',
        labelMy: 'မျောက်',
      ),
      MemoryPairItem(
        id: 'animal-rabbit',
        emoji: '🐰',
        colorValue: 0xFFFFFFFF,
        labelEn: 'Rabbit',
        labelMy: 'ယုန်',
      ),
      MemoryPairItem(
        id: 'animal-frog',
        emoji: '🐸',
        colorValue: 0xFF4CB963,
        labelEn: 'Frog',
        labelMy: 'ဖား',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-stem-1',
    subject: 'stem',
    grade: Grade.nursery,
    titleEn: 'Floats or Sinks',
    titleMy: 'မျောနေသလား၊ နစ်နေသလား',
    descriptionEn:
        'Flip cards to find matching pairs of things that float or sink in water.',
    descriptionMy:
        'ရေပေါ်မျောနေသည့် သို့မဟုတ် ရေထဲနစ်နေသည့် အရာများကို ကတ်များလှန်ပြီး တွဲစုံရှာပါ။',
    starsReward: 7,
    emoji: '💧',
    pairs: [
      MemoryPairItem(
        id: 'boat',
        emoji: '🛶',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Boat',
        labelMy: 'လှေ',
      ),
      MemoryPairItem(
        id: 'leaf',
        emoji: '🍃',
        colorValue: 0xFF4CB963,
        labelEn: 'Leaf',
        labelMy: 'အရွက်',
      ),
      MemoryPairItem(
        id: 'rock',
        emoji: '🪨',
        colorValue: 0xFFB5B557,
        labelEn: 'Rock',
        labelMy: 'ကျောက်တုံး',
      ),
      MemoryPairItem(
        id: 'key',
        emoji: '🔑',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Key',
        labelMy: 'သော့',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-stem-1',
    subject: 'stem',
    grade: Grade.kg,
    titleEn: 'Magnet Match',
    titleMy: 'သံလိုက် တွဲစုံရှာဂိမ်း',
    descriptionEn:
        'Flip cards to find matching pairs of things a magnet can pull.',
    descriptionMy:
        'သံလိုက်ဆွဲနိုင်သော အရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '🧲',
    pairs: [
      MemoryPairItem(
        id: 'nail',
        emoji: '🔩',
        colorValue: 0xFFB5B557,
        labelEn: 'Nail',
        labelMy: 'သံချွန်',
      ),
      MemoryPairItem(
        id: 'paperclip',
        emoji: '📎',
        colorValue: 0xFF7271F7,
        labelEn: 'Paperclip',
        labelMy: 'စာချိတ်',
      ),
      MemoryPairItem(
        id: 'spoon',
        emoji: '🥄',
        colorValue: 0xFF94BDFF,
        labelEn: 'Spoon',
        labelMy: 'ဇွန်း',
      ),
      MemoryPairItem(
        id: 'key',
        emoji: '🔑',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Key',
        labelMy: 'သော့',
      ),
      MemoryPairItem(
        id: 'coin',
        emoji: '🪙',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Coin',
        labelMy: 'ဒင်္ဂါးပြား',
      ),
      MemoryPairItem(
        id: 'fork',
        emoji: '🍴',
        colorValue: 0xFF4CB963,
        labelEn: 'Fork',
        labelMy: 'ခက်ရင်း',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-coding-1',
    subject: 'coding',
    grade: Grade.nursery,
    titleEn: 'Robot Directions',
    titleMy: 'ရိုဘော့ ဦးတည်ရာများ',
    descriptionEn:
        'Flip cards to find matching pairs of arrows that tell a robot which way to go.',
    descriptionMy:
        'ရိုဘော့ကို လမ်းညွှန်ပေးသည့် မြှားများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🤖',
    pairs: [
      MemoryPairItem(
        id: 'arrow-up',
        emoji: '⬆️',
        colorValue: 0xFFFF7F91,
        labelEn: 'Up',
        labelMy: 'အပေါ်',
      ),
      MemoryPairItem(
        id: 'arrow-down',
        emoji: '⬇️',
        colorValue: 0xFF7271F7,
        labelEn: 'Down',
        labelMy: 'အောက်',
      ),
      MemoryPairItem(
        id: 'arrow-left',
        emoji: '⬅️',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Left',
        labelMy: 'ဘယ်ဘက်',
      ),
      MemoryPairItem(
        id: 'arrow-right',
        emoji: '➡️',
        colorValue: 0xFF4CB963,
        labelEn: 'Right',
        labelMy: 'ညာဘက်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-coding-1',
    subject: 'coding',
    grade: Grade.kg,
    titleEn: 'Robot Steps',
    titleMy: 'ရိုဘော့ လုပ်ဆောင်ချက်များ',
    descriptionEn:
        'Flip cards to find matching pairs of commands that make a robot start, stop, and move.',
    descriptionMy:
        'ရိုဘော့ကို စတင်စေ၊ ရပ်စေ၊ ရွှေ့စေသည့် ညွှန်ကြားချက်များ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '🤖',
    pairs: [
      MemoryPairItem(
        id: 'arrow-up',
        emoji: '⬆️',
        colorValue: 0xFFFF7F91,
        labelEn: 'Up',
        labelMy: 'အပေါ်',
      ),
      MemoryPairItem(
        id: 'arrow-down',
        emoji: '⬇️',
        colorValue: 0xFF7271F7,
        labelEn: 'Down',
        labelMy: 'အောက်',
      ),
      MemoryPairItem(
        id: 'arrow-left',
        emoji: '⬅️',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Left',
        labelMy: 'ဘယ်ဘက်',
      ),
      MemoryPairItem(
        id: 'arrow-right',
        emoji: '➡️',
        colorValue: 0xFF4CB963,
        labelEn: 'Right',
        labelMy: 'ညာဘက်',
      ),
      MemoryPairItem(
        id: 'cmd-start',
        emoji: '▶️',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Start',
        labelMy: 'စတင်',
      ),
      MemoryPairItem(
        id: 'cmd-stop',
        emoji: '⏹️',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Stop',
        labelMy: 'ရပ်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-engineering-1',
    subject: 'engineering',
    grade: Grade.nursery,
    titleEn: 'Building Tools',
    titleMy: 'အဆောက်အအုံ ကိရိယာများ',
    descriptionEn:
        'Flip cards to find matching pairs of tools used to build things.',
    descriptionMy:
        'အရာဝတ္ထုများ တည်ဆောက်ရန် သုံးသော ကိရိယာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🧱',
    pairs: [
      MemoryPairItem(
        id: 'hammer',
        emoji: '🔨',
        colorValue: 0xFFE64545,
        labelEn: 'Hammer',
        labelMy: 'တူ',
      ),
      MemoryPairItem(
        id: 'blocks',
        emoji: '🧱',
        colorValue: 0xFFB5734A,
        labelEn: 'Blocks',
        labelMy: 'အုတ်ခဲများ',
      ),
      MemoryPairItem(
        id: 'ladder',
        emoji: '🪜',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Ladder',
        labelMy: 'လှေကား',
      ),
      MemoryPairItem(
        id: 'wheel',
        emoji: '🛞',
        colorValue: 0xFF7271F7,
        labelEn: 'Wheel',
        labelMy: 'ဘီး',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-engineering-1',
    subject: 'engineering',
    grade: Grade.kg,
    titleEn: 'Tall Tower Builders',
    titleMy: 'မျှော်စင် တည်ဆောက်ခြင်း',
    descriptionEn:
        'Flip cards to find matching pairs of things used to build tall towers and bridges.',
    descriptionMy:
        'မျှော်စင်များနှင့် တံတားများ တည်ဆောက်ရာတွင် သုံးသော အရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '🏗️',
    pairs: [
      MemoryPairItem(
        id: 'blocks',
        emoji: '🧱',
        colorValue: 0xFFB5734A,
        labelEn: 'Blocks',
        labelMy: 'အုတ်ခဲများ',
      ),
      MemoryPairItem(
        id: 'bridge',
        emoji: '🌉',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Bridge',
        labelMy: 'တံတား',
      ),
      MemoryPairItem(
        id: 'crane',
        emoji: '🏗️',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Crane',
        labelMy: 'ကရိန်း',
      ),
      MemoryPairItem(
        id: 'ladder',
        emoji: '🪜',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Ladder',
        labelMy: 'လှေကား',
      ),
      MemoryPairItem(
        id: 'hammer',
        emoji: '🔨',
        colorValue: 0xFFE64545,
        labelEn: 'Hammer',
        labelMy: 'တူ',
      ),
      MemoryPairItem(
        id: 'gear',
        emoji: '⚙️',
        colorValue: 0xFF4CB963,
        labelEn: 'Gear',
        labelMy: 'ဂီယာ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-history-1',
    subject: 'history',
    grade: Grade.nursery,
    titleEn: 'Long Ago Friends',
    titleMy: 'ရှေးအခါက မိတ်ဆွေများ',
    descriptionEn:
        'Flip cards to find matching pairs of things from long, long ago.',
    descriptionMy:
        'ကာလကြာရှည်စွာ ရှေးက အသုံးပြုခဲ့သော အရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🕰️',
    pairs: [
      MemoryPairItem(
        id: 'grandma',
        emoji: '👵',
        colorValue: 0xFFFF7F91,
        labelEn: 'Grandma',
        labelMy: 'အဖွား',
      ),
      MemoryPairItem(
        id: 'grandpa',
        emoji: '👴',
        colorValue: 0xFF7271F7,
        labelEn: 'Grandpa',
        labelMy: 'အဖိုး',
      ),
      MemoryPairItem(
        id: 'old-clock',
        emoji: '🕰️',
        colorValue: 0xFFB5734A,
        labelEn: 'Old Clock',
        labelMy: 'ရှေးနာရီ',
      ),
      MemoryPairItem(
        id: 'crown',
        emoji: '👑',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Crown',
        labelMy: 'သရဖူ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-history-1',
    subject: 'history',
    grade: Grade.kg,
    titleEn: 'Long, Long Ago',
    titleMy: 'ကာလအလွန်ကြာသော ရှေးအခါက',
    descriptionEn:
        'Flip cards to find matching pairs of things people used long ago, before today.',
    descriptionMy:
        'ယနေ့မတိုင်မီ ရှေးက လူတို့ အသုံးပြုခဲ့သည့် အရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '📜',
    pairs: [
      MemoryPairItem(
        id: 'old-clock',
        emoji: '🕰️',
        colorValue: 0xFFB5734A,
        labelEn: 'Old Clock',
        labelMy: 'ရှေးနာရီ',
      ),
      MemoryPairItem(
        id: 'castle',
        emoji: '🏰',
        colorValue: 0xFF94BDFF,
        labelEn: 'Castle',
        labelMy: 'ရဲတိုက်',
      ),
      MemoryPairItem(
        id: 'scroll',
        emoji: '📜',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Scroll',
        labelMy: 'စာလိပ်',
      ),
      MemoryPairItem(
        id: 'candle',
        emoji: '🕯️',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Candle',
        labelMy: 'ဖယောင်းတိုင်',
      ),
      MemoryPairItem(
        id: 'old-ship',
        emoji: '⛵',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Old Ship',
        labelMy: 'ရှေးသင်္ဘော',
      ),
      MemoryPairItem(
        id: 'crown',
        emoji: '👑',
        colorValue: 0xFF7271F7,
        labelEn: 'Crown',
        labelMy: 'သရဖူ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-geography-1',
    subject: 'geography',
    grade: Grade.nursery,
    titleEn: 'My World',
    titleMy: 'ကျွန်တော့် ကမ္ဘာလေး',
    descriptionEn: 'Flip cards to find matching pairs of places in nature.',
    descriptionMy: 'သဘာဝထဲက နေရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🗺️',
    pairs: [
      MemoryPairItem(
        id: 'mountain',
        emoji: '⛰️',
        colorValue: 0xFFB5B557,
        labelEn: 'Mountain',
        labelMy: 'တောင်',
      ),
      MemoryPairItem(
        id: 'ocean',
        emoji: '🌊',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Ocean',
        labelMy: 'သမုဒ္ဒရာ',
      ),
      MemoryPairItem(
        id: 'forest',
        emoji: '🌳',
        colorValue: 0xFF4CB963,
        labelEn: 'Forest',
        labelMy: 'သစ်တော',
      ),
      MemoryPairItem(
        id: 'island',
        emoji: '🏝️',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Island',
        labelMy: 'ကျွန်း',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-geography-1',
    subject: 'geography',
    grade: Grade.kg,
    titleEn: 'Map My World',
    titleMy: 'ကမ္ဘာလေးကို မြေပုံဆွဲကြမယ်',
    descriptionEn:
        'Flip cards to find matching pairs of places and maps from around the world.',
    descriptionMy:
        'ကမ္ဘာတစ်ဝှမ်းရှိ နေရာများနှင့် မြေပုံများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '🌍',
    pairs: [
      MemoryPairItem(
        id: 'mountain',
        emoji: '⛰️',
        colorValue: 0xFFB5B557,
        labelEn: 'Mountain',
        labelMy: 'တောင်',
      ),
      MemoryPairItem(
        id: 'ocean',
        emoji: '🌊',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Ocean',
        labelMy: 'သမုဒ္ဒရာ',
      ),
      MemoryPairItem(
        id: 'desert',
        emoji: '🏜️',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Desert',
        labelMy: 'သဲကန္တာရ',
      ),
      MemoryPairItem(
        id: 'forest',
        emoji: '🌳',
        colorValue: 0xFF4CB963,
        labelEn: 'Forest',
        labelMy: 'သစ်တော',
      ),
      MemoryPairItem(
        id: 'map',
        emoji: '🗺️',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Map',
        labelMy: 'မြေပုံ',
      ),
      MemoryPairItem(
        id: 'flag',
        emoji: '🚩',
        colorValue: 0xFFE64545,
        labelEn: 'Flag',
        labelMy: 'အလံ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-computing-1',
    subject: 'computing',
    grade: Grade.nursery,
    titleEn: 'Computer Friends',
    titleMy: 'ကွန်ပျူတာ မိတ်ဆွေများ',
    descriptionEn: 'Flip cards to find matching pairs of computer parts.',
    descriptionMy:
        'ကွန်ပျူတာ အစိတ်အပိုင်းများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '💻',
    pairs: [
      MemoryPairItem(
        id: 'computer',
        emoji: '💻',
        colorValue: 0xFF7271F7,
        labelEn: 'Computer',
        labelMy: 'ကွန်ပျူတာ',
      ),
      MemoryPairItem(
        id: 'mouse',
        emoji: '🖱️',
        colorValue: 0xFFB5B557,
        labelEn: 'Mouse',
        labelMy: 'မောက်စ်',
      ),
      MemoryPairItem(
        id: 'keyboard',
        emoji: '⌨️',
        colorValue: 0xFF4CB963,
        labelEn: 'Keyboard',
        labelMy: 'ကီးဘုတ်',
      ),
      MemoryPairItem(
        id: 'screen',
        emoji: '🖥️',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Screen',
        labelMy: 'မျက်နှာပြင်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-computing-1',
    subject: 'computing',
    grade: Grade.kg,
    titleEn: 'My Computer Parts',
    titleMy: 'ကျွန်တော့် ကွန်ပျူတာ အစိတ်အပိုင်းများ',
    descriptionEn:
        'Flip cards to find matching pairs of computer parts and gadgets.',
    descriptionMy:
        'ကွန်ပျူတာ အစိတ်အပိုင်းများနှင့် ပစ္စည်းများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 10,
    emoji: '🖥️',
    pairs: [
      MemoryPairItem(
        id: 'computer',
        emoji: '💻',
        colorValue: 0xFF7271F7,
        labelEn: 'Computer',
        labelMy: 'ကွန်ပျူတာ',
      ),
      MemoryPairItem(
        id: 'mouse',
        emoji: '🖱️',
        colorValue: 0xFFB5B557,
        labelEn: 'Mouse',
        labelMy: 'မောက်စ်',
      ),
      MemoryPairItem(
        id: 'keyboard',
        emoji: '⌨️',
        colorValue: 0xFF4CB963,
        labelEn: 'Keyboard',
        labelMy: 'ကီးဘုတ်',
      ),
      MemoryPairItem(
        id: 'screen',
        emoji: '🖥️',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Screen',
        labelMy: 'မျက်နှာပြင်',
      ),
      MemoryPairItem(
        id: 'headphones',
        emoji: '🎧',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Headphones',
        labelMy: 'နားကြပ်',
      ),
      MemoryPairItem(
        id: 'printer',
        emoji: '🖨️',
        colorValue: 0xFFE64545,
        labelEn: 'Printer',
        labelMy: 'ပရင်တာ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-math-2',
    subject: 'math',
    grade: Grade.nursery,
    titleEn: 'Shape Match',
    titleMy: 'ပုံသဏ္ဍာန် တွဲစုံရှာဂိမ်း',
    descriptionEn:
        'Flip cards to find matching pairs of shapes like circles and stars.',
    descriptionMy:
        'စက်ဝိုင်းနှင့် ကြယ်ကဲ့သို့သော ပုံသဏ္ဍာန်တွဲစုံများကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🔺',
    pairs: [
      MemoryPairItem(
        id: 'shape-circle',
        emoji: '🔵',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Circle',
        labelMy: 'စက်ဝိုင်း',
      ),
      MemoryPairItem(
        id: 'shape-square',
        emoji: '🟥',
        colorValue: 0xFFE64545,
        labelEn: 'Square',
        labelMy: 'လေးထောင့်',
      ),
      MemoryPairItem(
        id: 'shape-triangle',
        emoji: '🔺',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Triangle',
        labelMy: 'တြိဂံ',
      ),
      MemoryPairItem(
        id: 'shape-star',
        emoji: '⭐',
        colorValue: 0xFF7271F7,
        labelEn: 'Star',
        labelMy: 'ကြယ်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-math-2',
    subject: 'math',
    grade: Grade.kg,
    titleEn: 'Shapes Everywhere',
    titleMy: 'ပုံသဏ္ဍာန်များ နေရာအနှံ့',
    descriptionEn: 'Flip cards to find matching pairs of six different shapes.',
    descriptionMy:
        'ပုံသဏ္ဍာန် ခြောက်မျိုး၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '⭐',
    pairs: [
      MemoryPairItem(
        id: 'shape-circle',
        emoji: '🔵',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Circle',
        labelMy: 'စက်ဝိုင်း',
      ),
      MemoryPairItem(
        id: 'shape-square',
        emoji: '🟥',
        colorValue: 0xFFE64545,
        labelEn: 'Square',
        labelMy: 'လေးထောင့်',
      ),
      MemoryPairItem(
        id: 'shape-triangle',
        emoji: '🔺',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Triangle',
        labelMy: 'တြိဂံ',
      ),
      MemoryPairItem(
        id: 'shape-star',
        emoji: '⭐',
        colorValue: 0xFF7271F7,
        labelEn: 'Star',
        labelMy: 'ကြယ်',
      ),
      MemoryPairItem(
        id: 'shape-heart',
        emoji: '🧡',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Heart',
        labelMy: 'နှလုံးပုံ',
      ),
      MemoryPairItem(
        id: 'shape-diamond',
        emoji: '🔶',
        colorValue: 0xFFB5B557,
        labelEn: 'Diamond',
        labelMy: 'စိန်ပုံ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-phonics-2',
    subject: 'phonics',
    grade: Grade.nursery,
    titleEn: 'More Letter Friends',
    titleMy: 'နောက်ထပ် အက္ခရာ မိတ်ဆွေများ',
    descriptionEn: 'Flip cards to find matching letter-sound picture pairs.',
    descriptionMy: 'အက္ခရာအသံ ပုံစံတွဲစုံများကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🥚',
    pairs: [
      MemoryPairItem(
        id: 'letter-e',
        emoji: '🥚',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Egg',
        labelMy: 'ဥ',
      ),
      MemoryPairItem(
        id: 'letter-f',
        emoji: '🐟',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Fish',
        labelMy: 'ငါး',
      ),
      MemoryPairItem(
        id: 'letter-g',
        emoji: '🐐',
        colorValue: 0xFFB5B557,
        labelEn: 'Goat',
        labelMy: 'ဆိတ်',
      ),
      MemoryPairItem(
        id: 'letter-h',
        emoji: '🎩',
        colorValue: 0xFF7271F7,
        labelEn: 'Hat',
        labelMy: 'ဦးထုပ်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-phonics-2',
    subject: 'phonics',
    grade: Grade.kg,
    titleEn: 'Fruit Letter Match',
    titleMy: 'အသီးအနှံ အက္ခရာ တွဲစုံရှာဂိမ်း',
    descriptionEn: 'Flip cards to find matching letter-sound fruit pairs.',
    descriptionMy:
        'အက္ခရာအသံပါသော အသီးအနှံ ပုံစံတွဲစုံများကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '🍇',
    pairs: [
      MemoryPairItem(
        id: 'fruit-apple',
        emoji: '🍎',
        colorValue: 0xFFE64545,
        labelEn: 'Apple',
        labelMy: 'ပန်းသီး',
      ),
      MemoryPairItem(
        id: 'fruit-banana',
        emoji: '🍌',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Banana',
        labelMy: 'ငှက်ပျောသီး',
      ),
      MemoryPairItem(
        id: 'fruit-grape',
        emoji: '🍇',
        colorValue: 0xFF7271F7,
        labelEn: 'Grape',
        labelMy: 'စပျစ်သီး',
      ),
      MemoryPairItem(
        id: 'fruit-orange',
        emoji: '🍊',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Orange',
        labelMy: 'လိမ္မော်သီး',
      ),
      MemoryPairItem(
        id: 'fruit-mango',
        emoji: '🥭',
        colorValue: 0xFFB5734A,
        labelEn: 'Mango',
        labelMy: 'သရက်သီး',
      ),
      MemoryPairItem(
        id: 'fruit-pear',
        emoji: '🍐',
        colorValue: 0xFF4CB963,
        labelEn: 'Pear',
        labelMy: 'သစ်တော်သီး',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-art-1',
    subject: 'art',
    grade: Grade.nursery,
    titleEn: 'Color Friends',
    titleMy: 'အရောင် မိတ်ဆွေများ',
    descriptionEn: 'Flip cards to find matching pairs of colors.',
    descriptionMy: 'အရောင်တွဲစုံများကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🎨',
    pairs: [
      MemoryPairItem(
        id: 'color-red',
        emoji: '🔴',
        colorValue: 0xFFE64545,
        labelEn: 'Red',
        labelMy: 'အနီရောင်',
      ),
      MemoryPairItem(
        id: 'color-blue',
        emoji: '🔵',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Blue',
        labelMy: 'အပြာရောင်',
      ),
      MemoryPairItem(
        id: 'color-yellow',
        emoji: '🟡',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Yellow',
        labelMy: 'အဝါရောင်',
      ),
      MemoryPairItem(
        id: 'color-green',
        emoji: '🟢',
        colorValue: 0xFF4CB963,
        labelEn: 'Green',
        labelMy: 'အစိမ်းရောင်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-art-1',
    subject: 'art',
    grade: Grade.kg,
    titleEn: 'Painting Tools and Colors',
    titleMy: 'ဆေးဆွဲကိရိယာများနှင့် အရောင်များ',
    descriptionEn: 'Flip cards to find matching pairs of art tools and colors.',
    descriptionMy:
        'ပန်းချီကိရိယာများနှင့် အရောင်များ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '🖌️',
    pairs: [
      MemoryPairItem(
        id: 'paintbrush',
        emoji: '🖌️',
        colorValue: 0xFF7271F7,
        labelEn: 'Paintbrush',
        labelMy: 'ဆေးတံ',
      ),
      MemoryPairItem(
        id: 'palette',
        emoji: '🎨',
        colorValue: 0xFFB5734A,
        labelEn: 'Palette',
        labelMy: 'ဆေးခွက်',
      ),
      MemoryPairItem(
        id: 'crayon',
        emoji: '🖍️',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Crayon',
        labelMy: 'ဆေးခဲ',
      ),
      MemoryPairItem(
        id: 'color-purple',
        emoji: '🟣',
        colorValue: 0xFF7271F7,
        labelEn: 'Purple',
        labelMy: 'ခရမ်းရောင်',
      ),
      MemoryPairItem(
        id: 'color-orange',
        emoji: '🟠',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Orange',
        labelMy: 'လိမ္မော်ရောင်',
      ),
      MemoryPairItem(
        id: 'rainbow',
        emoji: '🌈',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Rainbow',
        labelMy: 'သက်တံ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-generalknowledge-1',
    subject: 'generalknowledge',
    grade: Grade.nursery,
    titleEn: 'Good Habits',
    titleMy: 'အလေ့အကျင့်ကောင်းများ',
    descriptionEn: 'Flip cards to find matching pairs of everyday good habits.',
    descriptionMy:
        'နေ့စဉ်ပြုလုပ်သင့်သည့် အလေ့အကျင့်ကောင်းများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🪥',
    pairs: [
      MemoryPairItem(
        id: 'brush-teeth',
        emoji: '🪥',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Brush Teeth',
        labelMy: 'သွားတိုက်ခြင်း',
      ),
      MemoryPairItem(
        id: 'wash-hands',
        emoji: '🧼',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Wash Hands',
        labelMy: 'လက်ဆေးခြင်း',
      ),
      MemoryPairItem(
        id: 'sleep',
        emoji: '😴',
        colorValue: 0xFF7271F7,
        labelEn: 'Sleep',
        labelMy: 'အိပ်ခြင်း',
      ),
      MemoryPairItem(
        id: 'eat-well',
        emoji: '🍎',
        colorValue: 0xFFE64545,
        labelEn: 'Eat Well',
        labelMy: 'ကျန်းမာစွာ စားခြင်း',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-generalknowledge-1',
    subject: 'generalknowledge',
    grade: Grade.kg,
    titleEn: 'Community Helpers',
    titleMy: 'ရပ်ရွာကို ကူညီသူများ',
    descriptionEn:
        'Flip cards to find matching pairs of people who help our community.',
    descriptionMy:
        'ကျွန်ုပ်တို့ ရပ်ရွာကို ကူညီပေးသော သူများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '👩‍⚕️',
    pairs: [
      MemoryPairItem(
        id: 'doctor',
        emoji: '👩‍⚕️',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Doctor',
        labelMy: 'ဆရာဝန်',
      ),
      MemoryPairItem(
        id: 'firefighter',
        emoji: '👨‍🚒',
        colorValue: 0xFFE64545,
        labelEn: 'Firefighter',
        labelMy: 'မီးသတ်သမား',
      ),
      MemoryPairItem(
        id: 'police',
        emoji: '👮',
        colorValue: 0xFF7271F7,
        labelEn: 'Police',
        labelMy: 'ရဲ',
      ),
      MemoryPairItem(
        id: 'teacher',
        emoji: '👩‍🏫',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Teacher',
        labelMy: 'ဆရာမ',
      ),
      MemoryPairItem(
        id: 'farmer',
        emoji: '👨‍🌾',
        colorValue: 0xFF4CB963,
        labelEn: 'Farmer',
        labelMy: 'တောင်သူ',
      ),
      MemoryPairItem(
        id: 'chef',
        emoji: '👨‍🍳',
        colorValue: 0xFFB5734A,
        labelEn: 'Chef',
        labelMy: 'စားဖိုမှူး',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-stem-2',
    subject: 'stem',
    grade: Grade.nursery,
    titleEn: 'Weather Watch',
    titleMy: 'မိုးလေဝသ လေ့လာခြင်း',
    descriptionEn: 'Flip cards to find matching pairs of weather in the sky.',
    descriptionMy:
        'ကောင်းကင်ပေါ်ရှိ မိုးလေဝသအခြေအနေများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '☀️',
    pairs: [
      MemoryPairItem(
        id: 'weather-sun',
        emoji: '☀️',
        colorValue: 0xFFFFC93C,
        labelEn: 'Sun',
        labelMy: 'နေ',
      ),
      MemoryPairItem(
        id: 'weather-rain',
        emoji: '🌧️',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Rain',
        labelMy: 'မိုး',
      ),
      MemoryPairItem(
        id: 'weather-cloud',
        emoji: '☁️',
        colorValue: 0xFF94BDFF,
        labelEn: 'Cloud',
        labelMy: 'မိုးတိမ်',
      ),
      MemoryPairItem(
        id: 'weather-wind',
        emoji: '🌬️',
        colorValue: 0xFFB5B557,
        labelEn: 'Wind',
        labelMy: 'လေ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-stem-2',
    subject: 'stem',
    grade: Grade.kg,
    titleEn: 'Living or Not Living',
    titleMy: 'သက်ရှိ ဟုတ်၊ မဟုတ်',
    descriptionEn:
        'Flip cards to find matching pairs of living things and objects.',
    descriptionMy:
        'သက်ရှိသတ္တဝါများနှင့် အရာဝတ္ထုများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '🌱',
    pairs: [
      MemoryPairItem(
        id: 'tree',
        emoji: '🌳',
        colorValue: 0xFF4CB963,
        labelEn: 'Tree',
        labelMy: 'သစ်ပင်',
      ),
      MemoryPairItem(
        id: 'dog',
        emoji: '🐶',
        colorValue: 0xFFB5734A,
        labelEn: 'Dog',
        labelMy: 'ခွေး',
      ),
      MemoryPairItem(
        id: 'rock',
        emoji: '🪨',
        colorValue: 0xFFB5B557,
        labelEn: 'Rock',
        labelMy: 'ကျောက်တုံး',
      ),
      MemoryPairItem(
        id: 'car',
        emoji: '🚗',
        colorValue: 0xFFE64545,
        labelEn: 'Car',
        labelMy: 'ကား',
      ),
      MemoryPairItem(
        id: 'flower',
        emoji: '🌸',
        colorValue: 0xFFFF7F91,
        labelEn: 'Flower',
        labelMy: 'ပန်း',
      ),
      MemoryPairItem(
        id: 'fish',
        emoji: '🐟',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Fish',
        labelMy: 'ငါး',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-coding-2',
    subject: 'coding',
    grade: Grade.nursery,
    titleEn: 'Robot Actions',
    titleMy: 'ရိုဘော့ လှုပ်ရှားမှုများ',
    descriptionEn:
        'Flip cards to find matching pairs of fun actions a robot can do.',
    descriptionMy:
        'ရိုဘော့ ပြုလုပ်နိုင်သော ပျော်စရာလှုပ်ရှားမှုများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🤖',
    pairs: [
      MemoryPairItem(
        id: 'action-clap',
        emoji: '👏',
        colorValue: 0xFFFF7F91,
        labelEn: 'Clap',
        labelMy: 'လက်ခုပ်တီးခြင်း',
      ),
      MemoryPairItem(
        id: 'action-wave',
        emoji: '👋',
        colorValue: 0xFF7271F7,
        labelEn: 'Wave',
        labelMy: 'လက်ညိတ်ခြင်း',
      ),
      MemoryPairItem(
        id: 'action-jump',
        emoji: '🤸',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Jump',
        labelMy: 'ခုန်ခြင်း',
      ),
      MemoryPairItem(
        id: 'action-spin',
        emoji: '🌀',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Spin',
        labelMy: 'လည်ခြင်း',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-coding-2',
    subject: 'coding',
    grade: Grade.kg,
    titleEn: 'Code a Dance',
    titleMy: 'ကုဒ်ဖြင့် အကကတီးကမယ်',
    descriptionEn:
        'Flip cards to find matching pairs of actions to code a robot dance.',
    descriptionMy:
        'ရိုဘော့ကို အကကတီးစေရန် ညွှန်ကြားချက်များ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '💃',
    pairs: [
      MemoryPairItem(
        id: 'action-clap',
        emoji: '👏',
        colorValue: 0xFFFF7F91,
        labelEn: 'Clap',
        labelMy: 'လက်ခုပ်တီးခြင်း',
      ),
      MemoryPairItem(
        id: 'action-wave',
        emoji: '👋',
        colorValue: 0xFF7271F7,
        labelEn: 'Wave',
        labelMy: 'လက်ညိတ်ခြင်း',
      ),
      MemoryPairItem(
        id: 'action-jump',
        emoji: '🤸',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Jump',
        labelMy: 'ခုန်ခြင်း',
      ),
      MemoryPairItem(
        id: 'action-spin',
        emoji: '🌀',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Spin',
        labelMy: 'လည်ခြင်း',
      ),
      MemoryPairItem(
        id: 'action-repeat',
        emoji: '🔁',
        colorValue: 0xFF4CB963,
        labelEn: 'Repeat',
        labelMy: 'ထပ်လုပ်ခြင်း',
      ),
      MemoryPairItem(
        id: 'action-stop',
        emoji: '✋',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Stop',
        labelMy: 'ရပ်ခြင်း',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-engineering-2',
    subject: 'engineering',
    grade: Grade.nursery,
    titleEn: 'Construction Site',
    titleMy: 'အဆောက်အအုံ တည်ဆောက်ရာနေရာ',
    descriptionEn:
        'Flip cards to find matching pairs of things at a construction site.',
    descriptionMy:
        'အဆောက်အအုံ တည်ဆောက်ရာနေရာရှိ အရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🚧',
    pairs: [
      MemoryPairItem(
        id: 'cone',
        emoji: '🚧',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Cone',
        labelMy: 'လမ်းအမှတ်တိုင်',
      ),
      MemoryPairItem(
        id: 'truck',
        emoji: '🚚',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Truck',
        labelMy: 'ကုန်တင်ကား',
      ),
      MemoryPairItem(
        id: 'tractor',
        emoji: '🚜',
        colorValue: 0xFF4CB963,
        labelEn: 'Tractor',
        labelMy: 'ထရက်တာ',
      ),
      MemoryPairItem(
        id: 'worker',
        emoji: '👷',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Worker',
        labelMy: 'အလုပ်သမား',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-engineering-2',
    subject: 'engineering',
    grade: Grade.kg,
    titleEn: 'Simple Machines',
    titleMy: 'ရိုးရှင်းသော စက်ကိရိယာများ',
    descriptionEn:
        'Flip cards to find matching pairs of simple machines that help us work.',
    descriptionMy:
        'ကျွန်ုပ်တို့ကို အလုပ်လုပ်ရာတွင် ကူညီပေးသော ရိုးရှင်းသည့် စက်ကိရိယာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '⚙️',
    pairs: [
      MemoryPairItem(
        id: 'wheel',
        emoji: '🛞',
        colorValue: 0xFF7271F7,
        labelEn: 'Wheel',
        labelMy: 'ဘီး',
      ),
      MemoryPairItem(
        id: 'gear',
        emoji: '⚙️',
        colorValue: 0xFF4CB963,
        labelEn: 'Gear',
        labelMy: 'ဂီယာ',
      ),
      MemoryPairItem(
        id: 'screw',
        emoji: '🔩',
        colorValue: 0xFFB5B557,
        labelEn: 'Screw',
        labelMy: 'စကရူး',
      ),
      MemoryPairItem(
        id: 'ramp',
        emoji: '🛝',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Ramp',
        labelMy: 'စောင်းလမ်း',
      ),
      MemoryPairItem(
        id: 'rope',
        emoji: '🪢',
        colorValue: 0xFFB5734A,
        labelEn: 'Rope',
        labelMy: 'ကြိုး',
      ),
      MemoryPairItem(
        id: 'balance-scale',
        emoji: '⚖️',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Balance Scale',
        labelMy: 'ချိန်ခွင်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-history-2',
    subject: 'history',
    grade: Grade.nursery,
    titleEn: 'Knights of Old',
    titleMy: 'ရှေးခေတ် မြင်းစီးသူရဲကောင်းများ',
    descriptionEn:
        'Flip cards to find matching pairs of things knights used long ago.',
    descriptionMy:
        'ရှေးခေတ်က သူရဲကောင်းများ အသုံးပြုခဲ့သော အရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🛡️',
    pairs: [
      MemoryPairItem(
        id: 'shield',
        emoji: '🛡️',
        colorValue: 0xFF7271F7,
        labelEn: 'Shield',
        labelMy: 'ဒိုင်း',
      ),
      MemoryPairItem(
        id: 'sword',
        emoji: '⚔️',
        colorValue: 0xFFB5B557,
        labelEn: 'Sword',
        labelMy: 'သန်လျက်',
      ),
      MemoryPairItem(
        id: 'horse',
        emoji: '🐴',
        colorValue: 0xFFB5734A,
        labelEn: 'Horse',
        labelMy: 'မြင်း',
      ),
      MemoryPairItem(
        id: 'castle',
        emoji: '🏰',
        colorValue: 0xFF94BDFF,
        labelEn: 'Castle',
        labelMy: 'ရဲတိုက်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-history-2',
    subject: 'history',
    grade: Grade.kg,
    titleEn: "Grandma's Treasures",
    titleMy: 'အဖွား၏ ရတနာများ',
    descriptionEn:
        'Flip cards to find matching pairs of treasures from long ago.',
    descriptionMy:
        'ရှေးခေတ်က ရတနာပစ္စည်းများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '💰',
    pairs: [
      MemoryPairItem(
        id: 'radio',
        emoji: '📻',
        colorValue: 0xFFB5734A,
        labelEn: 'Radio',
        labelMy: 'ရေဒီယို',
      ),
      MemoryPairItem(
        id: 'telephone',
        emoji: '☎️',
        colorValue: 0xFF7271F7,
        labelEn: 'Telephone',
        labelMy: 'တယ်လီဖုန်း',
      ),
      MemoryPairItem(
        id: 'lantern',
        emoji: '🏮',
        colorValue: 0xFFE64545,
        labelEn: 'Lantern',
        labelMy: 'မီးအိမ်',
      ),
      MemoryPairItem(
        id: 'quill-pen',
        emoji: '🪶',
        colorValue: 0xFF94BDFF,
        labelEn: 'Quill Pen',
        labelMy: 'ငှက်တောင်ဘောပင်',
      ),
      MemoryPairItem(
        id: 'coin',
        emoji: '🪙',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Coin',
        labelMy: 'ဒင်္ဂါးပြား',
      ),
      MemoryPairItem(
        id: 'compass',
        emoji: '🧭',
        colorValue: 0xFF4CB963,
        labelEn: 'Compass',
        labelMy: 'အရပ်ညွှန်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-geography-2',
    subject: 'geography',
    grade: Grade.nursery,
    titleEn: 'Homes Around the World',
    titleMy: 'ကမ္ဘာပေါ်ရှိ အိမ်များ',
    descriptionEn:
        'Flip cards to find matching pairs of different homes people live in.',
    descriptionMy:
        'လူတို့နေထိုင်ကြသော အိမ်အမျိုးမျိုး၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '🏠',
    pairs: [
      MemoryPairItem(
        id: 'house',
        emoji: '🏠',
        colorValue: 0xFFFF7F91,
        labelEn: 'House',
        labelMy: 'အိမ်',
      ),
      MemoryPairItem(
        id: 'apartment',
        emoji: '🏢',
        colorValue: 0xFF94BDFF,
        labelEn: 'Apartment',
        labelMy: 'တိုက်ခန်း',
      ),
      MemoryPairItem(
        id: 'hut',
        emoji: '🛖',
        colorValue: 0xFFB5734A,
        labelEn: 'Hut',
        labelMy: 'တဲ',
      ),
      MemoryPairItem(
        id: 'boat-house',
        emoji: '🛶',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Boat House',
        labelMy: 'ရေပေါ်အိမ်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-geography-2',
    subject: 'geography',
    grade: Grade.kg,
    titleEn: "Let's Travel the World",
    titleMy: 'ကမ္ဘာပတ် ခရီးသွားကြမယ်',
    descriptionEn:
        'Flip cards to find matching pairs of things we use to travel and explore.',
    descriptionMy:
        'ခရီးသွားလေ့လာရာတွင် အသုံးပြုသော အရာများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '✈️',
    pairs: [
      MemoryPairItem(
        id: 'airplane',
        emoji: '✈️',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Airplane',
        labelMy: 'လေယာဉ်',
      ),
      MemoryPairItem(
        id: 'globe',
        emoji: '🌍',
        colorValue: 0xFF4CB963,
        labelEn: 'Globe',
        labelMy: 'ကမ္ဘာလုံးပုံ',
      ),
      MemoryPairItem(
        id: 'suitcase',
        emoji: '🧳',
        colorValue: 0xFFB5734A,
        labelEn: 'Suitcase',
        labelMy: 'ခရီးဆောင်အိတ်',
      ),
      MemoryPairItem(
        id: 'train',
        emoji: '🚂',
        colorValue: 0xFFE64545,
        labelEn: 'Train',
        labelMy: 'ရထား',
      ),
      MemoryPairItem(
        id: 'palm-tree',
        emoji: '🌴',
        colorValue: 0xFF4CB963,
        labelEn: 'Palm Tree',
        labelMy: 'ထန်းပင်',
      ),
      MemoryPairItem(
        id: 'tower',
        emoji: '🗼',
        colorValue: 0xFFFFBF3C,
        labelEn: 'Tower',
        labelMy: 'မျှော်စင်',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-nursery-memory-computing-2',
    subject: 'computing',
    grade: Grade.nursery,
    titleEn: 'Gadgets at Home',
    titleMy: 'အိမ်ရှိ လျှပ်စစ်ပစ္စည်းများ',
    descriptionEn:
        'Flip cards to find matching pairs of gadgets we use at home.',
    descriptionMy:
        'အိမ်တွင် အသုံးပြုသော လျှပ်စစ်ပစ္စည်းများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 7,
    emoji: '📱',
    pairs: [
      MemoryPairItem(
        id: 'tablet',
        emoji: '📱',
        colorValue: 0xFF7271F7,
        labelEn: 'Tablet',
        labelMy: 'တက်ဘလက်',
      ),
      MemoryPairItem(
        id: 'television',
        emoji: '📺',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Television',
        labelMy: 'တီဗွီ',
      ),
      MemoryPairItem(
        id: 'camera',
        emoji: '📷',
        colorValue: 0xFFB5B557,
        labelEn: 'Camera',
        labelMy: 'ကင်မရာ',
      ),
      MemoryPairItem(
        id: 'speaker',
        emoji: '🔊',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Speaker',
        labelMy: 'စပီကာ',
      ),
    ],
  ),
  NurseryMemoryDef(
    id: 'mock-kg-memory-computing-2',
    subject: 'computing',
    grade: Grade.kg,
    titleEn: 'Smart Gadgets Everywhere',
    titleMy: 'နေရာအနှံ့ရှိ စမတ်ပစ္စည်းများ',
    descriptionEn:
        'Flip cards to find matching pairs of smart gadgets we use every day.',
    descriptionMy:
        'နေ့စဉ် အသုံးပြုသော စမတ်ပစ္စည်းများ၏ တွဲစုံကတ်များကို ကတ်များလှန်ပြီး ရှာပါ။',
    starsReward: 9,
    emoji: '⌚',
    pairs: [
      MemoryPairItem(
        id: 'tablet',
        emoji: '📱',
        colorValue: 0xFF7271F7,
        labelEn: 'Tablet',
        labelMy: 'တက်ဘလက်',
      ),
      MemoryPairItem(
        id: 'smartwatch',
        emoji: '⌚',
        colorValue: 0xFFB5B557,
        labelEn: 'Smartwatch',
        labelMy: 'စမတ်နာရီ',
      ),
      MemoryPairItem(
        id: 'camera',
        emoji: '📷',
        colorValue: 0xFF4CB963,
        labelEn: 'Camera',
        labelMy: 'ကင်မရာ',
      ),
      MemoryPairItem(
        id: 'speaker',
        emoji: '🔊',
        colorValue: 0xFFFF8A3D,
        labelEn: 'Speaker',
        labelMy: 'စပီကာ',
      ),
      MemoryPairItem(
        id: 'television',
        emoji: '📺',
        colorValue: 0xFF4CB6FF,
        labelEn: 'Television',
        labelMy: 'တီဗွီ',
      ),
      MemoryPairItem(
        id: 'game-controller',
        emoji: '🎮',
        colorValue: 0xFFE64545,
        labelEn: 'Game Controller',
        labelMy: 'ဂိမ်းကွန်ထရိုလာ',
      ),
    ],
  ),
];
