import '../../models/child_model.dart';
import 'mock_quiz_data.dart';

/// One Secondary/IGCSE curriculum module: bilingual catalog metadata plus
/// its own fixed set of MCQ [QuizQuestion]s. Structurally identical to
/// [PrimaryActivityDef] in `primary_curriculum_bank.dart` -- content plays
/// back through the same shared [McqQuizScreen].
class SecondaryActivityDef {
  const SecondaryActivityDef({
    required this.id,
    required this.subject,
    required this.grade,
    required this.contentType,
    required this.titleEn,
    required this.titleMy,
    required this.descriptionEn,
    required this.descriptionMy,
    required this.starsReward,
    required this.questions,
  });

  final String id;
  final String subject;
  final Grade grade;
  final String contentType;
  final String titleEn;
  final String titleMy;
  final String descriptionEn;
  final String descriptionMy;
  final int starsReward;
  final List<QuizQuestion> questions;
}

const List<SecondaryActivityDef> secondaryCurriculumBank = [
  // ============================== SECONDARY 1 ==============================
  SecondaryActivityDef(
    id: 'mock-secondary1-algebra-1',
    subject: 'algebra',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Linear Equations',
    titleMy: 'မျဉ်းညီညွှတ်ညီမျှခြင်းများ',
    descriptionEn: 'Solve simple linear equations with one unknown.',
    descriptionMy: 'အမည်မသိတစ်ခုပါသော ရိုးရှင်းသော မျဉ်းညီညွှတ်ညီမျှခြင်းများကို ဖြေရှင်းပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'Solve for x: x + 7 = 15',
        questionMy: 'x ကိုဖြေရှင်းပါ- x + 7 = 15',
        optionsEn: ['8', '22', '7', '15'],
        optionsMy: ['8', '22', '7', '15'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Solve for x: 3x = 21',
        questionMy: 'x ကိုဖြေရှင်းပါ- 3x = 21',
        optionsEn: ['7', '18', '24', '3'],
        optionsMy: ['7', '18', '24', '3'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Solve for x: 2x - 4 = 10',
        questionMy: 'x ကိုဖြေရှင်းပါ- 2x - 4 = 10',
        optionsEn: ['7', '3', '6', '14'],
        optionsMy: ['7', '3', '6', '14'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Solve for x: x / 4 = 9',
        questionMy: 'x ကိုဖြေရှင်းပါ- x / 4 = 9',
        optionsEn: ['36', '13', '5', '2.25'],
        optionsMy: ['36', '13', '5', '2.25'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'If a number plus 12 equals 30, what is the number?',
        questionMy: 'ကိန်းတစ်ခုကို ၁၂ နှင့်ပေါင်းလျှင် ၃၀ ဖြစ်ပါက ထိုကိန်းမှာ အဘယ်နည်း။',
        optionsEn: ['18', '42', '12', '30'],
        optionsMy: ['18', '42', '12', '30'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-algebra-2',
    subject: 'algebra',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Expanding Brackets',
    titleMy: 'အနားသတ်ကွင်းများ ဖြန့်ချခြင်း',
    descriptionEn: 'Practice expanding simple bracketed algebraic expressions.',
    descriptionMy: 'ရိုးရှင်းသော ကွင်းစကားရပ်များကို ဖြန့်ချလေ့ကျင့်ပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'Expand: 3(x + 2)',
        questionMy: 'ဖြန့်ချပါ- 3(x + 2)',
        optionsEn: ['3x + 6', '3x + 2', 'x + 6', '3x + 5'],
        optionsMy: ['3x + 6', '3x + 2', 'x + 6', '3x + 5'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Expand: 4(y - 3)',
        questionMy: 'ဖြန့်ချပါ- 4(y - 3)',
        optionsEn: ['4y - 12', '4y - 3', 'y - 12', '4y + 12'],
        optionsMy: ['4y - 12', '4y - 3', 'y - 12', '4y + 12'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Expand: 2(a + b)',
        questionMy: 'ဖြန့်ချပါ- 2(a + b)',
        optionsEn: ['2a + 2b', 'a + b', '2a + b', 'a + 2b'],
        optionsMy: ['2a + 2b', 'a + b', '2a + b', 'a + 2b'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Expand: 5(2x - 1)',
        questionMy: 'ဖြန့်ချပါ- 5(2x - 1)',
        optionsEn: ['10x - 5', '10x - 1', '2x - 5', '7x - 5'],
        optionsMy: ['10x - 5', '10x - 1', '2x - 5', '7x - 5'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Expand: -2(x + 4)',
        questionMy: 'ဖြန့်ချပါ- -2(x + 4)',
        optionsEn: ['-2x - 8', '-2x + 8', '2x - 8', '-2x - 4'],
        optionsMy: ['-2x - 8', '-2x + 8', '2x - 8', '-2x - 4'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-algebra-3',
    subject: 'algebra',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Substitution',
    titleMy: 'အစားထိုးခြင်း',
    descriptionEn: 'Substitute given values into simple algebraic expressions.',
    descriptionMy: 'ပေးထားသောတန်ဖိုးများကို ရိုးရှင်းသော အက္ခရာသင်္ချာဖော်ပြချက်များထဲသို့ အစားထိုးပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'If x = 3, what is 2x + 5?',
        questionMy: 'x = 3 ဖြစ်လျှင် 2x + 5 ၏တန်ဖိုးမှာ အဘယ်နည်း။',
        optionsEn: ['11', '8', '10', '13'],
        optionsMy: ['11', '8', '10', '13'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'If x = 4 and y = 2, what is x + 3y?',
        questionMy: 'x = 4 နှင့် y = 2 ဖြစ်လျှင် x + 3y ၏တန်ဖိုးမှာ အဘယ်နည်း။',
        optionsEn: ['10', '9', '14', '6'],
        optionsMy: ['10', '9', '14', '6'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'If a = 5, what is a squared (a²)?',
        questionMy: 'a = 5 ဖြစ်လျှင် a squared (a²) ၏တန်ဖိုးမှာ အဘယ်နည်း။',
        optionsEn: ['25', '10', '15', '20'],
        optionsMy: ['25', '10', '15', '20'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'If x = -2, what is x + 6?',
        questionMy: 'x = -2 ဖြစ်လျှင် x + 6 ၏တန်ဖိုးမှာ အဘယ်နည်း။',
        optionsEn: ['4', '8', '-4', '-8'],
        optionsMy: ['4', '8', '-4', '-8'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'If p = 6 and q = 3, what is p / q + 1?',
        questionMy: 'p = 6 နှင့် q = 3 ဖြစ်လျှင် p / q + 1 ၏တန်ဖိုးမှာ အဘယ်နည်း။',
        optionsEn: ['3', '2', '9', '1'],
        optionsMy: ['3', '2', '9', '1'],
        correctIndex: 0,
      ),
    ],
  ),

  // ---- physics ----
  SecondaryActivityDef(
    id: 'mock-secondary1-physics-1',
    subject: 'physics',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Forces and Motion',
    titleMy: 'အားများနှင့် ရွေ့လျားမှု',
    descriptionEn: 'Understand how forces cause objects to speed up, slow down, or change direction.',
    descriptionMy: 'အားများသည် အရာဝတ္ထုများကို မြန်စေခြင်း၊ နှေးစေခြင်း၊ သို့မဟုတ် ဦးတည်ရာပြောင်းလဲစေခြင်းကို နားလည်ပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What is a force?',
        questionMy: 'အား ဆိုသည်မှာ အဘယ်နည်း။',
        optionsEn: [
          'A push or a pull on an object',
          'A type of energy source',
          'The speed of an object',
          'The weight of an object only',
        ],
        optionsMy: [
          'အရာဝတ္ထုတစ်ခုအား တွန်းခြင်း သို့မဟုတ် ဆွဲခြင်း',
          'စွမ်းအင်အမျိုးအစားတစ်ခု',
          'အရာဝတ္ထုတစ်ခု၏ အလျင်',
          'အလေးချိန်သာ',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is the unit used to measure force?',
        questionMy: 'အားကို တိုင်းတာရန် အသုံးပြုသော ယူနစ်မှာ အဘယ်နည်း။',
        optionsEn: ['Newton (N)', 'Joule (J)', 'Watt (W)', 'Metre (m)'],
        optionsMy: ['နယူတန် (N)', 'ဂျူး (J)', 'ဝပ် (W)', 'မီတာ (m)'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which force pulls objects down toward the Earth?',
        questionMy: 'အရာဝတ္ထုများကို မြေကြီးဘက်သို့ ဆွဲချသော အားမှာ အဘယ်နည်း။',
        optionsEn: ['Gravity', 'Friction', 'Magnetism', 'Upthrust'],
        optionsMy: ['ဆွဲငင်အား', 'ပွတ်တိုက်အား', 'သံလိုက်အား', 'အထက်တွန်းအား'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What force acts against the motion of two surfaces sliding against each other?',
        questionMy: 'မျက်နှာပြင်နှစ်ခု ပွတ်တိုက်ရွေ့လျားနေချိန် ဆန့်ကျင်လျက်ရှိသော အားမှာ အဘယ်နည်း။',
        optionsEn: ['Friction', 'Gravity', 'Tension', 'Thrust'],
        optionsMy: ['ပွတ်တိုက်အား', 'ဆွဲငင်အား', 'တင်းအား', 'တွန်းအား'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'If a moving object has no unbalanced force acting on it, what happens to its motion?',
        questionMy: 'ရွေ့လျားနေသော အရာဝတ္ထုတစ်ခုအပေါ် မမျှတသောအား မလွှမ်းမိုးပါက ၎င်း၏ ရွေ့လျားမှုသည် မည်သို့ဖြစ်မည်နည်း။',
        optionsEn: [
          'It keeps moving at the same speed and direction',
          'It stops immediately',
          'It speeds up automatically',
          'It changes direction randomly',
        ],
        optionsMy: [
          'တူညီသောအလျင်နှင့် ဦးတည်ရာဖြင့် ဆက်ရွေ့လျားနေမည်',
          'ချက်ချင်း ရပ်တန့်သွားမည်',
          'အလိုအလျောက် မြန်လာမည်',
          'ဦးတည်ရာ ကျပန်းပြောင်းသွားမည်',
        ],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-physics-2',
    subject: 'physics',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Forms of Energy',
    titleMy: 'စွမ်းအင်၏ ပုံစံများ',
    descriptionEn: 'Identify different forms of energy and how they transform from one to another.',
    descriptionMy: 'စွမ်းအင်၏ ပုံစံအမျိုးမျိုးနှင့် ၎င်းတို့ တစ်ပုံစံမှတစ်ပုံစံသို့ ပြောင်းလဲပုံကို ခွဲခြားသိမြင်ပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What type of energy does a moving car have?',
        questionMy: 'ရွေ့လျားနေသော ကားတစ်စီးတွင် မည်သည့်စွမ်းအင်အမျိုးအစား ရှိသနည်း။',
        optionsEn: ['Kinetic energy', 'Potential energy', 'Chemical energy', 'Sound energy'],
        optionsMy: ['ရွေ့လျားစွမ်းအင်', 'အနေအထားစွမ်းအင်', 'ဓာတုစွမ်းအင်', 'အသံစွမ်းအင်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'A ball held high above the ground has what type of energy?',
        questionMy: 'မြေပြင်အထက် မြင့်စွာကိုင်ထားသော ဘောလုံးတွင် မည်သည့်စွမ်းအင် ရှိသနည်း။',
        optionsEn: [
          'Gravitational potential energy',
          'Kinetic energy',
          'Electrical energy',
          'Thermal energy',
        ],
        optionsMy: [
          'ဆွဲငင်အား အနေအထားစွမ်းအင်',
          'ရွေ့လျားစွမ်းအင်',
          'လျှပ်စစ်စွမ်းအင်',
          'အပူစွမ်းအင်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'A light bulb converts electrical energy mainly into which two forms?',
        questionMy: 'မီးလုံးတစ်လုံးသည် လျှပ်စစ်စွမ်းအင်ကို အဓိကအားဖြင့် မည်သည့်ပုံစံနှစ်ခုအဖြစ် ပြောင်းလဲပေးသနည်း။',
        optionsEn: [
          'Light and heat',
          'Sound and light',
          'Chemical and sound',
          'Kinetic and magnetic',
        ],
        optionsMy: [
          'အလင်းနှင့် အပူ',
          'အသံနှင့် အလင်း',
          'ဓာတုနှင့် အသံ',
          'ရွေ့လျားမှုနှင့် သံလိုက်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What law states that energy cannot be created or destroyed, only transformed?',
        questionMy: 'စွမ်းအင်ကို ဖန်တီးခြင်း သို့မဟုတ် ဖျက်ဆီးခြင်း မပြုနိုင်ဘဲ ပြောင်းလဲနိုင်ရုံသာ ရှိသည်ဟု ဆိုသော ဥပဒေမှာ အဘယ်နည်း။',
        optionsEn: [
          'The law of conservation of energy',
          'The law of gravity',
          'Newton\'s first law',
          'The law of friction',
        ],
        optionsMy: [
          'စွမ်းအင်ထိန်းသိမ်းမှုဥပဒေ',
          'ဆွဲငင်အားဥပဒေ',
          'နယူတန်၏ ပထမဥပဒေ',
          'ပွတ်တိုက်အားဥပဒေ',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Food gives our bodies energy in which form, before we use it to move?',
        questionMy: 'အစားအစာသည် ကျွန်ုပ်တို့ခန္ဓာကိုယ်ကို ရွေ့လျားရန်မသုံးမီ မည်သည့်ပုံစံဖြင့် စွမ်းအင်ပေးသနည်း။',
        optionsEn: ['Chemical energy', 'Nuclear energy', 'Electrical energy', 'Sound energy'],
        optionsMy: ['ဓာတုစွမ်းအင်', 'နျူကလီးယားစွမ်းအင်', 'လျှပ်စစ်စွမ်းအင်', 'အသံစွမ်းအင်'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-physics-3',
    subject: 'physics',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Simple Circuits',
    titleMy: 'ရိုးရှင်းသော ဆားကစ်များ',
    descriptionEn: 'Learn how electricity flows in a simple circuit with a battery, wires, and a bulb.',
    descriptionMy: 'ဘက်ထရီ၊ ကြေးနန်းနှင့် မီးလုံးပါသော ရိုးရှင်းသောဆားကစ်တွင် လျှပ်စစ်စီးဆင်းပုံကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What is needed for a simple electric circuit to work?',
        questionMy: 'ရိုးရှင်းသော လျှပ်စစ်ဆားကစ်တစ်ခု အလုပ်လုပ်ရန် အဘယ်အရာလိုအပ်သနည်း။',
        optionsEn: [
          'A complete, closed loop of conducting material',
          'Only a battery',
          'Only a wire',
          'A broken wire',
        ],
        optionsMy: [
          'လျှပ်ကူးပစ္စည်းဖြင့် ပြီးစီးပိတ်နေသော ကွင်းစက်',
          'ဘက်ထရီတစ်ခုသာ',
          'ကြေးနန်းတစ်ခုသာ',
          'ပြတ်နေသောကြေးနန်း',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What happens to a bulb in a circuit if the wire is broken?',
        questionMy: 'ကြေးနန်းပြတ်သွားပါက ဆားကစ်ထဲရှိ မီးလုံးမှာ မည်သို့ဖြစ်မည်နည်း။',
        optionsEn: [
          'It stops lighting up',
          'It gets brighter',
          'It stays the same',
          'It changes color',
        ],
        optionsMy: [
          'အလင်းရောင်ပေးတော့မည် မဟုတ်ပါ',
          'ပိုတောက်ပလာမည်',
          'ပြောင်းလဲမှု မရှိပါ',
          'အရောင်ပြောင်းလိမ့်မည်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What device provides the electrical energy in a simple circuit?',
        questionMy: 'ရိုးရှင်းသောဆားကစ်တွင် လျှပ်စစ်စွမ်းအင်ကို ပေးအပ်သော ကိရိယာမှာ အဘယ်နည်း။',
        optionsEn: ['Battery (cell)', 'Bulb', 'Switch', 'Resistor'],
        optionsMy: ['ဘက်ထရီ (ဆဲလ်)', 'မီးလုံး', 'ခလုတ်', 'ခုခံကိရိယာ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is the purpose of a switch in a circuit?',
        questionMy: 'ဆားကစ်ထဲရှိ ခလုတ်၏ ရည်ရွယ်ချက်မှာ အဘယ်နည်း။',
        optionsEn: [
          'To open or close the circuit',
          'To store electricity',
          'To increase voltage',
          'To produce light',
        ],
        optionsMy: [
          'ဆားကစ်ကို ဖွင့်ရန်သို့မဟုတ်ပိတ်ရန်',
          'လျှပ်စစ်ကို သိုလှောင်ရန်',
          'ဗို့အားကို တိုးမြှင့်ရန်',
          'အလင်းရောင် ထုတ်ရန်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What material is commonly used for wires because it conducts electricity well?',
        questionMy: 'လျှပ်စစ်ကို ကောင်းစွာကူးစက်နိုင်သောကြောင့် ကြေးနန်းများတွင် များသောအားဖြင့် အသုံးပြုသော ပစ္စည်းမှာ အဘယ်နည်း။',
        optionsEn: ['Copper', 'Rubber', 'Wood', 'Plastic'],
        optionsMy: ['ကြေး', 'ရော်ဘာ', 'သစ်သား', 'ပလတ်စတစ်'],
        correctIndex: 0,
      ),
    ],
  ),

  // ---- chemistry ----
  SecondaryActivityDef(
    id: 'mock-secondary1-chemistry-1',
    subject: 'chemistry',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'States of Matter',
    titleMy: 'ရုပ်ဝတ္ထု၏ အခြေအနေများ',
    descriptionEn: 'Explore solids, liquids, and gases and how particles behave in each state.',
    descriptionMy: 'အခဲ၊ အရည်နှင့် ဓာတ်ငွေ့များနှင့် အခြေအနေတစ်ခုစီတွင် အနုမြူများ၏ အပြုအမူကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'In which state of matter are particles most tightly packed and fixed in place?',
        questionMy: 'အနုမြူများသည် အနီးကပ်ဆုံးထိတွေ့ကာ တည်နေရာတွင် ပုံသေရှိနေသော ရုပ်ဝတ္ထုအခြေအနေမှာ အဘယ်နည်း။',
        optionsEn: ['Solid', 'Liquid', 'Gas', 'Plasma'],
        optionsMy: ['အခဲ', 'အရည်', 'ဓာတ်ငွေ့', 'ပလာစမာ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What happens to particles when a liquid is heated and becomes a gas?',
        questionMy: 'အရည်ကို ပူစေပြီး ဓာတ်ငွေ့ဖြစ်လာသောအခါ အနုမြူများ မည်သို့ဖြစ်သွားသနည်း။',
        optionsEn: [
          'They gain energy and move further apart',
          'They stop moving completely',
          'They become heavier',
          'They lose their mass',
        ],
        optionsMy: [
          'စွမ်းအင်ရရှိကာ ပိုကွာဝေးသွားသည်',
          'လုံးဝ ရွေ့လျားမှုရပ်သွားသည်',
          'ပိုလေးလာသည်',
          'အလေးချိန် ဆုံးရှုံးသွားသည်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which state of matter has no fixed shape and no fixed volume?',
        questionMy: 'ပုံသေပုံစံနှင့် ပုံသေထုထည် မရှိသော ရုပ်ဝတ္ထုအခြေအနေမှာ အဘယ်နည်း။',
        optionsEn: ['Gas', 'Solid', 'Liquid', 'Crystal'],
        optionsMy: ['ဓာတ်ငွေ့', 'အခဲ', 'အရည်', 'ပုလဲကျောက်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is the process called when a solid changes directly into a gas without becoming liquid?',
        questionMy: 'အခဲတစ်ခုသည် အရည်မဖြစ်ဘဲ ဓာတ်ငွေ့သို့ တိုက်ရိုက်ပြောင်းလဲခြင်းကို မည်သို့ခေါ်သနည်း။',
        optionsEn: ['Sublimation', 'Condensation', 'Freezing', 'Melting'],
        optionsMy: ['ရုန်းငွေ့ခြင်း', 'ရေငွေ့စွန်းခြင်း', 'အေးခဲခြင်း', 'အရည်ပျော်ခြင်း'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What name is given to the temperature at which a liquid turns into a gas?',
        questionMy: 'အရည်တစ်ခု ဓာတ်ငွေ့သို့ ပြောင်းလဲသည့် အပူချိန်ကို မည်သို့ခေါ်သနည်း။',
        optionsEn: ['Boiling point', 'Freezing point', 'Melting point', 'Dew point'],
        optionsMy: ['ဆူညံအပူချိန်', 'အေးခဲအပူချိန်', 'အရည်ပျော်အပူချိန်', 'နှင်းရည်ခေါင်းအပူချိန်'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-chemistry-2',
    subject: 'chemistry',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Elements, Compounds and Mixtures',
    titleMy: 'ဒြပ်စင်များ၊ ဒြပ်ပေါင်းများနှင့် ရောနှောပစ္စည်းများ',
    descriptionEn: 'Tell the difference between elements, compounds, and mixtures.',
    descriptionMy: 'ဒြပ်စင်၊ ဒြပ်ပေါင်းနှင့် ရောနှောပစ္စည်းများ၏ ကွာခြားချက်ကို ခွဲခြားသိမြင်ပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What is an element?',
        questionMy: 'ဒြပ်စင် ဆိုသည်မှာ အဘယ်နည်း။',
        optionsEn: [
          'A substance made of only one type of atom',
          'Two or more substances chemically joined',
          'Any mix of two liquids',
          'A substance that can be separated by filtering only',
        ],
        optionsMy: [
          'အနုမြူတစ်မျိုးတည်းဖြင့် ဖွဲ့စည်းထားသော ပစ္စည်း',
          'ဓာတုနည်းအားဖြင့် ပေါင်းစပ်ထားသော ပစ္စည်းနှစ်မျိုးသို့မဟုတ်ထို့ထက်ပို',
          'အရည်နှစ်မျိုးရောနှောမှု မည်သည့်ပုံစံမဆို',
          'စစ်ထုတ်ခြင်းဖြင့်သာ ပိုင်းခြားနိုင်သော ပစ္စည်း',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Water (H₂O) is an example of what?',
        questionMy: 'ရေ (H₂O) သည် မည်သည့်အရာ၏ ဥပမာဖြစ်သနည်း။',
        optionsEn: ['A compound', 'An element', 'A mixture only', 'A gas only'],
        optionsMy: ['ဒြပ်ပေါင်း', 'ဒြပ်စင်', 'ရောနှောပစ္စည်းသာ', 'ဓာတ်ငွေ့သာ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which of these is a mixture, not chemically bonded?',
        questionMy: 'ဓာတုနည်းဖြင့် မချိတ်ဆက်ထားဘဲ ရောနှောပစ္စည်းဖြစ်သည်မှာ အောက်ပါတို့တွင် အဘယ်နည်း။',
        optionsEn: ['Salt water', 'Carbon dioxide', 'Table salt', 'Water'],
        optionsMy: ['ဆားရေ', 'ကာဗွန်ဒိုင်အောက်ဆိုဒ်', 'စားသုံးဆား', 'ရေ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which method can separate the parts of a mixture but not a compound?',
        questionMy: 'ဒြပ်ပေါင်းကို မခွဲခြားနိုင်သော်လည်း ရောနှောပစ္စည်းကို ခွဲခြားနိုင်သော နည်းလမ်းမှာ အဘယ်နည်း။',
        optionsEn: [
          'Physical separation methods, e.g. filtering',
          'Nuclear reaction',
          'Combustion only',
          'Electrolysis of the compound',
        ],
        optionsMy: [
          'ရုပ်ပိုင်းဆိုင်ရာခွဲခြားနည်းများ၊ ဥပမာ- စစ်ထုတ်ခြင်း',
          'နျူကလီးယားတုံ့ပြန်မှု',
          'မီးလောင်ခြင်းသာ',
          'ဒြပ်ပေါင်း၏ လျှပ်စစ်ဓာတ်ခွဲခြင်း',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is the smallest particle that still keeps the properties of an element?',
        questionMy: 'ဒြပ်စင်တစ်ခု၏ ဂုဏ်သတ္တိကို ထိန်းသိမ်းထားနိုင်သေးသော အသေးငယ်ဆုံးအနုမြူမှာ အဘယ်နည်း။',
        optionsEn: ['Atom', 'Molecule', 'Cell', 'Mixture'],
        optionsMy: ['အက်တမ်', 'မော်လီကျူး', 'ဆဲလ်', 'ရောနှောပစ္စည်း'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-chemistry-3',
    subject: 'chemistry',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Separating Techniques',
    titleMy: 'ခွဲခြားနည်းများ',
    descriptionEn: 'Learn methods used to separate mixtures such as filtration, evaporation, and distillation.',
    descriptionMy: 'စစ်ထုတ်ခြင်း၊ ငွေ့ပျံခြင်းနှင့် ပြန်ခံနွှေးခြင်းကဲ့သို့ ရောနှောပစ္စည်းများကို ခွဲခြားရန် အသုံးပြုသောနည်းလမ်းများကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'Which method separates a solid from a liquid using a porous paper or mesh?',
        questionMy: 'အပေါက်ပါစက္ကူ သို့မဟုတ် ကွန်ရက်ဖြင့် အခဲကို အရည်မှ ခွဲခြားသောနည်းမှာ အဘယ်နည်း။',
        optionsEn: ['Filtration', 'Evaporation', 'Distillation', 'Magnetism'],
        optionsMy: ['စစ်ထုတ်ခြင်း', 'ငွေ့ပျံခြင်း', 'ပြန်ခံနွှေးခြင်း', 'သံလိုက်ဆွဲခြင်း'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which method is best for separating salt from salt water by heating away the water?',
        questionMy: 'ရေကို ငွေ့ပျံစေခြင်းဖြင့် ဆားရေမှ ဆားကို ခွဲခြားရန် အကောင်းဆုံးနည်းမှာ အဘယ်နည်း။',
        optionsEn: ['Evaporation', 'Filtration', 'Magnetic separation', 'Sieving'],
        optionsMy: ['ငွေ့ပျံခြင်း', 'စစ်ထုတ်ခြင်း', 'သံလိုက်ဖြင့်ခွဲခြားခြင်း', 'ချောစစ်ခြင်း'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What technique is used to separate two liquids with different boiling points?',
        questionMy: 'ဆူညံအပူချိန်ကွာခြားသော အရည်နှစ်မျိုးကို ခွဲခြားရန် အသုံးပြုသောနည်းစနစ်မှာ အဘယ်နည်း။',
        optionsEn: ['Distillation', 'Filtration', 'Sieving', 'Sedimentation'],
        optionsMy: ['ပြန်ခံနွှေးခြင်း', 'စစ်ထုတ်ခြင်း', 'ချောစစ်ခြင်း', 'အနည်ကျစေခြင်း'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which technique uses a magnet to remove iron filings from a mixture of sand and iron?',
        questionMy: 'သဲနှင့်သံဖုန်ရောနှောထားသော ပစ္စည်းမှ သံဖုန်ကို ဖယ်ရှားရန် သံလိုက်ကို အသုံးပြုသောနည်းစနစ်မှာ အဘယ်နည်း။',
        optionsEn: ['Magnetic separation', 'Distillation', 'Evaporation', 'Chromatography'],
        optionsMy: ['သံလိုက်ဖြင့်ခွဲခြားခြင်း', 'ပြန်ခံနွှေးခြင်း', 'ငွေ့ပျံခြင်း', 'ခရိုမက်တိုဂရပ်ဖီ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which technique separates different colored dyes in ink by how far they travel on paper?',
        questionMy: 'မှင်ထဲက အရောင်အမျိုးမျိုးကို စက္ကူပေါ်တွင် သွားရောက်နိုင်သောအကွာအဝေးအလိုက် ခွဲခြားသောနည်းစနစ်မှာ အဘယ်နည်း။',
        optionsEn: ['Chromatography', 'Filtration', 'Evaporation', 'Sieving'],
        optionsMy: ['ခရိုမက်တိုဂရပ်ဖီ', 'စစ်ထုတ်ခြင်း', 'ငွေ့ပျံခြင်း', 'ချောစစ်ခြင်း'],
        correctIndex: 0,
      ),
    ],
  ),

  // ---- biology ----
  SecondaryActivityDef(
    id: 'mock-secondary1-biology-1',
    subject: 'biology',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Cells and Organization',
    titleMy: 'ဆဲလ်များနှင့် ဖွဲ့စည်းပုံ',
    descriptionEn: 'Learn the basic structure of cells and how they organize into tissues and organs.',
    descriptionMy: 'ဆဲလ်များ၏ အခြေခံဖွဲ့စည်းပုံနှင့် ၎င်းတို့ တစ်ရှူးများနှင့် အင်္ဂါများအဖြစ် ဖွဲ့စည်းပုံကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What is the basic unit of life?',
        questionMy: 'အသက်ရှင်ခြင်း၏ အခြေခံယူနစ်မှာ အဘယ်နည်း။',
        optionsEn: ['The cell', 'The tissue', 'The organ', 'The atom'],
        optionsMy: ['ဆဲလ်', 'တစ်ရှူး', 'အင်္ဂါ', 'အက်တမ်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which part of a cell controls its activities and contains genetic material?',
        questionMy: 'ဆဲလ်၏ လုပ်ဆောင်ချက်များကို ထိန်းချုပ်ပြီး မျိုးရိုးဗီဇပါဝင်သော အစိတ်အပိုင်းမှာ အဘယ်နည်း။',
        optionsEn: ['Nucleus', 'Cell membrane', 'Cytoplasm', 'Cell wall'],
        optionsMy: ['နျူကလိယ', 'ဆဲလ်အခွံ', 'ဆဲလ်အတွင်းအရည်', 'ဆဲလ်နံရံ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What structure do plant cells have that animal cells do not?',
        questionMy: 'တိရစ္ဆာန်ဆဲလ်များတွင် မရှိဘဲ အပင်ဆဲလ်များတွင် ရှိသော ဖွဲ့စည်းပုံမှာ အဘယ်နည်း။',
        optionsEn: ['Cell wall and chloroplasts', 'Nucleus', 'Cytoplasm', 'Cell membrane'],
        optionsMy: ['ဆဲလ်နံရံနှင့် ခလိုရိုပလပ်', 'နျူကလိယ', 'ဆဲလ်အတွင်းအရည်', 'ဆဲလ်အခွံ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'A group of similar cells working together forms what?',
        questionMy: 'တူညီသောဆဲလ်များ အုပ်စုတစ်ခုက အတူတကွ လုပ်ဆောင်ခြင်းသည် မည်သည့်အရာကို ဖွဲ့စည်းသနည်း။',
        optionsEn: ['A tissue', 'An organ', 'An organism', 'A nucleus'],
        optionsMy: ['တစ်ရှူး', 'အင်္ဂါ', 'သက်ရှိသတ္တဝါ', 'နျူကလိယ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is the correct order of levels of organization from simplest to most complex?',
        questionMy: 'အရိုးရှင်းဆုံးမှ အရှုပ်ထွေးဆုံးအထိ ဖွဲ့စည်းပုံအဆင့်များ၏ မှန်ကန်သောအစီအစဉ်မှာ အဘယ်နည်း။',
        optionsEn: [
          'Cell, tissue, organ, organ system',
          'Organ, tissue, cell, organ system',
          'Organ system, organ, cell, tissue',
          'Tissue, organ system, cell, organ',
        ],
        optionsMy: [
          'ဆဲလ်၊ တစ်ရှူး၊ အင်္ဂါ၊ အင်္ဂါစနစ်',
          'အင်္ဂါ၊ တစ်ရှူး၊ ဆဲလ်၊ အင်္ဂါစနစ်',
          'အင်္ဂါစနစ်၊ အင်္ဂါ၊ ဆဲလ်၊ တစ်ရှူး',
          'တစ်ရှူး၊ အင်္ဂါစနစ်၊ ဆဲလ်၊ အင်္ဂါ',
        ],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-biology-2',
    subject: 'biology',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Classification of Living Things',
    titleMy: 'သက်ရှိများ၏ အုပ်စုခွဲခြားခြင်း',
    descriptionEn: 'Understand how scientists group living things by shared characteristics.',
    descriptionMy: 'သိပ္ပံပညာရှင်များသည် သက်ရှိများကို ဆက်စပ်ဂုဏ်သတ္တိအလိုက် မည်သို့ စုစည်းခွဲခြားသည်ကို နားလည်ပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'Why do scientists classify living things into groups?',
        questionMy: 'သိပ္ပံပညာရှင်များသည် သက်ရှိများကို အုပ်စုအလိုက် အဘယ်ကြောင့် ခွဲခြားကြသနည်း။',
        optionsEn: [
          'To organize and study them more easily based on shared features',
          'To make them look more colorful',
          'To reduce their population',
          'To give them the same name',
        ],
        optionsMy: [
          'ဆက်စပ်ဂုဏ်သတ္တိများအပေါ် အခြေခံ၍ ပိုမိုလွယ်ကူစွာ စီစဉ်လေ့လာရန်',
          'ပိုအရောင်စုံစေရန်',
          'ရေအစုအဝေးလျှော့ချရန်',
          'တူညီသောအမည် ပေးရန်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which of these is a main group (kingdom) of living things?',
        questionMy: 'အောက်ပါတို့တွင် သက်ရှိများ၏ အဓိကအုပ်စု (ဆွန်းနိုင်ငံ) တစ်ခုမှာ အဘယ်နည်း။',
        optionsEn: ['Animals', 'Rocks', 'Water', 'Weather'],
        optionsMy: ['တိရစ္ဆာန်', 'ကျောက်', 'ရေ', 'ရာသီဥတု'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What key feature distinguishes vertebrates from invertebrates?',
        questionMy: 'ကျောရိုးရှိသတ္တဝါများနှင့် ကျောရိုးမဲ့သတ္တဝါများကို ခွဲခြားပေးသော အဓိကလက္ခဏာမှာ အဘယ်နည်း။',
        optionsEn: [
          'Vertebrates have a backbone, invertebrates do not',
          'Vertebrates live in water only',
          'Invertebrates are always larger',
          'Vertebrates cannot move',
        ],
        optionsMy: [
          'ကျောရိုးရှိသတ္တဝါများတွင် ကျောရိုးရှိပြီး ကျောရိုးမဲ့သတ္တဝါများတွင် မရှိပါ',
          'ကျောရိုးရှိသတ္တဝါများသည် ရေတွင်သာ နေထိုင်သည်',
          'ကျောရိုးမဲ့သတ္တဝါများသည် အမြဲကြီးမားသည်',
          'ကျောရိုးရှိသတ္တဝါများသည် မရွေ့လျားနိုင်ပါ',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which of these animals is classified as a reptile?',
        questionMy: 'အောက်ပါတိရစ္ဆာန်များထဲမှ တွားသွားသတ္တဝါ (reptile) အဖြစ် ခွဲခြားထားသည်မှာ အဘယ်နည်း။',
        optionsEn: ['Snake', 'Dog', 'Eagle', 'Frog'],
        optionsMy: ['မြွေ', 'ခွေး', 'လင်းယုန်', 'ဖား'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Plants and animals are both classified as living things because they share which feature?',
        questionMy: 'အပင်နှင့် တိရစ္ဆာန်နှစ်မျိုးလုံးကို သက်ရှိများအဖြစ် ခွဲခြားထားရသည်မှာ မည်သည့်ဂုဏ်သတ္တိကို ဆက်စပ်ထားသောကြောင့်နည်း။',
        optionsEn: [
          'They can grow, reproduce, and respond to their environment',
          'They both eat sunlight directly',
          'They both have backbones',
          'They both live only on land',
        ],
        optionsMy: [
          'ကြီးထွားနိုင်ခြင်း၊ မျိုးပွားနိုင်ခြင်းနှင့် ပတ်ဝန်းကျင်ကို တုံ့ပြန်နိုင်ခြင်း',
          'နှစ်ခုစလုံး နေရောင်ခြည်ကို တိုက်ရိုက်စားသောကြောင့်',
          'နှစ်ခုစလုံး ကျောရိုးရှိသောကြောင့်',
          'နှစ်ခုစလုံး ကုန်းပေါ်တွင်သာ နေထိုင်သောကြောင့်',
        ],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-biology-3',
    subject: 'biology',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Introduction to Human Body Systems',
    titleMy: 'လူ့ခန္ဓာကိုယ်စနစ်များ နိဒါန်း',
    descriptionEn: 'Learn the basic roles of the digestive, circulatory, and respiratory systems.',
    descriptionMy: 'အစာချေဖျက်စနစ်၊ သွေးလှည့်ပတ်စနစ်နှင့် အသက်ရှူစနစ်တို့၏ အခြေခံလုပ်ငန်းဆောင်တာများကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'Which body system breaks down food so the body can use it?',
        questionMy: 'ခန္ဓာကိုယ်က အသုံးပြုနိုင်ရန် အစားအစာကို ပြိုကွဲစေသော စနစ်မှာ အဘယ်နည်း။',
        optionsEn: [
          'The digestive system',
          'The circulatory system',
          'The respiratory system',
          'The skeletal system',
        ],
        optionsMy: [
          'အစာချေဖျက်စနစ်',
          'သွေးလှည့်ပတ်စနစ်',
          'အသက်ရှူစနစ်',
          'အရိုးစနစ်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which organ pumps blood around the body?',
        questionMy: 'ခန္ဓာကိုယ်တစ်ဝှမ်း သွေးကို စုပ်တွန်းပေးသော အင်္ဂါမှာ အဘယ်နည်း။',
        optionsEn: ['The heart', 'The lungs', 'The stomach', 'The liver'],
        optionsMy: ['နှလုံး', 'အဆုတ်', 'အစာအိမ်', 'အသည်း'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which organs are mainly responsible for taking in oxygen and releasing carbon dioxide?',
        questionMy: 'အောက်ဆီဂျင်ကို စုပ်ယူပြီး ကာဗွန်ဒိုင်အောက်ဆိုဒ်ကို ထုတ်လွှတ်ရန် အဓိကတာဝန်ရှိသော အင်္ဂါများမှာ အဘယ်နည်း။',
        optionsEn: ['The lungs', 'The heart', 'The stomach', 'The kidneys'],
        optionsMy: ['အဆုတ်', 'နှလုံး', 'အစာအိမ်', 'ကျောက်ကပ်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is the main role of the circulatory system?',
        questionMy: 'သွေးလှည့်ပတ်စနစ်၏ အဓိကလုပ်ငန်းတာဝန်မှာ အဘယ်နည်း။',
        optionsEn: [
          'To transport blood, oxygen, and nutrients around the body',
          'To digest food',
          'To filter air only',
          'To control body movement',
        ],
        optionsMy: [
          'ခန္ဓာကိုယ်တစ်ဝှမ်း သွေး၊ အောက်ဆီဂျင်နှင့် အာဟာရများကို သယ်ဆောင်ပေးရန်',
          'အစားအစာကို ချေဖျက်ရန်',
          'လေကိုသာ စစ်ထုတ်ရန်',
          'ခန္ဓာကိုယ်ရွေ့လျားမှုကို ထိန်းချုပ်ရန်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which of these correctly describes the path air takes when breathing in?',
        questionMy: 'အသက်ရှုသွင်းသည့်အခါ လေသွားလာသည့်လမ်းကြောင်းကို မှန်ကန်စွာဖော်ပြသည်မှာ အဘယ်နည်း။',
        optionsEn: [
          'Nose, windpipe, lungs',
          'Lungs, windpipe, nose',
          'Nose, stomach, lungs',
          'Windpipe, heart, lungs',
        ],
        optionsMy: [
          'နှာခေါင်း၊ လေပြွန်၊ အဆုတ်',
          'အဆုတ်၊ လေပြွန်၊ နှာခေါင်း',
          'နှာခေါင်း၊ အစာအိမ်၊ အဆုတ်',
          'လေပြွန်၊ နှလုံး၊ အဆုတ်',
        ],
        correctIndex: 0,
      ),
    ],
  ),

  // ---- ict ----
  SecondaryActivityDef(
    id: 'mock-secondary1-ict-1',
    subject: 'ict',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Computer Systems and Hardware',
    titleMy: 'ကွန်ပျူတာစနစ်နှင့် ဟာ့ဒ်ဝဲ',
    descriptionEn: 'Learn the main hardware parts of a computer and what each one does.',
    descriptionMy: 'ကွန်ပျူတာ၏ အဓိကဟာ့ဒ်ဝဲအစိတ်အပိုင်းများနှင့် ၎င်းတို့၏ လုပ်ဆောင်ချက်များကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What part of a computer is often called its "brain"?',
        questionMy: 'ကွန်ပျူတာ၏ "ဦးနှောက်" ဟုခေါ်လေ့ရှိသော အစိတ်အပိုင်းမှာ အဘယ်နည်း။',
        optionsEn: ['CPU (Central Processing Unit)', 'Monitor', 'Keyboard', 'Mouse'],
        optionsMy: ['CPU (ဗဟိုစီမံဆောင်ရွက်ရေးယူနစ်)', 'မော်နီတာ', 'ကီးဘုတ်', 'မောက်စ်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which device is used to permanently store files even when the computer is off?',
        questionMy: 'ကွန်ပျူတာပိတ်ထားချိန်တွင်ပင် ဖိုင်များကို အမြဲသိမ်းဆည်းထားရန် အသုံးပြုသော ကိရိယာမှာ အဘယ်နည်း။',
        optionsEn: ['Hard disk (storage drive)', 'RAM', 'Monitor', 'Speaker'],
        optionsMy: ['ဟတ်ဒစ် (သိုလှောင်ကွန်ရက်)', 'RAM', 'မော်နီတာ', 'စပီကာ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is an example of an input device?',
        questionMy: 'အင်ပွတ်ကိရိယာ၏ ဥပမာတစ်ခုမှာ အဘယ်နည်း။',
        optionsEn: ['Keyboard', 'Printer', 'Monitor', 'Speaker'],
        optionsMy: ['ကီးဘုတ်', 'ပရင်တာ', 'မော်နီတာ', 'စပီကာ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is an example of an output device?',
        questionMy: 'အောက်ပွတ်ကိရိယာ၏ ဥပမာတစ်ခုမှာ အဘယ်နည်း။',
        optionsEn: ['Printer', 'Keyboard', 'Mouse', 'Scanner'],
        optionsMy: ['ပရင်တာ', 'ကီးဘုတ်', 'မောက်စ်', 'စကင်နာ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What does RAM stand for and mainly do in a computer?',
        questionMy: 'RAM ၏ အဓိပ္ပါယ်ဖော်ပြသည့်စကားလုံးများနှင့် ကွန်ပျူတာတွင် အဓိကလုပ်ဆောင်ချက်မှာ အဘယ်နည်း။',
        optionsEn: [
          'Random Access Memory -- temporarily stores data being used',
          'Read Access Machine -- prints documents',
          'Rapid Application Module -- runs the internet',
          'Remote Audio Monitor -- plays sound',
        ],
        optionsMy: [
          'Random Access Memory -- အသုံးပြုနေသော ဒေတာကို ယာယီသိမ်းဆည်းသည်',
          'Read Access Machine -- စာရွက်စာတမ်း ပရင့်ထုတ်သည်',
          'Rapid Application Module -- အင်တာနက်ကို ဖွင့်ပေးသည်',
          'Remote Audio Monitor -- အသံဖွင့်ပေးသည်',
        ],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-ict-2',
    subject: 'ict',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Data Representation Basics',
    titleMy: 'ဒေတာဖော်ပြမှု အခြေခံများ',
    descriptionEn: 'Understand how computers represent data using bits, bytes, and binary numbers.',
    descriptionMy: 'ကွန်ပျူတာများသည် ဘစ်၊ ဘိုက်နှင့် ဘိုင်နရီကိန်းများကို အသုံးပြု၍ ဒေတာကို မည်သို့ ဖော်ပြသည်ကို နားလည်ပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What is the smallest unit of data in a computer?',
        questionMy: 'ကွန်ပျူတာတွင် ဒေတာ၏ အသေးငယ်ဆုံးယူနစ်မှာ အဘယ်နည်း။',
        optionsEn: ['A bit', 'A byte', 'A file', 'A folder'],
        optionsMy: ['ဘစ်', 'ဘိုက်', 'ဖိုင်', 'ဖိုလ်ဒါ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'How many bits make up one byte?',
        questionMy: 'ဘိုက်တစ်ခုတွင် ဘစ်မည်မျှ ပါဝင်သနည်း။',
        optionsEn: ['8', '4', '16', '2'],
        optionsMy: ['8', '4', '16', '2'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Computers store and process all data using which number system?',
        questionMy: 'ကွန်ပျူတာများသည် ဒေတာအားလုံးကို မည်သည့်ကိန်းစနစ်ဖြင့် သိမ်းဆည်းစီမံသနည်း။',
        optionsEn: ['Binary (base 2)', 'Decimal (base 10)', 'Roman numerals', 'Hexagon system'],
        optionsMy: ['ဘိုင်နရီ (base 2)', 'ဒဿမ (base 10)', 'ရိုမန်ကိန်းများ', 'ဟက်ဇဂွန်စနစ်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What two digits are used in binary code?',
        questionMy: 'ဘိုင်နရီကုဒ်တွင် အသုံးပြုသော ဂဏန်းနှစ်လုံးမှာ အဘယ်နည်း။',
        optionsEn: ['0 and 1', '1 and 2', '0 and 9', '1 and 10'],
        optionsMy: ['0 နှင့် 1', '1 နှင့် 2', '0 နှင့် 9', '1 နှင့် 10'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Roughly how many bytes are in one kilobyte (KB)?',
        questionMy: 'ကီလိုဘိုက် (KB) တစ်ခုတွင် ဘိုက် မည်မျှ ခန့်မှန်းရှိသနည်း။',
        optionsEn: ['1,024', '100', '10', '1,000,000'],
        optionsMy: ['1,024', '100', '10', '1,000,000'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-ict-3',
    subject: 'ict',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Internet Safety',
    titleMy: 'အင်တာနက် ဘေးကင်းလုံခြုံမှု',
    descriptionEn: 'Learn how to stay safe online, protect personal information, and recognize risks.',
    descriptionMy: 'အွန်လိုင်းတွင် ဘေးကင်းစွာနေထိုင်ရန်၊ ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ကာကွယ်ရန်နှင့် အန္တရာယ်များကို သိရှိနိုင်ရန် လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What should you do if a stranger online asks for your home address?',
        questionMy: 'အွန်လိုင်းရှိ လူစိမ်းတစ်ဦးက သင့်နေအိမ်လိပ်စာကို တောင်းလျှင် သင်မည်သို့ ပြုလုပ်သင့်သနည်း။',
        optionsEn: [
          'Refuse to share it and tell a trusted adult',
          'Give it to them right away',
          'Ask them for their address too',
          'Ignore the message but keep chatting',
        ],
        optionsMy: [
          'မပေးဘဲ ယုံကြည်ရသော အသက်ကြီးသူတစ်ဦးအား ပြောပြပါ',
          'ချက်ချင်း ပေးလိုက်ပါ',
          'သူတို့လိပ်စာကို ပြန်တောင်းပါ',
          'စာကို လျစ်လျူရှုပြီး ဆက်စကားပြောပါ',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What makes a password strong and safe to use?',
        questionMy: 'စကားဝှက်တစ်ခုကို ခိုင်မာပြီး လုံခြုံစွာ အသုံးပြုနိုင်စေသည့်အချက်မှာ အဘယ်နည်း။',
        optionsEn: [
          'A mix of letters, numbers, and symbols that is hard to guess',
          'Your own name only',
          'The word "password"',
          'Your birth year only',
        ],
        optionsMy: [
          'ခန့်မှန်းရခက်သော စာလုံး၊ ဂဏန်းနှင့် သင်္ကေတများ ရောနှောထားခြင်း',
          'သင့်ကိုယ်ပိုင်အမည်သာ',
          '"password" ဟူသောစကားလုံး',
          'သင်၏မွေးနှစ်သာ',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is "cyberbullying"?',
        questionMy: '"cyberbullying" ဆိုသည်မှာ အဘယ်နည်း။',
        optionsEn: [
          'Using the internet or phones to repeatedly hurt or threaten someone',
          'Playing online games with friends',
          'Sending a birthday message to a classmate',
          'Learning a new skill online',
        ],
        optionsMy: [
          'အင်တာနက် သို့မဟုတ် ဖုန်းများကို အသုံးပြု၍ တစ်စုံတစ်ဦးအား ထပ်ခါထပ်ခါ နာကျင်စေခြင်း သို့မဟုတ် ခြိမ်းခြောက်ခြင်း',
          'သူငယ်ချင်းများနှင့် အွန်လိုင်းဂိမ်း ကစားခြင်း',
          'အတန်းဖော်တစ်ဦးထံ မွေးနေ့ဆုံသို့ ပို့ခြင်း',
          'အွန်လိုင်းတွင် အသစ်သောကျွမ်းကျင်မှု လေ့လာခြင်း',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Before clicking a link from an unknown email, what should you do first?',
        questionMy: 'မသိသောအီးမေးလ်မှ လင့်ခ်ကို မနှိပ်မီ သင်ဦးစွာ မည်သို့ ပြုလုပ်သင့်သနည်း။',
        optionsEn: [
          'Check if the sender and link look suspicious before clicking',
          'Click it immediately to see what it is',
          'Forward it to all your friends',
          'Reply with your password',
        ],
        optionsMy: [
          'မနှိပ်မီ ပေးပို့သူနှင့် လင့်ခ်ကို သံသယဖြစ်ဖွယ်ရှိမရှိ စစ်ဆေးပါ',
          'ချက်ချင်းနှိပ်ကြည့်ပါ',
          'သူငယ်ချင်းအားလုံးထံ ပို့ပေးပါ',
          'စကားဝှက်ဖြင့် ပြန်စာပေးပါ',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which of the following is personal information you should keep private online?',
        questionMy: 'အောက်ပါအထဲမှ အွန်လိုင်းတွင် လျှို့ဝှက်ထားသင့်သော ကိုယ်ရေးကိုယ်တာအချက်အလက်မှာ အဘယ်နည်း။',
        optionsEn: [
          'Your full name, school, and phone number',
          'Your favorite color',
          'Your favorite movie',
          'The weather today',
        ],
        optionsMy: [
          'သင်၏ အမည်အပြည့်၊ ကျောင်းနှင့် ဖုန်းနံပါတ်',
          'သင်ကြိုက်သောအရောင်',
          'သင်ကြိုက်သောရုပ်ရှင်',
          'ယနေ့ ရာသီဥတု',
        ],
        correctIndex: 0,
      ),
    ],
  ),

  // ---- socialstudies ----
  SecondaryActivityDef(
    id: 'mock-secondary1-socialstudies-1',
    subject: 'socialstudies',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Myanmar Geography',
    titleMy: 'မြန်မာနိုင်ငံ၏ ပထဝီဝင်',
    descriptionEn: 'Learn about the regions, rivers, and neighboring countries of Myanmar.',
    descriptionMy: 'မြန်မာနိုင်ငံ၏ ဒေသများ၊ မြစ်များနှင့် အိမ်နီးချင်းနိုင်ငံများအကြောင်း လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What is the longest river in Myanmar?',
        questionMy: 'မြန်မာနိုင်ငံ၏ အရှည်ဆုံးမြစ်မှာ အဘယ်နည်း။',
        optionsEn: ['The Ayeyarwady River', 'The Sittaung River', 'The Thanlwin River', 'The Chindwin River'],
        optionsMy: ['ဧရာဝတီမြစ်', 'စစ်တောင်းမြစ်', 'သံလွင်မြစ်', 'ချင်းတွင်းမြစ်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which country lies to the north of Myanmar?',
        questionMy: 'မြန်မာနိုင်ငံ၏ မြောက်ဘက်တွင် တည်ရှိသော နိုင်ငံမှာ အဘယ်နည်း။',
        optionsEn: ['China', 'Thailand', 'Bangladesh', 'Laos'],
        optionsMy: ['တရုတ်', 'ထိုင်း', 'ဘင်္ဂလားဒေ့ရှ်', 'လာအို'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which sea/bay lies along Myanmar\'s southern and western coastline?',
        questionMy: 'မြန်မာနိုင်ငံ၏ တောင်ဘက်နှင့် အနောက်ဘက်ကမ်းရိုးတန်းတလျှောက် တည်ရှိသော ပင်လယ်/ပင်လယ်အော်မှာ အဘယ်နည်း။',
        optionsEn: ['The Andaman Sea and Bay of Bengal', 'The South China Sea', 'The Arabian Sea', 'The Yellow Sea'],
        optionsMy: ['အန္ဒမန်ပင်လယ်နှင့် ဘင်္ဂေါလ်ပင်လယ်အော်', 'တောင်တရုတ်ပင်လယ်', 'အာရေဗျပင်လယ်', 'ဝါပင်လယ်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which of these is one of Myanmar\'s major mountain ranges?',
        questionMy: 'အောက်ပါတို့တွင် မြန်မာနိုင်ငံ၏ အဓိကတောင်တန်းတစ်ခုမှာ အဘယ်နည်း။',
        optionsEn: ['The Shan Hills', 'The Andes', 'The Alps', 'The Rockies'],
        optionsMy: ['ရှမ်းကုန်းရိုးတန်း', 'အင်ဒီးစ်တောင်တန်း', 'အယ်လ်ပ်တောင်တန်း', 'ရော့ကီတောင်တန်း'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Myanmar is located in which region of the world?',
        questionMy: 'မြန်မာနိုင်ငံသည် ကမ္ဘာ့မည်သည့်ဒေသတွင် တည်ရှိသနည်း။',
        optionsEn: ['Southeast Asia', 'East Africa', 'South America', 'Western Europe'],
        optionsMy: ['အရှေ့တောင်အာရှ', 'အရှေ့အာဖရိက', 'တောင်အမေရိက', 'အနောက်ဥရောပ'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-socialstudies-2',
    subject: 'socialstudies',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'World Geography',
    titleMy: 'ကမ္ဘာ့ပထဝီဝင်',
    descriptionEn: 'Explore continents, oceans, and major geographic features around the world.',
    descriptionMy: 'ကမ္ဘာတစ်ဝှမ်းရှိ တိုက်ကြီးများ၊ သမုဒ္ဒရာများနှင့် အဓိကပထဝီဝင်လက္ခဏာများကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'How many continents are there in the world?',
        questionMy: 'ကမ္ဘာပေါ်တွင် တိုက်ကြီးမည်မျှ ရှိသနည်း။',
        optionsEn: ['7', '5', '6', '9'],
        optionsMy: ['7', '5', '6', '9'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which is the largest continent by land area?',
        questionMy: 'မြေဧရိယာအလိုက် အကြီးဆုံးတိုက်မှာ အဘယ်နည်း။',
        optionsEn: ['Asia', 'Africa', 'Europe', 'Australia'],
        optionsMy: ['အာရှတိုက်', 'အာဖရိကတိုက်', 'ဥရောပတိုက်', 'သြစတြေးလျတိုက်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is the longest river in the world?',
        questionMy: 'ကမ္ဘာပေါ်ရှိ အရှည်ဆုံးမြစ်မှာ အဘယ်နည်း။',
        optionsEn: ['The Nile River', 'The Amazon River', 'The Yangtze River', 'The Mississippi River'],
        optionsMy: ['နိုင်းမြစ်', 'အမေဇုန်းမြစ်', 'ယန်စီမြစ်', 'မစ္စစ္စပီမြစ်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which mountain is known as the tallest in the world?',
        questionMy: 'ကမ္ဘာပေါ်တွင် အမြင့်ဆုံးအဖြစ် လူသိများသောတောင်မှာ အဘယ်နည်း။',
        optionsEn: ['Mount Everest', 'Mount Kilimanjaro', 'Mount Fuji', 'Mount Elbrus'],
        optionsMy: ['ဧဝရက်တောင်', 'ကီလီမန်ဂျာရိုတောင်', 'ဖူဂျီတောင်', 'အယ်ဘရပ်စ်တောင်'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which ocean is the largest on Earth?',
        questionMy: 'ကမ္ဘာပေါ်ရှိ အကြီးဆုံးသမုဒ္ဒရာမှာ အဘယ်နည်း။',
        optionsEn: ['The Pacific Ocean', 'The Atlantic Ocean', 'The Indian Ocean', 'The Arctic Ocean'],
        optionsMy: ['ပစိဖိတ်သမုဒ္ဒရာ', 'အတ္လန္တိတ်သမုဒ္ဒရာ', 'အိန္ဒိယသမုဒ္ဒရာ', 'အာတိတ်သမုဒ္ဒရာ'],
        correctIndex: 0,
      ),
    ],
  ),
  SecondaryActivityDef(
    id: 'mock-secondary1-socialstudies-3',
    subject: 'socialstudies',
    grade: Grade.secondary1,
    contentType: 'quiz',
    titleEn: 'Government and Citizenship',
    titleMy: 'အစိုးရနှင့် နိုင်ငံသားဖြစ်မှု',
    descriptionEn: 'Learn what government does and what it means to be a responsible citizen.',
    descriptionMy: 'အစိုးရ၏ လုပ်ငန်းတာဝန်များနှင့် တာဝန်သိသောနိုင်ငံသားတစ်ဦးဖြစ်ခြင်း၏ အဓိပ္ပာယ်ကို လေ့လာပါ။',
    starsReward: 22,
    questions: [
      QuizQuestion(
        questionEn: 'What is one main role of a government?',
        questionMy: 'အစိုးရ၏ အဓိကလုပ်ငန်းတာဝန်တစ်ခုမှာ အဘယ်နည်း။',
        optionsEn: [
          'To make and enforce laws for the country',
          'To sell food in markets',
          'To write novels',
          'To play sports professionally',
        ],
        optionsMy: [
          'နိုင်ငံအတွက် ဥပဒေများ ရေးဆွဲအကောင်အထည်ဖော်ရန်',
          'ဈေးများတွင် အစားအစာရောင်းရန်',
          'ဝတ္ထုများ ရေးသားရန်',
          'အားကစားကို ပရော်ဖက်ရှင်နယ်အနေဖြင့် ကစားရန်',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What is a "citizen"?',
        questionMy: '"နိုင်ငံသား" ဆိုသည်မှာ အဘယ်နည်း။',
        optionsEn: [
          'A legally recognized member of a country with rights and duties',
          'Anyone visiting a country for a holiday',
          'A person who owns a business',
          'A person who works for the government only',
        ],
        optionsMy: [
          'အခွင့်အရေးနှင့် တာဝန်ဝတ္တရားများပါရှိသော နိုင်ငံ၏ တရားဝင်အသိအမှတ်ပြုအဖွဲ့ဝင်',
          'ခရီးသွားရန် နိုင်ငံသို့ လာရောက်သူ မည်သူမဆို',
          'စီးပွားရေးလုပ်ငန်းပိုင်ဆိုင်သူ',
          'အစိုးရအတွက်သာ အလုပ်လုပ်သူ',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Which of these is a responsibility of a good citizen?',
        questionMy: 'ကောင်းမွန်သောနိုင်ငံသားတစ်ဦး၏ တာဝန်တစ်ခုမှာ အောက်ပါတို့တွင် အဘယ်နည်း။',
        optionsEn: [
          'Obeying the laws of the country',
          'Ignoring community rules',
          'Avoiding all public duties',
          'Refusing to help others',
        ],
        optionsMy: [
          'နိုင်ငံ၏ ဥပဒေများကို လိုက်နာခြင်း',
          'ရပ်ရွာစည်းကမ်းများကို လျစ်လျူရှုခြင်း',
          'အများပြည်သူဆိုင်ရာတာဝန်များကို ရှောင်ရှားခြင်း',
          'သူတစ်ပါးကို ကူညီရန် ငြင်းဆန်ခြင်း',
        ],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'What do we call the basic rules that a country is governed by?',
        questionMy: 'နိုင်ငံတစ်ခု အုပ်ချုပ်ခံရသည့် အခြေခံစည်းမျဉ်းများကို မည်သို့ခေါ်သနည်း။',
        optionsEn: ['The constitution', 'The dictionary', 'The textbook', 'The newspaper'],
        optionsMy: ['ဖွဲ့စည်းပုံအခြေခံဥပဒေ', 'အဘိဓာန်', 'သင်ရိုးစာအုပ်', 'သတင်းစာ'],
        correctIndex: 0,
      ),
      QuizQuestion(
        questionEn: 'Why is voting in elections an important civic duty?',
        questionMy: 'ရွေးကောက်ပွဲများတွင် မဲပေးခြင်းသည် အရေးကြီးသော နိုင်ငံသားတာဝန်တစ်ခု ဖြစ်ရသည့်အကြောင်းရင်းမှာ အဘယ်နည်း။',
        optionsEn: [
          'It lets citizens choose leaders who represent their interests',
          'It is required to get a job',
          'It replaces paying taxes',
          'It only matters in large cities',
        ],
        optionsMy: [
          'နိုင်ငံသားများအား ၎င်းတို့အကျိုးစီးပွားကို ကိုယ်စားပြုမည့် ခေါင်းဆောင်များကို ရွေးချယ်ခွင့်ပေးသောကြောင့်',
          'အလုပ်ရရန်အတွက် လိုအပ်သောကြောင့်',
          'အခွန်ပေးဆောင်ခြင်းကို အစားထိုးသောကြောင့်',
          'မြို့ကြီးများတွင်သာ အရေးပါသောကြောင့်',
        ],
        correctIndex: 0,
      ),
    ],
  ),
];
