// File: ai_data_bridge/igcse_economics_all_terms.dart
// IGCSE Economics Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseEconomicsAllTermsData = [
  // ================= TERM 1: The Basic Economic Problem =================
  {
    "week": 1,
    "term": 1,
    "theme": "Microeconomics",
    "title_en": "The Basic Economic Problem",
    "title_my": "အခြေခံ စီးပွားရေး ပြဿနာ",
    "topics": [
      "Scarcity and Choice",
      "Opportunity Cost",
      "Factors of Production",
    ],
    "description_en":
        "Understand the fundamental economic problem of unlimited wants versus scarce resources and the concept of opportunity cost.",
    "description_my":
        "အကန့်အသတ်မရှိသော လူတို့၏ဆန္ဒနှင့် ရှားပါးသော အရင်းအမြစ်များကြားရှိ အခြေခံ စီးပွားရေးပြဿနာနှင့် အခွင့်အလမ်း ကုန်ကျစရိတ်ကို နားလည်စေမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Microeconomics",
    "title_en": "Production Possibility Curves (PPC)",
    "title_my": "ထုတ်လုပ်နိုင်စွမ်း ဖြစ်တန်စွမ်း မျဉ်းကွေးများ (PPC)",
    "topics": [
      "PPC Diagrams",
      "Economic Growth and Decline",
      "Opportunity Cost on PPC",
    ],
    "description_en":
        "Analyze production possibility curves to illustrate economic choices, growth, and the reallocation of resources.",
    "description_my":
        "စီးပွားရေး ရွေးချယ်မှုများ၊ တိုးတက်မှုနှင့် အရင်းအမြစ်များ ပြန်လည်ခွဲဝေမှုကို ဖော်ပြရန် PPC ဂရပ်များကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Microeconomics",
    "title_en": "Economic Systems",
    "title_my": "စီးပွားရေး စနစ်များ",
    "topics": ["Market Economy", "Planned Economy", "Mixed Economy"],
    "description_en":
        "Compare how different economic systems (market, planned, and mixed) solve the core economic questions.",
    "description_my":
        "စျေးကွက်စီးပွားရေး၊ စီမံကိန်းစီးပွားရေးနှင့် ရောနှောစီးပွားရေးစနစ်များက အဓိက စီးပွားရေး မေးခွန်းများကို မည်သို့ဖြေရှင်းကြောင်း နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Economic Systems Case Study",
    "title_my": "စီးပွားရေးစနစ်များ လက်တွေ့လေ့လာမှု ပရောဂျက်",
    "topics": [
      "Resource Allocation Evaluation",
      "Role of Government",
      "Comparative Analysis",
    ],
    "description_en":
        "Evaluate how various nations allocate resources and the efficiency of different economic models.",
    "description_my":
        "နိုင်ငံအမျိုးမျိုးက အရင်းအမြစ်များကို မည်သို့ခွဲဝေကြောင်းနှင့် စီးပွားရေး မော်ဒယ်လ်များ၏ ထိရောက်မှုကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 2: The Allocation of Resources =================
  {
    "week": 5,
    "term": 2,
    "theme": "Microeconomics",
    "title_en": "Demand and Supply Analysis",
    "title_my": "တောင်းဆိုမှုနှင့် ထောက်ပံ့မှု ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": ["Law of Demand", "Law of Supply", "Market Equilibrium"],
    "description_en":
        "Examine the forces of demand and supply, price determination, and equilibrium in free markets.",
    "description_my":
        "တောင်းဆိုမှုနှင့် ထောက်ပံ့မှု အခြေအနေများ၊ ဈေးနှုန်းသတ်မှတ်ခြင်းနှင့် လွတ်လပ်သော စျေးကွက်အတွင်း ညီမျှခြင်းဖြစ်ပေါ်မှုကို လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Microeconomics",
    "title_en": "Price Elasticity of Demand (PED)",
    "title_my": "တောင်းဆိုမှု၏ ဈေးနှုန်း တုံ့ပြန်မှုနှုန်း (PED)",
    "topics": [
      "Calculating PED",
      "Elastic vs Inelastic Demand",
      "Revenue Implications",
    ],
    "description_en":
        "Calculate price elasticity of demand and understand its significance for business pricing strategies.",
    "description_my":
        "PED ကို တွက်ချက်ခြင်းနှင့် လုပ်ငန်းများ၏ ဈေးနှုန်း သတ်မှတ်ရေး မဟာဗျူဟာများအတွက် ၎င်း၏ အရေးပါမှုကို နားလည်စေမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Microeconomics",
    "title_en": "Price Elasticity of Supply (PES)",
    "title_my": "ထောက်ပံ့မှု၏ ဈေးနှုန်း တုံ့ပြန်မှုနှုန်း (PES)",
    "topics": [
      "Calculating PES",
      "Factors Affecting Supply Elasticity",
      "Time and Production Constraints",
    ],
    "description_en":
        "Explore price elasticity of supply and how quickly producers can respond to price changes.",
    "description_my":
        "PES ကို စူးစမ်းခြင်းနှင့် ထုတ်လုပ်သူများသည် ဈေးနှုန်းပြောင်းလဲမှုအပေါ် မည်မျှမြန်ဆန်စွာ တုံ့ပြန်နိုင်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Market Intervention and Price Controls",
    "title_my":
        "စျေးကွက်အတွင်း အစိုးရ ဝင်ရောက်စွက်ဖက်ခြင်းနှင့် ဈေးနှုန်း ထိန်းချုပ်မှုများ",
    "topics": [
      "Maximum and Minimum Prices",
      "Taxes and Subsidies",
      "Market Failure Introduction",
    ],
    "description_en":
        "Analyze the impact of government price controls, indirect taxes, and subsidies on market outcomes.",
    "description_my":
        "အစိုးရ၏ ဈေးနှုန်းထိန်းချုပ်မှုများ၊ သွယ်ဝိုက်အခွန်များနှင့် ထောက်ပံ့ကြေးများ၏ စျေးကွက်ရလဒ်အပေါ် သက်ရောက်မှုကို ခွဲခြမ်းမည်။",
  },

  // ================= TERM 3: Microeconomic Decision Makers =================
  {
    "week": 9,
    "term": 3,
    "theme": "Microeconomics",
    "title_en": "Households and Workers",
    "title_my": "အိမ်ထောင်စုများနှင့် အလုပ်သမားများ",
    "topics": [
      "Factors Affecting Spending and Saving",
      "Wage Determination",
      "Trade Unions",
    ],
    "description_en":
        "Examine what influences household spending/saving patterns and how wages are determined in labor markets.",
    "description_my":
        "အိမ်ထောင်စုများ၏ သုံးစွဲမှု/စုဆောင်းမှု ပုံစံအပေါ် သက်ရောက်သည့် အကြောင်းရင်းများနှင့် လုပ်အားစျေးကွက်တွင် လုပ်ခလစာ သတ်မှတ်ပုံကို လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Microeconomics",
    "title_en": "Firms and Production Costs",
    "title_my": "ကုမ္ပဏီများနှင့် ထုတ်လုပ်မှု ကုန်ကျစရိတ်များ",
    "topics": [
      "Fixed and Variable Costs",
      "Economies and Diseconomies of Scale",
      "Objectives of Firms",
    ],
    "description_en":
        "Analyze production costs, revenues, profit maximization, and economies of scale for business firms.",
    "description_my":
        "စီးပွားရေး လုပ်ငန်းများအတွက် ထုတ်လုပ်မှု ကုန်ကျစရိတ်၊ ဝင်ငွေ၊ အမြတ်အများဆုံးရရှိရေးနှင့် စကေးအကျိုးအမြတ်များကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Microeconomics",
    "title_en": "Market Structures",
    "title_my": "စျေးကွက် တည်ဆောက်ပုံများ",
    "topics": ["Perfect Competition", "Monopoly", "Competitive Strategies"],
    "description_en":
        "Compare market structures ranging from perfect competition to monopolies and their impact on consumers.",
    "description_my":
        "စုံလင်စွာ ပြိုင်ဆိုင်သော စျေးကွက်မှသည် လက်ဝါးကြီးအုပ် စျေးကွက်အထိ စျေးကွက်ဖွဲ့စည်းပုံများကို နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Microeconomics Case Study Studio",
    "title_my": "မိုက်ခရိုဘောဂဗေဒ လက်တွေ့လေ့လာမှု အလုပ်ရုံ",
    "topics": [
      "Monopoly Regulation",
      "Market Failure Analysis",
      "Consumer Welfare",
    ],
    "description_en":
        "Evaluate government policies designed to regulate monopolies and correct market failures.",
    "description_my":
        "လက်ဝါးကြီးအုပ်မှုများကို ထိန်းညှိရန်နှင့် စျေးကွက်ချို့ယွင်းချက်များကို ပြုပြင်ရန် အစိုးရမူဝါဒများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 4: Government and the Macroeconomy =================
  {
    "week": 13,
    "term": 4,
    "theme": "Macroeconomics",
    "title_en": "Government Economic Objectives",
    "title_my": "အစိုးရ၏ စီးပွားရေး ရည်မှန်းချက်များ",
    "topics": [
      "Economic Growth",
      "Full Employment",
      "Price Stability",
      "Balance of Payments",
    ],
    "description_en":
        "Identify primary macroeconomic objectives of governments and potential policy conflicts.",
    "description_my":
        "အစိုးရများ၏ အဓိက မက်ခရိုစီးပွားရေး ရည်မှန်းချက်များနှင့် မူဝါဒဆိုင်ရာ ဖြစ်နိုင်ချေ ပဋိပက္ခများကို ဖော်ထုတ်မည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Macroeconomics",
    "title_en": "Fiscal Policy",
    "title_my": "ဘဏ္ဍာရေး မူဝါဒ (Fiscal Policy)",
    "topics": [
      "Government Spending",
      "Taxation (Direct and Indirect)",
      "Budget Deficits and Surpluses",
    ],
    "description_en":
        "Examine how governments use taxation and public spending to manage economic activity.",
    "description_my":
        "စီးပွားရေးလုပ်ငန်းများကို စီမံခန့်ခွဲရန် အစိုးရက အခွန်ကောက်ခံမှုနှင့် အများပြည်သူ သုံးစရိတ်ကို မည်သို့အသုံးပြုကြောင်း လေ့လာမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Macroeconomics",
    "title_en": "Monetary Policy",
    "title_my": "ငွေကြေး မူဝါဒ (Monetary Policy)",
    "topics": ["Interest Rates", "Money Supply", "Quantitative Easing"],
    "description_en":
        "Understand how central banks use interest rates and money supply to control inflation and growth.",
    "description_my":
        "ငွေကြေးဖောင်းပွမှုနှင့် တိုးတက်မှုကို ထိန်းချုပ်ရန် ဗဟိုဘဏ်များက အတိုးနှုန်းနှင့် ငွေကြေးပမာဏကို မည်သို့သုံးကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Supply-Side Policies",
    "title_my": "ထောက်ပံ့မှုဘက်ဆိုင်ရာ မူဝါဒများ (Supply-Side Policies)",
    "topics": [
      "Education and Training",
      "Deregulation",
      "Privatisation and Infrastructure",
    ],
    "description_en":
        "Analyze supply-side policies aimed at increasing long-term productive capacity and economic growth.",
    "description_my":
        "ရေရှည် ထုတ်လုပ်မှုစွမ်းရည်နှင့် စီးပွားရေးတိုးတက်မှုကို မြှင့်တင်ရန် ရည်ရွယ်သည့် ထောက်ပံ့မှုဘက်ဆိုင်ရာ မူဝါဒများကို ခွဲခြမ်းမည်။",
  },

  // ================= TERM 5: Economic Indicators =================
  {
    "week": 17,
    "term": 5,
    "theme": "Macroeconomics",
    "title_en": "Economic Growth (GDP)",
    "title_my": "စီးပွားရေး တိုးတက်မှု (GDP)",
    "topics": ["Measuring GDP", "Recessions", "Standard of Living Comparisons"],
    "description_en":
        "Measure economic growth using Gross Domestic Product and understand the business cycle.",
    "description_my":
        "GDP ကို အသုံးပြု၍ စီးပွားရေးတိုးတက်မှုကို တိုင်းတာခြင်းနှင့် စီးပွားရေး စက်ဝန်းကို နားလည်စေမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Macroeconomics",
    "title_en": "Employment and Unemployment",
    "title_my": "အလုပ်အကိုင်နှင့် အလုပ်လက်မဲ့နှုန်း",
    "topics": [
      "Measuring Unemployment",
      "Types of Unemployment (Structural, Frictional, Cyclical)",
      "Consequences of Unemployment",
    ],
    "description_en":
        "Examine how unemployment is measured, its various causes, and its economic/social impacts.",
    "description_my":
        "အလုပ်လက်မဲ့နှုန်း တိုင်းတာပုံ၊ အကြောင်းရင်း အမျိုးမျိုးနှင့် ၎င်း၏ စီးပွားရေး/လူမှုရေး သက်ရောက်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Macroeconomics",
    "title_en": "Inflation and Deflation",
    "title_my": "ငွေကြေးဖောင်းပွမှုနှင့် ငွေကြေးကျုံ့မှု",
    "topics": [
      "Consumer Price Index (CPI)",
      "Causes of Inflation (Cost-push, Demand-pull)",
      "Consequences of Inflation",
    ],
    "description_en":
        "Calculate and analyze inflation rates using price indices and evaluate its economic impact.",
    "description_my":
        "ဈေးနှုန်းညွှန်းကိန်းများကို သုံး၍ ငွေကြေးဖောင်းပွမှုနှုန်းကို တွက်ချက်ခွဲခြမ်းစိတ်ဖြာပြီး စီးပွားရေး သက်ရောက်မှုကို အကဲဖြတ်မည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Macroeconomic Indicators Studio",
    "title_my": "မက်ခရိုစီးပွားရေး ညွှန်းကိန်းများ အလုပ်ရုံ",
    "topics": [
      "Interpreting Economic Data",
      "Policy Trade-offs",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate complex macroeconomic data sets and analyze policy trade-offs between inflation and unemployment.",
    "description_my":
        "ရှုပ်ထွေးသော မက်ခရိုစီးပွားရေး ဒေတာများကို အဓိပ္ပာယ်ဖော်ပြီး ငွေကြေးဖောင်းပွမှုနှင့် အလုပ်လက်မဲ့အကြား မူဝါဒ ချိန်ညှိမှုများကို လေ့လာမည်။",
  },

  // ================= TERM 6: Developed and Developing Economies =================
  {
    "week": 21,
    "term": 6,
    "theme": "Development",
    "title_en": "Living Standards and Human Development",
    "title_my": "နေထိုင်မှုစံနှုန်းနှင့် လူ့စွမ်းအား ဖွံ့ဖြိုးတိုးတက်မှု",
    "topics": [
      "GDP per capita",
      "Human Development Index (HDI)",
      "Poverty Lines",
    ],
    "description_en":
        "Compare living standards across nations using single and composite indices like HDI.",
    "description_my":
        "HDI ကဲ့သို့သော ညွှန်းကိန်းများကို အသုံးပြု၍ နိုင်ငံအသီးသီး၏ နေထိုင်မှုစံနှုန်းများကို နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Development",
    "title_en": "Poverty and Inequality",
    "title_my": "ဆင်းရဲမွဲတေမှုနှင့် မညီမျှခြင်း",
    "topics": [
      "Absolute vs Relative Poverty",
      "Causes of Poverty",
      "Policies to Alleviate Poverty",
    ],
    "description_en":
        "Examine the causes of poverty and evaluate government and international strategies for reduction.",
    "description_my":
        "ဆင်းရဲမွဲတေမှု၏ အကြောင်းရင်းများကို လေ့လာပြီး ဆင်းရဲမှု လျှော့ချရေးအတွက် အစိုးရနှင့် နိုင်ငံတကာ မဟာဗျူဟာများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Development",
    "title_en": "Population Dynamics",
    "title_my": "လူဦးရေ ပြောင်းလဲနှုန်းများ",
    "topics": ["Birth and Death Rates", "Net Migration", "Population Pyramids"],
    "description_en":
        "Analyze population growth rates, demographic structures, and their economic implications.",
    "description_my":
        "လူဦးရေ တိုးတက်နှုန်းများ၊ လူဦးရေ တည်ဆောက်ပုံနှင့် ၎င်းတို့၏ စီးပွားရေး သက်ရောက်မှုများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Economic Development Case Study",
    "title_my": "စီးပွားရေး ဖွံ့ဖြိုးတိုးတက်မှု လက်တွေ့လေ့လာမှု",
    "topics": [
      "Comparing Developed vs Developing Nations",
      "Aid and Debt Relief",
      "Exam Practice",
    ],
    "description_en":
        "Investigate barriers to economic development and the role of international aid and foreign investment.",
    "description_my":
        "စီးပွားရေး ဖွံ့ဖြိုးတိုးတက်မှုအတွက် အတားအဆီးများနှင့် နိုင်ငံတကာ အကူအညီ/ရင်းနှီးမြှုပ်နှံမှု၏ အခန်းကဏ္ဍကို စူးစမ်းမည်။",
  },

  // ================= TERM 7: International Trade and Globalisation =================
  {
    "week": 25,
    "term": 7,
    "theme": "International Trade",
    "title_en": "International Specialisation and Trade",
    "title_my": "နိုင်ငံတကာ အထူးပြုလုပ်ဆောင်မှုနှင့် ကုန်သွယ်ရေး",
    "topics": [
      "Benefits of Specialisation",
      "Exports and Imports",
      "Current Account of Balance of Payments",
    ],
    "description_en":
        "Understand why countries specialise and trade, and analyze the components of the balance of payments.",
    "description_my":
        "နိုင်ငံများသည် အဘယ်ကြောင့် အထူးပြု၍ ကုန်သွယ်သည်ကို နားလည်စေပြီး ငွေပေးချေမှု ရှင်းတမ်း၏ အစိတ်အပိုင်းများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "International Trade",
    "title_en": "Protectionism and Trade Barriers",
    "title_my":
        "ပြည်တွင်းကုန်ထုတ်လုပ်မှုကို ကာကွယ်ခြင်း (Protectionism) နှင့် ကုန်သွယ်ရေး အတားအဆီးများ",
    "topics": [
      "Tariffs and Quotas",
      "Arguments for and against Protectionism",
      "Free Trade Agreements",
    ],
    "description_en":
        "Evaluate the use of tariffs, quotas, and trade restrictions by governments to protect domestic industries.",
    "description_my":
        "ပြည်တွင်းစက်မှုလုပ်ငန်းများကို ကာကွယ်ရန် အစိုးရများ၏ အခွန်စည်းကြပ်မှု၊ ခွဲတမ်းသတ်မှတ်မှုနှင့် ကုန်သွယ်ရေး ကန့်သတ်ချက်များကို အကဲဖြတ်မည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "International Trade",
    "title_en": "Foreign Exchange Rates",
    "title_my": "နိုင်ငံခြား ငွေလဲလှယ်နှုန်းများ",
    "topics": [
      "Determining Exchange Rates",
      "Appreciation and Depreciation",
      "Impact on Imports and Exports",
    ],
    "description_en":
        "Examine how foreign exchange rates are determined by market forces and their impact on trade competitiveness.",
    "description_my":
        "နိုင်ငံခြား ငွေလဲလှယ်နှုန်းများ စျေးကွက်စွမ်းအားဖြင့် သတ်မှတ်ပုံနှင့် ကုန်သွယ်ရေး ပြိုင်ဆိုင်နိုင်စွမ်းအပေါ် သက်ရောက်မှုကို လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Globalisation and Multinational Companies",
    "title_my":
        "ကမ္ဘာ့ရွာကြီးစနစ် (Globalisation) နှင့် နိုင်ငံစုံ ကုမ္ပဏီများ",
    "topics": [
      "Drivers of Globalisation",
      "Role of MNCs",
      "Pros and Cons for Economies",
    ],
    "description_en":
        "Analyze the economic impacts of globalisation and multinational corporations on developed and developing nations.",
    "description_my":
        "ဖွံ့ဖြိုးပြီးနှင့် ဖွံ့ဖြိုးဆဲနိုင်ငံများအပေါ် ကမ္ဘာ့ရွာကြီးစနစ်နှင့် နိုင်ငံစုံကုမ္ပဏီများ၏ စီးပွားရေး သက်ရောက်မှုများကို ခွဲခြမ်းမည်။",
  },

  // ================= TERM 8: Economic Data Analysis & Case Studies =================
  {
    "week": 29,
    "term": 8,
    "theme": "Application",
    "title_en": "Interpreting Economic Charts and Tables",
    "title_my": "စီးပွားရေး ဇယားများနှင့် ဂရပ်များကို အဓိပ္ပာယ်ဖော်ခြင်း",
    "topics": [
      "Reading Macro Data",
      "Trend Analysis",
      "Data Response Techniques",
    ],
    "description_en":
        "Master the skill of interpreting complex macroeconomic charts, tables, and trend data for IGCSE Paper 2.",
    "description_my":
        "IGCSE Paper 2 အတွက် ရှုပ်ထွေးသော မက်ခရိုစီးပွားရေး ဂရပ်များ၊ ဇယားများနှင့် ခေတ်ရေစီးကြောင်း ဒေတာများကို အဓိပ္ပာယ်ဖော်ရန် လေ့လာမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Application",
    "title_en": "Evaluating Economic Policies",
    "title_my": "စီးပွားရေး မူဝါဒများကို အကဲဖြတ်ခြင်း",
    "topics": [
      "Policy Effectiveness",
      "Unintended Consequences",
      "Cost-Benefit Justification",
    ],
    "description_en":
        "Construct well-reasoned evaluations of government policy interventions using economic theory.",
    "description_my":
        "စီးပွားရေး သီအိုရီများကို အသုံးပြု၍ အစိုးရ၏ မူဝါဒဝင်ရောက်စွက်ဖက်မှုများအပေါ် ကျိုးကြောင်းဆီလျော်စွာ အကဲဖြတ်ချက်များ တည်ဆောက်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Application",
    "title_en": "Structured Essay Writing Techniques",
    "title_my": "ဖွဲ့စည်းတည်ဆောက်ထားသော အက်ဆေး ရေးသားခြင်း နည်းပညာများ",
    "topics": [
      "Structuring 6-mark and 8-mark questions",
      "Using Economic Terminology",
      "Balanced Arguments",
    ],
    "description_en":
        "Learn how to write high-scoring structured essay answers incorporating balanced arguments and diagrams.",
    "description_my":
        "မျှတသော အငြင်းပွားမှုများနှင့် ပုံကားချပ်များ ထည့်သွင်းကာ အမှတ်မြင့်မည့် အက်ဆေးအဖြေများ ရေးသားနည်းကို လေ့လာမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Economics Paper 2 Mock Simulation",
    "title_my": "Economics Paper 2 ပုံစံတူ စာမေးပွဲ ဖြေဆိုခြင်း",
    "topics": [
      "Timed Case Study Paper",
      "Data Response Practice",
      "Exam Review",
    ],
    "description_en":
        "Complete a full-length timed Economics Paper 2 exam under simulated testing conditions.",
    "description_my":
        "ပုံစံတူ စာမေးပွဲ အခြေအနေများအောက်တွင် အချိန်သတ်မှတ်ချက်ဖြင့် Economics Paper 2 စာမေးပွဲကို အစအဆုံး ဖြေဆိုမည်။",
  },

  // ================= TERM 9: Exam Prep & Final Countdown =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Multiple Choice) Intensive",
    "title_my": "Paper 1 (ရွေးချယ်ရန် မေးခွန်းများ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "MCQ Strategy",
      "Elimination Techniques",
      "Quick-fire Definitions",
    ],
    "description_en":
        "Master multiple-choice question strategies and rapid recall of economic definitions and graphs.",
    "description_my":
        "စီးပွားရေး အဓိပ္ပာယ်ဖွင့်ဆိုချက်များနှင့် ဂရပ်များကို အမြန်ဆုံးပြန်လည်ဖော်ထုတ်ရန် MCQ မူဝါဒများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Targeted Weakness Remediation",
    "title_my": "အားနည်းချက်ရှိသော ကဏ္ဍများကို အထူးပြုပြင်ခြင်း",
    "topics": [
      "Personalised Past Paper Drills",
      "Diagram Drawing Practice",
      "Q&A Review",
    ],
    "description_en":
        "Target individual student weak points through intensive past paper question and diagram practice.",
    "description_my":
        "အတိတ် မေးခွန်းဟောင်းများနှင့် ပုံကားချပ် လေ့ကျင့်မှုများမှတစ်ဆင့် တစ်ဦးချင်း အားနည်းချက်များကို အထူးပြုပြင်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Past Paper Mock Examinations",
    "title_my": "မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 2",
      "Mark Scheme Analysis",
    ],
    "description_en":
        "Complete full-length past paper mock examinations under rigorous timed conditions.",
    "description_my":
        "တင်းကျပ်သော အချိန်သတ်မှတ်ချက်များအောက်တွင် မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Economics Graduation",
    "title_my": "IGCSE ဘောဂဗေဒ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Economic Literacy",
      "Pathways to A-Level Economics",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Economics and preparation for advanced economic studies.",
    "description_my":
        "IGCSE ဘောဂဗေဒ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး အဆင့်မြင့် ဘောဂဗေဒ ပညာရေးဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
