// File: ai_data_bridge/igcse_physics_all_terms.dart
// IGCSE Physics Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcsePhysicsAllTermsData = [
  // ================= TERM 1: Motion, Forces and Energy =================
  {
    "week": 1,
    "term": 1,
    "theme": "General Physics",
    "title_en": "Motion and Speed-Time Graphs",
    "title_my": "ရွေ့လျားမှုနှင့် အမြန်နှုန်း-အချိန် ဂရပ်များ",
    "topics": [
      "Speed, Velocity, and Acceleration",
      "Distance-Time Graphs",
      "Speed-Time Graphs (Calculating Distance and Acceleration)",
    ],
    "description_en":
        "Master calculating speed, acceleration, and interpreting motion graphs for IGCSE standards.",
    "description_my":
        "အမြန်နှုန်း၊ အရှိန်တွက်ချက်ခြင်းနှင့် IGCSE စံနှုန်းများအတွက် ရွေ့လျားမှု ဂရပ်များကို အဓိပ္ပာယ်ဖော်ခြင်းကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "General Physics",
    "title_en": "Mass, Weight and Density",
    "title_my": "ထုထည် (Mass)၊ အလေးချိန်နှင့် သိပ်သည်းဆ",
    "topics": [
      "Gravitational Field Strength (g)",
      "Density Formula (rho = m/V)",
      "Displacement Method for Liquids and Solids",
    ],
    "description_en":
        "Calculate mass, weight, and density using rigorous formulas and experimental methods.",
    "description_my":
        "ခိုင်မာသော ဖော်မြူလာများနှင့် စမ်းသပ်မှု နည်းလမ်းများကို အသုံးပြု၍ ထုထည်၊ အလေးချိန်နှင့် သိပ်သည်းဆကို တွက်ချက်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "General Physics",
    "title_en": "Effects of Forces and Momentum",
    "title_my": "အားများ၏ သက်ရောက်မှုနှင့် အဟုန် (Momentum)",
    "topics": [
      "Newton's Laws of Motion (F = ma)",
      "Hooke's Law and Springs",
      "Momentum and Conservation of Momentum",
    ],
    "description_en":
        "Apply Newton's laws, Hooke's law, and momentum calculations to complex mechanical systems.",
    "description_my":
        "နယူတန်၏ နိယာမများ၊ ဟုခ်၏ နိယာမနှင့် အဟုန် တွက်ချက်မှုများကို စက်မှုစနစ်များတွင် အသုံးချမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Mechanics Problem-Solving Studio",
    "title_my": "မက္ကင်းနစ် ပြဿနာဖြေရှင်းခြင်း အလုပ်ရုံ",
    "topics": [
      "Turning Effects (Moments)",
      "Centre of Gravity",
      "Pressure Calculations (P = F/A)",
    ],
    "description_en":
        "Calculate moments, center of gravity, and pressure in advanced mechanical scenarios.",
    "description_my":
        "အဆင့်မြင့် မက္ကင်းနစ် အခြေအနေများတွင် လှည့်အားများ (Moments)၊ ဆွဲငင်အား ဗဟိုချက်နှင့် ဖိအားများကို တွက်ချက်မည်။",
  },

  // ================= TERM 2: Thermal Physics =================
  {
    "week": 5,
    "term": 2,
    "theme": "Thermal Physics",
    "title_en": "Kinetic Particle Model of Matter",
    "title_my": "ဒြပ်ဝတ္ထု၏ အမှုန်သီအိုရီ မော်ဒယ်",
    "topics": [
      "States of Matter (Solid, Liquid, Gas)",
      "Brownian Motion",
      "Evaporation and Gas Pressure",
    ],
    "description_en":
        "Understand particle theory, Brownian motion, and how molecular movement creates gas pressure.",
    "description_my":
        "အမှုန်သီအိုရီ၊ ဘရောက်နီယံ လှုပ်ရှားမှုနှင့် မော်လီကျူး ရွေ့လျားမှုက ဓာတ်ငွေ့ဖိအားကို မည်သို့ဖန်တီးကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Thermal Physics",
    "title_en": "Thermal Expansion and Temperature",
    "title_my": "အပူကြောင့် ပျံ့ကားခြင်းနှင့် အပူချိန်",
    "topics": [
      "Expansion of Solids, Liquids, and Gases",
      "Thermometers and Calibration",
      "Specific Heat Capacity Calculations",
    ],
    "description_en":
        "Calculate thermal energy changes using specific heat capacity formulas and examine thermal expansion.",
    "description_my":
        "သီးသန့်အပူဆံ့နှုန်း ဖော်မြူလာများကို သုံး၍ အပူစွမ်းအင် ပြောင်းလဲမှုကို တွက်ချက်ပြီး အပူကြောင့် ပျံ့ကားမှုကို လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Thermal Physics",
    "title_en": "Thermal Energy Transfer",
    "title_my": "အပူစွမ်းအင် ကူးပြောင်းခြင်း",
    "topics": [
      "Conduction, Convection, and Radiation",
      "Investigating Thermal Emission and Absorption",
      "Insulation Applications",
    ],
    "description_en":
        "Analyze the three methods of thermal energy transfer and design effective thermal insulators.",
    "description_my":
        "အပူစွမ်းအင် ကူးပြောင်းသည့် နည်းလမ်းသုံးမျိုးကို ခွဲခြမ်းစိတ်ဖြာပြီး ထိရောက်သော အပူကာကွယ် ပစ္စည်းများကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Thermal Physics Practical Lab",
    "title_my": "အပူရူပဗေဒ ဓာတ်ခွဲခန်း လက်တွေ့စမ်းသပ်မှု",
    "topics": [
      "Latent Heat Experiments",
      "Cooling Curves",
      "Exam Practical Questions",
    ],
    "description_en":
        "Execute practical experiments investigating specific latent heat and cooling curves.",
    "description_my":
        "သီးသန့် မငြိမ်အပူ (Latent heat) နှင့် အေးမြခြင်း ဂရပ်များကို စမ်းသပ်သည့် လက်တွေ့စမ်းသပ်မှုများကို လုပ်ဆောင်မည်။",
  },

  // ================= TERM 3: Properties of Waves =================
  {
    "week": 9,
    "term": 3,
    "theme": "Waves",
    "title_en": "General Wave Properties",
    "title_my": "လှိုင်းများ၏ အထွေထွေ ဂုဏ်သတ္တိများ",
    "topics": [
      "Transverse and Longitudinal Waves",
      "Wave Equation (v = f * lambda)",
      "Reflection, Refraction, and Diffraction",
    ],
    "description_en":
        "Master wave calculations and behaviors including reflection, refraction, and wave diffraction.",
    "description_my":
        "လှိုင်း တွက်ချက်မှုများနှင့် အလင်းပြန်ခြင်း၊ ယိုင်ခြင်း၊ ကွေ့ဝိုက်ခြင်း (Diffraction) အပါအဝင် လှိုင်းအမူအကျင့်များကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Light",
    "title_en": "Light and Optics",
    "title_my": "အလင်းနှင့် အလင်းဗေဒ (Optics)",
    "topics": [
      "Reflection in Plane Mirrors",
      "Refraction of Light (Snell's Law)",
      "Total Internal Reflection (TIR) and Critical Angle",
    ],
    "description_en":
        "Calculate refractive indices, critical angles, and trace light rays through lenses and prisms.",
    "description_my":
        "အလင်းယိုင်ကိန်း (Refractive index)၊ Critical angle များကို တွက်ချက်ပြီး မှန်ဘီူးများနှင့် ဖန်တုံးများမှတစ်ဆင့် အလင်းတန်းများကို ခြေရာခံမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Sound",
    "title_en": "Sound Waves",
    "title_my": "အသံလှိုင်းများ",
    "topics": [
      "Production and Propagation of Sound",
      "Speed of Sound Experiments",
      "Echoes and Ultrasound",
    ],
    "description_en":
        "Understand sound wave characteristics, frequency limits of human hearing, and echo sounding.",
    "description_my":
        "အသံလှိုင်း၏ လက္ခဏာများ၊ လူသားများ ကြားနိုင်သည့် ကြိမ်နှုန်း ကန့်သတ်ချက်နှင့် ပဲ့တင်သံ (Echo) တို့ကို နားလည်စေမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Waves and Optics Practical Studio",
    "title_my": "လှိုင်းနှင့် အလင်းဗေဒ ဓာတ်ခွဲခန်း အလုပ်ရုံ",
    "topics": [
      "Glass Block Refraction Experiments",
      "Ripple Tank Studies",
      "Exam Practice",
    ],
    "description_en":
        "Analyze practical wave phenomena and optical experiments required for IGCSE assessment.",
    "description_my":
        "IGCSE စာမေးပွဲအတွက် လိုအပ်သော လှိုင်းဖြစ်စဉ်များနှင့် အလင်းဗေဒ စမ်းသပ်ချက်များကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },

  // ================= TERM 4: Electricity and Magnetism =================
  {
    "week": 13,
    "term": 4,
    "theme": "Electricity",
    "title_en": "Simple Phenomena of Magnetism",
    "title_my": "သံလိုက်စွမ်းပကား၏ အခြေခံ ဖြစ်စဉ်များ",
    "topics": [
      "Magnetic Poles and Fields",
      "Permanent and Induced Magnets",
      "Magnetic Materials",
    ],
    "description_en":
        "Explore magnetic field lines, permanent magnets, and the difference between magnetic and non-magnetic materials.",
    "description_my":
        "သံလိုက်စက်ကွင်း မျဉ်းများ၊ အမြဲတမ်း သံလိုက်များနှင့် သံလိုက်ပါဝင်သော/မပါဝင်သော ပစ္စည်းများ၏ ကွာခြားချက်ကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Electricity",
    "title_en": "Electrical Quantities and Circuits",
    "title_my": "လျှပ်စစ် ပမာဏများနှင့် ပတ်လမ်းများ",
    "topics": [
      "Current, Voltage, and Resistance",
      "Ohm's Law (V = IR)",
      "Electrical Power (P = IV) and Energy (E = IVt)",
    ],
    "description_en":
        "Calculate current, voltage, resistance, and electrical power using fundamental physics equations.",
    "description_my":
        "အခြေခံ ရူပဗေဒ ဖော်မြူလာများကို အသုံးပြု၍ လျှပ်စီးကြောင်း၊ ဗို့အား၊ ခံနိုင်ရည်နှင့် လျှပ်စစ်စွမ်းအားများကို တွက်ချက်မည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Electricity",
    "title_en": "Series and Parallel Circuits",
    "title_my": "ဆက်တိုက် (Series) နှင့် ယှဉ်တွဲ (Parallel) ပတ်လမ်းများ",
    "topics": [
      "Current and Voltage Rules in Series/Parallel",
      "Combined Resistance Calculations",
      "Potential Dividers",
    ],
    "description_en":
        "Analyze complex circuit diagrams, calculate total resistance, and design potential divider circuits.",
    "description_my":
        "ရှုပ်ထွေးသော ပတ်လမ်းပုံစံများကို ခွဲခြမ်းစိတ်ဖြာပြီး စုစုပေါင်း ခံနိုင်ရည်ကို တွက်ချက်ကာ Potential divider ပတ်လမ်းများကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Electrical Safety and Mains Electricity",
    "title_my": "လျှပ်စစ် လုံခြုံရေးနှင့် အိမ်သုံး မိုင်းလျှပ်စစ်မီး",
    "topics": [
      "Fuses, Circuit Breakers, and Earth Wires",
      "Double Insulation",
      "Cost of Electrical Energy Calculations",
    ],
    "description_en":
        "Understand household electrical safety devices and calculate the financial cost of electrical energy usage.",
    "description_my":
        "အိမ်သုံး လျှပ်စစ် လုံခြုံရေး ကိရိယာများကို နားလည်စေပြီး လျှပ်စစ်စွမ်းအင် သုံးစွဲမှုအတွက် ငွေကြေးကုန်ကျစရိတ်ကို တွက်ချက်မည်။",
  },

  // ================= TERM 5: Electromagnetic Effects =================
  {
    "week": 17,
    "term": 5,
    "theme": "Electromagnetism",
    "title_en": "Electromagnetic Effects",
    "title_my": "လျှပ်စစ်သံလိုက် သက်ရောက်မှုများ",
    "topics": [
      "Magnetic Effect of a Current (Solenoids)",
      "The Motor Effect (Fleming's Left-Hand Rule)",
      "Electric DC Motors",
    ],
    "description_en":
        "Explore how current-carrying conductors experience forces in magnetic fields and how electric motors operate.",
    "description_my":
        "လျှပ်စီးကြောင်း သယ်ဆောင်ထားသော ဝိုင်ယာများသည် သံလိုက်စက်ကွင်းအတွင်း အားသက်ရောက်ပုံနှင့် လျှပ်စစ်မော်တာများ အလုပ်လုပ်ပုံကို စူးစမ်းမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Electromagnetism",
    "title_en": "Electromagnetic Induction",
    "title_my": "လျှပ်စစ်သံလိုက် လှုံ့ဆော်မှု (Induction)",
    "topics": [
      "Generating Electricity (Faraday's Law)",
      "AC Generators",
      "Transformers and Efficiency",
    ],
    "description_en":
        "Understand electromagnetic induction, AC generator mechanics, and step-up/step-down transformers.",
    "description_my":
        "လျှပ်စစ်သံလိုက် လှုံ့ဆော်မှု၊ AC ဂျင်နရေတာ လုပ်ဆောင်ပုံနှင့် ဗို့တက်/ဗို့ကျ Transformer များကို နားလည်စေမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Electronics",
    "title_en": "Electronic Systems",
    "title_my": "အီလက်ထရောနစ် စနစ်များ",
    "topics": [
      "Logic Gates (AND, OR, NOT, NAND, NOR)",
      "Relays and Thermistors",
      "LDRs in Control Circuits",
    ],
    "description_en":
        "Analyze electronic control systems incorporating logic gates, thermistors, LDRs, and relays.",
    "description_my":
        "လော့ဂျစ်ဂိတ်များ၊ Thermistors၊ LDRs နှင့် Relays များပါဝင်သော အီလက်ထရောနစ် ထိန်းချုပ်ရေး စနစ်များကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Electromagnetic & Electronic Studio",
    "title_my": "လျှပ်စစ်သံလိုက်နှင့် အီလက်ထရောနစ် အလုပ်ရုံ",
    "topics": [
      "Transformer Calculations",
      "Logic Circuit Design",
      "Exam Practice",
    ],
    "description_en":
        "Solve complex numerical problems involving transformers and electronic logic circuits.",
    "description_my":
        "Transformer တွက်ချက်မှုများနှင့် အီလက်ထရောနစ် လော့ဂျစ်ပတ်လမ်း ဒီဇိုင်းပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 6: Atomic Physics =================
  {
    "week": 21,
    "term": 6,
    "theme": "Atomic Physics",
    "title_en": "The Nuclear Atom",
    "title_my": "နူကလီးယား အက်တမ် တည်ဆောက်ပုံ",
    "topics": [
      "Atomic Structure (Protons, Neutrons, Electrons)",
      "Isotopes",
      "Rutherford's Alpha Scattering Experiment",
    ],
    "description_en":
        "Examine atomic structure, isotopes, and the historical significance of Rutherford's scattering experiment.",
    "description_my":
        "အက်တမ် ဖွဲ့စည်းပုံ၊ အိုင်ဆိုတုပ်များနှင့် ရသာဖို့ဒ်၏ အယ်လ်ဖာ ကျဲဖြန့်မှု စမ်းသပ်ချက်၏ သမိုင်းဝင် အရေးပါမှုကို လေ့လာမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Atomic Physics",
    "title_en": "Radioactivity",
    "title_my": "ရယ်ဒီယိုသတ္တိကြွမှု (Radioactivity)",
    "topics": [
      "Alpha, Beta, and Gamma Radiation Properties",
      "Detection using Geiger-Müller Tubes",
      "Background Radiation",
    ],
    "description_en":
        "Compare the properties, penetrating powers, and ionising effects of alpha, beta, and gamma radiation.",
    "description_my":
        "အယ်လ်ဖာ၊ ဘီတာနှင့် ဂမ်မာ ရောင်ခြည်တို့၏ ဂုဏ်သတ္တိများ၊ ထိုးဖောက်နိုင်စွမ်းနှင့် အိုင်းယွန်းဖြစ်စေနိုင်စွမ်းကို နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Atomic Physics",
    "title_en": "Radioactive Decay and Half-Life",
    "title_my":
        "ရယ်ဒီယိုသတ္တိကြွ ပျက်စီးယိုယွင်းခြင်းနှင့် သက်တမ်းဝက် (Half-Life)",
    "topics": [
      "Radioactive Decay Equations (Alpha and Beta Decay)",
      "Calculating Half-Life from Graphs and Data",
      "Safety Precautions",
    ],
    "description_en":
        "Calculate half-life from decay curves and write balanced nuclear decay equations.",
    "description_my":
        "ပျက်စီးယိုယွင်းမှု ဂရပ်များမှ Half-life ကို တွက်ချက်ခြင်းနှင့် ချိန်ညှိထားသော နူကလီးယား ညီမျှခြင်းများ ရေးသားမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Atomic Physics Problem-Solving Studio",
    "title_my": "အေတမ် ရူပဗေဒ ပြဿနာဖြေရှင်းခြင်း အလုပ်ရုံ",
    "topics": ["Half-Life Calculations", "Radiation Safety", "Exam Practice"],
    "description_en":
        "Master rigorous half-life calculation tasks and radiation safety application questions.",
    "description_my":
        "တင်းကျပ်သော သက်တမ်းဝက် တွက်ချက်မှု တာဝန်များနှင့် ရောင်ခြယ် လုံခြုံရေး မေးခွန်းများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },

  // ================= TERM 7: Space Physics =================
  {
    "week": 25,
    "term": 7,
    "theme": "Space Physics",
    "title_en": "Earth and the Solar System",
    "title_my": "ကမ္ဘာနှင့် နေအဖွဲ့အစည်း",
    "topics": [
      "Orbits of Planets, Comets, and Moons",
      "Gravitational Field Strength across Planets",
      "Orbital Speed Calculations (v = 2*pi*r / T)",
    ],
    "description_en":
        "Calculate orbital speeds and examine gravitational forces maintaining orbits in our solar system.",
    "description_my":
        "ဂြိုဟ်ပတ်လမ်း အမြန်နှုန်းများကို တွက်ချက်ပြီး နေအဖွဲ့အစည်းအတွင်း ပတ်လမ်းများကို ထိန်းသိမ်းထားသည့် ဆွဲငင်အားများကို လေ့လာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Space Physics",
    "title_en": "Stars and the Universe",
    "title_my": "ကြယ်များနှင့် စကြဝဠာ",
    "topics": [
      "Life Cycle of Stars (Sun-like vs Massive Stars)",
      "Nuclear Fusion in Stars",
      "The Big Bang Theory and Redshift",
    ],
    "description_en":
        "Trace the lifecycle of stars, nuclear fusion power sources, and evidence for the expanding universe.",
    "description_my":
        "ကြယ်များ၏ ဘဝစက်ဝန်း၊ နူကလီးယား ပေါင်းစပ်စွမ်းအင်ရင်းမြစ်နှင့် စကြဝဠာ ကျယ်ပြန့်နေမှုအတွက် အထောက်အထားများကို ခြေရာခံမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Space Physics",
    "title_en": "Cosmic Evolution and Redshift",
    "title_my": "စကြဝဠာ ဆင့်ကဲဖြစ်စဉ်နှင့် ရက်ဒ်ရှစ် (Redshift)",
    "topics": [
      "Measuring Distance with Supernovae",
      "Cosmic Microwave Background Radiation (CMBR)",
      "Calculating Hubble's Law Concepts",
    ],
    "description_en":
        "Examine CMBR and redshift as foundational evidence supporting the Big Bang theory.",
    "description_my":
        "Big Bang သီအိုရီကို ထောက်ခံသည့် အဓိက အထောက်အထားများအဖြစ် CMBR နှင့် Redshift ကို လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Space Physics Masterclass",
    "title_my": "အာကာသ ရူပဗေဒ အထူးသင်ခန်းစာ",
    "topics": [
      "Orbital Speed Calculations",
      "Stellar Evolution Analysis",
      "Exam Problem Solving",
    ],
    "description_en":
        "Solve quantitative space physics problems and analyze cosmological evidence.",
    "description_my":
        "အရေအတွက်ပိုင်းဆိုင်ရာ အာကာသ ရူပဗေဒ ပြဿနာများကို ဖြေရှင်းပြီး ကိုစမိုလိုဂျီ အထောက်အထားများကို ခွဲခြမ်းမည်။",
  },

  // ================= TERM 8: Alternative to Practical & Experimental Skills =================
  {
    "week": 29,
    "term": 8,
    "theme": "Experimental Skills",
    "title_en": "Designing Physics Experiments",
    "title_my": "ရူပဗေဒ စမ်းသပ်မှုများ ဒီဇိုင်းဆွဲခြင်း",
    "topics": [
      "Controlling Variables",
      "Choosing Appropriate Measuring Instruments",
      "Minimising Experimental Errors",
    ],
    "description_en":
        "Master the methodology of designing fair and accurate physics experiments for Paper 6.",
    "description_my":
        "Paper 2/6 အတွက် တရားမျှတပြီး တိကျသော ရူပဗေဒ စမ်းသပ်မှုများ ဒီဇိုင်းဆွဲသည့် နည်းစနစ်ကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Experimental Skills",
    "title_en": "Data Analysis and Graphical Work",
    "title_my": "ဒေတာ ခွဲခြမ်းစိတ်ဖြာခြင်းနှင့် ဂရပ်ဖစ် အလုပ်များ",
    "topics": [
      "Plotting Best-Fit Lines",
      "Calculating Gradients from Experimental Graphs",
      "Evaluating Reliability of Results",
    ],
    "description_en":
        "Practice drawing best-fit lines, calculating gradients, and evaluating anomalous data points.",
    "description_my":
        "သင့်လျော်ဆုံးမျဉ်း (Best-fit line) ဆွဲခြင်း၊ စမ်းသပ်ဂရပ်များမှ အစောင်းနှုန်း တွက်ချက်ခြင်းနှင့် ပုံမှန်မဟုတ်သော ဒေတာများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Experimental Skills",
    "title_en": "Common Practical Scenarios",
    "title_my": "သာမန် လက်တွေ့စမ်းသပ်မှု အခြေအနေများ",
    "topics": [
      "Pendulum Experiments",
      "Circuit Verification",
      "Lens Focal Length Determination",
    ],
    "description_en":
        "Review core IGCSE practical experiments including pendulums, ohms law verification, and optics.",
    "description_my":
        "မဏ္ဍိုင်လွှဲ (Pendulum)၊ ဩမ်းနိယာမ စစ်ဆေးခြင်းနှင့် အလင်းဗေဒ စမ်းသပ်မှုများ ပါဝင်သော အဓိက IGCSE လက်တွေ့စမ်းသပ်မှုများကို ပြန်လည်သုံးသပ်မည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Practical Paper Simulation Studio",
    "title_my": "လက်တွေ့ စာမေးပွဲ ပုံစံတူ အလုပ်ရုံ",
    "topics": [
      "Paper 6 Simulation",
      "Table Formatting and Units",
      "Error Evaluation",
    ],
    "description_en":
        "Complete full practical paper simulations under strict examination conditions.",
    "description_my":
        "တင်းကျပ်သော စာမေးပွဲ အခြေအနေများအောက်တွင် လက်တွေ့စာစောင် ပုံစံတူ အစအဆုံး ဖြေဆိုမည်။",
  },

  // ================= TERM 9: Exam Prep & Final Countdown =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Multiple Choice) Intensive",
    "title_my": "Paper 1 (ရွေးချယ်ရန် မေးခွန်းများ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "MCQ Strategy",
      "Rapid Physics Calculations",
      "Formula Recall Drills",
    ],
    "description_en":
        "Master multiple-choice question strategies and rapid formula recall for Paper 1 success.",
    "description_my":
        "Paper 1 တွင် အောင်မြင်မှုရရန် ရွေးချယ်ရန် မေးခွန်း မူဝါဒများနှင့် အမြန်ဖော်မြူလာ ပြန်လည်ဖော်ထုတ်မှုကို လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 3/4 (Theory Calculations) Mastery",
    "title_my": "Paper 3/4 (သီအိုရီ တွက်ချက်မှုများ) ကျွမ်းကျင်မှု",
    "topics": [
      "Structuring Extended Calculations",
      "Explaining Physical Phenomena",
      "Time Management",
    ],
    "description_en":
        "Intensive practice on structured theory and calculation questions for Paper 4 Extended.",
    "description_my":
        "Paper 4 Extended အတွက် ပုံစံကျ သီအိုရီနှင့် တွက်ချက်မှု မေးခွန်းများကို အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Past Paper Mock Examinations",
    "title_my": "မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 4",
      "Timed Mock Paper 6",
    ],
    "description_en":
        "Complete full-length past paper mock examinations across all papers under rigorous timed conditions.",
    "description_my":
        "တင်းကျပ်သော အချိန်သတ်မှတ်ချက်များအောက်တွင် စာစောင်အားလုံးအတွက် မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Physics Graduation",
    "title_my": "IGCSE ရူပဗေဒ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Physical Sciences",
      "Pathways to A-Level Physics",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Physics and preparation for advanced physical sciences.",
    "description_my":
        "IGCSE ရူပဗေဒ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး အဆင့်မြင့် ရူပဗေဒ ပညာရေးဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
