// File: ai_data_bridge/igcse_computer_science_all_terms.dart
// IGCSE Computer Science Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseComputerScienceAllTermsData = [
  // ================= TERM 1: Data Representation =================
  {
    "week": 1,
    "term": 1,
    "theme": "Data Representation",
    "title_en": "Binary Systems and Conversions",
    "title_my": "ဘိုင်နရီစနစ်နှင့် ကိန်းဂဏန်း ပြောင်းလဲခြင်း",
    "topics": [
      "Denary to Binary",
      "Hexadecimal Systems",
      "Binary Addition and Overflow",
    ],
    "description_en":
        "Master binary and hexadecimal number systems, conversions, and binary arithmetic including overflow errors.",
    "description_my":
        "ဘိုင်နရီနှင့် ဟက်ဇာဒက်ဆီမယ် နံပါတ်စနစ်များ၊ အချင်းချင်းပြောင်းလဲခြင်းနှင့် အိုဗာဖလိုး အမှားများပါဝင်သော ဘိုင်နရီ တွက်ချက်မှုကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Data Representation",
    "title_en": "Text, Sound, and Images",
    "title_my": "စာသား၊ အသံနှင့် ပုံရိပ်များ",
    "topics": [
      "ASCII and Unicode",
      "Sampling Rate and Resolution",
      "Pixel Depth and Bitmap Images",
    ],
    "description_en":
        "Understand how computers represent text, audio samples, and bitmap images using digital data.",
    "description_my":
        "ကွန်ပျူတာများသည် စာသား၊ အသံနမူနာများနှင့် ပစ်ဇယ်ပုံများကို ဒစ်ဂျစ်တယ် အချက်အလက်အဖြစ် မည်သို့ဖော်ပြကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Data Storage and Compression",
    "title_en": "Data Storage and Compression",
    "title_my": "အချက်အလက် သိုလှောင်မှုနှင့် ဖိုင်ချုံ့ခြင်း",
    "topics": [
      "Bits, Bytes, and File Sizes",
      "Lossy vs Lossless Compression",
      "Calculations of File Size",
    ],
    "description_en":
        "Calculate file sizes for images and sound, and explore the differences between lossy and lossless compression.",
    "description_my":
        "ပုံနှင့် အသံဖိုင်အရွယ်အစားများကို တွက်ချက်ခြင်းနှင့် Lossy နှင့် Lossless ဖိုင်ချုံ့ခြင်း ကွာခြားချက်များကို စူးစမ်းမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Data Representation Project",
    "title_my": "အချက်အလက် ဖော်ပြမှု ပရောဂျက်",
    "topics": [
      "Binary Calculation Tests",
      "Compression Efficiency Analysis",
      "Exam Practice",
    ],
    "description_en":
        "Apply data representation and compression concepts to solve complex IGCSE theoretical problems.",
    "description_my":
        "ရှုပ်ထွေးသော IGCSE သီအိုရီ ပြဿနာများကို ဖြေရှင်းရန် အချက်အလက် ဖော်ပြမှုနှင့် ချုံ့ခြင်း သဘောတရားများကို အသုံးချမည်။",
  },

  // ================= TERM 2: Communication and Internet Technologies =================
  {
    "week": 5,
    "term": 2,
    "theme": "Networks",
    "title_en": "Data Transmission",
    "title_my": "အချက်အလက် ပို့လွှတ်ခြင်း (Data Transmission)",
    "topics": [
      "Packet Switching",
      "Serial vs Parallel Transmission",
      "Error Detection (Parity, Checksum)",
    ],
    "description_en":
        "Explore how data is broken into packets, transmitted across networks, and checked for errors.",
    "description_my":
        "အချက်အလက်များကို အထုပ်ငယ်များခွဲ၍ ကွန်ရက်များတစ်လျှောက် ပို့လွှတ်ခြင်းနှင့် အမှားစစ်ဆေးနည်းများကို လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Networks",
    "title_en": "The Internet and World Wide Web",
    "title_my": "အင်တာနက်နှင့် ကမ္ဘာ့ဝဘ်ချိတ်ဆက်မှု (WWW)",
    "topics": [
      "IP and MAC Addresses",
      "Routers and DNS",
      "HTML Structure and Presentation",
    ],
    "description_en":
        "Understand internet infrastructure, IP/MAC addressing, DNS resolution, and basic HTML/CSS roles.",
    "description_my":
        "အင်တာနက် အဆောက်အအုံ၊ IP/MAC လိပ်စာများ၊ DNS နှင့် HTML/CSS တို့၏ အခန်းကဏ္ဍကို နားလည်စေမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Security",
    "title_en": "Network Security and Encryption",
    "title_my": "ကွန်ရက် လုံခြုံရေးနှင့် ကုဒ်ဝှက်ခြင်း",
    "topics": [
      "Symmetric and Asymmetric Encryption",
      "Firewalls and Proxy Servers",
      "Malware Types",
    ],
    "description_en":
        "Examine security threats, firewall defenses, and how encryption secures data communication.",
    "description_my":
        "လုံခြုံရေး ခြိမ်းခြောက်မှုများ၊ Firewall ကာကွယ်မှုများနှင့် ကုဒ်ဝှက်စနစ်က ဆက်သွယ်ရေးကို မည်သို့လုံခြုံစေကြောင်း လေ့လာမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Network Architecture Audit",
    "title_my": "ကွန်ရက် ဗိသုကာ စစ်ဆေးမှု ပရောဂျက်",
    "topics": [
      "Designing Secure Networks",
      "Encryption Scenarios",
      "Exam Practice",
    ],
    "description_en":
        "Design a secure corporate network architecture addressing potential cybersecurity threats.",
    "description_my":
        "ဆိုက်ဘာလုံခြုံရေး ခြိမ်းခြောက်မှုများကို ဖြေရှင်းနိုင်မည့် လုံခြုံသော ကွန်ရက် ဗိသုကာပုံစံကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 3: Hardware and Logic Gates =================
  {
    "week": 9,
    "term": 3,
    "theme": "Hardware",
    "title_en": "Computer Architecture (Von Neumann)",
    "title_my": "ကွန်ရက် ဗိသုကာပုံစံ (Von Neumann Architecture)",
    "topics": [
      "CPU Components (ALU, CU, Registers)",
      "Fetch-Decode-Execute Cycle",
      "Core Factors Affecting Performance",
    ],
    "description_en":
        "Deep dive into the CPU structure, registers, buses, and the fetch-decode-execute cycle.",
    "description_my":
        "CPU ဖွဲ့စည်းပုံ၊ Registers၊ Buses နှင့် Fetch-Decode-Execute စက်ဝန်းတို့ကို အသေးစိတ် လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Hardware",
    "title_en": "Input, Output, and Storage Devices",
    "title_my": "ထည့်သွင်း၊ ထုတ်ပေးနှင့် သိုလှောင်သည့် ကိရိယာများ",
    "topics": [
      "Sensors and Actuators",
      "Primary Memory (RAM, ROM)",
      "Secondary Storage (Magnetic, Optical, SSD)",
    ],
    "description_en":
        "Compare storage media technologies and understand the role of sensors in automated systems.",
    "description_my":
        "သိုလှောင်မှု မီဒီယာ နည်းပညာများကို နှိုင်းယှဉ်ပြီး အလိုအလျောက် စနစ်များတွင် ဆင်ဆာများ၏ အခန်းကဏ္ဍကို နားလည်စေမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Logic Gates",
    "title_en": "Logic Gates and Truth Tables",
    "title_my": "လော့ဂျစ်ဂိတ်များနှင့် မှန်ကန်မှု ဇယားများ",
    "topics": [
      "AND, OR, NOT, NAND, NOR, XOR Gates",
      "Drawing Logic Circuits",
      "Completing Truth Tables",
    ],
    "description_en":
        "Master logic gate symbols, truth tables, and constructing logic circuits from problem statements.",
    "description_my":
        "လော့ဂျစ်ဂိတ် သင်္ကေတများ၊ မှန်ကန်မှု ဇယားများနှင့် ပုစ္ဆာများမှတစ်ဆင့် လော့ဂျစ်ပတ်လမ်းများ တည်ဆောက်ခြင်းကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Logic Circuit Design Challenge",
    "title_my": "လော့ဂျစ်ပတ်လမ်း ဒီဇိုင်း စိန်ခေါ်မှု",
    "topics": [
      "Boolean Expressions",
      "Complex Circuit Design",
      "Exam Problem Solving",
    ],
    "description_en":
        "Design logic circuits and write Boolean expressions for complex real-world control systems.",
    "description_my":
        "လက်တွေ့ကမ္ဘာ ထိန်းချုပ်ရေး စနစ်များအတွက် လော့ဂျစ်ပတ်လမ်းများ ဒီဇိုင်းဆွဲပြီး Boolean အသုံးအနှုန်းများ ရေးသားမည်။",
  },

  // ================= TERM 4: Software and Operating Systems =================
  {
    "week": 13,
    "term": 4,
    "theme": "Software",
    "title_en": "Operating Systems and Utility Software",
    "title_my": "လည်ပတ်ရေးစနစ်များနှင့် အသုံးချ ဆော့ဖ်ဝဲများ",
    "topics": [
      "Functions of an OS",
      "Interrupts and Buffers",
      "Utility Software (Backup, Defrag)",
    ],
    "description_en":
        "Examine how operating systems manage hardware resources, handle interrupts, and run utility programs.",
    "description_my":
        "လည်ပတ်ရေးစနစ်က ဟာ့ဒ်ဝဲ အရင်းအမြစ်များကို စီမံခန့်ခွဲပုံ၊ Interrupts များကို ကိုင်တွယ်ပုံနှင့် Utility ပရိုဂရမ်များကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Software",
    "title_en": "High-Level vs Low-Level Languages",
    "title_my": "အဆင့်မြင့်နှင့် အဆင့်နိမ့် ပရိုဂရမ် ဘာသာစကားများ",
    "topics": [
      "Compilers vs Interpreters",
      "Assemblers",
      "Need for Translation",
    ],
    "description_en":
        "Understand the differences between assembly and high-level languages, and the role of translators.",
    "description_my":
        "Assembly နှင့် အဆင့်မြင့် ဘာသာစကားများ၏ ကွာခြားချက်နှင့် ဘာသာပြန်ဆော့ဖ်ဝဲများ၏ အခန်းကဏ္ဍကို နားလည်စေမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Ethics",
    "title_en": "Security, Privacy, and Ethics",
    "title_my": "လုံခြုံရေး၊ ကိုယ်ရေးလုံခြုံရေးနှင့် ကျင့်ဝတ်များ",
    "topics": [
      "Cybersecurity Threats",
      "Phishing and Pharming",
      "Ethical Issues in Computing",
    ],
    "description_en":
        "Analyze cybersecurity threats, social engineering attacks, and ethical responsibilities of developers.",
    "description_my":
        "ဆိုက်ဘာလုံခြုံရေး ခြိမ်းခြောက်မှုများ၊ ဆိုရှယ်အင်ဂျင်နီယာ တိုက်ခိုက်မှုများနှင့် တီထွင်သူများ၏ ကျင့်ဝတ်ဆိုင်ရာ တာဝန်များကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Software & Ethics Case Study",
    "title_my": "ဆော့ဖ်ဝဲနှင့် ကျင့်ဝတ် သုံးသပ်ချက် ပရောဂျက်",
    "topics": [
      "Case Study Analysis",
      "OS Resource Allocation",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate software performance scenarios and ethical dilemmas in modern computing.",
    "description_my":
        "ခေတ်သစ် ကွန်ပျူတာသိပ္ပံရှိ ဆော့ဖ်ဝဲ စွမ်းဆောင်ရည် အခြေအနေများနှင့် ကျင့်ဝတ်ဆိုင်ရာ အကျပ်အတည်းများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 5: Algorithms, Flowcharts and Pseudocode =================
  {
    "week": 17,
    "term": 5,
    "theme": "Algorithms",
    "title_en": "Flowcharts and Algorithm Design",
    "title_my": "လုပ်ငန်းစဉ်ပြဇယားများနှင့် အယ်လဂိုရီသမ် ဒီဇိုင်း",
    "topics": [
      "Flowchart Standard Symbols",
      "Trace Tables",
      "Designing Solutions",
    ],
    "description_en":
        "Construct standard flowcharts and trace tables to test and document logical algorithms.",
    "description_my":
        "စံသတ်မှတ်ထားသော လုပ်ငန်းစဉ်ပြဇယားများနှင့် ဇယားခြေရာခံမှုများ တည်ဆောက်၍ ယုတ္တိတန်သော အယ်လဂိုရီသမ်များကို စမ်းသပ်မည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Pseudocode",
    "title_en": "Pseudocode Basics and Control Structures",
    "title_my": "Pseudocode အခြေခံနှင့် ထိန်းချုပ်ရေး ဖွဲ့စည်းပုံများ",
    "topics": [
      "INPUT, OUTPUT, Assignment",
      "IF / THEN / ELSE / CASE",
      "Loops (FOR, WHILE, REPEAT UNTIL)",
    ],
    "description_en":
        "Write clear, structured pseudocode using standard IGCSE syntax rules and control structures.",
    "description_my":
        "စံ IGCSE ပုံစံစည်းမျဉ်းများနှင့် ထိန်းချုပ်ရေး ဖွဲ့စည်းပုံများကို အသုံးပြု၍ ရှင်းလင်းသော Pseudocode များကို ရေးသားမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Validation",
    "title_en": "Validation and Verification",
    "title_my": "အချက်အလက် စစ်ဆေးခြင်းနှင့် အတည်ပြုခြင်း",
    "topics": [
      "Validation Checks (Range, Presence, Format)",
      "Check Digits",
      "Visual Verification",
    ],
    "description_en":
        "Implement validation algorithms in pseudocode and understand error detection methods.",
    "description_my":
        "Pseudocode တွင် Validation အယ်လဂိုရီသမ်များကို ထည့်သွင်းခြင်းနှင့် အမှားရှာဖွေရေး နည်းလမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Pseudocode Masterclass",
    "title_my": "Pseudocode အထူးသင်ခန်းစာ",
    "topics": [
      "Complex Algorithm Design",
      "Trace Table Practice",
      "Exam Paper 2 Drills",
    ],
    "description_en":
        "Tackle high-tariff pseudocode design and trace table questions from IGCSE Paper 2.",
    "description_my":
        "IGCSE Paper 2 မှ အမှတ်များသော Pseudocode ဒီဇိုင်းနှင့် ဇယားခြေရာခံ မေးခွန်းများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 6: Programming Concepts in Python =================
  {
    "week": 21,
    "term": 6,
    "theme": "Programming",
    "title_en": "Programming Basics in Python",
    "title_my": "Python ဖြင့် ပရိုဂရမ်ရေးခြင်း အခြေခံ",
    "topics": [
      "Variables and Data Types",
      "Selection (if/elif/else)",
      "Iteration (for/while loops)",
    ],
    "description_en":
        "Translate pseudocode algorithms into fully functional Python programs.",
    "description_my":
        "Pseudocode အယ်လဂိုရီသမ်များကို အလုပ်လုပ်နိုင်သော Python ပရိုဂရမ်များအဖြစ် ပြောင်းလဲရေးသားမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Programming",
    "title_en": "Arrays and Data Structures",
    "title_my": "အေရေးများနှင့် ဒေတာ ဖွဲ့စည်းပုံများ",
    "topics": [
      "1D and 2D Arrays",
      "Searching and Sorting Arrays",
      "String Manipulation",
    ],
    "description_en":
        "Handle arrays and implement linear search and bubble sort algorithms in Python code.",
    "description_my":
        "Python ကုဒ်များတွင် အေရေးများကို ကိုင်တွယ်ခြင်း၊ Linear search နှင့် Bubble sort များကို အကောင်အထည်ဖော်မည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Subprograms",
    "title_en": "Functions and Procedures",
    "title_my": "ဖန်ရှင်များနှင့် ပရိုစီဂျာများ (Subprograms)",
    "topics": [
      "Defining Subprograms",
      "Parameters and Return Values",
      "Local and Global Scope",
    ],
    "description_en":
        "Write modular Python programs using functions and procedures with parameters.",
    "description_my":
        "Parameters များပါရှိသော ဖန်ရှင်များနှင့် ပရိုစီဂျာများကို သုံး၍ မော်ဂျူးစနစ်ပါသည့် Python ပရိုဂရမ်များ ရေးသားမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Python Programming Project",
    "title_my": "Python ပရိုဂရမ်ရေးဆွဲရေး ပရောဂျက်",
    "topics": ["Complete Application Build", "Error Handling", "Testing Code"],
    "description_en":
        "Build and test a comprehensive console application in Python incorporating arrays and subprograms.",
    "description_my":
        "အေရေးများနှင့် Subprograms များပါဝင်သည့် ပြည့်စုံသော ကွန်ဆိုးလ် အပလီကေးရှင်းတစ်ခု တည်ဆောက်စမ်းသပ်မည်။",
  },

  // ================= TERM 7: Databases and SQL =================
  {
    "week": 25,
    "term": 7,
    "theme": "Databases",
    "title_en": "Database Concepts and Structure",
    "title_my": "ဒေတာဘေ့စ် သဘောတရားနှင့် ဖွဲ့စည်းပုံ",
    "topics": [
      "Tables, Records, Fields",
      "Primary Keys and Foreign Keys",
      "Data Types in Databases",
    ],
    "description_en":
        "Understand relational database structures and how primary keys ensure data integrity.",
    "description_my":
        "ဆက်စပ် ဒေတာဘေ့စ် ဖွဲ့စည်းပုံများကို နားလည်စေပြီး Primary keys များက ဒေတာ မှန်ကန်မှုကို မည်သို့သေချာစေကြောင်း လေ့လာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "SQL",
    "title_en": "SQL Query Writing",
    "title_my": "SQL ညွှန်ကြားချက်များ ရေးသားခြင်း",
    "topics": [
      "SELECT, FROM, WHERE Statements",
      "Sorting Results (ORDER BY)",
      "Combining Criteria (AND, OR, LIKE)",
    ],
    "description_en":
        "Write Structured Query Language (SQL) statements to extract and filter data from databases.",
    "description_my":
        "ဒေတာဘေ့စ်များမှ အချက်အလက်များကို ထုတ်နုတ်ရန်နှင့် စစ်ထုတ်ရန် SQL ညွှန်ကြားချက်များ ရေးသားမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Databases",
    "title_en": "Database Management and Integrity",
    "title_my": "ဒေတာဘေ့စ် စီမံခန့်ခွဲမှုနှင့် လုံခြုံမှု",
    "topics": [
      "Querying Multiple Tables",
      "Avoiding Redundancy",
      "Data Validation in Tables",
    ],
    "description_en":
        "Design normalized tables and write multi-table queries to retrieve complex data records.",
    "description_my":
        "ပုံစံကျဇယားများ ဒီဇိုင်းဆွဲခြင်းနှင့် ရှုပ်ထွေးသော မှတ်တမ်းများကို ရယူရန် ဇယားပေါင်းစုံ ကွီရီများ ရေးသားမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "SQL Database Studio",
    "title_my": "SQL ဒေတာဘေ့စ် အလုပ်ရုံ",
    "topics": [
      "Database Design Tasks",
      "Advanced SQL Queries",
      "Exam Practice",
    ],
    "description_en":
        "Solve IGCSE database design and SQL query completion problems.",
    "description_my":
        "IGCSE ဒေတာဘေ့စ် ဒီဇိုင်းနှင့် SQL ကွီရီ ဖြည့်စွက် မေးခွန်းများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 8: Automated Systems and Robotics =================
  {
    "week": 29,
    "term": 8,
    "theme": "Automation",
    "title_en": "Automated Systems and Feedback Loops",
    "title_my": "အလိုအလျောက် စနစ်များနှင့် တုံ့ပြန်မှု စက်ဝန်းများ",
    "topics": [
      "Role of Microprocessors",
      "Feedback Loops in Control",
      "Monitoring vs Control Systems",
    ],
    "description_en":
        "Examine how sensors, microprocessors, and actuators interact in automated control systems.",
    "description_my":
        "အလိုအလျောက် ထိန်းချုပ်ရေး စနစ်များတွင် ဆင်ဆာများ၊ မိုက်ခရိုပရိုဆက်ဆာများနှင့် Actuators များ မည်သို့ချိတ်ဆက်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Robotics",
    "title_en": "Robotics and Artificial Intelligence",
    "title_my": "စက်ရုပ်ပညာနှင့် ဉာဏ်ရည်တု",
    "topics": [
      "Characteristics of Robots",
      "AI and Machine Learning Basics",
      "Applications in Industry",
    ],
    "description_en":
        "Understand robotic hardware independence, sensor integration, and basic AI applications.",
    "description_my":
        "စက်ရုပ်များ၏ လွတ်လပ်သော ဟာ့ဒ်ဝဲ ဂုဏ်သတ္တိများ၊ ဆင်ဆာ ပေါင်းစပ်မှုနှင့် အခြေခံ AI အသုံးချမှုများကို နားလည်စေမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Software Engineering",
    "title_en": "Testing and Verification Strategies",
    "title_my": "စမ်းသပ်ခြင်းနှင့် အတည်ပြုခြင်း ဗျူဟာများ",
    "topics": [
      "Test Data (Normal, Boundary, Erroneous)",
      "Debugging Techniques",
      "Trace Analysis",
    ],
    "description_en":
        "Master selecting appropriate test data and debugging software logic errors.",
    "description_my":
        "သင့်လျော်သော စ Test data ရွေးချယ်ခြင်းနှင့် ဆော့ဖ်ဝဲ ယုတ္တိအမှားများကို Debug လုပ်ခြင်း ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Automated System Design Project",
    "title_my": "အလိုအလျောက် စနစ် ဒီဇိုင်း ပရောဂျက်",
    "topics": ["System Specification", "Control Pseudocode", "Exam Practice"],
    "description_en":
        "Design a complete automated monitoring and control system with corresponding pseudocode.",
    "description_my":
        "စောင့်ကြည့်ခြင်းနှင့် ထိန်းချုပ်ခြင်းပါဝင်သည့် အလိုအလျောက်စနစ် တစ်ခုကို Pseudocode ဖြင့် ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 9: Exam Prep & Final Capstone =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 Theory Exam Intensive",
    "title_my": "Paper 1 သီအိုရီ စာမေးပွဲ အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Hardware & Software Revision",
      "Networks & Data Representation Drills",
      "Mark Scheme Mastery",
    ],
    "description_en":
        "Intensive drilling of theory concepts and structured questions for Paper 1.",
    "description_my":
        "Paper 1 အတွက် သီအိုရီ သဘောတရားများနှင့် အဆောက်အအုံပါ မေးခွန်းများကို အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 2 Problem-Solving & Programming",
    "title_my": "Paper 2 ပြဿနာဖြေရှင်းခြင်းနှင့် ပရိုဂရမ်ရေးခြင်း",
    "topics": [
      "Pseudocode Mastery",
      "Trace Table Drills",
      "SQL and Python Problem Solving",
    ],
    "description_en":
        "Master problem-solving, pseudocode writing, and SQL queries for Paper 2 success.",
    "description_my":
        "Paper 2 တွင် အောင်မြင်မှုရရန် ပြဿနာဖြေရှင်းခြင်း၊ Pseudocode ရေးသားခြင်းနှင့် SQL ကွီရီများကို လေ့ကျင့်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Past Paper Mock Examinations",
    "title_my": "မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 2",
      "Performance Diagnostics",
    ],
    "description_en":
        "Complete full-length mock examinations under strict official IGCSE timing conditions.",
    "description_my":
        "တရားဝင် IGCSE အချိန်သတ်မှတ်ချက်များအတိုင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Computer Science Graduation",
    "title_my": "IGCSE ကွန်ပျူတာသိပ္ပံ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Technical Growth",
      "Pathways to Advanced Computing",
    ],
    "description_en":
        "Celebrate the completion of IGCSE Computer Science and preparation for A-Level Computer Science.",
    "description_my":
        "IGCSE ကွန်ပျူတာသိပ္ပံ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး A-Level ကွန်ပျူတာသိပ္ပံဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
