// File: ai_data_bridge/igcse_global_perspectives_research_all_terms.dart
// IGCSE Global Perspectives & Research Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseGlobalPerspectivesResearchAllTermsData = [
  // ================= TERM 1: Research Skills & Global Issues Introduction =================
  {
    "week": 1,
    "term": 1,
    "theme": "Research Skills",
    "title_en": "Deconstructing Global Issues",
    "title_my": "ကမ္ဘာ့ပြဿနာများကို အပိုင်းပိုင်းခွဲ၍ လေ့လာခြင်း",
    "topics": [
      "Local-Global Links",
      "Identifying Causes and Consequences",
      "Perspective-Taking",
    ],
    "description_en":
        "Learn how to deconstruct complex global issues, identifying local-global connections and diverse perspectives.",
    "description_my":
        "ရှုပ်ထွေးသော ကမ္ဘာ့ပြဿနာများကို အသေးစိတ်ခွဲခြမ်းစိတ်ဖြာပြီး ဒေသတွင်းနှင့် ကမ္ဘာလုံးဆိုင်ရာ ချိတ်ဆက်မှုများကို ဖော်ထုတ်ရန် လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Research Skills",
    "title_en": "Evaluating Sources and Evidence",
    "title_my": "သတင်းရင်းမြစ်များနှင့် အထောက်အထားများကို အကဲဖြတ်ခြင်း",
    "topics": [
      "Credibility and Reliability",
      "Bias and Propaganda",
      "Fact vs Opinion",
    ],
    "description_en":
        "Master the critical skill of evaluating sources for bias, vested interests, and factual reliability.",
    "description_my":
        "ဘက်လိုက်မှု၊ ကိုယ်ကျိုးစီးပွားနှင့် အချက်အလက် တိကျမှုတို့အတွက် သတင်းရင်းမြစ်များကို အကဲဖြတ်သည့် ဝေဖန်ပိုင်းခြားရေး စွမ်းရည်ကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Research Skills",
    "title_en": "Formulating Research Questions",
    "title_my": "သုတေသန မေးခွန်းများ ရေးဆွဲခြင်း",
    "topics": [
      "Open-ended Questions",
      "Feasibility and Scope",
      "Research Objectives",
    ],
    "description_en":
        "Develop clear, focused, and open-ended research questions suitable for an academic investigation.",
    "description_my":
        "ပညာရပ်ဆိုင်ရာ သုတေသန စုံစမ်းစစ်ဆေးမှုတစ်ခုအတွက် ရှင်းလင်းပြီး စုစည်းမှုရှိသော ပွင့်လင်းမြင်သာသည့် သုတေသန မေးခွန်းများကို တည်ဆောက်မည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Research Proposal Workshop",
    "title_my": "သုတေသန အဆိုပြုချက် အလုပ်ရုံ",
    "topics": ["Drafting Proposals", "Selecting Topics", "Peer Review"],
    "description_en":
        "Draft and pitch a formal research proposal for an independent global perspectives investigation.",
    "description_my":
        "လွတ်လပ်သော ကမ္ဘာ့အမြင် စုံစမ်းစစ်ဆေးမှုတစ်ခုအတွက် တရားဝင် သုတေသန အဆိုပြုချက်ကို ရေးသားတင်ပြမည်။",
  },

  // ================= TERM 2: Ethics, Values and Belief Systems =================
  {
    "week": 5,
    "term": 2,
    "theme": "Ethics",
    "title_en": "Moral Dilemmas and Ethical Frameworks",
    "title_my": "ကိုယ်ကျင့်တရားဆိုင်ရာ အကျပ်အတည်းများနှင့် ကျင့်ဝတ်ဘောင်များ",
    "topics": [
      "Utilitarianism and Rights",
      "Conflicting Moral Values",
      "Case Studies in Bioethics",
    ],
    "description_en":
        "Examine complex moral dilemmas and evaluate ethical arguments from multiple philosophical standpoints.",
    "description_my":
        "ရှုပ်ထွေးသော ကိုယ်ကျင့်တရားဆိုင်ရာ အကျပ်အတည်းများကို လေ့လာပြီး ဒဿနိကဗေဒ ရှုထောင့်အမျိုးမျိုးမှ ကျင့်ဝတ်ဆိုင်ရာ အငြင်းပွားမှုများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Ethics",
    "title_en": "Belief Systems and Cultural Relativism",
    "title_my":
        "ယုံကြည်မှုစနစ်များနှင့် ယဉ်ကျေးမှု ဆွေမျိုးစပ်မှု (Cultural Relativism)",
    "topics": [
      "Tradition vs Modernity",
      "Universal Human Rights vs Cultural Practices",
      "Respecting Diversity",
    ],
    "description_en":
        "Explore the clash between traditional belief systems and universal human rights in a globalized world.",
    "description_my":
        "ကမ္ဘာ့ရွာကြီးစနစ်အတွင်း ရိုးရာယုံကြည်မှုစနစ်များနှင့် ကမ္ဘာ့လူ့အခွင့်အရေးများအကြား ပဋိပက္ခများကို စူးစမ်းမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Ethics",
    "title_en": "Freedom of Expression and Censorship",
    "title_my": "ထုတ်ဖော်ပြောဆိုခွင့် လွတ်လပ်မှုနှင့် သတင်းဆင်ဆာဖြတ်ခြင်း",
    "topics": [
      "Limits of Free Speech",
      "State Control of Information",
      "Digital Surveillance Ethics",
    ],
    "description_en":
        "Analyze arguments surrounding freedom of speech, hate speech legislation, and state censorship.",
    "description_my":
        "ပြောဆိုခွင့် လွတ်လပ်မှု၊ မုန်းတီးရေး စကားပြောဆိုမှု ဥပဒေများနှင့် နိုင်ငံတော်၏ ဆင်ဆာဖြတ်မှုဆိုင်ရာ အငြင်းပွားမှုများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Ethical Perspectives Essay Studio",
    "title_my": "ကျင့်ဝတ်ဆိုင်ရာ ရှုထောင့်များ အက်ဆေး အလုပ်ရုံ",
    "topics": [
      "Structuring Ethical Arguments",
      "Refuting Counter-claims",
      "Exam Practice",
    ],
    "description_en":
        "Write a structured analytical essay evaluating conflicting ethical perspectives on a global issue.",
    "description_my":
        "ကမ္ဘာ့ပြဿနာတစ်ခုအပေါ် ဆန့်ကျင်ဘက် ကျင့်ဝတ်ဆိုင်ရာ ရှုထောင့်များကို အကဲဖြတ်သည့် ဖွဲ့စည်းတည်ဆောက်ထားသော ခွဲခြမ်းစိတ်ဖြာ အက်ဆေး ရေးသားမည်။",
  },

  // ================= TERM 3: Demographics, Migration and Human Rights =================
  {
    "week": 9,
    "term": 3,
    "theme": "Human Rights",
    "title_en": "Universal Human Rights and Violations",
    "title_my": "ကမ္ဘာ့လူ့အခွင့်အရေးနှင့် ချိုးဖောက်မှုများ",
    "topics": [
      "UDHR Analysis",
      "Modern Slavery and Trafficking",
      "Rights of Vulnerable Groups",
    ],
    "description_en":
        "Investigate systemic human rights violations globally and evaluate the effectiveness of protective bodies.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ စနစ်ကျသော လူ့အခွင့်အရေး ချိုးဖောက်မှုများကို စူးစမ်းပြီး ကာကွယ်ရေး အဖွဲ့အစည်းများ၏ ထိရောက်မှုကို အကဲဖြတ်မည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Migration",
    "title_en": "Global Migration and Refugee Crises",
    "title_my":
        "ကမ္ဘာလုံးဆိုင်ရာ ရွှေ့ပြောင်းနေထိုင်မှုနှင့် ဒုက္ခသည် အကျပ်အတည်းများ",
    "topics": [
      "Push-Pull Dynamics",
      "Asylum Seekers vs Economic Migrants",
      "Integration and Multiculturalism",
    ],
    "description_en":
        "Examine the socioeconomic drivers of migration and the international community's response to refugee crises.",
    "description_my":
        "ရွှေ့ပြောင်းရခြင်း၏ လူမှုစီးပွား တွန်းအားများနှင့် ဒုက္ခသည် အကျပ်အတည်းများအပေါ် နိုင်ငံတကာ အသိုက်အဝန်း၏ တုံ့ပြန်မှုကို လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Inequality",
    "title_en": "Poverty, Wealth Gap, and Social Justice",
    "title_my": "ဆင်းရဲမွဲတေမှု၊ ဓနဥစ္စာ ကွာဟချက်နှင့် လူမှု တရားမျှတမှု",
    "topics": [
      "Causes of Extreme Poverty",
      "Global Inequality Indices",
      "Microfinance and Empowerment",
    ],
    "description_en":
        "Analyze the systemic causes of global poverty and evaluate anti-poverty strategies and interventions.",
    "description_my":
        "ကမ္ဘာ့ဆင်းရဲမွဲတေမှု၏ စနစ်ကျသော အကြောင်းရင်းများကို ခွဲခြမ်းစိတ်ဖြာပြီး ဆင်းရဲမှု တိုက်ဖျက်ရေး မဟာဗျူဟာများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Rights and Migration Simulation",
    "title_my": "အခွင့်အရေးနှင့် ရွှေ့ပြောင်းမှု ပုံစံတူ ဆွေးနွေးပွဲ",
    "topics": [
      "Policy Negotiation",
      "Defending Perspectives",
      "Collaborative Problem Solving",
    ],
    "description_en":
        "Participate in a simulated international summit addressing refugee resettlement policies.",
    "description_my":
        "ဒုက္ခသည် ပြန်လည်နေရာချထားရေး မူဝါဒများကို ဖြေရှင်းသည့် နိုင်ငံတကာ ညီလာခံ ပုံစံတူ ဆွေးနွေးပွဲတွင် ပါဝင်မည်။",
  },

  // ================= TERM 4: Environment, Climate and Sustainability =================
  {
    "week": 13,
    "term": 4,
    "theme": "Environment",
    "title_en": "Climate Change Politics and Policy",
    "title_my": "ရာသီဥတု ပြောင်းလဲမှု နိုင်ငံရေးနှင့် မူဝါဒများ",
    "topics": [
      "COP Summits and Paris Agreement",
      "Carbon Tax vs Cap-and-Trade",
      "National Interests vs Global Action",
    ],
    "description_en":
        "Evaluate international climate agreements and the political challenges of enforcing carbon reduction targets.",
    "description_my":
        "နိုင်ငံတကာ ရာသီဥတု သဘောတူညီချက်များနှင့် ကာဗွန်လျှော့ချရေး ပစ်မှတ်များကို အကောင်အထည်ဖော်ရာတွင် ရှိသည့် နိုင်ငံရေး စိန်ခေါ်မှုများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Environment",
    "title_en": "Biodiversity Loss and Ecosystem Collapse",
    "title_my": "ဇီဝမျိုးစုံမျိုးကွဲ ဆုံးရှုံးခြင်းနှင့် ဂေဟစနစ် ပြိုလဲခြင်း",
    "topics": [
      "Deforestation and Habitat Destruction",
      "Conservation Strategies",
      "Value of Ecosystem Services",
    ],
    "description_en":
        "Investigate the rapid loss of global biodiversity and evaluate conservation versus economic development.",
    "description_my":
        "ကမ္ဘာ့ဇီဝမျိုးစုံမျိုးကွဲများ လျင်မြန်စွာ ဆုံးရှုံးနေမှုကို စူးစမ်းပြီး သဘာဝထိန်းသိမ်းရေးနှင့် စီးပွားရေး ဖွံ့ဖြိုးတိုးတက်မှုကို ချိန်ညှိမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Sustainability",
    "title_en": "Sustainable Urbanisation and Energy",
    "title_my": "ရေရှည်တည်တံ့သော မြို့ပြထွန်းကားမှုနှင့် စွမ်းအင်",
    "topics": [
      "Smart Cities",
      "Renewable Energy Transitions",
      "Circular Economy Models",
    ],
    "description_en":
        "Examine how urban centers and industries transition toward sustainable, zero-carbon futures.",
    "description_my":
        "မြို့ပြများနှင့် စက်မှုလုပ်ငန်းများသည် ရေရှည်တည်တံ့ပြီး ကာဗွန်ထုတ်လွှတ်မှု မရှိသည့် အနာဂတ်ဆီသို့ မည်သို့ကူးပြောင်းနေကြောင်း လေ့လာမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Environmental Action Plan Studio",
    "title_my": "ပတ်ဝန်းကျင် လှုပ်ရှားမှု စီမံချက် အလုပ်ရုံ",
    "topics": [
      "Local-Global Environmental Projects",
      "Action Planning",
      "Feasibility Analysis",
    ],
    "description_en":
        "Design a localized action plan addressing a specific environmental crisis with global implications.",
    "description_my":
        "ကမ္ဘာလုံးဆိုင်ရာ သက်ရောက်မှုရှိသော သတ်မှတ်ထားသော ပတ်ဝန်းကျင် အကျပ်အတည်းတစ်ခုအတွက် ဒေသတွင်း လှုပ်ရှားမှု စီမံချက်တစ်ခုကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 5: Technology, Digital Future and AI Ethics =================
  {
    "week": 17,
    "term": 5,
    "theme": "Technology",
    "title_en": "The Artificial Intelligence Revolution and Ethics",
    "title_my": "ဉာဏ်ရည်တု (AI) တော်လှန်ရေးနှင့် ကျင့်ဝတ်များ",
    "topics": [
      "Automation of Labour",
      "Algorithmic Bias",
      "AGI and Human Agency",
    ],
    "description_en":
        "Analyze the ethical, social, and economic implications of rapid advancements in artificial intelligence.",
    "description_my":
        "ဉာဏ်ရည်တု တိုးတက်မှု အမြန်နှုန်း၏ ကျင့်ဝတ်ဆိုင်ရာ၊ လူမှုရေးနှင့် စီးပွားရေး သက်ရောက်မှုများကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Technology",
    "title_en": "Surveillance Capitalism and Data Privacy",
    "title_my": "စောင့်ကြည့်ရေး ရင်းနှီးမြှုပ်နှံမှုနှင့် ကိုယ်ရေးလုံခြုံရေး",
    "topics": [
      "Data Harvesting",
      "Facial Recognition and Civil Liberties",
      "The Right to Privacy",
    ],
    "description_en":
        "Explore how big tech data collection threatens personal privacy and democratic institutions.",
    "description_my":
        "နည်းပညာ ကုမ္ပဏီကြီးများ၏ ဒေတာကောက်ယူမှုက တစ်ဦးချင်း ကိုယ်ရေးလုံခြုံရေးနှင့် ဒီမိုကရေစီ အဖွဲ့အစည်းများကို မည်သို့ခြိမ်းခြောက်ကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Technology",
    "title_en": "The Digital Divide and Global Inequality",
    "title_my": "ဒီဂျစ်တယ် ကွာဟမှုနှင့် ကမ္ဘာ့ မညီမျှမှု",
    "topics": [
      "Internet Access Inequality",
      "Educational Digital Gap",
      "Technological Imperialism",
    ],
    "description_en":
        "Evaluate how unequal access to digital infrastructure exacerbates existing global inequalities.",
    "description_my":
        "ဒီဂျစ်တယ် အခြေခံအဆောက်အအုံ လက်လှမ်းမီမှု မညီမျှခြင်းက ရှိရင်းစွဲ ကမ္ဘာ့ မညီမျှမှုများကို ပိုမိုဆိုးရွားစေပုံကို အကဲဖြတ်မည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Technology Policy Regulation Studio",
    "title_my": "နည်းပညာ မူဝါဒ ထိန်းညှိမှု အလုပ်ရုံ",
    "topics": [
      "Drafting Tech Regulations",
      "Balancing Innovation and Safety",
      "Exam Practice",
    ],
    "description_en":
        "Draft a comprehensive regulatory framework balancing technological innovation with public safety and ethics.",
    "description_my":
        "နည်းပညာ တီထွင်ဖန်တီးမှုကို အများပြည်သူ ဘေးကင်းလုံခြုံရေးနှင့် ကျင့်ဝတ်တို့ဖြင့် ချိန်ညှိပေးသည့် မူဝါဒဘောင်တစ်ခုကို ရေးဆွဲမည်။",
  },

  // ================= TERM 6: Global Economy, Work and Corporations =================
  {
    "week": 21,
    "term": 6,
    "theme": "Global Economy",
    "title_en": "The Changing Nature of Work",
    "title_my": "ပြောင်းလဲနေသော အလုပ်အကိုင် သဘောသဘာဝ",
    "topics": [
      "The Gig Economy",
      "Remote Work and Global Talent",
      "Future-proofing Skills",
    ],
    "description_en":
        "Examine how globalization and automation are transforming employment structures and workers' rights worldwide.",
    "description_my":
        "ကမ္ဘာ့ရွာကြီးစနစ်နှင့် အလိုအလျောက်စနစ်တို့က ကမ္ဘာတစ်ဝန်းရှိ အလုပ်အကိုင် ဖွဲ့စည်းပုံနှင့် အလုပ်သမား အခွင့်အရေးများကို မည်သို့ပြောင်းလဲနေကြောင်း လေ့လာမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Global Economy",
    "title_en": "Multinational Corporations and Power",
    "title_my": "နိုင်ငံစုံ ကော်ပိုရေးရှင်းများနှင့် အာဏာစက်",
    "topics": [
      "Corporate Tax Avoidance",
      "Supply Chain Exploitation",
      "CSR and Accountability",
    ],
    "description_en":
        "Evaluate the political and economic influence of multinational corporations in developing nations.",
    "description_my":
        "ဖွံ့ဖြိုးဆဲနိုင်ငံများတွင် နိုင်ငံစုံ ကော်ပိုရေးရှင်းများ၏ နိုင်ငံရေးနှင့် စီးပွားရေး လွှမ်းမိုးမှုကို အကဲဖြတ်မည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Global Economy",
    "title_en": "Fair Trade and Ethical Consumerism",
    "title_my": "တရားမျှတသော ကုန်သွယ်ရေးနှင့် ကျင့်ဝတ်စောင့်သုံး စားသုံးမှု",
    "topics": [
      "Fair Trade Certification",
      "Ethical Supply Chains",
      "Consumer Power",
    ],
    "description_en":
        "Analyze the effectiveness of fair trade movements and consumer choices in driving corporate social responsibility.",
    "description_my":
        "ကော်ပိုရိတ် လူမှုတာဝန်ခံမှုကို တွန်းအားပေးရာတွင် တရားမျှတသော ကုန်သွယ်ရေး လှုပ်ရှားမှုများနှင့် စားသုံးသူ ရွေးချယ်မှုများ၏ ထိရောက်မှုကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Global Economy Case Study Studio",
    "title_my": "ကမ္ဘာ့စီးပွားရေး လက်တွေ့လေ့လာမှု အလုပ်ရုံ",
    "topics": [
      "Corporate Accountability",
      "Labor Rights Campaigns",
      "Exam Practice",
    ],
    "description_en":
        "Investigate real-world corporate misconduct and evaluate global activist campaigns for reform.",
    "description_my":
        "လက်တွေ့ကမ္ဘာ ကော်ပိုရိတ် အလွဲသုံးစားလုပ်မှုများကို လေ့လာပြီး ပြုပြင်ပြောင်းလဲရေးအတွက် ကမ္ဘာ့တက်ကြွလှုပ်ရှားမှု ကမ်ပိန်းများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 7: Independent Research Project - Formulation & Methodology =================
  {
    "week": 25,
    "term": 7,
    "theme": "Research Project",
    "title_en": "Research Design and Methodology",
    "title_my": "သုတေသန ဒီဇိုင်းနှင့် နည်းစနစ်များ",
    "topics": [
      "Primary vs Secondary Research",
      "Quantitative vs Qualitative Data",
      "Sampling Methods",
    ],
    "description_en":
        "Select and justify appropriate research methodologies for your IGCSE Research Report investigation.",
    "description_my":
        "သင်၏ IGCSE သုတေသန အစီရင်ခံစာ စုံစမ်းစစ်ဆေးမှုအတွက် သင့်လျော်သော သုတေသန နည်းစနစ်များကို ရွေးချယ်ပြီး ကျိုးကြောင်းပြမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Research Project",
    "title_en": "Literature Review and Contextual Analysis",
    "title_my": "စာပေသုံးသပ်ချက်နှင့် နောက်ခံ အကြောင်းအရာ ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": [
      "Synthesizing Existing Literature",
      "Identifying Research Gaps",
      "Theoretical Frameworks",
    ],
    "description_en":
        "Review existing academic and media literature to establish context and identify gaps for your research question.",
    "description_my":
        "နောက်ခံအခြေအနေ သတ်မှတ်ရန်နှင့် သုတေသန မေးခွန်းအတွက် လိုအပ်ချက်များကို ဖော်ထုတ်ရန် ရှိပြီးသား စာပေများကို သုံးသပ်မည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Research Project",
    "title_en": "Data Collection and Fieldwork Execution",
    "title_my": "ဒေတာကောက်ယူခြင်းနှင့် ကွင်းဆင်းလေ့လာမှု လုပ်ဆောင်ခြင်း",
    "topics": [
      "Designing Questionnaires and Surveys",
      "Conducting Interviews",
      "Ethical Considerations in Research",
    ],
    "description_en":
        "Execute primary data collection ethically and rigorously, ensuring reliable and valid results.",
    "description_my":
        "ယုံကြည်စိတ်ချရပြီး တိကျသော ရလဒ်များရရှိစေရန် ကျင့်ဝတ်နှင့်အညီ ပင်ရင်းဒေတာ ကောက်ယူမှုကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Research Progress Review Studio",
    "title_my": "သုတေသန တိုးတက်မှု သုံးသပ်ခြင်း အလုပ်ရုံ",
    "topics": ["Data Audit", "Methodology Adjustments", "Peer Review"],
    "description_en":
        "Evaluate collected data quality, address methodological limitations, and refine the research trajectory.",
    "description_my":
        "ကောက်ယူထားသော ဒေတာအရည်အသွေးကို အကဲဖြတ်ခြင်း၊ နည်းစနစ် ကန့်သတ်ချက်များကို ဖြေရှင်းခြင်းနှင့် သုတေသန လမ်းကြောင်းကို ပြင်ဆင်မည်။",
  },

  // ================= TERM 8: Data Analysis, Findings and Report Drafting =================
  {
    "week": 29,
    "term": 8,
    "theme": "Research Report",
    "title_en": "Analyzing Quantitative and Qualitative Data",
    "title_my":
        "အရေအတွက်နှင့် အရည်အသွေးဆိုင်ရာ ဒေတာများကို ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": [
      "Coding Qualitative Responses",
      "Statistical Analysis of Survey Data",
      "Triangulation of Evidence",
    ],
    "description_en":
        "Analyze collected research findings objectively, cross-referencing primary data with secondary sources.",
    "description_my":
        "ပင်ရင်းဒေတာကို ဒုတိယအဆင့် သတင်းရင်းမြစ်များနှင့် အပြန်အလှန် နှိုင်းယှဉ်စစ်ဆေးလျက် သုတေသန တွေ့ရှိချက်များကို ဘက်လိုက်မှုမရှိဘဲ ခွဲခြမ်းမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Research Report",
    "title_en": "Evaluating Perspectives and Formulating Conclusions",
    "title_my": "ရှုထောင့်များကို အကဲဖြတ်ခြင်းနှင့် ကောက်ချက်ချခြင်း",
    "topics": [
      "Weighing Competing Arguments",
      "Synthesizing Findings",
      "Answering the Research Question",
    ],
    "description_en":
        "Evaluate opposing perspectives based on empirical data and formulate a well-supported final conclusion.",
    "description_my":
        "လက်တွေ့ဒေတာ အပေါ်မူတည်၍ ဆန့်ကျင်ဘက် ရှုထောင့်များကို အကဲဖြတ်ပြီး ခိုင်မာသော နောက်ဆုံး ကောက်ချက်ကို တည်ဆောက်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Research Report",
    "title_en": "Reflective Thinking and Personal Growth",
    "title_my": "ဆင်ခြင်သုံးသပ်တွေးခေါ်မှုနှင့် ကိုယ်ပိုင် ဖွံ့ဖြိုးတိုးတက်မှု",
    "topics": [
      "Reflecting on Research Journey",
      "How Perspectives Have Changed",
      "Limitations of Personal Findings",
    ],
    "description_en":
        "Write a sophisticated personal reflection evaluating how your own views evolved throughout the research process.",
    "description_my":
        "သုတေသန လုပ်ငန်းစဉ်တစ်လျှောက် သင်၏ အမြင်များ မည်သို့ပြောင်းလဲခဲ့သည်ကို အကဲဖြတ်သည့် အဆင့်မြင့် ကိုယ်ပိုင် ဆင်ခြင်သုံးသပ်ချက် ရေးသားမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Drafting the Full IGCSE Research Report",
    "title_my": "IGCSE သုတေသန အစီရင်ခံစာ အပြည့်အစုံ ရေးသားခြင်း",
    "topics": [
      "Report Formatting",
      "Citations and Bibliography",
      "Final Polish",
    ],
    "description_en":
        "Assemble and refine the complete IGCSE Global Perspectives Research Report adhering strictly to word limits and citation rules.",
    "description_my":
        "စာလုံးရေ ကန့်သတ်ချက်များနှင့် ကိုးကားမှု စည်းမျဉ်းများကို တင်းကျပ်စွာ လိုက်နာလျက် IGCSE Global Perspectives သုတေသန အစီရင်ခံစာ အပြည့်အစုံကို စုစည်းမည်။",
  },

  // ================= TERM 9: Exam Prep, Presentation & Graduation =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Written Examination) Intensive",
    "title_my": "Paper 1 (စာမေးပွဲ စာစောင်) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Source Analysis Techniques",
      "Evaluating Global Arguments",
      "Timed Essay Practice",
    ],
    "description_en":
        "Intensive practice for the IGCSE Global Perspectives written examination paper, focusing on source evaluation and reasoning.",
    "description_my":
        "အရင်းအမြစ် အကဲဖြတ်ခြင်းနှင့် ကျိုးကြောင်းဆီလျော်မှုကို အဓိကထားလျက် IGCSE Global Perspectives စာရေးဖြေ စာမေးပွဲအတွက် အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Reflective Paper and Presentation Skills",
    "title_my": "ဆင်ခြင်သုံးသပ်ချက် စာစောင်နှင့် တင်ဆက်မှု စွမ်းရည်များ",
    "topics": [
      "Structuring Reflections",
      "Oral Presentation Design",
      "Defending Research Findings",
    ],
    "description_en":
        "Master the skills required for presenting research findings and structuring reflective coursework elements.",
    "description_my":
        "သုတေသန တွေ့ရှိချက်များကို တင်ပြခြင်းနှင့် ဆင်ခြင်သုံးသပ်ချက် ကိုယ်စားပြု အစိတ်အပိုင်းများကို ဖွဲ့စည်းခြင်းဆိုင်ရာ ကျွမ်းကျင်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Component Mock Simulations",
    "title_my": "အကဲဖြတ် အစိတ်အပိုင်း အားလုံး ပုံစံတူ စာမေးပွဲ ဖြေဆိုခြင်း",
    "topics": [
      "Timed Paper 1 Mock",
      "Research Report Review",
      "Presentation Simulation",
    ],
    "description_en":
        "Complete full-length mock examinations and final reviews of research reports under simulated conditions.",
    "description_my":
        "ပုံစံတူ အခြေအနေများအောက်တွင် အချိန်သတ်မှတ်ချက်ဖြင့် ပုံစံတူ စာမေးပွဲများနှင့် သုတေသန အစီရင်ခံစာ နောက်ဆုံး သုံးသပ်မှုများကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Global Perspectives & Research Graduation",
    "title_my": "IGCSE ကမ္ဘာ့အမြင်နှင့် သုတေသန ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Global Research Symposium",
      "Celebrating Academic Excellence",
      "Pathways to Advanced Global Studies",
    ],
    "description_en":
        "Celebrate the completion of IGCSE Global Perspectives & Research with a grand academic symposium and project showcase.",
    "description_my":
        "ကြီးမားသော ပညာရပ်ဆိုင်ရာ ညီလာခံနှင့် ပရောဂျက်ပြပွဲတို့ဖြင့် IGCSE ကမ္ဘာ့အမြင်နှင့် သုတေသန ပြီးမြောက်မှုကို ဂုဏ်ပြုကျင်းပမည်။",
  },
];
