// File: ai_data_bridge/igcse_chemistry_all_terms.dart
// IGCSE Chemistry Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseChemistryAllTermsData = [
  // ================= TERM 1: States of Matter & Atomic Structure =================
  {
    "week": 1,
    "term": 1,
    "theme": "States of Matter",
    "title_en": "The Particulate Nature of Matter",
    "title_my": "ဒြပ်ဝတ္ထု၏ အမှုန်သဘောသဘာဝ",
    "topics": [
      "Solid, Liquid, and Gas States",
      "Diffusion Experiments",
      "Changes of State and Heating Curves",
    ],
    "description_en":
        "Understand particle theory, diffusion rates, and state changes using kinetic particle models.",
    "description_my":
        "အမှုန်သီအိုရီ၊ ပျံ့နှံ့နှုန်းများနှင့် ရွေ့လျားမှု မော်ဒယ်များကို အသုံးပြု၍ အခြေအနေပြောင်းလဲမှုများကို နားလည်စေမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Experimental Techniques",
    "title_en": "Measurement and Experimental Techniques",
    "title_my": "တိုင်းတာမှုနှင့် လက်တွေ့စမ်းသပ်မှု နည်းစနစ်များ",
    "topics": [
      "Criteria of Purity",
      "Methods of Separation and Purification (Filtration, Distillation, Chromatography)",
      "Choosing Purification Methods",
    ],
    "description_en":
        "Master techniques to separate and purify mixtures and test substance purity.",
    "description_my":
        "အရောအနှောများကို ခွဲထုတ်သန့်စင်ခြင်းနှင့် ပစ္စည်းများ၏ သန့်စင်မှုကို စမ်းသပ်သည့် နည်းလမ်းများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Atoms and Bonding",
    "title_en": "Atomic Structure and Isotopes",
    "title_my": "အက်တမ် ဖွဲ့စည်းပုံနှင့် အိုင်ဆိုတုပ်များ",
    "topics": [
      "Protons, Neutrons, and Electrons",
      "Electronic Configurations",
      "Isotopes and Relative Atomic Mass",
    ],
    "description_en":
        "Explore atomic structure, electronic arrangement, and calculate relative atomic mass from isotopes.",
    "description_my":
        "အက်တမ် ဖွဲ့စည်းပုံ၊ အီလက်ထရွန် စီစဉ်ပုံကို လေ့လာပြီး အိုင်ဆိုတုပ်များမှ ဆွေမျိုးအက်တမ်ထုထည်ကို တွက်ချက်မည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Chemical Bonding: Ionic and Covalent",
    "title_my": "ဓာတု အချိတ်အဆက်များ - အိုင်းယွန်းနစ်နှင့် ကိုဗလင့်",
    "topics": [
      "Ionic Bonding and Lattices",
      "Covalent Molecules and Structures",
      "Metallic Bonding",
    ],
    "description_en":
        "Analyze how atoms form ionic, covalent, and metallic bonds, linking bonding to physical properties.",
    "description_my":
        "အက်တမ်များသည် အိုင်းယွန်းနစ်၊ ကိုဗလင့်နှင့် သတ္တု အချိတ်အဆက်များကို မည်သို့ဖွဲ့စည်းကြောင်း ခွဲခြမ်းစိတ်ဖြာမည်။",
  },

  // ================= TERM 2: Stoichiometry & Chemical Calculations =================
  {
    "week": 5,
    "term": 2,
    "theme": "Stoichiometry",
    "title_en": "Formulae and Balanced Equations",
    "title_my": "ဖော်မြူလာများနှင့် ချိန်ညှိထားသော ဓာတုညီမျှခြင်းများ",
    "topics": [
      "Writing Chemical Formulae",
      "Ionic Equations",
      "Balancing Equations",
    ],
    "description_en":
        "Master writing and balancing chemical and ionic equations for various reactions.",
    "description_my":
        "ဓာတ်ပြုမှု အမျိုးမျိုးအတွက် ဓာတုညီမျှခြင်းများနှင့် အိုင်းယွန်း ညီမျှခြင်းများကို ချိန်ညှိရေးသားနည်း လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Stoichiometry",
    "title_en": "The Mole Concept and Calculations",
    "title_my": "မိုးလ် (Mole) သဘောတရားနှင့် တွက်ချက်မှုများ",
    "topics": [
      "The Mole and Avogadro's Constant",
      "Reacting Masses Calculations",
      "Percentage Yield and Purity",
    ],
    "description_en":
        "Perform quantitative calculations using the mole concept, reacting masses, and solution concentrations.",
    "description_my":
        "မိုးလ်သဘောတရား၊ ဓာတ်ပြုထုထည်နှင့် ပျော်ရည် အာဟာရပါဝင်မှုကို အသုံးပြု၍ အရေအတွက်ဆိုင်ရာ တွက်ချက်မှုများ လုပ်ဆောင်မည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Stoichiometry",
    "title_en": "Gas Volumes and Concentration Calculations",
    "title_my": "ဓာတ်ငွေ့ ထုထည်နှင့် ပျော်ရည် အာဟာရပါဝင်မှု တွက်ချက်ခြင်း",
    "topics": [
      "Molar Gas Volume (24 dm³)",
      "Concentration of Solutions (mol/dm³)",
      "Titration Calculations",
    ],
    "description_en":
        "Calculate gas volumes, solution concentrations, and execute titration calculation problems.",
    "description_my":
        "ဓာတ်ငွေ့ ထုထည်များ၊ ပျော်ရည် အာဟာရပါဝင်မှုများကို တွက်ချက်ပြီး တိုက်ထရိတ်ရှင်း (Titration) တွက်ချက်မှုများကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Stoichiometry Masterclass Studio",
    "title_my": "စတိုင်ကျီအိုမေတြီ အထူးသင်ခန်းစာ အလုပ်ရုံ",
    "topics": ["Complex Mole Problems", "Limiting Reactants", "Exam Practice"],
    "description_en":
        "Tackle advanced quantitative chemistry problems mirroring IGCSE Extended Paper assessment.",
    "description_my":
        "IGCSE Extended Paper စာမေးပွဲ စံနှုန်းများနှင့် ကိုက်ညီသော အဆင့်မြင့် ပမာဏပိုင်းဆိုင်ရာ ဓာတုဗေဒ ပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 3: Electricity and Chemistry & Energetics =================
  {
    "week": 9,
    "term": 3,
    "theme": "Electricity and Chemistry",
    "title_en": "Electrolysis Principles",
    "title_my": "လျှပ်စစ်ဖြင့် ဓာတ်ခွဲခြင်း အခြေခံများ (Electrolysis)",
    "topics": [
      "Principles of Electrolysis",
      "Anions and Cations",
      "Electrolysis of Molten Ionic Compounds",
    ],
    "description_en":
        "Understand electrolysis mechanisms, electrode processes, and molten compound decomposition.",
    "description_my":
        "လျှပ်စစ်ဖြင့် ဓာတ်ခွဲခြင်း လုပ်ငန်းစဉ်၊ လျှပ်ကူးတိုင် ဖြစ်စဉ်များနှင့် ပျော်ရည်ပျော်ဝင်ထားသော ဒြပ်ပေါင်းများ ကွဲထွက်မှုကို နားလည်စေမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Electricity and Chemistry",
    "title_en": "Electrolysis of Aqueous Solutions",
    "title_my": "ရေပျော်ရည်များကို လျှပ်စစ်ဖြင့် ဓာတ်ခွဲခြင်း",
    "topics": [
      "Preferential Discharge Rules",
      "Electrolysis of Concentrated vs Dilute NaCl",
      "Electroplating and Refining Copper",
    ],
    "description_en":
        "Predict products of aqueous electrolysis and examine industrial applications like electroplating.",
    "description_my":
        "ရေပျော်ရည် လျှပ်စစ်ဓာတ်ခွဲမှုမှ ထွက်လာမည့် ထွက်ကုန်များကို ခန့်မှန်းပြီး လျှပ်စစ်ပလပ်စတစ်တင်ခြင်း စသည့် စက်မှုလုပ်ငန်းများကို လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Chemical Energetics",
    "title_en": "Exothermic and Endothermic Reactions",
    "title_my": "အပူထုတ်လွှတ်သော နှင့် အပူစုပ်ယူသော ဓာတ်ပြုမှုများ",
    "topics": [
      "Enthalpy Change (Delta H)",
      "Energy Profile Diagrams",
      "Bond Energy Calculations",
    ],
    "description_en":
        "Analyze energy changes during chemical reactions using energy profile diagrams and bond energies.",
    "description_my":
        "စွမ်းအင် ပရိုဖိုင် ဂရပ်များနှင့်နှောင်ကြိုး စွမ်းအင်များကို အသုံးပြု၍ ဓာတ်ပြုမှုအတွင်း စွမ်းအင်ပြောင်းလဲမှုကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Energetics and Electrolysis Studio",
    "title_my": "စွမ်းအင်နှင့် လျှပ်စစ်ဓာတ်ခွဲခြင်း အလုပ်ရုံ",
    "topics": [
      "Bond Energy Problem Solving",
      "Electrochemical Cell Design",
      "Exam Practice",
    ],
    "description_en":
        "Solve complex bond energy calculations and analyze advanced electrochemical cells.",
    "description_my":
        "ရှုပ်ထွေးသော နှောင်ကြိုးစွမ်းအင် တွက်ချက်မှုများကို ဖြေရှင်းပြီး အဆင့်မြင့် လျှပ်စစ်ဓာတု ဆဲလ်များကို ခွဲခြမ်းမည်။",
  },

  // ================= TERM 4: Chemical Reactions, Rates and Equilibrium =================
  {
    "week": 13,
    "term": 4,
    "theme": "Reaction Rates",
    "title_en": "Rates of Reaction",
    "title_my": "ဓာတ်ပြုနှုန်းများ (Rates of Reaction)",
    "topics": [
      "Collision Theory",
      "Factors Affecting Reaction Rate (Temperature, Concentration, Surface Area, Catalysts)",
      "Measuring Reaction Rates",
    ],
    "description_en":
        "Explain reaction rates using collision theory and evaluate experimental methods to measure rates.",
    "description_my":
        "တိုက်ိုက်မိခြင်း သီအိုရီကို အသုံးပြု၍ ဓာတ်ပြုနှုန်းများကို ရှင်းပြပြီး နှုန်းတိုင်းတာသည့် စမ်းသပ်မှု နည်းလမ်းများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Reversible Reactions",
    "title_en": "Reversible Reactions and Equilibrium",
    "title_my":
        "ပြန်လှည့်နိုင်သော ဓာတ်ပြုမှုများနှင့် မျှခြေအခြေအနေ (Equilibrium)",
    "topics": [
      "Dynamic Equilibrium",
      "Le Chatelier's Principle",
      "Factors Affecting Equilibrium Position",
    ],
    "description_en":
        "Understand dynamic equilibrium and apply Le Chatelier's principle to industrial processes like Haber.",
    "description_my":
        "ပြောင်းလဲနေသော မျှခြေအခြေအနေကို နားလည်စေပြီး Haber ကဲ့သို့သော စက်မှုလုပ်ငန်းများတွင် Le Chatelier ၏ နိယာမကို အသုံးချမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Redox",
    "title_en": "Redox Reactions",
    "title_my": "ရီဒေါက်စ် ဓာတ်ပြုမှုများ (Redox)",
    "topics": [
      "Oxidation and Reduction in terms of Oxygen, Hydrogen, and Electrons",
      "Oxidation Numbers",
      "Identifying Oxidising and Reducing Agents",
    ],
    "description_en":
        "Master identifying oxidation and reduction using electron transfer and oxidation states.",
    "description_my":
        "အီလက်ထရွန် လွှဲပြောင်းမှုနှင့် ဓာတ်တိုးကိန်းများကို အသုံးပြု၍ ဓာတ်တိုးခြင်းနှင့် လျော့ပါးခြင်းကို ဖော်ထုတ်ရန် ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Reaction Kinetics Studio",
    "title_my": "ဓာတ်ပြုမှု ရွေ့လျားဗေဒ အလုပ်ရုံ",
    "topics": [
      "Equilibrium Shift Analysis",
      "Redox Balancing",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate complex equilibrium shifts and master balancing advanced redox equations.",
    "description_my":
        "ရှုပ်ထွေးသော မျှခြေ ရွှေ့ပြောင်းမှုများကို အကဲဖြတ်ပြီး အဆင့်မြင့် ရီဒေါက်စ် ညီမျှခြင်းများ ချိန်ညှိခြင်းကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },

  // ================= TERM 5: Acids, Bases, Salts and The Periodic Table =================
  {
    "week": 17,
    "term": 5,
    "theme": "Acids and Bases",
    "title_en": "Properties of Acids, Bases, and Salts",
    "title_my": "အက်ဆစ်၊ ဘေ့စ်နှင့် ဆားများ၏ ဂုဏ်သတ္တိများ",
    "topics": [
      "Characteristic Reactions of Acids",
      "Acidity, Alkalinity, and the pH Scale",
      "Types of Oxides",
    ],
    "description_en":
        "Explore acid reactions, pH scales, and classify acidic, basic, amphoteric, and neutral oxides.",
    "description_my":
        "အက်ဆစ် ဓာတ်ပြုမှုများ၊ pH စကေးများကို လေ့လာပြီး အက်ဆစ်၊ ဘေ့စ်၊ နှစ်ဖက်သုံး (Amphoteric) နှင့် ကြားနေ အောက်ဆိုဒ်များကို အမျိုးအစားခွဲမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Salts Preparation",
    "title_en": "Preparation of Salts",
    "title_my": "ဆားများ ပြင်ဆင်ခြင်း",
    "topics": [
      "Soluble and Insoluble Salts",
      "Preparation Methods (Titration, Excess Solid, Precipitation)",
      "Water of Crystallisation",
    ],
    "description_en":
        "Select and execute appropriate laboratory methods to prepare soluble and insoluble salts.",
    "description_my":
        "ပျော်ဝင်နိုင်သောနှင့် မပျော်ဝင်သော ဆားများကို ပြင်ဆင်ရန် သင့်လျော်သော ဓာတ်ခွဲခန်း နည်းလမ်းများကို ရွေးချယ်လုပ်ဆောင်မည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Periodic Table",
    "title_en": "The Periodic Table Trends",
    "title_my": "ဒြပ်စင်အလှည့်ကျဇယား လက္ခဏာများ (Periodic Table)",
    "topics": [
      "Group I Alkali Metals",
      "Group VII Halogens",
      "Group VIII Noble Gases and Transition Elements",
    ],
    "description_en":
        "Examine trends in physical and chemical properties across groups and periods in the Periodic Table.",
    "description_my":
        "အလှည့်ကျဇယားရှိ အုပ်စုများနှင့် အတန်းများတစ်လျှောက် ရုပ်ပိုင်းနှင့် ဓာတုဂုဏ်သတ္တိ ပြောင်းလဲမှုများကို လေ့လာမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Inorganic Chemistry Studio",
    "title_my": "အဂ္ဂနီဗေဒ ဓာတုဗေဒ အလုပ်ရုံ",
    "topics": [
      "Salt Preparation Schemes",
      "Periodic Trends Predictions",
      "Exam Practice",
    ],
    "description_en":
        "Design multi-step salt preparation routes and predict unknown periodic element behaviors.",
    "description_my":
        "အဆင့်ဆင့် ဆားပြင်ဆင်ရေး လမ်းကြောင်းများကို ဒီဇိုင်းဆွဲပြီး အမည်မသိ ဒြပ်စင်များ၏ အမူအကျင့်များကို ခန့်မှန်းမည်။",
  },

  // ================= TERM 6: Metals and Chemistry of the Environment =================
  {
    "week": 21,
    "term": 6,
    "theme": "Metals",
    "title_en": "Properties and Reactivity of Metals",
    "title_my": "သတ္တုများ၏ ဂုဏ်သတ္တိနှင့် ဓာတ်ပြုနိုင်စွမ်း",
    "topics": [
      "The Metal Reactivity Series",
      "Displacement Reactions",
      "Corrosion Prevention (Galvanising, Sacrificial Protection)",
    ],
    "description_en":
        "Study the metal reactivity series, displacement reactions, and methods to prevent iron rusting.",
    "description_my":
        "သတ္တု ဓာတ်ပြုနိုင်စွမ်း အစဉ်၊ နေရာလွှဲပြောင်း ဓာတ်ပြုမှုများနှင့် သံမောင်းတက်ခြင်းမှ ကာကွယ်သည့် နည်းလမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Metals",
    "title_en": "Extraction of Metals",
    "title_my": "သတ္တုများ ထုတ်ယူခြင်း",
    "topics": [
      "Extraction of Iron from Haematite in the Blast Furnace",
      "Extraction of Aluminium by Electrolysis",
      "Uses of Alloys",
    ],
    "description_en":
        "Examine industrial metal extraction processes in blast furnaces and electrolytic cells.",
    "description_my":
        "Blast furnace နှင့် electrolytic cell များတွင် စက်မှုသတ္တု ထုတ်ယူသည့် လုပ်ငန်းစဉ်များကို လေ့လာမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Environment",
    "title_en": "Air, Water, and Environmental Chemistry",
    "title_my": "လေထု၊ ရေထုနှင့် ပတ်ဝန်းကျင် ဓာတုဗေဒ",
    "topics": [
      "Composition of Clean Air",
      "Air Pollution and Catalytic Converters",
      "Water Treatment and Purification",
    ],
    "description_en":
        "Analyze air pollutants, catalytic converter functions, greenhouse gases, and water purification steps.",
    "description_my":
        "လေထုညစ်ညမ်းစေသော ပစ္စည်းများ၊ ဓာတ်ကူပစ္စည်း မောင်းနှင်မှုများ၊ ဖန်လုံအိမ်ဓာတ်ငွေ့များနှင့် ရေစင်စစ်ထုတ်လုပ်မှုကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Metals & Environmental Studio",
    "title_my": "သတ္တုနှင့် ပတ်ဝန်းကျင် အလုပ်ရုံ",
    "topics": [
      "Extraction Chemistry Analysis",
      "Pollution Control Evaluations",
      "Exam Practice",
    ],
    "description_en":
        "Solve complex metal extraction stoichiometry and environmental chemistry problems.",
    "description_my":
        "ရှုပ်ထွေးသော သတ္တုထုတ်ယူမှု စတိုင်ကျီအိုမေတြီနှင့် ပတ်ဝန်းကျင် ဓာတုဗေဒ ပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 7: Organic Chemistry =================
  {
    "week": 25,
    "term": 7,
    "theme": "Organic Chemistry",
    "title_en": "Introduction to Organic Chemistry",
    "title_my": "အော်ဂဲနစ် ဓာတုဗေဒ မိတ်ဆက်",
    "topics": [
      "Homologous Series and Functional Groups",
      "Naming Organic Compounds (IUPAC)",
      "Structural and Displayed Formulae",
    ],
    "description_en":
        "Master naming and drawing organic compounds across different homologous series.",
    "description_my":
        "ဆင်တူ အစဉ်လိုက် အုပ်စုများ (Homologous series) အလိုက် အော်ဂဲနစ် ဒြပ်ပေါင်းများ အမည်ပေးခြင်းနှင့် ပုံဆွဲခြင်းကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Organic Chemistry",
    "title_en": "Alkanes, Alkenes, and Petroleum",
    "title_my": "အယ်လ်ကိန်းများ၊ အယ်လ်ကင်းများ နှင့် ရေနံစိမ်း",
    "topics": [
      "Fractional Distillation of Crude Oil",
      "Cracking of Hydrocarbons",
      "Reactions of Alkanes and Alkenes (Bromine Water Test)",
    ],
    "description_en":
        "Explore petroleum fractionation, catalytic cracking, and chemical tests to distinguish alkanes from alkenes.",
    "description_my":
        "ရေနံပေါင်းခံခြင်း၊ ကတ်တလစ်ဖြင့် ကွဲထွက်စေခြင်းနှင့် အယ်လ်ကိန်း/အယ်လ်ကင်း ခွဲခြားသည့် စမ်းသပ်မှုများကို စူးစမ်းမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Organic Chemistry",
    "title_en": "Alcohols and Carboxylic Acids",
    "title_my": "အယ်ကိုဟောများနှင့် ကာဘောက်ဆစ်လစ် အက်ဆစ်များ",
    "topics": [
      "Properties and Production of Ethanol (Fermentation and Hydration)",
      "Reactions of Carboxylic Acids",
      "Esterification",
    ],
    "description_en":
        "Study alcohol production, carboxylic acid reactions, and ester formation.",
    "description_my":
        "အယ်ကိုဟော ထုတ်လုပ်မှု၊ ကာဘောက်ဆစ်လစ် အက်ဆစ် ဓာတ်ပြုမှုများနှင့် အက်စတာ ဖြစ်ပေါ်မှုကို လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Polymers",
    "title_en": "Polymers and Macromolecules",
    "title_my": "ပိုလီမာများနှင့် မက်ခရိုမော်လီကျူးများ",
    "topics": [
      "Addition Polymerisation",
      "Condensation Polymerisation (Nylon and Terylene)",
      "Plastics Pollution and Disposal",
    ],
    "description_en":
        "Distinguish between addition and condensation polymerisation and understand polymer structures.",
    "description_my":
        "Addition နှင့် Condensation ပိုလီမာဖြစ်ပေါ်ခြင်း ကွာခြားချက်များကို နားလည်စေပြီး ပိုလီမာ ဖွဲ့စည်းပုံများကို လေ့လာမည်။",
  },

  // ================= TERM 8: Experimental Skills & Qualitative Analysis =================
  {
    "week": 29,
    "term": 8,
    "theme": "Experimental Skills",
    "title_en": "Designing Chemistry Experiments",
    "title_my": "ဓာတုဗေဒ စမ်းသပ်မှုများ ဒီဇိုင်းဆွဲခြင်း",
    "topics": [
      "Controlling Variables in Rate and Neutralisation Experiments",
      "Apparatus Selection",
      "Minimising Experimental Errors",
    ],
    "description_en":
        "Design rigorous laboratory experiments for measuring rates, titration, and enthalpy changes.",
    "description_my":
        "နှုန်းတိုင်းတာခြင်း၊ တိုက်ထရိတ်ရှင်းနှင့် အပူစွမ်းအင် ပြောင်းလဲမှုများအတွက် တိကျသော ဓာတုဗေဒ စမ်းသပ်မှုများ ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Qualitative Analysis",
    "title_en": "Identification of Ions and Gases",
    "title_my": "အိုင်းယွန်းများနှင့် ဓာတ်ငွေ့များကို ဖော်ထုတ်ခြင်း",
    "topics": [
      "Cation Tests (NaOH and Ammonia tests)",
      "Anion Tests (Halides, Sulfates, Carbonates)",
      "Gas Tests (Hydrogen, Oxygen, Carbon Dioxide, Chlorine, Ammonia)",
    ],
    "description_en":
        "Master chemical tests for identifying aqueous cations, anions, and common laboratory gases.",
    "description_my":
        "အိုင်းယွန်းများနှင့် ဓာတ်ခွဲခန်းသုံး ဓာတ်ငွေ့များကို ဖော်ထုတ်သည့် ဓာတုစမ်းသပ်မှုများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Experimental Skills",
    "title_en": "Titration Techniques and Calculations",
    "title_my": "တိုက်ထရိတ်ရှင်း နည်းစနစ်များနှင့် တွက်ချက်မှုများ",
    "topics": [
      "Indicator Selection",
      "Titration Procedure",
      "Volumetric Analysis Calculations",
    ],
    "description_en":
        "Execute precise volumetric analysis and titration calculation tasks for Paper 6/Paper 4.",
    "description_my":
        "Paper 6/4 အတွက် တိကျသော ပမာဏပိုင်းဆိုင်ရာ ခွဲခြမ်းစိတ်ဖြာမှုနှင့် တိုက်ထရိတ်ရှင်း တွက်ချက်မှုများကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Practical Paper Simulation Studio",
    "title_my": "လက်တွေ့ စာမေးပွဲ ပုံစံတူ အလုပ်ရုံ",
    "topics": [
      "Paper 6 Simulation",
      "Data Table Formatting",
      "Qualitative Analysis Deductions",
    ],
    "description_en":
        "Complete full practical paper simulations under strict examination conditions.",
    "description_my":
        "တင်းကျပ်သော စာမေးပွဲ အခြေအနေများအောက်တွင် လက်တွေ့စာစောင် ပုံစံတူ အစအဆုံး ဖြေဆိုမည်။",
  },

  // ================= TERM 9: Exam Prep & Final Countdown =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Multiple Choice) Intensive",
    "title_my": "Paper 1 (ရွေးချယ်ရန် မေးခွန်းများ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "MCQ Strategy",
      "Rapid Calculation Drills",
      "Core Concept Recall",
    ],
    "description_en":
        "Master multiple-choice question strategies and rapid chemical calculations for Paper 1.",
    "description_my":
        "Paper 1 အတွက် ရွေးချယ်ရန် မေးခွန်း မူဝါဒများနှင့် အမြန် ဓာတုဗေဒ တွက်ချက်မှုများကို လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 3/4 (Theory Calculations) Mastery",
    "title_my": "Paper 3/4 (သီအိုရီ တွက်ချက်မှုများ) ကျွမ်းကျင်မှု",
    "topics": [
      "Structuring Extended Stoichiometry",
      "Explaining Organic Mechanisms",
      "Time Management",
    ],
    "description_en":
        "Intensive practice on structured theory and stoichiometry calculation questions for Paper 4 Extended.",
    "description_my":
        "Paper 4 Extended အတွက် ပုံစံကျ သီအိုရီနှင့် စတိုင်ကျီအိုမေတြီ တွက်ချက်မှု မေးခွန်းများကို အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Past Paper Mock Examinations",
    "title_my": "မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 4",
      "Timed Mock Paper 6",
    ],
    "description_en":
        "Complete full-length past paper mock examinations across all papers under rigorous timed conditions.",
    "description_my":
        "တင်းကျပ်သော အချိန်သတ်မှတ်ချက်များအောက်တွင် စာစောင်အားလုံးအတွက် မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Chemistry Graduation",
    "title_my": "IGCSE ဓာတုဗေဒ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Chemical Sciences",
      "Pathways to A-Level Chemistry",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Chemistry and preparation for advanced chemical sciences.",
    "description_my":
        "IGCSE ဓာတုဗေဒ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး အဆင့်မြင့် ဓာတုဗေဒ ပညာရေးဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
