// File: ai_data_bridge/igcse_geography_all_terms.dart
// IGCSE Geography Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseGeographyAllTermsData = [
  // ================= TERM 1: Population and Settlement =================
  {
    "week": 1,
    "term": 1,
    "theme": "Population",
    "title_en": "Population Dynamics",
    "title_my": "လူဦးရေ ပြောင်းလဲနှုန်းများ",
    "topics": [
      "Birth and Death Rates",
      "Natural Increase",
      "The Demographic Transition Model",
    ],
    "description_en":
        "Examine population growth rates, birth/death dynamics, and the demographic transition model across nations.",
    "description_my":
        "နိုင်ငံအသီးသီး၏ လူဦးရေ တိုးတက်နှုန်းများ၊ မွေးဖွားမှု/သေဆုံးမှု ဒိုင်းနမစ်နှင့် လူဦးရေ ကူးပြောင်းမှု မော်ဒယ်ကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Population",
    "title_en": "Migration and Population Structure",
    "title_my": "ရွှေ့ပြောင်းနေထိုင်မှုနှင့် လူဦးရေ တည်ဆောက်ပုံ",
    "topics": [
      "Push and Pull Factors",
      "Internal and International Migration",
      "Population Pyramids",
    ],
    "description_en":
        "Analyze migration drivers and interpret population pyramids to understand age and gender distributions.",
    "description_my":
        "ရွှေ့ပြောင်းရခြင်း၏ တွန်းအားနှင့် ဆွဲအားများကို ခွဲခြမ်းစိတ်ဖြာပြီး အသက်နှင့် ကျား/မ ဖြန့်ဝေမှုကို နားလည်ရန် လူဦးရေ ပိရမစ်များကို ဖတ်ရှုမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Settlement",
    "title_en": "Settlement Hierarchies and Urbanisation",
    "title_my":
        "အခြေချနေထိုင်မှု အဆင့်ဆင့်နှင့် မြို့ပြထွန်းကားလာခြင်း (Urbanisation)",
    "topics": [
      "Services and Threshold Populations",
      "Urbanisation Rates",
      "Sphere of Influence",
    ],
    "description_en":
        "Explore settlement hierarchies, services threshold populations, and rapid global urbanisation trends.",
    "description_my":
        "အခြေချနေထိုင်မှု အဆင့်ဆင့်၊ ဝန်ဆောင်မှု လိုအပ်ချက် လူဦးရေနှင့် ကမ္ဘာ့မြို့ပြထွန်းကားမှု အရှိန်အဟုန်ကို စူးစမ်းမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Urban Environments and Land Use",
    "title_my": "မြို့ပြ ပတ်ဝန်းကျင်နှင့် မြေအသုံးချမှု",
    "topics": [
      "CBD, Inner City, and Suburbs",
      "Urban Traffic Problems",
      "Housing Shortages in Developing Nations",
    ],
    "description_en":
        "Investigate internal urban structures, land use models, and challenges faced by growing cities.",
    "description_my":
        "မြို့ပြအတွင်းပိုင်း ဖွဲ့စည်းပုံ၊ မြေအသုံးချမှု မော်ဒယ်များနှင့် ကြီးထွားလာသော မြို့ကြီးများ ရင်ဆိုင်နေရသော စိန်ခေါ်မှုများကို လေ့လာမည်။",
  },

  // ================= TERM 2: The Natural Environment - Earthquakes, Volcanoes and Rivers =================
  {
    "week": 5,
    "term": 2,
    "theme": "Tectonic Hazards",
    "title_en": "Plate Tectonics, Earthquakes and Volcanoes",
    "title_my": "မြေလွှာချပ်များ ရွေ့လျားမှု၊ ငလျင်နှင့် မီးတောင်များ",
    "topics": [
      "Plate Boundaries (Destructive, Constructive, Conservative)",
      "Volcano Structure",
      "Earthquake Preparedness",
    ],
    "description_en":
        "Understand tectonic plate movements, volcanic eruptions, earthquake hazards, and mitigation strategies.",
    "description_my":
        "မြေလွှာချပ်များ ရွေ့လျားမှု၊ မီးတောင်ပေါက်ကွဲမှု၊ ငလျင်အန္တရာယ်နှင့် ကာကွယ်ရေး မဟာဗျူဟာများကို နားလည်စေမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Rivers",
    "title_en": "River Processes and Landforms",
    "title_my": "မြစ်ကြောင်းဆိုင်ရာ ဖြစ်စဉ်များနှင့် မြေမျက်နှာသွင်ပြင်များ",
    "topics": [
      "Erosion, Transportation, and Deposition",
      "Waterfalls and Meanders",
      "Flood Management",
    ],
    "description_en":
        "Examine fluvial processes operating along a river's course and the formation of distinctive landforms.",
    "description_my":
        "မြစ်ကြောင်းတစ်လျှောက် လုပ်ဆောင်သည့် တိုက်စားခြင်း၊ သယ်ဆောင်ခြင်း၊ အနည်ချခြင်းနှင့် မြေမျက်နှာသွင်ပြင် ဖြစ်ပေါ်ပုံကို လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Coasts",
    "title_en": "Coasts and Marine Processes",
    "title_my": "ပင်လယ်ကမ်းစပ်နှင့် ရေလှိုင်းဆိုင်ရာ ဖြစ်စဉ်များ",
    "topics": [
      "Waves and Longshore Drift",
      "Clifflines and Spits",
      "Coastal Management Strategies",
    ],
    "description_en":
        "Analyze coastal erosion, longshore drift, depositional landforms, and hard/soft engineering defenses.",
    "description_my":
        "ကမ်းစပ် တိုက်စားခြင်း၊ ကမ်းရိုးတန်းတစ်လျှောက် သယ်ဆောင်ခြင်း (Longshore drift) နှင့် ကမ်းထိန်းသိမ်းရေး အင်ဂျင်နီယာ နည်းလမ်းများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Natural Environments Hazard Studio",
    "title_my": "သဘာဝ ပတ်ဝန်းကျင် အန္တရာယ်များ အလုပ်ရုံ",
    "topics": [
      "Hazard Risk Assessment",
      "Case Studies of Natural Disasters",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate tectonic, river, and coastal hazards through real-world case studies and impact analysis.",
    "description_my":
        "လက်တွေ့ကမ္ဘာ ဖြစ်ရပ်မှန်များနှင့် သက်ရောက်မှု ခွဲခြမ်းစိတ်ဖြာမှုမှတစ်ဆင့် မြေငလျင်၊ မြစ်နှင့် ကမ်းရိုးတန်း အန္တရာယ်များကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 3: Weather, Climate and Ecosystems =================
  {
    "week": 9,
    "term": 3,
    "theme": "Weather",
    "title_en": "Weather Instruments and Measurements",
    "title_my": "ရာသီဥတု တိုင်းတာသည့် ကိရိယာများနှင့် တိုင်းတာမှုများ",
    "topics": [
      "Stevenson Screen",
      "Rain Gauges and Barometers",
      "Interpreting Weather Stations",
    ],
    "description_en":
        "Learn how meteorological data is collected using standard instruments and interpreted from weather charts.",
    "description_my":
        "စံကိရိယာများကို သုံး၍ မိုးလေဝသ ဒေတာ မည်သို့ကောက်ယူကြောင်းနှင့် ရာသီဥတု ဇယားများမှ အဓိပ္ပာယ်ဖော်နည်းကို လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Climate",
    "title_en": "Climate Characteristics and Graphs",
    "title_my": "ရာသီဥတု လက္ခဏာများနှင့် ရာသီဥတု ဂရပ်များ",
    "topics": [
      "Hot Deserts Climate",
      "Equatorial Rainforest Climate",
      "Reading Climate Graphs",
    ],
    "description_en":
        "Analyze temperature and precipitation patterns in extreme climate zones using climate graphs.",
    "description_my":
        "ရာသီဥတု ဂရပ်များကို အသုံးပြု၍ အလွန်အမင်း ပြင်းထန်သော ရာသီဥတုဇုန်များရှိ အပူချိန်နှင့် မိုးရေချိန် ပုံစံများကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Ecosystems",
    "title_en": "Tropical Rainforests and Hot Deserts",
    "title_my": "အီကွေတာ မိုးသစ်တောများနှင့် ပူပြင်းခြောက်သွေ့သော သဲကန္တာရများ",
    "topics": [
      "Rainforest Nutrient Cycling",
      "Adaptations of Desert Plants and Animals",
      "Causes and Impacts of Deforestation",
    ],
    "description_en":
        "Explore the interdependent components of ecosystems and the severe threats of deforestation and desertification.",
    "description_my":
        "ဂေဟစနစ်များ၏ အပြန်အလှန် မှီခိုမှုကို စူးစမ်းပြီး သစ်တောပြုန်းတီးမှုနှင့် သဲကန္တာရဖြစ်ထွန်းလာမှု ခြိမ်းခြောက်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Ecosystems and Climate Studio",
    "title_my": "ဂေဟစနစ်နှင့် ရာသီဥတု အလုပ်ရုံ",
    "topics": [
      "Rainforest Conservation",
      "Desertification Solutions",
      "Exam Problem Solving",
    ],
    "description_en":
        "Evaluate sustainable management strategies for tropical rainforests and fragile desert ecosystems.",
    "description_my":
        "အီကွေတာ မိုးသစ်တောများနှင့် ပျက်စီးလွယ်သော သဲကန္တာရ ဂေဟစနစ်များအတွက် ရေရှည်တည်တံ့သော စီမံခန့်ခွဲမှု မဟာဗျူဟာများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 4: Economic Development =================
  {
    "week": 13,
    "term": 4,
    "theme": "Development",
    "title_en": "Measuring Economic Development",
    "title_my": "စီးပွားရေး ဖွံ့ဖြိုးတိုးတက်မှုကို တိုင်းတာခြင်း",
    "topics": [
      "Development Indicators (GNI per capita, Literacy, Life Expectancy)",
      "Human Development Index (HDI)",
      "The Development Gap",
    ],
    "description_en":
        "Examine social and economic indicators used to classify countries and measure the global development gap.",
    "description_my":
        "နိုင်ငံများကို အမျိုးအစားခွဲခြားရန်နှင့် ကမ္ဘာ့ဖွံ့ဖြိုးတိုးတက်မှု ကွာဟချက်ကို တိုင်းတာရန် လူမှုရေးနှင့် စီးပွားရေး ညွှန်းကိန်းများကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Food Production",
    "title_en": "Agricultural Systems and Food Production",
    "title_my": "စိုက်ပျိုးရေး စနစ်များနှင့် စားနပ်ရိက္ခာ ထုတ်လုပ်မှု",
    "topics": [
      "Arable, Pastoral, and Mixed Farming",
      "Commercial vs Subsistence Farming",
      "Causes of Food Shortages",
    ],
    "description_en":
        "Analyze agricultural systems as inputs, processes, and outputs, and investigate global food supply issues.",
    "description_my":
        "သွင်းအားစု၊ လုပ်ငန်းစဉ်နှင့် ထွက်ကုန်များအဖြစ် စိုက်ပျိုးရေးစနစ်များကို ခွဲခြမ်းစိတ်ဖြာပြီး ကမ္ဘာ့စားနပ်ရိက္ခာ ထောက်ပံ့ရေး ပြဿနာများကို စူးစမ်းမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Industry",
    "title_en": "Industrial Systems and Manufacturing",
    "title_my": "စက်မှုလက်မှု စနစ်များနှင့် ကုန်ထုတ်လုပ်ငန်း",
    "topics": [
      "Factors Influencing Industrial Location",
      "High-Tech Industries",
      "Informal Employment",
    ],
    "description_en":
        "Evaluate location factors for manufacturing industries and the growth of high-tech and informal sectors.",
    "description_my":
        "ကုန်ထုတ်လုပ်ငန်းများအတွက် တည်နေရာ သက်ရောက်သည့် အကြောင်းရင်းများနှင့် အဆင့်မြင့်နည်းပညာ ကဏ္ဍများ တိုးတက်မှုကို အကဲဖြတ်မည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Economic Development Case Studies Studio",
    "title_my": "စီးပွားရေး ဖွံ့ဖြိုးတိုးတက်မှု လက်တွေ့လေ့လာမှု အလုပ်ရုံ",
    "topics": [
      "Case Studies of Newly Industrialised Countries (NICs)",
      "Agricultural Innovations",
      "Exam Practice",
    ],
    "description_en":
        "Investigate how developing nations successfully industrialise and improve agricultural yields.",
    "description_my":
        "ဖွံ့ဖြိုးဆဲနိုင်ငံများက စက်မှုထွန်းကားလာအောင်နှင့် စိုက်ပျိုးရေး အထွက်နှုန်း တိုးတက်အောင် မည်သို့လုပ်ဆောင်ကြောင်း လေ့လာမည်။",
  },

  // ================= TERM 5: Resource Management and Energy =================
  {
    "week": 17,
    "term": 5,
    "theme": "Water Resources",
    "title_en": "Water Supply and Management",
    "title_my": "ရေပေးဝေမှုနှင့် စီမံခန့်ခွဲမှု",
    "topics": [
      "Sources of Fresh Water",
      "Water Scarcity Causes",
      "Dams, Reservoirs, and Desalination",
    ],
    "description_en":
        "Examine global water usage, the causes of water scarcity, and large-scale engineering solutions.",
    "description_my":
        "ကမ္ဘာ့ရေသုံးစွဲမှု၊ ရေရှားပါးရသည့် အကြောင်းရင်းများနှင့် ကြီးမားသော အင်ဂျင်နီယာ ဖြေရှင်းချက်များကို လေ့လာမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Energy",
    "title_en": "Energy Resources and Power Generation",
    "title_my": "စွမ်းအင် အရင်းအမြစ်များနှင့် လျှပ်စစ်ထုတ်လုပ်ခြင်း",
    "topics": [
      "Fossil Fuels vs Renewable Energy (Solar, Wind, Hydroelectric)",
      "Energy Security",
      "Environmental Impacts of Energy",
    ],
    "description_en":
        "Compare energy sources, assess global energy security, and evaluate environmental consequences.",
    "description_my":
        "စွမ်းအင် အရင်းအမြစ်များကို နှိုင်းယှဉ်ခြင်း၊ ကမ္ဘာ့စွမ်းအင် လုံခြုံမှုကို အကဲဖြတ်ခြင်းနှင့် ပတ်ဝန်းကျင် သက်ရောက်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Environmental Risks",
    "title_en": "Environmental Risks of Economic Development",
    "title_my":
        "စီးပွားရေး ဖွံ့ဖြိုးတိုးတက်မှုကြောင့် ဖြစ်ပေါ်လာသည့် ပတ်ဝန်းကျင်ဆိုင်ရာ အန္တရာယ်များ",
    "topics": [
      "Land Pollution",
      "Water Pollution",
      "Air Pollution and Acid Rain",
    ],
    "description_en":
        "Analyze pollution types generated by human and industrial activities and their impacts on ecosystems.",
    "description_my":
        "လူသားနှင့် စက်မှုလုပ်ငန်း လုပ်ဆောင်ချက်များကြောင့် ဖြစ်ပေါ်လာသော ညစ်ညမ်းမှု အမျိုးအစားများနှင့် ဂေဟစနစ်အပေါ် သက်ရောက်မှုကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Sustainable Resource Management Studio",
    "title_my": "ရေရှည်တည်တံ့သော အရင်းအမြစ် စီမံခန့်ခွဲမှု အလုပ်ရုံ",
    "topics": [
      "Renewable Energy Transitions",
      "Water Conservation Strategies",
      "Exam Practice",
    ],
    "description_en":
        "Design sustainable resource management policies for nations transitioning to green economies.",
    "description_my":
        "စိမ်းလန်းသော စီးပွားရေးစနစ်သို့ ကူးပြောင်းနေသော နိုင်ငံများအတွက် ရေရှည်တည်တံ့သော အရင်းအမြစ် စီမံခန့်ခွဲမှု မူဝါဒများကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 6: Tourism and Interdependence =================
  {
    "week": 21,
    "term": 6,
    "theme": "Tourism",
    "title_en": "The Tourism Industry",
    "title_my": "ခရီးသွားလာရေး လုပ်ငန်း (Tourism)",
    "topics": [
      "Growth of International Tourism",
      "Benefits and Drawbacks of Tourism",
      "Ecotourism and Sustainable Tourism",
    ],
    "description_en":
        "Examine why international tourism has grown, its socio-economic impacts, and sustainable tourism models.",
    "description_my":
        "နိုင်ငံတကာ ခရီးသွားလုပ်ငန်း ကြီးထွားလာရခြင်း၊ လူမှုစီးပွား သက်ရောက်မှုများနှင့် ရေရှည်တည်တံ့သော ခရီးသွားလုပ်ငန်း မော်ဒယ်များကို လေ့လာမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Interdependence",
    "title_en": "Global Interdependence and Trade",
    "title_my": "ကမ္ဘာလုံးဆိုင်ရာ အပြန်အလှန် မှီခိုမှုနှင့် ကုန်သွယ်ရေး",
    "topics": [
      "Globalisation Drivers",
      "Transnational Corporations (TNCs)",
      "Trade Flows and Tariffs",
    ],
    "description_en":
        "Analyze how countries depend on each other through trade, investments, and global supply chains.",
    "description_my":
        "နိုင်ငံများသည် ကုန်သွယ်ရေး၊ ရင်းနှီးမြှုပ်နှံမှုနှင့် ကမ္ဘာ့ထောက်ပံ့ရေး ကွင်းဆက်များမှတစ်ဆင့် တစ်နိုင်ငံနှင့်တစ်နိုင်ငံ မည်သို့မှီခိုကြောင်း ခွဲခြမ်းမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Interdependence",
    "title_en": "Aid and Debt Relief",
    "title_my": "အကူအညီနှင့် ကြွေးမြီ ကင်းလွတ်ခွင့်",
    "topics": [
      "Types of Aid (Bilateral, Multilateral, Emergency)",
      "Impact of Foreign Aid",
      "The Problem of National Debt",
    ],
    "description_en":
        "Evaluate the effectiveness of foreign aid and debt relief programs in supporting developing nations.",
    "description_my":
        "ဖွံ့ဖြိုးဆဲနိုင်ငံများကို ကူညီရာတွင် ပြည်ပအကူအညီနှင့် ကြွေးမြီ ကင်းလွတ်ခွင့် အစီအစဉ်များ၏ ထိရောက်မှုကို အကဲဖြတ်မည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Globalisation and Tourism Case Studies Studio",
    "title_my":
        "ကမ္ဘာ့ရွာကြီးစနစ်နှင့် ခရီးသွားလုပ်ငန်း လက်တွေ့လေ့လာမှု အလုပ်ရုံ",
    "topics": [
      "Overtourism Management",
      "Global Trade Agreements",
      "Exam Practice",
    ],
    "description_en":
        "Investigate case studies involving sustainable tourism management and global trade impacts.",
    "description_my":
        "ရေရှည်တည်တံ့သော ခရီးသွား စီမံခန့်ခွဲမှုနှင့် ကမ္ဘာ့ကုန်သွယ်ရေး သက်ရောက်မှုများပါဝင်သည့် လက်တွေ့လေ့လာမှုများကို လုပ်ဆောင်မည်။",
  },

  // ================= TERM 7: Geographical Skills, Map Work and Fieldwork =================
  {
    "week": 25,
    "term": 7,
    "theme": "Map Skills",
    "title_en": "Topographical Map Skills and Interpretation",
    "title_my":
        "မြေမျက်နှာသွင်ပြင် မြေပုံ ကျွမ်းကျင်မှုနှင့် အဓိပ္ပာယ်ဖော်ခြင်း",
    "topics": [
      "Grid References",
      "Scale and Distance Calculations",
      "Contour Lines and Relief Representation",
    ],
    "description_en":
        "Master topographical map reading, 4-figure and 6-figure grid references, and contour interpretation.",
    "description_my":
        "မြေပုံဖတ်ရှုခြင်း၊ ၄-ဂဏန်း/၆-ဂဏန်း ဂရစ် ရည်ညွှန်းချက်များနှင့် ကုန်းစောက်မျဉ်း (Contour) အဓိပ္ပာယ်ဖော်ခြင်းကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Map Skills",
    "title_en": "Cross-Sections and Settlement Patterns on Maps",
    "title_my":
        "မြေပုံများပေါ်ရှိ ဘက်စုံဖြတ်ပိုင်းများ (Cross-sections) နှင့် အခြေချမှု ပုံစံများ",
    "topics": [
      "Drawing Cross-Sections",
      "Identifying Settlement Patterns (Linear, Nucleated, Dispersed)",
      "Land Use Mapping",
    ],
    "description_en":
        "Construct cross-sections from topographical maps and identify geographic settlement patterns.",
    "description_my":
        "မြေမျက်နှာသွင်ပြင် မြေပုံများမှ ဘက်စုံဖြတ်ပိုင်းများ ဆွဲခြင်းနှင့် အခြေချနေထိုင်မှု ပုံစံများကို ဖော်ထုတ်ခြင်း ပြုလုပ်မည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Fieldwork Skills",
    "title_en": "Geographical Fieldwork Methodology",
    "title_my": "ပထဝီဝင် ကွင်းဆင်းလေ့လာရေး နည်းစနစ်များ",
    "topics": [
      "Formulating Hypotheses",
      "Data Collection Techniques (Sampling, Questionnaires)",
      "Data Presentation (Graphs, Scatter Plots, Choropleth Maps)",
    ],
    "description_en":
        "Learn the complete fieldwork inquiry process from hypothesis formulation to data presentation.",
    "description_my":
        "ယူဆချက် ထုတ်ခြင်းမှသည် ဒေတာတင်ပြခြင်းအထိ ကွင်းဆင်းလေ့လာရေး စုံစမ်းစစ်ဆေးမှု လုပ်ငန်းစဉ်အပြည့်အစုံကို လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Fieldwork Analysis and Evaluation Studio",
    "title_my":
        "ကွင်းဆင်းလေ့လာရေး ခွဲခြမ်းစိတ်ဖြာမှုနှင့် အကဲဖြတ်ခြင်း အလုပ်ရုံ",
    "topics": [
      "Analyzing Field Data",
      "Evaluating Methodology Limitations",
      "Drawing Conclusions",
    ],
    "description_en":
        "Analyze sample fieldwork datasets, evaluate method anomalies, and write sound geographical conclusions.",
    "description_my":
        "ကွင်းဆင်း ဒေတာနမူနာများကို ခွဲခြမ်းစိတ်ဖြာခြင်း၊ နည်းစနစ်ပိုင်းဆိုင်ရာ ကန့်သတ်ချက်များကို အကဲဖြတ်ခြင်းနှင့် တိကျသော ကောက်ချက်များ ရေးသားမည်။",
  },

  // ================= TERM 8: Advanced Exam Preparation - Paper 1, Paper 2 & Paper 4 =================
  {
    "week": 29,
    "term": 8,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Geographical Themes) Intensive",
    "title_my":
        "Paper 1 (ပထဝီဝင် အဓိက အကြောင်းအရာများ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Structured Answer Techniques",
      "Case Study Recall",
      "Thematic Integration",
    ],
    "description_en":
        "Master structured answer techniques and case study recall for IGCSE Paper 1 geographical themes.",
    "description_my":
        "IGCSE Paper 1 ပထဝီဝင် အဓိက ခေါင်းစဉ်များအတွက် ပုံစံကျ အဖြေရေးနည်းများနှင့် လက်တွေ့ဖြစ်ရပ်များ ပြန်လည်ဖော်ထုတ်မှုကို လေ့ကျင့်မည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Exam Prep",
    "title_en": "Paper 2 (Map Skills) Intensive",
    "title_my": "Paper 2 (မြေပုံ ကျွမ်းကျင်မှု) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Speed Map Reading Drills",
      "Scale and Bearing Calculations",
      "Photograph Interpretation",
    ],
    "description_en":
        "Intensive drilling of map reading speed, bearing calculations, and landscape photograph analysis.",
    "description_my":
        "မြေပုံဖတ်ရှုမှု အမြန်နှုန်း၊ ထောင့်နှင့် ပုံရိပ်ဖော် လေ့လာမှုများကို အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Exam Prep",
    "title_en": "Paper 4 (Alternative to Coursework) Mastery",
    "title_my": "Paper 4 (သင်တန်းလက်ရာ အစားထိုးစာမေးပွဲ) ကျွမ်းကျင်မှု",
    "topics": [
      "Fieldwork Question Structures",
      "Hypothesis Testing",
      "Data Analysis and Evaluation Questions",
    ],
    "description_en":
        "Master answering Paper 4 fieldwork and alternative-to-coursework examination questions.",
    "description_my":
        "Paper 4 ကွင်းဆင်းလေ့လာရေးနှင့် အစားထိုး စာမေးပွဲ မေးခွန်းများကို ဖြေဆိုရာတွင် ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Full Past Paper Mock Examinations",
    "title_my": "မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 2",
      "Timed Mock Paper 4",
    ],
    "description_en":
        "Complete full-length past paper mock examinations across all papers under rigorous timed conditions.",
    "description_my":
        "တင်းကျပ်သော အချိန်သတ်မှတ်ချက်များအောက်တွင် စာမေးပွဲ စာစောင်အားလုံးအတွက် မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },

  // ================= TERM 9: Final Exam Countdown & Graduation =================
  {
    "week": 33,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "Targeted Weakness Remediation",
    "title_my": "အားနည်းချက်ရှိသော ကဏ္ဍများကို အထူးပြုပြင်ခြင်း",
    "topics": [
      "Personalised Past Paper Drills",
      "Case Study Refresher",
      "Exam Strategy Review",
    ],
    "description_en":
        "Target individual student weak points through intensive, personalized past-paper question drills.",
    "description_my":
        "အတိတ် မေးခွန်းဟောင်း လေ့ကျင့်ခန်းများမှတစ်ဆင့် တစ်ဦးချင်း အားနည်းချက် ရှိသော ကဏ္ဍများကို အထူးပြုပြင်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "Exam Stamina and Time Management",
    "title_my": "စာမေးပွဲ ခံနိုင်ရည်နှင့် အချိန်စီမံခန့်ခွဲမှု",
    "topics": [
      "Pacing Strategies for Multiple Papers",
      "Exam Stress Management",
      "Final Tips",
    ],
    "description_en":
        "Refine psychological endurance and time management strategies for the actual IGCSE examination days.",
    "description_my":
        "တကယ့် IGCSE စာမေးပွဲရက်များအတွက် စိတ်ပိုင်းဆိုင်ရာ ခံနိုင်ရည်နှင့် အချိန်စီမံခန့်ခွဲမှု ဗျူဟာများကို ထက်မြက်စေမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "The Final Warm-Up Simulation",
    "title_my": "နောက်ဆုံး အကြိုလေ့ကျင့်ခန်း ပုံစံတူ ဖြေဆိုခြင်း",
    "topics": ["Light Practice Session", "Anxiety Reduction", "Final Review"],
    "description_en":
        "Participate in a final, low-stress simulated exam session to build unbreakable confidence.",
    "description_my":
        "စိတ်ဖိစီးမှုကင်းပြီး စာမေးပွဲ ယုံကြည်မှု အပြည့်အဝရရှိရန် နောက်ဆုံး အကြိုလေ့ကျင့်ခန်း စာမေးပွဲကို ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Geography Graduation",
    "title_my": "IGCSE ပထဝီဝင် ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Global Understanding",
      "Pathways to Advanced Geography",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Geography and look forward to advanced geographical studies.",
    "description_my":
        "IGCSE ပထဝီဝင် ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး အဆင့်မြင့် ပထဝီဝင် ပညာရေးဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
