// File: ai_data_bridge/igcse_maths_all_terms.dart
// IGCSE Mathematics Core & Extended Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseMathsAllTermsData = [
  // ================= TERM 1: Advanced Number & Sets =================
  {
    "week": 1,
    "term": 1,
    "theme": "Advanced Number",
    "title_en": "Sets, Venn Diagrams and Logic",
    "title_my": "ဆက်စ်များ၊ ဗန်းဇယားများ နှင့် ယုတ္တိဗေဒ",
    "topics": [
      "Union and Intersection",
      "Complement of Sets",
      "Venn Diagram Word Problems",
    ],
    "description_en":
        "Master set notation, Venn diagrams, and logical problem-solving for IGCSE examination standards.",
    "description_my":
        "IGCSE စာမေးပွဲစံနှုန်းများနှင့်အညီ ဆက်စ်သင်္ကေတများ၊ ဗန်းဇယားများနှင့် ယုတ္တိဗေဒ ပြဿနာဖြေရှင်းခြင်းကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Advanced Number",
    "title_en": "Indices and Standard Form",
    "title_my": "ထပ်ကိန်းများ နှင့် စံပုံစံ ကိန်းရေးနည်း",
    "topics": [
      "Fractional and Negative Indices",
      "Operations in Standard Form",
      "Estimation and Limits of Accuracy",
    ],
    "description_en":
        "Handle fractional and negative indices along with rigorous standard form calculations.",
    "description_my":
        "အပိုင်းကိန်းနှင့် အနှုတ်ထပ်ကိန်းများအပြင် တိကျသော စံပုံစံ တွက်ချက်မှုများကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Financial Arithmetic",
    "title_en": "Compound Interest and Depreciation",
    "title_my": "ပေါင်းစပ်အတိုး နှင့် တန်ဖိုးလျော့နည်းခြင်း",
    "topics": [
      "Compound Interest Formula",
      "Depreciation",
      "Reverse Percentages",
    ],
    "description_en":
        "Calculate compound interest over multiple periods and solve complex financial percentage problems.",
    "description_my":
        "ကာလပေါင်းများစွာအတွက် ပေါင်းစပ်အတိုးကို တွက်ချက်ပြီး ရှုပ်ထွေးသော ဘဏ္ဍာရေး ရာခိုင်နှုန်း ပြဿနာများကို ဖြေရှင်းမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Number Mastery Exam Prep",
    "title_my": "နံပါတ်ပိုင်းဆိုင်ရာ အပြည့်အစုံ ပြင်ဆင်ခြင်း",
    "topics": [
      "Ratio and Proportion Word Problems",
      "Speed, Distance, Time Graphs",
      "Paper 2/4 Practice",
    ],
    "description_en":
        "Apply advanced number and proportional reasoning to high-tariff IGCSE examination questions.",
    "description_my":
        "IGCSE စာမေးပွဲ မေးခွန်းခက်များအတွက် အဆင့်မြင့် နံပါတ်ပိုင်းနှင့် အချိုးကျ စဉ်းစားတွေးခေါ်မှုကို အသုံးချမည်။",
  },

  // ================= TERM 2: Algebra & Graphs =================
  {
    "week": 5,
    "term": 2,
    "theme": "Algebra",
    "title_en": "Quadratic Equations and Formula",
    "title_my": "နှစ်ထပ် ညီမျှခြင်းများနှင့် ဖော်မြူလာ",
    "topics": [
      "Completing the Square",
      "Quadratic Formula",
      "Solving by Factorising",
    ],
    "description_en":
        "Solve quadratic equations using factorization, completing the square, and the quadratic formula.",
    "description_my":
        "ဆခွဲကိန်းခွဲခြင်း၊ နှစ်ထပ်ကိန်းဖြည့်ခြင်းနှင့် နှစ်ထပ်ညီမျှခြင်း ဖော်မြူလာတို့ကို အသုံးပြု၍ ညီမျှခြင်းများကို ဖြေရှင်းမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Algebra",
    "title_en": "Simultaneous Equations (Linear & Non-Linear)",
    "title_my": "တွဲဖက်ညီမျှခြင်းများ (မျဉ်းဖြောင့်နှင့် မျဉ်းကွေး)",
    "topics": [
      "Substitution Method",
      "Intersection of Lines and Curves",
      "Graphical Solutions",
    ],
    "description_en":
        "Solve simultaneous equations where one equation is linear and the other is quadratic.",
    "description_my":
        "ညီမျှခြင်းတစ်ခုက မျဉ်းဖြောင့်ဖြစ်ပြီး နောက်တစ်ခုက မျဉ်းကွေးဖြစ်သော တွဲဖက်ညီမျှခြင်းများကို ဖြေရှင်းမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Graphs",
    "title_en": "Sketching Curves and Gradients",
    "title_my": "မျဉ်းကွေးများ ပုံဖော်ခြင်းနှင့် အစောင်းနှုန်းများ",
    "topics": [
      "Exponential Graphs",
      "Trigonometric Graphs",
      "Estimating Gradients of Curves",
    ],
    "description_en":
        "Sketch exponential and trigonometric graphs and estimate gradients of curves using tangents.",
    "description_my":
        "အိတ်စပိုနန်ရှယ်နှင့် တြိဂံထောင့် ဂရပ်များကို ပုံဖော်ပြီး အက္ခရာမျဉ်းထိစပ်ချက်များသုံးကာ အစောင်းနှုန်းများကို ခန့်မှန်းမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Algebraic Proofs",
    "title_my": "အက္ခရာသင်္ချာ သက်သေပြချက်များ",
    "topics": [
      "Algebraic Arguments",
      "Proving Identities",
      "Exam Style Proofs",
    ],
    "description_en":
        "Construct rigorous algebraic proofs to demonstrate mathematical properties and identities.",
    "description_my":
        "သင်္ချာဂုဏ်သတ္တိများနှင့် Identity များကို သက်သေပြရန် တင်းကျပ်သော အက္ခရာသင်္ချာ သက်သေပြချက်များကို တည်ဆောက်မည်။",
  },

  // ================= TERM 3: Coordinate Geometry & Mensuration =================
  {
    "week": 9,
    "term": 3,
    "theme": "Coordinate Geometry",
    "title_en": "Advanced Coordinate Geometry",
    "title_my": "အဆင့်မြင့် ကိုဩဒိနိတ် ဂျီဩမေတြီ",
    "topics": [
      "Length of a Line Segment",
      "Midpoint Formula",
      "Equation of Perpendicular Bisectors",
    ],
    "description_en":
        "Calculate lengths, midpoints, and equations of parallel and perpendicular lines on a coordinate plane.",
    "description_my":
        "ကိုဩဒိနိတ် ပြင်ပေါ်ရှိ အနားစွန်းအကွာအဝေး၊ အလယ်မှတ်နှင့် ထောင့်မှန်ကျ မျဉ်းညီမျှခြင်းများကို တွက်ချက်မည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Mensuration",
    "title_en": "Sectors, Arcs and 3D Volumes",
    "title_my": "စက်ဝိုင်းခြမ်းများ၊ လေးများ နှင့် ၃-ဖက်မြင် ထုထည်များ",
    "topics": [
      "Area of Sectors",
      "Arc Lengths",
      "Volumes of Pyramids, Cones and Spheres",
    ],
    "description_en":
        "Calculate arc lengths, sector areas, and surface areas/volumes of complex 3D shapes.",
    "description_my":
        "လေးအရှည်၊ စက်ဝိုင်းခြမ်းဧရိယာနှင့် ရှုပ်ထွေးသော ၃-ဖက်မြင် အခဲများ၏ မျက်နှာပြင်ဧရိယာ/ထုထည်များကို တွက်ချက်မည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Geometry",
    "title_en": "Circle Theorems (Advanced)",
    "title_my": "စက်ဝိုင်း သီအိုရမ်များ (အဆင့်မြင့်)",
    "topics": [
      "Angle at Centre vs Circumference",
      "Cyclic Quadrilaterals",
      "Alternate Segment Theorem",
    ],
    "description_en":
        "Apply circle theorems to solve complex geometric angle and length problems.",
    "description_my":
        "ရှုပ်ထွေးသော ဂျီဩမေတြီ ထောင့်နှင့် အနားပြဿနာများကို ဖြေရှင်းရန် စက်ဝိုင်းသီအိုရမ်များကို အသုံးချမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Geometry & Mensuration Exam Studio",
    "title_my": "ဂျီဩမေတြီနှင့် တိုင်းတာမှု စာမေးပွဲ အလုပ်ရုံ",
    "topics": [
      "Multi-step Geometric Proofs",
      "Composite Shape Calculations",
      "Past Paper Practice",
    ],
    "description_en":
        "Tackle multi-step IGCSE geometry and circle theorem proof questions.",
    "description_my":
        "အဆင့်များစွာပါသော IGCSE ဂျီဩမေတြီနှင့် စက်ဝိုင်းသီအိုရမ် သက်သေပြ မေးခွန်းများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 4: Trigonometry & Vectors =================
  {
    "week": 13,
    "term": 4,
    "theme": "Trigonometry",
    "title_en": "Sine Rule and Cosine Rule",
    "title_my": "ဆိုင်း နိယာမ (Sine Rule) နှင့် ကိုဆိုင်း နိယာမ (Cosine Rule)",
    "topics": [
      "Non-Right-Angled Triangles",
      "Area of Triangle = ½ab sin C",
      "Bearings and Trig",
    ],
    "description_en":
        "Solve any triangle using the Sine rule, Cosine rule, and trigonometric area formulas.",
    "description_my":
        "Sine rule, Cosine rule နှင့် တြိဂံဧရိယာ ဖော်မြူလာများကို အသုံးပြု၍ ထောင့်မှန်မဟုတ်သော တြိဂံများကို ဖြေရှင်းမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Trigonometry",
    "title_en": "3D Trigonometry",
    "title_my": "၃-ဖက်မြင် တြိဂံထောင့် တိုင်းတာမှု",
    "topics": [
      "Angles between Lines and Planes",
      "Complex 3D Triangles",
      "Real-world Navigation",
    ],
    "description_en":
        "Calculate angles and lengths in three-dimensional geometric structures.",
    "description_my":
        "၃-ဖက်မြင် ဂျီဩမေတြီ ဖွဲ့စည်းပုံများအတွင်းရှိ ထောင့်များနှင့် အနားအလျားများကို တွက်ချက်မည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Vectors",
    "title_en": "Vector Geometry and Proofs",
    "title_my": "ဗက်တာ ဂျီဩမေတြီ နှင့် သက်သေပြချက်များ",
    "topics": ["Column Vectors", "Geometric Vector Proofs", "Collinear Points"],
    "description_en":
        "Use vector algebra to prove geometric theorems and collinearity in shapes.",
    "description_my":
        "ဂျီဩမေတြီ သီအိုရီများနှင့် ပုံသဏ္ဍာန်များ တန်းတူညီညာမှုကို သက်သေပြရန် ဗက်တာ အက္ခရာသင်္ချာကို အသုံးချမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Trig and Vector Masterclass",
    "title_my": "Trig နှင့် ဗက်တာ အဆင့်မြင့် လေ့ကျင့်ခန်း",
    "topics": ["Advanced Bearings", "Vector Proof Challenges", "Exam Prep"],
    "description_en":
        "Master high-tariff trigonometry and vector proof questions for Paper 4 Extended.",
    "description_my":
        "Paper 4 Extended စာမေးပွဲအတွက် အဆင့်မြင့် trig နှင့် ဗက်တာ သက်သေပြ မေးခွန်းများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },

  // ================= TERM 5: Probability & Statistics =================
  {
    "week": 17,
    "term": 5,
    "theme": "Probability",
    "title_en": "Conditional Probability & Tree Diagrams",
    "title_my":
        "အခြေအနေနှင့် သက်ဆိုင်သော ဖြစ်နိုင်ခြေနှင့် တြိဂံပုံစံ ဂရပ်များ",
    "topics": [
      "Dependent Events",
      "Multiplication and Addition Laws",
      "Conditional Probability Formula",
    ],
    "description_en":
        "Calculate probabilities of complex dependent events using tree diagrams and conditional formulas.",
    "description_my":
        "တြိဂံပုံစံဂရပ်များနှင့် အခြေအနေပြ ဖော်မြူလာများကို သုံး၍ ရှုပ်ထွေးသော မှီခိုအဖြစ်အပျက်များ၏ ဖြစ်နိုင်ခြေကို တွက်ချက်မည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Statistics",
    "title_en": "Cumulative Frequency and Box Plots",
    "title_my": "စုစုပေါင်းအကြိမ်ရေ နှင့် သေတ္တာပုံစံ ဂရပ်များ",
    "topics": [
      "Drawing Cumulative Frequency Curves",
      "Interquartile Range (IQR)",
      "Comparing Distributions",
    ],
    "description_en":
        "Analyze data distributions using cumulative frequency graphs and box-and-whisker plots.",
    "description_my":
        "စုစုပေါင်းအကြိမ်ရေ ဂရပ်များနှင့် Box plots များကို အသုံးပြု၍ အချက်အလက် ပျံ့နှံ့မှုကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Statistics",
    "title_en": "Histograms and Frequency Density",
    "title_my": "ဟစ္စတိုဂရမ်များနှင့် အကြိမ်ရေ သိပ်သည်းဆ",
    "topics": [
      "Frequency Density Formula",
      "Interpreting Histograms",
      "Calculating Medians from Histograms",
    ],
    "description_en":
        "Construct and interpret histograms with unequal class intervals.",
    "description_my":
        "မတူညီသော အတန်းအကျယ်များပါရှိသော Histograms များကို တည်ဆောက်ခြင်းနှင့် အဓိပ္ပာယ်ဖော်ခြင်း ပြုလုပ်မည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Statistics & Probability Studio",
    "title_my": "စာရင်းအင်းနှင့် ဖြစ်နိုင်ခြေ အလုပ်ရုံ",
    "topics": [
      "Data Comparison Tasks",
      "Complex Probability Scenarios",
      "Exam Strategy",
    ],
    "description_en":
        "Solve rigorous statistics and probability problems mirroring final IGCSE exam papers.",
    "description_my":
        "နောက်ဆုံး IGCSE စာမေးပွဲ မေးခွန်းများနှင့် တူညီသော တင်းကျပ်သည့် စာရင်းအင်းနှင့် ဖြစ်နိုင်ခြေ ပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 6: Transformations, Matrices & Functions =================
  {
    "week": 21,
    "term": 6,
    "theme": "Transformations",
    "title_en": "Matrix Transformations",
    "title_my": "မက်ထရစ် ရွေ့လျားမှုများ (Matrix Transformations)",
    "topics": [
      "2x2 Transformation Matrices",
      "Reflection and Rotation Matrices",
      "Enlargement and Shear",
    ],
    "description_en":
        "Use 2x2 matrices to perform and describe geometric transformations on a coordinate plane.",
    "description_my":
        "ကိုဩဒိနိတ် ပြင်ပေါ်တွင် ဂျီဩမေတြီ ရွေ့လျားမှုများကို ဖော်ပြရန်နှင့် လုပ်ဆောင်ရန် 2x2 မက်ထရစ်များကို အသုံးပြုမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Functions",
    "title_en": "Composite and Inverse Functions",
    "title_my": "ပေါင်းစပ်ဖန်ရှင်များနှင့် ပြောင်းပြန်ဖန်ရှင်များ",
    "topics": [
      "Evaluating fg(x)",
      "Finding Inverse Functions f⁻¹(x)",
      "Domain and Range",
    ],
    "description_en":
        "Master composite functions and derive inverse functions algebraically.",
    "description_my":
        "ပေါင်းစပ်ဖန်ရှင်များကို တွက်ချက်ခြင်းနှင့် အက္ခရာသင်္ချာနည်းဖြင့် ပြောင်းပြန်ဖန်ရှင်များကို ဖော်ထုတ်ခြင်း ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Calculus Intro",
    "title_en": "Introduction to Calculus (Differentiation)",
    "title_my": "ကဲကူလပ်စ် မိတ်ဆက် (ကွဲပြားခြင်း / Differentiation)",
    "topics": [
      "Power Rule for Differentiation",
      "Finding Gradients of Curves",
      "Turning Points",
    ],
    "description_en":
        "Introduction to basic differentiation for finding gradients and stationary points on curves.",
    "description_my":
        "မျဉ်းကွေးများပေါ်ရှိ အစောင်းနှုန်းနှင့် ရပ်တန့်မှတ်များကို ရှာဖွေရန် အခြေခံ differentiation ကို စတင်မိတ်ဆက်မည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Advanced Algebra & Calculus Challenge",
    "title_my": "အဆင့်မြင့် အက္ခရာသင်္ချာနှင့် ကဲကူလပ်စ် စိန်ခေါ်မှု",
    "topics": [
      "Optimisation Problems",
      "Matrix Proofs",
      "Exam Style Integration",
    ],
    "description_en":
        "Apply differentiation and advanced algebraic methods to solve optimization problems.",
    "description_my":
        "အကောင်းဆုံး တန်ဖိုးရှာဖွေရေး (Optimisation) ပြဿနာများကို ဖြေရှင်းရန် differentiation နှင့် အဆင့်မြင့် အက္ခရာသင်္ချာ နည်းလမ်းများကို အသုံးချမည်။",
  },

  // ================= TERM 7: Advanced Modeling & Problem Solving =================
  {
    "week": 25,
    "term": 7,
    "theme": "Mathematical Modeling",
    "title_en": "Real-World Mathematical Modeling",
    "title_my": "လက်တွေ့ဘဝ သင်္ချာ ပုံဖော်ခြင်း",
    "topics": [
      "Exponential Growth/Decay Models",
      "Financial Mathematics Applications",
      "Optimization",
    ],
    "description_en":
        "Model complex real-world scenarios using exponential functions and advanced algebra.",
    "description_my":
        "အိတ်စပိုနန်ရှယ် ဖန်ရှင်များနှင့် အဆင့်မြင့် အက္ခရာသင်္ချာကို အသုံးပြု၍ ရှုပ်ထွေးသော လက်တွေ့ဘဝ အခြေအနေများကို ပုံဖော်မည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Advanced Geometry",
    "title_en": "Geometric Proofs and Congruence/Similarity",
    "title_my": "ဂျီဩမေတြီ သက်သေပြချက်များနှင့် ပုံတူ/ဆင်တူခြင်း",
    "topics": [
      "Formal Proofs of Congruence",
      "Similar Triangles Proofs",
      "Area/Volume Scale Factors",
    ],
    "description_en":
        "Construct formal geometric proofs for triangle congruence and similarity.",
    "description_my":
        "တြိဂံပုံတူခြင်းနှင့် ဆင်တူခြင်းများအတွက် တရားဝင် ဂျီဩမေတြီ သက်သေပြချက်များကို တည်ဆောက်မည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Advanced Number",
    "title_en": "Surds and Exact Arithmetic",
    "title_my": "ဆတ် (Surds) နှင့် တိကျသော ဂဏန်းတွက်ချက်မှု",
    "topics": [
      "Simplifying Surds",
      "Expanding Brackets with Surds",
      "Rationalising Denominators",
    ],
    "description_en":
        "Perform exact arithmetic operations with surds without using decimal approximations.",
    "description_my":
        "ဒသမ ခန့်မှန်းခြေကို မသုံးဘဲ surds များကို အသုံးပြု၍ တိကျသော သင်္ချာတွက်ချက်မှုများ လုပ်ဆောင်မည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Mathematical Investigation Project",
    "title_my": "သင်္ချာ စူးစမ်းလေ့လာမှု ပရောဂျက်",
    "topics": [
      "Open-ended Problem Solving",
      "Generalising Patterns",
      "Mathematical Writing",
    ],
    "description_en":
        "Conduct an open-ended mathematical investigation, generalizing patterns into algebraic formulas.",
    "description_my":
        "အဆုံးသတ်မရှိသော သင်္ချာစူးစမ်းလေ့လာမှုတစ်ခုကို လုပ်ဆောင်ပြီး ပုံစံများကို အက္ခရာသင်္ချာ ဖော်မြူလာများအဖြစ် အထွေထွေထုတ်ဖော်မည်။",
  },

  // ================= TERM 8: Exam Intensive - Paper 2 & Paper 4 (Extended) =================
  {
    "week": 29,
    "term": 8,
    "theme": "Exam Intensive",
    "title_en": "Paper 2 (Non-Calculator) Intensive",
    "title_my": "Paper 2 (စက်မသုံးရ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Mental Math Fluency",
      "Algebraic Manipulation Speed",
      "Exact Value Mastery",
    ],
    "description_en":
        "Intensive practice for the IGCSE Extended Paper 2 non-calculator examination.",
    "description_my":
        "IGCSE Extended Paper 2 (စက်မသုံးရ) စာမေးပွဲအတွက် အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Exam Intensive",
    "title_en": "Paper 4 (Calculator) Intensive",
    "title_my": "Paper 4 (စက်သုံးရ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Complex Problem Solving",
      "Trigonometry & Vectors Applications",
      "Statistical Analysis",
    ],
    "description_en":
        "Master high-tariff structured questions for the IGCSE Extended Paper 4 examination.",
    "description_my":
        "IGCSE Extended Paper 4 စာမေးပွဲအတွက် အမှတ်များသော အဆောက်အအုံပါ မေးခွန်းများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Exam Intensive",
    "title_en": "Error Analysis and Mark Scheme Mastery",
    "title_my":
        "အမှားများကို ခွဲခြမ်းစိတ်ဖြာခြင်းနှင့် အမှတ်ပေးစည်းမျဉ်း ကျွမ်းကျင်မှု",
    "topics": [
      "Common Student Pitfalls",
      "Understanding Examiner Reports",
      "Maximising Method Marks",
    ],
    "description_en":
        "Analyze common exam pitfalls and learn how to secure method marks according to Cambridge mark schemes.",
    "description_my":
        "စာမေးပွဲတွင် ဖြစ်လေ့ရှိသော အမှားများကို လေ့လာပြီး Cambridge အမှတ်ပေးစည်းမျဉ်းအတိုင်း အမှတ်ပြည့်ရရန် နည်းလမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Full Mock Exam Series 1",
    "title_my": "ပုံစံတူ စာမေးပွဲ အစုံ (၁)",
    "topics": [
      "Timed Paper 2 Mock",
      "Timed Paper 4 Mock",
      "Detailed Performance Review",
    ],
    "description_en":
        "Sit a complete set of mock IGCSE Mathematics papers under strict exam conditions.",
    "description_my":
        "တင်းကျပ်သော စာမေးပွဲ အခြေအနေများအောက်တွင် IGCSE သင်္ချာ ပုံစံတူ စာမေးပွဲ အစုံအလင်ကို ဖြေဆိုမည်။",
  },

  // ================= TERM 9: Final Countdown & IGCSE Graduation =================
  {
    "week": 33,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "Targeted Topic Weakness Workshop",
    "title_my": "အားနည်းချက်ရှိသော ခေါင်းစဉ်များကို အထူးပြုပြင်သည့် အလုပ်ရုံ",
    "topics": [
      "Personalised Revision",
      "Challenging Past Paper Questions",
      "Q&A Sessions",
    ],
    "description_en":
        "Address individual topic weaknesses through targeted past paper question drills.",
    "description_my":
        "တစ်ဦးချင်းစီ၏ အားနည်းချက်ရှိသော ခေါင်းစဉ်များကို ယခင်မေးခွန်းဟောင်းများဖြင့် အထူးပြုပြင် လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "Full Mock Exam Series 2",
    "title_my": "ပုံစံတူ စာမေးပွဲ အစုံ (၂)",
    "topics": [
      "Final Paper 2 Simulation",
      "Final Paper 4 Simulation",
      "Final Grading and Feedback",
    ],
    "description_en":
        "Complete the final mock examination series to build unshakeable exam confidence.",
    "description_my":
        "စာမေးပွဲ ယုံကြည်မှု အပြည့်အဝရရှိရန် နောက်ဆုံး ပုံစံတူ စာမေးပွဲ အစုံ (၂) ကို ဖြေဆိုမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "Exam Day Readiness and Mental Preparation",
    "title_my":
        "စာမေးပွဲနေ့အတွက် အသင့်ဖြစ်မှုနှင့် စိတ်ပိုင်းဆိုင်ရာ ပြင်ဆင်မှု",
    "topics": [
      "Time Management Strategies",
      "Exam Stress Management",
      "Final Tips",
    ],
    "description_en":
        "Prepare mentally and strategically for the actual IGCSE examination days ahead.",
    "description_my":
        "ရှေ့ဆက်ဖြေဆိုရမည့် တကယ့် IGCSE စာမေးပွဲရက်များအတွက် စိတ်ပိုင်းဆိုင်ရာနှင့် ဗျူဟာမြောက် ပြင်ဆင်မှုများ လုပ်ဆောင်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Mathematics Graduation",
    "title_my": "IGCSE သင်္ချာ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Course Completion Celebration",
      "Reflecting on Mathematical Growth",
      "Next Steps to Advanced Level",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Mathematics and look ahead to A-Level / Advanced Mathematics.",
    "description_my":
        "IGCSE သင်္ချာ အောင်မြင်စွာ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး A-Level / အဆင့်မြင့် သင်္ချာဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
