// File: ai_data_bridge/igcse_history_all_terms.dart
// IGCSE History Syllabus Terms 1 to 9 (Weeks 1-36) - 20th Century International Relations
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseHistoryAllTermsData = [
  // ================= TERM 1: Were the Peace Treaties of 1919-23 Fair? =================
  {
    "week": 1,
    "term": 1,
    "theme": "International Relations",
    "title_en": "The Paris Peace Conference and Versailles",
    "title_my": "ပါရီ ငြိမ်းချမ်းရေး ညီလာခံနှင့် ဗာဆိုင်ဆွေးနွေးပွဲ",
    "topics": [
      "The Big Three (Wilson, Clemenceau, Lloyd George)",
      "Aims of the Peacemakers",
      "Terms of the Treaty of Versailles",
    ],
    "description_en":
        "Examine the motives and conflicting aims of the leaders at the Paris Peace Conference and the harsh terms imposed on Germany.",
    "description_my":
        "ပါရီ ငြိမ်းချမ်းရေး ညီလာခံရှိ ခေါင်းဆောင်များ၏ ရည်မှန်းချက် ကွာခြားချက်များနှင့် ဂျာမနီအပေါ် ချမှတ်ခဲ့သည့် ကြမ်းတမ်းသော ဗာဆိုင်စာချုပ် စည်းကမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "International Relations",
    "title_en": "The Other Peace Treaties",
    "title_my": "အခြား ငြိမ်းချမ်းရေး စာချုပ်များ",
    "topics": [
      "Treaty of St Germain, Trianon, Neuilly, and Sèvres",
      "Redrawing the Map of Europe",
      "Self-Determination Successes and Failures",
    ],
    "description_en":
        "Analyze the treaties affecting Austria, Hungary, Bulgaria, and Turkey, and the redrawing of European borders.",
    "description_my":
        "ဩစတြီးယား၊ ဟန်ဂေရီ၊ ဘူလ်ဂေးရီးယားနှင့် တူရကီတို့အပေါ် သက်ရောက်သော စာချုပ်များနှင့် ဥရောပ နယ်နိမိတ် အသစ်ပြန်လည် ရေးဆွဲမှုကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "International Relations",
    "title_en": "Contemporary Reactions to the Treaties",
    "title_my": "စာချုပ်များအပေါ် ခေတ်ပြိုင် တုံ့ပြန်မှုများ",
    "topics": [
      "German Reactions and 'Diktat'",
      "Economic and Political Impact on Germany",
      "Justification of the Treaties",
    ],
    "description_en":
        "Evaluate how contemporaries viewed the treaties, focusing particularly on German outrage and economic consequences.",
    "description_my":
        "ဂျာမနီ၏ ဒေါသတကြီး တုံ့ပြန်မှုနှင့် စီးပွားရေး သက်ရောက်မှုများကို အဓိကထား၍ ခေတ်ပြိုင်လူထုက စာချုပ်များကို မည်သို့ရှုမြင်ကြောင်း အကဲဖြတ်မည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Peace Treaties Evaluation Studio",
    "title_my": "ငြိမ်းချမ်းရေး စာချုပ်များ အကဲဖြတ်ခြင်း အလုပ်ရုံ",
    "topics": [
      "Was Versailles Fair?",
      "Historical Interpretations",
      "Exam Essay Practice",
    ],
    "description_en":
        "Synthesize arguments to debate whether the 1919-23 peace settlements were justified or caused future conflicts.",
    "description_my":
        "၁၉၁၉-၂၃ ငြိမ်းချမ်းရေး အခြေချမှုများသည် တရားမျှတမှု ရှိမရှိ သို့မဟုတ် အနာဂတ် ပဋိပက္ခများကို ဖန်တီးခဲ့ခြင်းလားဆိုသည်ကို ဆွေးနွေးမည်။",
  },

  // ================= TERM 2: To What Extent Was the League of Nations a Success? =================
  {
    "week": 5,
    "term": 2,
    "theme": "The League of Nations",
    "title_en": "Establishment and Aims of the League",
    "title_my": "အသင်းချုပ် တည်ထောင်ခြင်းနှင့် ရည်မှန်းချက်များ",
    "topics": [
      "Structure of the League (Assembly, Council, Secretariat)",
      "Aims and Covenant",
      "Absence of Key Powers (USA, USSR, Germany)",
    ],
    "description_en":
        "Understand the organisational structure of the League of Nations and the structural weaknesses from its inception.",
    "description_my":
        "နိုင်ငံပေါင်းချုပ် အသင်းကြီး၏ ဖွဲ့စည်းပုံ အဆောက်အအုံနှင့် စတင်တည်ထောင်ချိန်ကတည်းက ပါရှိနေသော အားနည်းချက်များကို နားလည်စေမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "The League of Nations",
    "title_en": "Successes and Failures in the 1920s",
    "title_my": "၁၉၂၀ ပြည့်လွန်နှစ်များအတွင်း အောင်မြင်မှုနှင့် ကျရှုံးမှုများ",
    "topics": [
      "Aaland Islands, Vilna, Upper Silesia",
      "Washington Conferences and Locarno Treaties",
      "Humanitarian Work of the League",
    ],
    "description_en":
        "Examine the diplomatic successes of the League in the 1920s alongside its early limitations.",
    "description_my":
        "၁၉၂၀ ပြည့်လွန်နှစ်များအတွင်း အသင်းချုပ်၏ သံတမန်ရေးရာ အောင်မြင်မှုများနှင့် ကန့်သတ်ချက်များကို လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "The League of Nations",
    "title_en": "The Manchurian and Abyssinian Crises",
    "title_my": "မန်ချူးရီးယားနှင့် အဘစ်ဆီးနီးယား အကျပ်အတည်းများ",
    "topics": [
      "Japanese Invasion of Manchuria (1931)",
      "Italian Invasion of Abyssinia (1935)",
      "Failure of Collective Security and Sanctions",
    ],
    "description_en":
        "Analyze how major crises in Manchuria and Abyssinia exposed the fatal weaknesses of the League.",
    "description_my":
        "မန်ချူးရီးယားနှင့် အဘစ်ဆီးနီးယား အကျပ်အတည်းများသည် အသင်းချုပ်၏ အဓိက အားနည်းချက်များကို မည်သို့ပေါ်လွင်စေကြောင်း ခွဲခြမ်းမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "League of Nations Trial Studio",
    "title_my": "နိုင်ငံပေါင်းချုပ် အသင်းကြီး တရားခွင် ပုံစံတူ အလုပ်ရုံ",
    "topics": [
      "Why Did the League Fail?",
      "Assessing Collective Security",
      "Exam Paper 1/2 Practice",
    ],
    "description_en":
        "Evaluate the overall effectiveness of the League of Nations and construct balanced historical arguments.",
    "description_my":
        "နိုင်ငံပေါင်းချုပ် အသင်းကြီး၏ စုစုပေါင်း ထိရောက်မှုကို အကဲဖြတ်ပြီး မျှတသော သမိုင်းဆိုင်ရာ အငြင်းပွားမှုများကို တည်ဆောက်မည်။",
  },

  // ================= TERM 3: Why Had International Peace Collapsed by 1939? =================
  {
    "week": 9,
    "term": 3,
    "theme": "Road to War",
    "title_en": "Hitler's Foreign Policy Aims",
    "title_my": "ဟစ်တလရာ၏ နိုင်ငံခြားရေး မူဝါဒ ရည်မှန်းချက်များ",
    "topics": [
      "Overturning Versailles",
      "Lebensraum (Living Space)",
      "Rearmament and Saar Plebiscite",
    ],
    "description_en":
        "Examine Adolf Hitler's core foreign policy objectives and initial steps to dismantle the Treaty of Versailles.",
    "description_my":
        "အဒေါဖ် ဟစ်တလရာ၏ အဓိက နိုင်ငံခြားရေး ရည်မှန်းချက်များနှင့် ဗာဆိုင်စာချုပ်ကို ဖျက်သိမ်းရန် ပထမအဆင့် အစပြုမှုများကို လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Road to War",
    "title_en": "Aggression in the 1930s",
    "title_my": "၁၉၃၀ ပြည့်လွန်နှစ်များအတွင်း ကျူးကျော်မှုများ",
    "topics": [
      "Remilitarisation of the Rhineland",
      "Anschluss with Austria",
      "The Sudetenland Crisis and Munich Agreement",
    ],
    "description_en":
        "Analyze aggressive German expansion steps in the mid-to-late 1930s and international responses.",
    "description_my":
        "၁၉၃၀ ပြည့်လွန်နှစ်များ အလယ်ပိုင်းနှင့် နောက်ပိုင်းကာလများအတွင်း ဂျာမနီ၏ ရန်လိုသော နယ်မြေချဲ့ထွင်မှုနှင့် နိုင်ငံတကာ၏ တုံ့ပြန်မှုကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Road to War",
    "title_en": "Appeasement and the Outbreak of War",
    "title_my":
        "အကြိုက်လိုက်လျောရေး မူဝါဒ (Appeasement) နှင့် စစ်ပွဲ စတင်ခြင်း",
    "topics": [
      "Policy of Appeasement (Chamberlain)",
      "Nazi-Soviet Pact",
      "Invasion of Poland and Declaration of War",
    ],
    "description_en":
        "Evaluate the policy of appeasement, the shock Nazi-Soviet Pact, and the final triggers for World War II.",
    "description_my":
        "Appeasement မူဝါဒ၊ အံ့သြဖွယ် နာဇီ-ဆိုဗီယက် သဘောတူညီချက်နှင့် ဒုတိယကမ္ဘာစစ် ဖြစ်ပွားစေသည့် နောက်ဆုံး အကြောင်းရင်းများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Who Was to Blame for WWII?",
    "title_my": "ဒုတိယကမ္ဘာစစ်အတွက် မည်သူ့တွင် တာဝန်ရှိသနည်း?",
    "topics": [
      "Hitler vs Western Powers",
      "Failure of Appeasement",
      "Exam Source Evaluation",
    ],
    "description_en":
        "Analyze historical sources to assign responsibility for the outbreak of World War II in Europe.",
    "description_my":
        "ဥရောပတွင် ဒုတိယကမ္ဘာစစ် ဖြစ်ပွားရခြင်းအတွက် တာဝန်ရှိမှုကို ဆုံးဖြတ်ရန် သမိုင်းဝင် အရင်းအမြစ်များကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },

  // ================= TERM 4: Who Was to Blame for the Cold War? =================
  {
    "week": 13,
    "term": 4,
    "theme": "The Cold War",
    "title_en": "Origins of the Cold War and Wartime Conferences",
    "title_my": "စစ်အေးတိုက်ပွဲ အစနှင့် စစ်အတွင်း ညီလာခံများ",
    "topics": [
      "Teheran, Yalta, and Potsdam Conferences",
      "Ideological Differences (Capitalism vs Communism)",
      "The Breakdown of the Grand Alliance",
    ],
    "description_en":
        "Examine how wartime cooperation deteriorated into mistrust between the USA and USSR at Yalta and Potsdam.",
    "description_my":
        "Yalta နှင့် Potsdam ညီလာခံများတွင် စစ်အတွင်း ပူးပေါင်းဆောင်ရွက်မှုသည် အမေရိကန်နှင့် ဆိုဗီယက်တို့ကြား အယုံအကြည်ကင်းမဲ့မှုအဖြစ်သို့ မည်သို့ပြောင်းလဲခဲ့ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "The Cold War",
    "title_en": "Soviet Expansion in Eastern Europe",
    "title_my": "အရှေ့ဥရောပတွင် ဆိုဗီယက်၏ နယ်မြေလွှမ်းမိုးမှု",
    "topics": [
      "The Iron Curtain Speech (Churchill)",
      "Satellite States Creation",
      "Truman Doctrine and Marshall Plan",
    ],
    "description_en":
        "Analyze the imposition of Soviet control in Eastern Europe and the American containment response.",
    "description_my":
        "အရှေ့ဥရောပတွင် ဆိုဗီယက်တို့၏ ထိန်းချုပ်မှု သက်ရောက်လာခြင်းနှင့် အမေရိကန်၏ တားဆီးထိန်းချုပ်ရေး တုံ့ပြန်မှုကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "The Cold War",
    "title_en": "The Berlin Blockade and Airlift",
    "title_my":
        "ဘာလင် ပိတ်ဆို့မှုနှင့် လေကြောင်းမှ ထောက်ပံ့ခြင်း (Berlin Airlift)",
    "topics": [
      "Division of Germany and Berlin",
      "The 1948-49 Blockade",
      "Formation of NATO and Warsaw Pact",
    ],
    "description_en":
        "Explore the first major Cold War confrontation over Berlin and the militarisation of alliances.",
    "description_my":
        "ဘာလင်မြို့အပေါ် ပထမဆုံးအကြိမ် ကြီးမားသော စစ်အေးတိုက်ပွဲ ပဋိပက္ခနှင့် မဟာမိတ်အဖွဲ့များ စစ်ရေးပြင်းထန်လာမှုကို စူးစမ်းမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Cold War Origins Studio",
    "title_my": "စစ်အေးတိုက်ပွဲ အစပိုင်း အလုပ်ရုံ",
    "topics": [
      "US vs USSR Perspectives",
      "Historiography of the Cold War",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate contrasting historical interpretations regarding who caused the Cold War.",
    "description_my":
        "စစ်အေးတိုက်ပွဲကို မည်သူက စတင်ခဲ့သည်ဆိုသည့် ကွဲပြားခြားနားသော သမိုင်းဆိုင်ရာ အယူအဆများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 5: How Effectively Did the USA Contain Communism? =================
  {
    "week": 17,
    "term": 5,
    "theme": "Containment",
    "title_en": "The Korean War (1950-53)",
    "title_my": "ကိုရီးယားစစ်ပွဲ (၁၉၅၀-၅၃)",
    "topics": [
      "Division of Korea",
      "UN Intervention",
      "MacArthur vs Truman and Outcomes",
    ],
    "description_en":
        "Examine the Korean conflict as the first military test of containment in Asia.",
    "description_my":
        "အာရှတိုက်တွင် တားဆီးထိန်းချုပ်ရေး၏ ပထမဆုံး စစ်ရေးစမ်းသပ်မှုအဖြစ် ကိုရီးယား ပဋိပက္ခကို လေ့လာမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Containment",
    "title_en": "The Vietnam War (1955-75)",
    "title_my": "ဗီယက်နမ်စစ်ပွဲ (၁၉၅၅-၇၅)",
    "topics": [
      "US Involvement under Kennedy and Johnson",
      "Guerrilla Warfare Tactics",
      "Tet Offensive and US Withdrawal",
    ],
    "description_en":
        "Analyze why the USA failed to contain communism in Vietnam despite military superiority.",
    "description_my":
        "စစ်ရေးအသာစီးရသော်လည်း အမေရိကန်တို့ ဗီယက်နမ်တွင် ကွန်မြူနစ်ဝါဒကို အဘယ်ကြောင့် မတားဆီးနိုင်ခဲ့ကြောင်း ခွဲခြမ်းမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Containment",
    "title_en": "The Cuban Missile Crisis (1962)",
    "title_my": "ကျူးဘား ဒုံးကျည် အကျပ်အတည်း (၁၉၆၂)",
    "topics": [
      "Fidel Castro and the Cuban Revolution",
      "The 13 Days of Crisis",
      "Khrushchev, Kennedy, and Outcomes",
    ],
    "description_en":
        "Investigate the closest the world came to nuclear war during the 1962 Cuban Missile Crisis.",
    "description_my":
        "၁၉၆၂ ကျူးဘား ဒုံးကျည် အကျပ်အတည်းကာလတွင် ကမ္ဘာကြီးသည် နူကလီးယားစစ်ပွဲနှင့် မည်မျှနီးကပ်ခဲ့ကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Containment Evaluation Studio",
    "title_my": "တားဆီးထိန်းချုပ်ရေး အကဲဖြတ်ခြင်း အလုပ်ရုံ",
    "topics": [
      "Success or Failure of Containment?",
      "Nuclear Standoff Analysis",
      "Exam Practice",
    ],
    "description_en":
        "Synthesize the effectiveness of US containment strategies across Korea, Vietnam, and Cuba.",
    "description_my":
        "ကိုရီးယား၊ ဗီယက်နမ်နှင့် ကျူးဘားတို့တွင် အမေရိကန်၏ တားဆီးထိန်းချုပ်ရေး မဟာဗျူဟာများ၏ ထိရောက်မှုကို ပေါင်းစပ်သုံးသပ်မည်။",
  },

  // ================= TERM 6: Soviet Control Over Eastern Europe =================
  {
    "week": 21,
    "term": 6,
    "theme": "Eastern Europe",
    "title_en": "Challenges to Soviet Control: Hungary and Czechoslovakia",
    "title_my":
        "ဆိုဗီယက် ထိန်းချုပ်မှုအပေါ် စိန်ခေါ်မှုများ - ဟန်ဂေရီနှင့် ချက်ကိုစလိုဗားကီးယား",
    "topics": [
      "Hungarian Uprising (1956) and Imre Nagy",
      "Prague Spring (1968) and Alexander Dubček",
      "Brezhnev Doctrine",
    ],
    "description_en":
        "Examine popular uprisings in Hungary and Czechoslovakia and brutal Soviet military suppressions.",
    "description_my":
        "ဟန်ဂေရီနှင့် ချက်ကိုစလိုဗားကီးယားတို့ရှိ လူထုထကြွမှုများနှင့် ဆိုဗီယက်တို့၏ ကြမ်းတမ်းသော စစ်ရေးဖြိုခွဲမှုများကို လေ့လာမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Eastern Europe",
    "title_en": "The Berlin Wall",
    "title_my": "ဘာလင် တံတိုင်း",
    "topics": [
      "Brain Drain from East Berlin",
      "Construction of the Wall (1961)",
      "Checkpoint Charlie and Impact",
    ],
    "description_en":
        "Understand why the Berlin Wall was built and its significance as a symbol of the Cold War division.",
    "description_my":
        "ဘာလင်တံတိုင်းကို အဘယ်ကြောင့် တည်ဆောက်ခဲ့ရကြောင်းနှင့် စစ်အေးတိုက်ပွဲ ခွဲခြားမှု၏ သင်္ကေတအဖြစ် ၎င်း၏ အရေးပါမှုကို နားလည်စေမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Eastern Europe",
    "title_en": "Collapse of the Soviet Empire",
    "title_my": "ဆိုဗီယက် အင်ပါယာ ပြိုလဲခြင်း",
    "topics": [
      "Gorbachev's Policies (Glasnost and Perestroika)",
      "Solidarity in Poland",
      "Fall of the Berlin Wall (1989) and Collapse of USSR",
    ],
    "description_en":
        "Analyze the factors leading to the collapse of communism in Eastern Europe and the end of the USSR.",
    "description_my":
        "အရှေ့ဥရောပတွင် ကွန်မြူနစ်ဝါဒ ပြိုလဲရခြင်းနှင့် ဆိုဗီယက်ပြည်ထောင်စု ပျက်သုဉ်းရခြင်း၏ အကြောင်းရင်းများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Soviet Control Case Study Studio",
    "title_my": "ဆိုဗီယက် ထိန်းချုပ်မှု လက်တွေ့လေ့လာမှု အလုပ်ရုံ",
    "topics": [
      "Why Did Eastern Europe Rebel?",
      "Gorbachev's Role",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate the stability of Soviet control and the catalysts that triggered the end of the Cold War.",
    "description_my":
        "ဆိုဗီယက် ထိန်းချုပ်မှု၏ တည်ငြိမ်မှုနှင့် စစ်အေးတိုက်ပွဲ ကို အဆုံးစေသည့် အဓိက အကြောင်းရင်းများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 7: Depth Study / Regional Conflict Option =================
  {
    "week": 25,
    "term": 7,
    "theme": "Regional Conflict",
    "title_en": "The Gulf Conflict (1990-91)",
    "title_my": "ပင်လယ်ကွေ့ ပဋိပက္ခ (၁၉၉၀-၉၁)",
    "topics": [
      "Saddam Hussein and Iraq",
      "Invasion of Kuwait",
      "Operation Desert Storm and Consequences",
    ],
    "description_en":
        "Examine the causes, course, and international consequences of the 1990-91 Gulf War.",
    "description_my":
        "၁၉၉၀-၉၁ ပပင်လယ်ကွေ့စစ်ပွဲ၏ ဖြစ်ပွားရသည့် အကြောင်းရင်းများ၊ ဖြစ်စဉ်များနှင့် နိုင်ငံတကာ သက်ရောက်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Regional Conflict",
    "title_en": "The Arab-Israeli Conflict (Overview)",
    "title_my": "အာရပ်-အစ္စရေး ပဋိပက္ခ (ခြုံငုံသုံးသပ်ချက်)",
    "topics": [
      "Creation of Israel (1948)",
      "Suez Crisis and Six-Day War",
      "Peace Efforts and Camp David",
    ],
    "description_en":
        "Explore key turning points in the Middle East conflict and international mediation efforts.",
    "description_my":
        "အရှေ့အလယ်ပိုင်း ပဋိပက္ခရှိ အဓိက လှည့်ကွက်များနှင့် နိုင်ငံတကာ ကြားဝင်စေ့စပ်မှု ကြိုးပမ်းချက်များကို စူးစမ်းမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Source Skills",
    "title_en": "Advanced Historical Source Analysis",
    "title_my": "အဆင့်မြင့် သမိုင်းဝင် အရင်းအမြစ် ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": [
      "Cross-referencing Sources",
      "Evaluating Reliability and Tone",
      "Detecting Bias",
    ],
    "description_en":
        "Master the skill of cross-referencing and evaluating historical sources for Paper 1 and 2 exams.",
    "description_my":
        "Paper 1 နှင့် 2 စာမေးပွဲများအတွက် သမိုင်းဝင် အရင်းအမြစ်များကို အပြန်အလှန် နှိုင်းယှဉ်စစ်ဆေးခြင်းနှင့် ယုံကြည်စိတ်ချရမှုကို အကဲဖြတ်ခြင်း ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Source Analysis Masterclass",
    "title_my": "အရင်းအမြစ် ခွဲခြမ်းစိတ်ဖြာမှု အထူးသင်ခန်းစာ",
    "topics": [
      "Handling Conflicting Sources",
      "Contextual Knowledge Application",
      "Exam Practice",
    ],
    "description_en":
        "Practice tackling complex, contradictory historical sources using precise contextual knowledge.",
    "description_my":
        "တိကျသော သမိုင်းနောက်ခံ အသိပညာကို အသုံးပြု၍ ရှုပ်ထွေးပြီး ဆန့်ကျင်ဘက်ဖြစ်သော သမိုင်းအရင်းအမြစ်များကို ကိုင်တွယ်ဖြေဆိုမည်။",
  },

  // ================= TERM 8: Exam Intensive - Paper 1 & Paper 2 (Source Work & Essays) =================
  {
    "week": 29,
    "term": 8,
    "theme": "Exam Intensive",
    "title_en": "Paper 1 (Core Content Essays) Intensive",
    "title_my":
        "Paper 1 (အဓိက အကြောင်းအရာ အက်ဆေးများ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Structuring 10-mark and 6-mark questions",
      "Analytical Explanations",
      "Time Management",
    ],
    "description_en":
        "Intensive practice for IGCSE History Paper 1, focusing on detailed historical explanations and structure.",
    "description_my":
        "အသေးစိတ် သမိုင်းရှင်းလင်းချက်များနှင့် ဖွဲ့စည်းပုံကို အဓိကထား၍ IGCSE History Paper 1 အတွက် အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Exam Intensive",
    "title_en": "Paper 2 (Source-Based Investigation) Intensive",
    "title_my":
        "Paper 2 (အရင်းအမြစ်အခြေပြု စုံစမ်းခြင်း) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Answering Source Question Sub-parts",
      "Evaluating Utility and Reliability",
      "Comparing Source Claims",
    ],
    "description_en":
        "Master answering source-based inquiry questions under strict timed examination conditions.",
    "description_my":
        "တင်းကျပ်သော စာမေးပွဲ အချိန်သတ်မှတ်ချက်အောက်တွင် အရင်းအမြစ်အခြေပြု စုံစမ်းမေးခွန်းများကို ဖြေဆိုနည်း ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Exam Intensive",
    "title_en": "Mark Scheme Diagnostics and Common Pitfalls",
    "title_my": "အမှတ်ပေးစည်းမျဉ်း သုံးသပ်ခြင်းနှင့် ရှောင်ရှားရန် အမှားများ",
    "topics": [
      "Examiner Report Insights",
      "Avoiding Descriptive Traps",
      "Writing Evaluative Conclusions",
    ],
    "description_en":
        "Analyze Cambridge examiner reports to avoid descriptive-only answers and secure top-band evaluation marks.",
    "description_my":
        "ဖော်ပြချက်သက်သက်သာ ပါဝင်သော အဖြေများကို ရှောင်ရှားရန်နှင့် အမြင့်ဆုံး အကဲဖြတ်အမှတ်များ ရယူရန် Cambridge စစ်ဆေးသူများ၏ အစီရင်ခံစာများကို လေ့လာမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Full Mock History Examinations",
    "title_my": "သမိုင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 2",
      "Comprehensive Grading",
    ],
    "description_en":
        "Complete full-length past paper mock examinations across Paper 1 and Paper 2.",
    "description_my":
        "Paper 1 နှင့် Paper 2 စာစောင်များအတွက် မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },

  // ================= TERM 9: Final Exam Countdown & Graduation =================
  {
    "week": 33,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "Targeted Weakness Remediation",
    "title_my": "အားနည်းချက်ရှိသော ကဏ္ဍများကို အထူးပြုပြင်ခြင်း",
    "topics": [
      "Personalised Past Paper Drills",
      "Chronology Refresher",
      "Targeted Source Practice",
    ],
    "description_en":
        "Target individual student weak points through intensive, personalized past-paper question drills.",
    "description_my":
        "အတိတ် မေးခွန်းဟောင်း လေ့ကျင့်ခန်းများမှတစ်ဆင့် တစ်ဦးချင်း အားနည်းချက် ရှိသော ကဏ္ဍများကို အထူးပြုပြင်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "Exam Stamina and Pacing Strategies",
    "title_my": "စာမေးပွဲ ခံနိုင်ရည်နှင့် အချိန်စီမံခန့်ခွဲမှု ဗျူဟာများ",
    "topics": [
      "Time Management for Essays",
      "Source Question Pacing",
      "Stress Management",
    ],
    "description_en":
        "Refine psychological endurance and time management strategies for the actual IGCSE History exams.",
    "description_my":
        "တကယ့် IGCSE သမိုင်းစာမေးပွဲရက်များအတွက် စိတ်ပိုင်းဆိုင်ရာ ခံနိုင်ရည်နှင့် အချိန်စီမံခန့်ခွဲမှု ဗျူဟာများကို ထက်မြက်စေမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Final Countdown",
    "title_en": "The Final Warm-Up Simulation",
    "title_my": "နောက်ဆုံး အကြိုလေ့ကျင့်ခန်း ပုံစံတူ ဖြေဆိုခြင်း",
    "topics": ["Light Practice Session", "Anxiety Reduction", "Final Review"],
    "description_en":
        "Participate in a final, low-stress simulated exam session to build unbreakable confidence.",
    "description_my":
        "စိတ်ဖိစီးမှုကင်းပြီး စာမေးပွဲ ယုံကြည်မှု အပြည့်အဝရရှိရန် နောက်ဆုံး အကြိုလေ့ကျင့်ခန်း စာမေးပွဲကို ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE History Graduation",
    "title_my": "IGCSE သမိုင်းပညာ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Historical Insight",
      "Pathways to A-Level History",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE History and preparation for advanced historical studies.",
    "description_my":
        "IGCSE သမိုင်းပညာ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး အဆင့်မြင့် သမိုင်းပညာ လေ့လာမှုများဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
