// File: ai_data_bridge/igcse_accounting_all_terms.dart
// IGCSE Accounting Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseAccountingAllTermsData = [
  // ================= TERM 1: Introduction to Bookkeeping and Double-Entry System =================
  {
    "week": 1,
    "term": 1,
    "theme": "Bookkeeping",
    "title_en": "The Role of Accounting and Business Documents",
    "title_my": "စာရင်းကိုင်ပညာ၏ အခန်းကဏ္ဍနှင့် စီးပွားရေး စာရွက်စာတမ်းများ",
    "topics": [
      "Purpose of Accounting",
      "Business Documents (Invoices, Credit/Debit Notes)",
      "Trade Discounts and Cash Discounts",
    ],
    "description_en":
        "Understand the fundamental purpose of accounting and how source documents initiate business transactions.",
    "description_my":
        "စာရင်းကိုင်ပညာ၏ အဓိက ရည်ရွယ်ချက်နှင့် စာရွက်စာတမ်းများက စီးပွားရေး ငွေပေးငွေယူများကို မည်သို့စတင်ကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Bookkeeping",
    "title_en": "The Double-Entry System of Bookkeeping",
    "title_my": "နှစ်ထပ် စာရင်းသွင်းခြင်း စနစ် (Double-Entry System)",
    "topics": [
      "The Accounting Equation (Assets = Capital + Liabilities)",
      "Debit and Credit Rules",
      "Recording Transactions in Ledger Accounts",
    ],
    "description_en":
        "Master the golden rules of double-entry bookkeeping and how to record transactions in ledger accounts.",
    "description_my":
        "နှစ်ထပ် စာရင်းသွင်းခြင်း၏ ရွှေစည်းမျဉ်းများနှင့် Ledger အကောင့်များတွင် ငွေပေးငွေယူများ မှတ်တမ်းတင်နည်းကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Bookkeeping",
    "title_en": "Ledger Accounts and Balancing",
    "title_my": "Ledger အကောင့်များနှင့် လက်ကျန်တွက်ချက်ခြင်း",
    "topics": [
      "Balancing Ledger Accounts",
      "Distinguishing Asset, Liability, and Capital Accounts",
      "Posting to Ledgers",
    ],
    "description_en":
        "Learn how to balance ledger accounts at the end of an accounting period and interpret balances.",
    "description_my":
        "စာရင်းပိတ်ကာလတွင် Ledger အကောင့်များ၏ လက်ကျန်ကို တွက်ချက်ခြင်းနှင့် လက်ကျန်များကို အဓိပ္ပာယ်ဖော်ခြင်း လေ့လာမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Trial Balance and Error Introduction",
    "title_my":
        "စာရင်းလက်ကျန် စစ်ဆေးချက် (Trial Balance) နှင့် အမှားများ မိတ်ဆက်",
    "topics": [
      "Purpose of Trial Balance",
      "Extracting Ledger Balances",
      "Identifying Types of Errors",
    ],
    "description_en":
        "Construct a trial balance from ledger accounts and understand its role in checking arithmetic accuracy.",
    "description_my":
        "Ledger အကောင့်များမှ Trial Balance တည်ဆောက်ခြင်းနှင့် ဂဏန်းသင်္ချာ တိကျမှုကို စစ်ဆေးရာတွင် ၎င်း၏ အခန်းကဏ္ဍကို နားလည်စေမည်။",
  },

  // ================= TERM 2: Books of Prime Entry and Cash Control =================
  {
    "week": 5,
    "term": 2,
    "theme": "Books of Prime Entry",
    "title_en": "Books of Prime Entry (Day Books)",
    "title_my": "မူလစာရင်းသွင်း စာအုပ်များ (Books of Prime Entry)",
    "topics": [
      "Sales and Purchases Journals",
      "Sales Returns and Purchases Returns Journals",
      "General Journal Entries",
    ],
    "description_en":
        "Record business transactions in books of prime entry before posting them to ledger accounts.",
    "description_my":
        "Ledger အကောင့်များသို့ မတင်မီ စီးပွားရေး ငွေပေးငွေယူများကို မူလစာရင်းသွင်း စာအုပ်များတွင် မှတ်တမ်းတင်မည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Books of Prime Entry",
    "title_en": "The Cash Book and Petty Cash Book",
    "title_my":
        "ငွေစာရင်းစာအုပ် (Cash Book) နှင့် ငွေအသေးစား စာအုပ် (Petty Cash Book)",
    "topics": [
      "Two-Column and Three-Column Cash Books",
      "Contra Entries",
      "Imprest System of Petty Cash",
    ],
    "description_en":
        "Manage cash and bank transactions using multi-column cash books and the imprest petty cash system.",
    "description_my":
        "ကလပ်စုံ ငွေစာရင်းစာအုပ်များနှင့် Imprest စနစ်သုံး ငွေအသေးစား စာအုပ်များကို အသုံးပြု၍ ငွေသားနှင့် ဘဏ်လုပ်ငန်းများကို စီမံမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Bank Reconciliation",
    "title_en": "Bank Reconciliation Statements",
    "title_my": "ဘဏ်စာရင်း ညှိနှိုင်းမှု ရှင်းတမ်းများ (Bank Reconciliation)",
    "topics": [
      "Updated Cash Book",
      "Unpresented Cheques and Deposits in Transit",
      "Reconciling Bank Statements",
    ],
    "description_en":
        "Reconcile cash book balances with bank statements by identifying timing differences and bank errors.",
    "description_my":
        "အချိန်ကွာခြားချက်နှင့် ဘဏ်အမှားများကို ဖော်ထုတ်ခြင်းဖြင့် ငွေစာရင်းစာအုပ်နှင့် ဘဏ်ရှင်းတမ်း လက်ကျန်များကို ညှိနှိုင်းမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Cash Control and Books Studio",
    "title_my": "ငွေကြေး ထိန်းချုပ်မှုနှင့် မူလစာရင်း အလုပ်ရုံ",
    "topics": [
      "Cash Book Adjustments",
      "Bank Reconciliation Practice",
      "Exam Problem Solving",
    ],
    "description_en":
        "Solve comprehensive cash book and bank reconciliation problems under exam conditions.",
    "description_my":
        "စာမေးပွဲ အခြေအနေများအောက်တွင် ပြည့်စုံသော ငွေစာရင်းစာအုပ်နှင့် ဘဏ်ညှိနှိုင်းမှု ပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 3: Verification of Accounting Records =================
  {
    "week": 9,
    "term": 3,
    "theme": "Verification",
    "title_en": "Control Accounts",
    "title_my": "ထိန်းချုပ် အကောင့်များ (Control Accounts)",
    "topics": [
      "Trade Receivables Control Account",
      "Trade Payables Control Account",
      "Contra Settlements and Refunds",
    ],
    "description_en":
        "Construct total trade receivables and payables control accounts to verify ledger accuracy and detect errors.",
    "description_my":
        "Ledger တိကျမှုကို စစ်ဆေးရန်နှင့် အမှားများကို ရှာဖွေရန် ရစာနှင့် ပေးစာ ထိန်းချုပ် အကောင့်များကို တည်ဆောက်မည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Verification",
    "title_en": "Correction of Errors and Suspense Accounts",
    "title_my":
        "အမှားများ ပြင်ဆင်ခြင်းနှင့် ယာယီအကောင့်များ (Suspense Accounts)",
    "topics": [
      "Errors Not Affecting Trial Balance",
      "Errors Affecting Trial Balance",
      "Using Suspense Accounts",
    ],
    "description_en":
        "Identify different types of accounting errors and use suspense accounts to correct trial balance imbalances.",
    "description_my":
        "စာရင်းကိုင် အမှားအမျိုးအစားများကို ခွဲခြားပြီး Trial Balance မညီမျှမှုကို ပြင်ဆင်ရန် Suspense accounts များကို အသုံးပြုမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Verification",
    "title_en": "Capital and Revenue Expenditure",
    "title_my": "အရင်းအနှီးနှင့် ဝင်ငွေဆိုင်ရာ ကုန်ကျစရိတ်များ",
    "topics": [
      "Distinction between Capital and Revenue Items",
      "Impact of Misclassification on Profits and Assets",
      "Adjusting Ledger Accounts",
    ],
    "description_en":
        "Understand the critical distinction between capital and revenue expenditures and their effect on financial statements.",
    "description_my":
        "အရင်းအနှီးနှင့် ဝင်ငွေ ကုန်ကျစရိတ်များကြား အဓိက ကွာခြားချက်နှင့် ဘဏ္ဍာရေး ရှင်းတမ်းအပေါ် သက်ရောက်မှုကို နားလည်စေမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Error Correction Masterclass",
    "title_my": "အမှားပြင်ဆင်ခြင်း အထူးသင်ခန်းစာ",
    "topics": [
      "Suspense Account Drill",
      "Corrected Profit Calculations",
      "Exam Practice",
    ],
    "description_en":
        "Master correcting complex bookkeeping errors and recalculating corrected net profit figures.",
    "description_my":
        "ရှုပ်ထွေးသော စာရင်းသွင်း အမှားများကို ပြင်ဆင်ခြင်းနှင့် အသားတင်အမြတ်ကို ပြန်လည်တွက်ချက်ခြင်း ကျွမ်းကျင်အောင် လုပ်မည်။",
  },

  // ================= TERM 4: Financial Statements - Sole Traders =================
  {
    "week": 13,
    "term": 4,
    "theme": "Financial Statements",
    "title_en": "Income Statements (Trading and Profit & Loss Accounts)",
    "title_my":
        "ဝင်ငွေ ရှင်းတမ်းများ (ကုန်သွယ်မှုနှင့် အမြတ်အရှုံး အကောင့်များ)",
    "topics": [
      "Calculating Gross Profit (Revenue less Cost of Sales)",
      "Calculating Profit for the Year",
      "Accounting Adjustments Intro",
    ],
    "description_en":
        "Prepare income statements for sole traders, determining gross and net profits accurately.",
    "description_my":
        "တစ်ဦးတည်းပိုင် လုပ်ငန်းများအတွက် ဝင်ငွေရှင်းတမ်းများကို ပြင်ဆင်ပြီး စုစုပေါင်းအမြတ်နှင့် အသားတင်အမြတ်ကို တိကျစွာ တွက်ချက်မည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Financial Statements",
    "title_en": "Statements of Financial Position",
    "title_my": "ဘဏ္ဍာရေး အနေအထား ရှင်းတမ်းများ (Balance Sheets)",
    "topics": [
      "Non-Current Assets and Current Assets",
      "Current Liabilities and Non-Current Liabilities",
      "Capital and Equity Structure",
    ],
    "description_en":
        "Construct statements of financial position to present business assets, liabilities, and capital.",
    "description_my":
        "လုပ်ငန်း၏ ပိုင်ဆိုင်မှုများ၊ တာဝန်ဝတ္တရားများနှင့် အရင်းအနှီးတို့ကို တင်ပြရန် ဘဏ္ဍာရေး အနေအထား ရှင်းတမ်းများကို တည်ဆောက်မည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Adjustments",
    "title_en": "Year-End Adjustments: Accruals and Prepayments",
    "title_my":
        "နှစ်ပိတ် ချိန်ညှိချက်များ - ကျသင့်ငွေများ (Accruals) နှင့် ကြိုတင်ပေးငွေများ (Prepayments)",
    "topics": [
      "Accrued Expenses and Income",
      "Prepaid Expenses and Income",
      "Adjusting Ledger Accounts for Year-End",
    ],
    "description_en":
        "Adjust financial statements for expenses and revenues paid or received in advance or in arrears.",
    "description_my":
        "ကြိုတင်ပေး/ရ သို့မဟုတ် ပေးရန်ကျန် ငွေကြေးများအတွက် ဘဏ္ဍာရေး ရှင်းတမ်းများကို ချိန်ညှိပြင်ဆင်မည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Depreciation",
    "title_en": "Depreciation and Disposal of Non-Current Assets",
    "title_my":
        "စက်ပစ္စည်း/ပိုင်ဆိုင်မှုများ တန်ဖိုးလျော့ခြင်း (Depreciation) နှင့် ရောင်းချစွန့်ပစ်ခြင်း",
    "topics": [
      "Causes of Depreciation",
      "Straight-Line, Reducing Balance, and Revaluation Methods",
      "Disposal Account Entries",
    ],
    "description_en":
        "Calculate depreciation using various methods and record non-current asset disposals in ledger accounts.",
    "description_my":
        "နည်းလမ်းအမျိုးမျိုးသုံး၍ တန်ဖိုးလျော့ခြင်းကို တွက်ချက်ခြင်းနှင့် ပိုင်ဆိုင်မှု စွန့်ပစ်ခြင်းများကို Ledger တွင် မှတ်တမ်းတင်မည်။",
  },

  // ================= TERM 5: Accounting Adjustments and Year-End Extensions =================
  {
    "week": 17,
    "term": 5,
    "theme": "Adjustments",
    "title_en": "Bad Debts and Provision for Doubtful Debts",
    "title_my":
        "ကြွေးဆိုးများ (Bad Debts) နှင့် သံသယဖြစ်ဖွယ် ကြွေးမြီအတွက် လျာထားချက် (Provision)",
    "topics": [
      "Writing Off Bad Debts",
      "Creating and Adjusting Provision for Doubtful Debts",
      "Presentation in Financial Statements",
    ],
    "description_en":
        "Account for irrecoverable debts and maintain provisions for doubtful debts at year-end.",
    "description_my":
        "မရနိုင်တော့သော ကြွေးမြီများကို စာရင်းဖျက်ခြင်းနှင့် သံသယဖြစ်ဖွယ် ကြွေးမြီ လျာထားချက်များကို နှစ်ပိတ်တွင် ထိန်းသိမ်းမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Inventory",
    "title_en": "Inventory Valuation",
    "title_my": "ကုန်ပစ္စည်းလက်ကျန် တန်ဖိုးဖြတ်ခြင်း (Inventory Valuation)",
    "topics": [
      "IAS 2 Valuation Rule (Lower of Cost and Net Realisable Value)",
      "Calculating Inventory Value",
      "Impact on Profit",
    ],
    "description_en":
        "Value inventory correctly at the lower of cost and net realisable value and assess profit impacts.",
    "description_my":
        "ကုန်ကျစရိတ်နှင့် ရောင်းထွက်နိုင်သည့် တန်ဖိုးတို့အနက် နိမ့်ရာကို အသုံးပြု၍ ကုန်လက်ကျန် တန်ဖိုးဖြတ်ခြင်းကို လေ့လာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Financial Statements",
    "title_en": "Comprehensive Financial Statements for Sole Traders",
    "title_my":
        "တစ်ဦးတည်းပိုင် လုပ်ငန်းများအတွက် ပြည့်စုံသော ဘဏ္ဍာရေး ရှင်းတမ်းများ",
    "topics": [
      "Integrating All Adjustments",
      "Drafting Complete Income Statement and Statement of Financial Position",
      "Exam Practice",
    ],
    "description_en":
        "Prepare complete financial statements incorporating multiple year-end adjustments simultaneously.",
    "description_my":
        "နှစ်ပိတ် ချိန်ညှိချက်များ အားလုံးကို တစ်ပြိုင်နက် ထည့်သွင်းလျက် ပြည့်စုံသော ဘဏ္ဍာရေး ရှင်းတမ်းများကို ပြင်ဆင်မည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Sole Trader Financial Statements Studio",
    "title_my": "တစ်ဦးတည်းပိုင် လုပ်ငန်း ဘဏ္ဍာရေး ရှင်းတမ်းများ အလုပ်ရုံ",
    "topics": [
      "Full Adjustments Drill",
      "Complex Balance Sheet Preparation",
      "Exam Revision",
    ],
    "description_en":
        "Tackle full-scale sole trader financial statement problems mirroring IGCSE Paper 2 standards.",
    "description_my":
        "IGCSE Paper 2 စံနှုန်းများနှင့် ကိုက်ညီသော တစ်ဦးတည်းပိုင် လုပ်ငန်း ဘဏ္ဍာရေး ရှင်းတမ်း မေးခွန်းအပြည့်အစုံကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 6: Specialised Accounts - Partnerships and Clubs =================
  {
    "week": 21,
    "term": 6,
    "theme": "Partnerships",
    "title_en": "Partnership Accounts: Appropriation",
    "title_my":
        "အဖွဲအစည်း/လုပ်ငန်းဖက်စပ် အကောင့်များ - အမြတ်ခွဲဝေမှု (Appropriation)",
    "topics": [
      "Partnership Agreements",
      "Interest on Capital, Interest on Drawings, and Salaries",
      "Profit and Loss Appropriation Account",
    ],
    "description_en":
        "Account for partnership formations, profit-sharing agreements, and appropriation accounts.",
    "description_my":
        "လုပ်ငန်းဖက်စပ် သဘောတူညီချက်များ၊ အမြတ်ခွဲဝေမှုနှင့် Appropriation အကောင့်များကို စာရင်းသွင်းခြင်း လေ့လာမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Partnerships",
    "title_en": "Partnership Current and Capital Accounts",
    "title_my":
        "လုပ်ငန်းဖက်စပ် လက်ကျန် အကောင့်များနှင့် အရင်းအနှီး အကောင့်များ",
    "topics": [
      "Capital Accounts (Fixed vs Fluctuating)",
      "Current Accounts",
      "Partnership Statements of Financial Position",
    ],
    "description_en":
        "Maintain separate capital and current accounts for partners and prepare final statements.",
    "description_my":
        "ဖက်စပ်လုပ်ငန်းများအတွက် အရင်းအနှီးနှင့် လက်ကျန် အကောင့်များကို သီးသန့်ထားရှိပြီး နောက်ဆုံးရှင်းတမ်းများ ပြင်ဆင်မည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Clubs and Societies",
    "title_en": "Accounts of Clubs and Societies",
    "title_my":
        "အသင်းအဖွဲ့များနှင့် အသင်းအစည်းများ၏ စာရင်းများ (Clubs & Societies)",
    "topics": [
      "Receipts and Payments Account",
      "Subscription Accounts",
      "Income and Expenditure Account",
    ],
    "description_en":
        "Prepare non-profit financial records, subscription accounts, and income and expenditure statements.",
    "description_my":
        "အမြတ်အစွန်း မယူသော အသင်းအဖွဲ့များအတွက် ဝင်ငွေ/ထွက်ငွေ ရှင်းတမ်းများနှင့် စာရင်းများကို ပြင်ဆင်မည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Partnerships and Clubs Studio",
    "title_my": "ဖက်စပ်လုပ်ငန်းနှင့် အသင်းအဖွဲ့ စာရင်းများ အလုပ်ရုံ",
    "topics": [
      "Partnership Final Accounts Drill",
      "Club Subscription Adjustments",
      "Exam Practice",
    ],
    "description_en":
        "Solve complex partnership and non-profit organization accounting problems.",
    "description_my":
        "ရှုပ်ထွေးသော ဖက်စပ်လုပ်ငန်းနှင့် အမြတ်မယူသော အဖွဲ့အစည်း စာရင်းကိုင် ပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 7: Manufacturing and Limited Company Accounts =================
  {
    "week": 25,
    "term": 7,
    "theme": "Manufacturing",
    "title_en": "Manufacturing Accounts",
    "title_my": "ကုန်ထုတ်လုပ်မှု အကောင့်များ (Manufacturing Accounts)",
    "topics": [
      "Direct and Indirect Costs (Overheads)",
      "Cost of Production",
      "Factory Profit Calculation",
    ],
    "description_en":
        "Calculate prime cost, production cost, and factory profit for manufacturing businesses.",
    "description_my":
        "ကုန်ထုတ်လုပ်မှု လုပ်ငန်းများအတွက် မူလကုန်ကျစရိတ်၊ ထုတ်လုပ်မှု ကုန်ကျစရိတ်နှင့် စက်ရုံအမြတ်ကို တွက်ချက်မည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Limited Companies",
    "title_en": "Introduction to Limited Company Accounts",
    "title_my": "လီမိတက် ကုမ္ပဏီ စာရင်းများ မိတ်ဆက် (Limited Companies)",
    "topics": [
      "Share Capital and Reserves",
      "Debentures and Loan Notes",
      "Dividends and Retained Earnings",
    ],
    "description_en":
        "Understand corporate capital structures, share issues, and basic limited company financial terminology.",
    "description_my":
        "ကော်ပိုရိတ် အရင်းအနှီး ဖွဲ့စည်းပုံ၊ ရှယ်ယာထုတ်ဝေမှုနှင့် လီမိတက်ကုမ္ပဏီ စာရင်းကိုင် ဝေါဟာရများကို နားလည်စေမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Limited Companies",
    "title_en": "Financial Statements for Limited Companies",
    "title_my": "လီမိတက် ကုမ္ပဏီများအတွက် ဘဏ္ဍာရေး ရှင်းတမ်းများ",
    "topics": [
      "Company Income Statements",
      "Statements of Changes in Equity",
      "Company Statements of Financial Position",
    ],
    "description_en":
        "Prepare standard financial statements for limited liability companies.",
    "description_my":
        "တာဝန်ခံမှု အကန့်အသတ်ရှိသော ကုမ္ပဏီများအတွက် စံဘဏ္ဍာရေး ရှင်းတမ်းများကို ပြင်ဆင်မည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Manufacturing & Corporate Accounts Studio",
    "title_my": "ကုန်ထုတ်လုပ်မှုနှင့် ကော်ပိုရိတ် စာရင်းများ အလုပ်ရုံ",
    "topics": [
      "Manufacturing Cost Drill",
      "Company Statement Preparation",
      "Exam Practice",
    ],
    "description_en":
        "Complete structured exercises covering manufacturing cost statements and corporate financial reporting.",
    "description_my":
        "ကုန်ထုတ်လုပ်မှု ကုန်ကျစရိတ် ရှင်းတမ်းများနှင့် ကော်ပိုရိတ် ဘဏ္ဍာရေး အစီရင်ခံစာများ ပါဝင်သော လေ့ကျင့်ခန်းများကို လုပ်ဆောင်မည်။",
  },

  // ================= TERM 8: Incomplete Records and Accounting Ratios =================
  {
    "week": 29,
    "term": 8,
    "theme": "Incomplete Records",
    "title_en": "Incomplete Records",
    "title_my": "မပြည့်စုံသော စာရင်းများ (Incomplete Records)",
    "topics": [
      "Finding Missing Figures using Accounting Equations",
      "Mark-up and Margin Calculations",
      "Statement of Affairs",
    ],
    "description_en":
        "Reconstruct missing financial figures and calculate profit from incomplete bookkeeping records.",
    "description_my":
        "စာရင်းကိုင်ညီမျှခြင်းများကို သုံး၍ ပျောက်ဆုံးနေသော ကိန်းဂဏန်းများကို ရှာဖွေပြီး အမြတ်အစွန်း တွက်ချက်မည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Accounting Ratios",
    "title_en": "Accounting Ratios: Profitability",
    "title_my": "စာရင်းကိုင် အချိုးအစားများ - အမြတ်အစွန်း ဆိုင်ရာ အချိုးများ",
    "topics": [
      "Gross Margin and Profit Margin",
      "Return on Capital Employed (ROCE)",
      "Interpreting Profitability Ratios",
    ],
    "description_en":
        "Calculate and evaluate profitability ratios to assess business operational performance.",
    "description_my":
        "လုပ်ငန်း စွမ်းဆောင်ရည်ကို အကဲဖြတ်ရန် အမြတ်အစွန်းဆိုင်ရာ အချိုးများကို တွက်ချက်ပြီး အကဲဖြတ်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Accounting Ratios",
    "title_en": "Accounting Ratios: Liquidity and Efficiency",
    "title_my":
        "စာရင်းကိုင် အချိုးအစားများ - ငွေဖြစ်လွယ်မှုနှင့် ထိရောက်မှု ဆိုင်ရာ အချိုးများ",
    "topics": [
      "Current Ratio and Quick (Acid Test) Ratio",
      "Rate of Inventory Turnover",
      "Trade Receivables and Payables Turnover Days",
    ],
    "description_en":
        "Analyze liquidity, working capital management, and efficiency ratios for business health.",
    "description_my":
        "လုပ်ငန်းကျန်းမာရေးအတွက် ငွေဖြစ်လွယ်မှု၊ လုပ်ငန်းသုံး ငွေသား စီမံခန့်ခွဲမှုနှင့် ထိရောက်မှု အချိုးများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Ratio Analysis and Incomplete Records Studio",
    "title_my":
        "အချိုး ခွဲခြမ်းစိတ်ဖြာမှုနှင့် မပြည့်စုံသော စာရင်းများ အလုပ်ရုံ",
    "topics": [
      "Ratio Interpretation Task",
      "Incomplete Records Reconstruction",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate business performance using financial ratios and reconstruct records from sparse data.",
    "description_my":
        "ဘဏ္ဍာရေး အချိုးများကို အသုံးပြု၍ လုပ်ငန်းစွမ်းဆောင်ရည်ကို အကဲဖြတ်ပြီး အချက်အလက် အနည်းငယ်မှ စာရင်းများကို ပြန်လည်တည်ဆောက်မည်။",
  },

  // ================= TERM 9: Exam Prep & Final Countdown =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Multiple Choice) Intensive",
    "title_my": "Paper 1 (ရွေးချယ်ရန် မေးခွန်းများ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "MCQ Strategies",
      "Bookkeeping Calculations Drill",
      "Quick Definitions Review",
    ],
    "description_en":
        "Master multiple-choice question techniques and fast-paced bookkeeping calculations for Paper 1.",
    "description_my":
        "Paper 1 အတွက် ရွေးချယ်ရန် မေးခွန်း ဖြေဆိုနည်းများနှင့် အမြန်နှုန်းဖြင့် စာရင်းကိုင် တွက်ချက်မှုများကို လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 2 (Structured Questions & Statements) Mastery",
    "title_my":
        "Paper 2 (ပုံစံကျ မေးခွန်းများနှင့် ရှင်းတမ်းများ) ကျွမ်းကျင်မှု",
    "topics": [
      "Full Financial Statement Drills",
      "Error Correction Practice",
      "Time Management",
    ],
    "description_en":
        "Intensive practice on preparing full financial statements and structured accounting questions.",
    "description_my":
        "ဘဏ္ဍာရေး ရှင်းတမ်းအပြည့်အစုံ ပြင်ဆင်ခြင်းနှင့် ပုံစံကျ စာရင်းကိုင် မေးခွန်းများကို အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Past Paper Mock Examinations",
    "title_my": "မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 2",
      "Mark Scheme Diagnostics",
    ],
    "description_en":
        "Complete full-length past paper mock examinations under rigorous timed conditions.",
    "description_my":
        "တင်းကျပ်သော အချိန်သတ်မှတ်ချက်များအောက်တွင် မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Accounting Graduation",
    "title_my": "IGCSE စာရင်းကိုင်ပညာ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Financial Literacy",
      "Pathways to Advanced Accounting",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Accounting and preparation for professional financial studies.",
    "description_my":
        "IGCSE စာရင်းကိုင်ပညာ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး ပညာရှင်အဆင့် ဘဏ္ဍာရေး လေ့လာမှုများဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
