// File: ai_data_bridge/igcse_ict_all_terms.dart
// IGCSE Information and Communication Technology (ICT) Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseIctAllTermsData = [
  // ================= TERM 1: Hardware, Software and Components =================
  {
    "week": 1,
    "term": 1,
    "theme": "Hardware & Software",
    "title_en": "Types and Components of Computer Systems",
    "title_my": "ကွန်ပျူတာ စနစ်များ၏ အမျိုးအစားများနှင့် အစိတ်အပိုင်းများ",
    "topics": [
      "Hardware vs Software",
      "Mainframe, Desktop, Laptop, and Mobile Devices",
      "CPU, RAM, ROM, and Backing Storage",
    ],
    "description_en":
        "Examine the hardware and software components making up various computer systems and their specific uses.",
    "description_my":
        "ကွန်ပျူတာစနစ် အမျိုးမျိုးကို ဖွဲ့စည်းထားသည့် ဟာ့ဒ်ဝဲနှင့် ဆော့ဖ်ဝဲ အစိတ်အပိုင်းများနှင့် ၎င်းတို့၏ အသုံးဝင်ပုံများကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Hardware",
    "title_en": "Input and Output Devices",
    "title_my": "ထည့်သွင်းခြင်း (Input) နှင့် ထုတ်ပေးခြင်း (Output) ကိရိယာများ",
    "topics": [
      "Keyboards, Mice, Scanners, and Sensors",
      "Screens, Printers, and Actuators",
      "Choosing Devices for Specific Applications",
    ],
    "description_en":
        "Analyze input and output devices and select appropriate hardware for specific real-world scenarios.",
    "description_my":
        "အထွက်/အသွင်း ကိရိယာများကို ခွဲခြမ်းစိတ်ဖြာပြီး လက်တွေ့အခြေအနေ အသီးသီးအတွက် သင့်လျော်သော ဟာ့ဒ်ဝဲကို ရွေးချယ်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Storage",
    "title_en": "Storage Devices and Media",
    "title_my": "သိုလှောင်သည့် ကိရိယာများနှင့် မီဒီယာများ",
    "topics": [
      "Magnetic Storage (HDDs)",
      "Optical Storage (CD, DVD, Blu-ray)",
      "Solid State Storage (SSDs, Flash Memory)",
    ],
    "description_en":
        "Compare storage technologies based on capacity, speed, volatility, and portability.",
    "description_my":
        "သိုလှောင်မှု ပမာဏ၊ အမြန်နှုန်းနှင့် သယ်ဆောင်ရလွယ်ကူမှုအပေါ် မူတည်၍ သိုလှောင်မှု နည်းပညာများကို နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Hardware & Systems Audit Studio",
    "title_my": "ဟာ့ဒ်ဝဲနှင့် စနစ်များ စစ်ဆေးခြင်း အလုပ်ရုံ",
    "topics": [
      "System Specifications Evaluation",
      "Hardware Selection Scenarios",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate computer system specifications for various business and personal requirements.",
    "description_my":
        "လုပ်ငန်းနှင့် ကိုယ်ပိုင် လိုအပ်ချက်များအတွက် ကွန်ပျူတာစနစ် သတ်မှတ်ချက်များကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 2: Networks, Communication and Internet =================
  {
    "week": 5,
    "term": 2,
    "theme": "Networks",
    "title_en": "Networks and the Internet",
    "title_my": "ကွန်ရက်များနှင့် အင်တာနက်",
    "topics": [
      "LAN, WAN, and WLAN Structures",
      "Network Hardware (Routers, Switches, NICs)",
      "Cloud Computing and Storage",
    ],
    "description_en":
        "Understand local and wide area network structures, network hardware, and cloud computing principles.",
    "description_my":
        "ဒေသန္တရနှင့် ကမ္ဘာ့ကွန်ရက် ဖွဲ့စည်းပုံများ၊ ကွန်ရက် ဟာ့ဒ်ဝဲများနှင့် ကလောက်ဒ် ကွန်ပျူတာ စနစ်များကို နားလည်စေမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Communication",
    "title_en": "Electronic Communication and Email",
    "title_my": "အီလက်ထရောနစ် ဆက်သွယ်ရေးနှင့် အီးမေးလ်",
    "topics": [
      "Email Structure and Protocols",
      "Benefits and Drawbacks of Electronic Communication",
      "Video Conferencing and VoIP",
    ],
    "description_en":
        "Examine email communication structures, protocols, and the mechanics of video conferencing.",
    "description_my":
        "အီးမေးလ် ဆက်သွယ်ရေး ဖွဲ့စည်းပုံများ၊ ပရိုတိုကောများနှင့် ဗီဒီယို ကွန်ဖရင့် လုပ်ဆောင်ပုံများကို လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Security",
    "title_en": "Data Safety, Security, and Privacy",
    "title_my": "အချက်အလက် လုံခြုံရေး၊ ဘေးကင်းမှုနှင့် ကိုယ်ရေးလုံခြုံမှု",
    "topics": [
      "Malware (Viruses, Spyware, Phishing)",
      "Security Measures (Passwords, Firewalls, Encryption)",
      "Data Backup Strategies",
    ],
    "description_en":
        "Analyze cybersecurity threats and implement safety measures to protect data integrity.",
    "description_my":
        "ဆိုက်ဘာလုံခြုံရေး ခြိမ်းခြောက်မှုများကို ခွဲခြမ်းစိတ်ဖြာပြီး အချက်အလက်များကို ကာကွယ်ရန် လုံခြုံရေး အစီအမံများကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Network Security Audit Studio",
    "title_my": "ကွန်ရက် လုံခြုံရေး စစ်ဆေးမှု အလုပ်ရုံ",
    "topics": [
      "Vulnerability Assessment",
      "Backup Plan Design",
      "Exam Practice",
    ],
    "description_en":
        "Design a secure network and data backup policy for an enterprise organization.",
    "description_my":
        "ကော်ပိုရိတ် အဖွဲ့အစည်းတစ်ခုအတွက် လုံခြုံသော ကွန်ရက်နှင့် ဒေတာ ဘက်ကပ် မူဝါဒကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 3: ICT Applications and Effects of Using IT =================
  {
    "week": 9,
    "term": 3,
    "theme": "ICT Applications",
    "title_en": "ICT Applications in Everyday Life",
    "title_my": "နေ့စဉ်ဘဝတွင် ICT အသုံးချမှုများ",
    "topics": [
      "Communication and Online Banking",
      "Online Shopping and Booking Systems",
      "Expert Systems in Medicine and Finance",
    ],
    "description_en":
        "Explore how ICT applications transform banking, retail, medicine, and public administration.",
    "description_my":
        "ဘဏ်လုပ်ငန်း၊ လက်လီအရောင်းအဝယ်၊ ဆေးပညာနှင့် အုပ်ချုပ်ရေးတို့တွင် ICT က မည်သို့ပြောင်းလဲကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Industrial Control",
    "title_en": "Microprocessor Control and Automated Systems",
    "title_my": "မိုက်ခရိုပရိုဆက်ဆာ ထိန်းချုပ်မှုနှင့် အလိုအလျောက် စနစ်များ",
    "topics": [
      "Sensors, Microprocessors, and Actuators",
      "Automatic Doors, Greenhouses, and Streetlights",
      "Monitoring vs Control Systems",
    ],
    "description_en":
        "Understand how sensors and microprocessors interact in automated monitoring and control systems.",
    "description_my":
        "အလိုအလျောက် စောင့်ကြည့် ထိန်းချုပ်ရေး စနစ်များတွင် ဆင်ဆာများနှင့် မိုက်ခရိုပရိုဆက်ဆာများ ချိတ်ဆက်ပုံကို နားလည်စေမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Effects of IT",
    "title_en": "The Effects of Using IT",
    "title_my": "IT အသုံးပြုခြင်း၏ သက်ရောက်မှုများ",
    "topics": [
      "Impact on Employment and Automation",
      "Microprocessor Health Issues (RSI, Eye Strain)",
      "Environmental Impacts of E-Waste",
    ],
    "description_en":
        "Evaluate social, health, and environmental impacts resulting from widespread IT adoption.",
    "description_my":
        "ကျယ်ပြန့်လာသော IT သုံးစွဲမှုကြောင့် လူမှုရေး၊ ကျန်းမာရေးနှင့် ပတ်ဝန်းကျင်အပေါ် သက်ရောက်မှုများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "ICT Applications & Effects Studio",
    "title_my": "ICT အသုံးချမှုနှင့် သက်ရောက်မှုများ အလုပ်ရုံ",
    "topics": [
      "Case Study Analysis",
      "Expert System Design Scenarios",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate complex case studies involving automated control systems and societal IT impacts.",
    "description_my":
        "အလိုအလျောက် ထိန်းချုပ်ရေး စနစ်များနှင့် လူ့အဖွဲ့အစည်းအပေါ် IT သက်ရောက်မှုများပါဝင်သော လက်တွေ့လေ့လာမှုများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 4: Practical Document Production (Word Processing) =================
  {
    "week": 13,
    "term": 4,
    "theme": "Document Production",
    "title_en": "Advanced Document Formatting and Styles",
    "title_my": "အဆင့်မြင့် စာရွက်စာတမ်း ဖော်မတ်ချခြင်းနှင့် စတိုင်လ်များ",
    "topics": [
      "Paragraph and Character Styles",
      "Headers, Footers, and Page Numbering",
      "Page Layouts and Section Breaks",
    ],
    "description_en":
        "Master professional word processing formatting, corporate styles, and multi-page layouts.",
    "description_my":
        "ပရော်ဖက်ရှင်နယ် စာရွက်စာတမ်း ဖော်မတ်ချခြင်း၊ ကော်ပိုရိတ် စတိုင်လ်များနှင့် စာမျက်နှာ အပြင်အဆင်များကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Document Production",
    "title_en": "Tables, Images, and Object Manipulation",
    "title_my": "ဇယားများ၊ ပုံများနှင့် အရာဝတ္ထုများကို ကိုင်တွယ်ခြင်း",
    "topics": [
      "Inserting and Formatting Tables",
      "Image Resizing, Cropping, and Text Wrapping",
      "Bulleting and Numbered Lists",
    ],
    "description_en":
        "Integrate and format tables, images, and lists seamlessly into complex documents.",
    "description_my":
        "ရှုပ်ထွေးသော စာရွက်စာတမ်းများအတွင်း ဇယားများ၊ ပုံများနှင့် စာရင်းများကို ချောမွေ့စွာ ထည့်သွင်းဖော်မတ်ချမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Document Production",
    "title_en": "Mail Merge and Automated Documents",
    "title_my": "မေးလ်မာ့ချ် (Mail Merge) နှင့် အလိုအလျောက် စာရွက်စာတမ်းများ",
    "topics": [
      "Connecting Data Sources to Master Letters",
      "Creating Labels and Certificates",
      "Conditional Mail Merge Fields",
    ],
    "description_en":
        "Execute mail merge procedures to produce personalised batch documents efficiently.",
    "description_my":
        "ပုဂ္ဂိုလ်ရေးသီးသန့် အစုလိုက် စာရွက်စာတမ်းများကို ထိရောက်စွာ ထုတ်လုပ်ရန် Mail Merge လုပ်ငန်းစဉ်များကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Document Production Timed Practical Studio",
    "title_my":
        "စာရွက်စာတမ်း ထုတ်လုပ်ရေး အချိန်ကိုက် လက်တွေ့စမ်းသပ်မှု အလုပ်ရုံ",
    "topics": [
      "Timed Practical Assessment",
      "Error-checking and Proofing",
      "Exam Simulation",
    ],
    "description_en":
        "Produce a fully formatted professional corporate report under timed practical exam conditions.",
    "description_my":
        "အချိန်ကိုက် လက်တွေ့စာမေးပွဲ အခြေအနေများအောက်တွင် ပြီးပြည့်စုံသော ပရော်ဖက်ရှင်နယ် ကော်ပိုရိတ် အစီရင်ခံစာကို ထုတ်လုပ်မည်။",
  },

  // ================= TERM 5: Practical Data Manipulation (Spreadsheets) =================
  {
    "week": 17,
    "term": 5,
    "theme": "Spreadsheets",
    "title_en": "Spreadsheet Creation and Referencing",
    "title_my":
        "စပရက်ရှိက် (Spreadsheet) တည်ဆောက်ခြင်းနှင့် ဆက်စပ်ကိုးကားခြင်း",
    "topics": [
      "Cell Formatting and Data Types",
      "Absolute vs Relative Cell Referencing",
      "Basic Arithmetic Operations",
    ],
    "description_en":
        "Build structured spreadsheets using correct cell referencing and professional formatting rules.",
    "description_my":
        "မှန်ကန်သော ဆက်စပ်ကိုးကားမှုများနှင့် ပရော်ဖက်ရှင်နယ် ဖော်မတ်စည်းမျဉ်းများကို သုံး၍ စပရက်ရှိက်များကို တည်ဆောက်မည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Spreadsheets",
    "title_en": "Mathematical and Logical Functions",
    "title_my": "သင်္ချာနှင့် ယုတ္တိဗေဒ ဖန်ရှင်များ",
    "topics": [
      "SUM, AVERAGE, MIN, MAX, COUNT",
      "Logical IF and Nested IF Functions",
      "VLOOKUP and XLOOKUP Data Retrieval",
    ],
    "description_en":
        "Master advanced spreadsheet functions for data extraction, automated calculation, and logical evaluation.",
    "description_my":
        "ဒေတာ ထုတ်နုတ်ရန်၊ အလိုအလျောက် တွက်ချက်ရန်နှင့် ယုတ္တိတန်သော အကဲဖြတ်မှုအတွက် အဆင့်မြင့် စပရက်ရှိက် ဖန်ရှင်များကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Spreadsheets",
    "title_en": "Data Sorting, Filtering, and Charting",
    "title_my": "ဒေတာ စီစဥ်ခြင်း၊ စစ်ထုတ်ခြင်းနှင့် ဂရပ်များထုတ်လုပ်ခြင်း",
    "topics": [
      "Multi-level Data Sorting",
      "Advanced Filtering Rules",
      "Creating and Formatting Professional Charts",
    ],
    "description_en":
        "Analyze data using sorting and filtering tools, and present findings visually with professional charts.",
    "description_my":
        "စီစဥ်ခြင်းနှင့် စစ်ထုတ်ခြင်း ကိရိယာများကို သုံး၍ ဒေတာများကို ခွဲခြမ်းစိတ်ဖြာပြီး ပရော်ဖက်ရှင်နယ် ဂရပ်များဖြင့် တင်ပြမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Spreadsheet Modeling Studio",
    "title_my": "စပရက်ရှိက် မော်ဒယ်လ် တည်ဆောက်ရေး အလုပ်ရုံ",
    "topics": [
      "Complex Financial Model Build",
      "Formula Debugging",
      "Exam Practice",
    ],
    "description_en":
        "Design and test a complex automated financial spreadsheet model for business forecasting.",
    "description_my":
        "စီးပွားရေး ခန့်မှန်းချက်များအတွက် ရှုပ်ထွေးပြီး အလိုအလျောက် တွက်ချက်ပေးသော ဘဏ္ဍာရေး စပရက်ရှိက် မော်ဒယ်ကို ဒီဇိုင်းဆွဲ စမ်းသပ်မည်။",
  },

  // ================= TERM 6: Practical Database Manipulation (Access) =================
  {
    "week": 21,
    "term": 6,
    "theme": "Databases",
    "title_en": "Database Design and Table Creation",
    "title_my": "ဒေတာဘေ့စ် ဒီဇိုင်းနှင့် ဇယားများ တည်ဆောက်ခြင်း",
    "topics": [
      "Tables, Records, and Fields",
      "Data Types (Text, Numeric, Date, Boolean)",
      "Primary Keys and Data Integrity",
    ],
    "description_en":
        "Design relational database structures, assign appropriate data types, and establish primary keys.",
    "description_my":
        "ဆက်စပ် ဒေတာဘေ့စ် ဖွဲ့စည်းပုံများကို ဒီဇိုင်းဆွဲခြင်း၊ သင့်လျော်သော ဒေတာ အမျိုးအစားများကို သတ်မှတ်ခြင်းနှင့် Primary keys များ ထည့်သွင်းမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Databases",
    "title_en": "Data Entry, Forms, and Validation",
    "title_my":
        "ဒေတာ ထည့်သွင်းခြင်း၊ ဖောင်များ (Forms) နှင့် မှန်ကန်မှု စစ်ဆေးခြင်း",
    "topics": [
      "Designing User-friendly Data Entry Forms",
      "Validation Rules and Presence Checks",
      "Masking and Formatting Input Data",
    ],
    "description_en":
        "Implement data validation rules and design efficient data entry forms to maintain database accuracy.",
    "description_my":
        "ဒေတာ မှန်ကန်မှုကို ထိန်းသိမ်းရန် Validation စည်းမျဉ်းများကို အကောင်အထည်ဖော်ပြီး အသုံးပြုရ လွယ်ကူသော ဒေတာသွင်းဖောင်များကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Databases",
    "title_en": "Advanced Queries and Reports",
    "title_my": "အဆင့်မြင့် ကွီရီများ (Queries) နှင့် အစီရင်ခံစာများ (Reports)",
    "topics": [
      "Multi-criteria Queries (AND, OR, Wildcards)",
      "Calculated Fields in Queries",
      "Designing Grouped Reports",
    ],
    "description_en":
        "Extract specific records using complex queries and format professional database summary reports.",
    "description_my":
        "ရှုပ်ထွေးသော ကွီရီများကို သုံး၍ သီးခြား မှတ်တမ်းများကို ထုတ်နုတ်ပြီး ပရော်ဖက်ရှင်နယ် ဒေတာဘေ့စ် အကျဉ်းချုပ် အစီရင်ခံစာများကို ပြင်ဆင်မည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Relational Database Project Studio",
    "title_my": "ဆက်စပ် ဒေတာဘေ့စ် ပရောဂျက် အလုပ်ရုံ",
    "topics": [
      "Full Database Build",
      "Complex Query Testing",
      "Exam Simulation",
    ],
    "description_en":
        "Build a complete multi-table relational database system with forms, queries, and reports.",
    "description_my":
        "ဖောင်များ၊ ကွီရီများနှင့် အစီရင်ခံစာများ ပါဝင်သော ဇယားပေါင်းစုံ ဆက်စပ် ဒေတာဘေ့စ်စနစ် အပြည့်အစုံကို တည်ဆောက်မည်။",
  },

  // ================= TERM 7: Practical Web Authoring (HTML & CSS) =================
  {
    "week": 25,
    "term": 7,
    "theme": "Web Authoring",
    "title_en": "HTML Structure and Headings",
    "title_my": "HTML ဖွဲ့စည်းပုံနှင့် ခေါင်းစဉ်များ",
    "topics": [
      "HTML Document Structure (<html>, <head>, <body>)",
      "Headings, Paragraphs, and Lists",
      "Inserting Images and Alternate Text",
    ],
    "description_en":
        "Write clean, structured HTML markup for basic web page creation.",
    "description_my":
        "အခြေခံ ဝဘ်စာမျက်နှာများ ဖန်တီးရန် သန့်ရှင်းပြီး ဖွဲ့စည်းပုံကျသော HTML markup များကို ရေးသားမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Web Authoring",
    "title_en": "Tables, Hyperlinks, and Anchors",
    "title_my": "ဇယားများ၊ ဟိုက်ပါလင့်များ (Hyperlinks) နှင့် အန်ကာများ",
    "topics": [
      "Creating HTML Tables with Borders and Spans",
      "Hyperlinks to External Pages and Email Addresses",
      "Anchor Links for Page Navigation",
    ],
    "description_en":
        "Incorporate tables and hyperlinks into web pages to build interactive site navigation.",
    "description_my":
        "အပြန်အလှန် ချိတ်ဆက်မှုရှိသော ဆိုက်လမ်းညွှန်များကို တည်ဆောက်ရန် ဝဘ်စာမျက်နှာများတွင် ဇယားများနှင့် လင့်ခ်များကို ထည့်သွင်းမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Web Authoring",
    "title_en": "Cascading Style Sheets (CSS)",
    "title_my": "စတိုင်ရှာ ထည့်သွင်းခြင်း (CSS)",
    "topics": [
      "Inline, Internal, and External CSS Styles",
      "Styling Fonts, Colors, and Backgrounds",
      "Box Model and Element Positioning",
    ],
    "description_en":
        "Apply CSS styling rules to control visual layout, fonts, and colors across web pages.",
    "description_my":
        "ဝဘ်စာမျက်နှာများတစ်လျှောက် အမြင်အာရုံ အပြင်အဆင်၊ ဖောင့်နှင့် အရောင်များကို ထိန်းချုပ်ရန် CSS စတိုင်လ် စည်းမျဉ်းများကို အသုံးချမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Responsive Web Publishing Studio",
    "title_my": "တုံ့ပြန်မှုရှိသော ဝဘ်ထုတ်ဝေမှု အလုပ်ရုံ",
    "topics": [
      "Multi-page Website Build",
      "CSS Layout Validation",
      "Exam Practice",
    ],
    "description_en":
        "Design, code, and publish a multi-page styled website adhering to IGCSE web authoring standards.",
    "description_my":
        "IGCSE ဝဘ်ဒီဇိုင်း စံနှုန်းများနှင့် ကိုက်ညီသော စာမျက်နှာစုံပါရှိသည့် စတိုင်လ်ကျသော ဝဘ်ဆိုဒ်ကို ဒီဇိုင်းဆွဲပြီး ရေးသားမည်။",
  },

  // ================= TERM 8: Presentations & Integrated Practical Skills =================
  {
    "week": 29,
    "term": 8,
    "theme": "Presentations",
    "title_en": "Presentation Software and Multimedia",
    "title_my": "တင်ဆက်မှု ဆော့ဖ်ဝဲနှင့် မာလ်တီမီဒီယာ (Presentations)",
    "topics": [
      "Master Slide Creation and Consistent Formatting",
      "Animations and Transition Effects",
      "Integrating Audio, Video, and Graphs",
    ],
    "description_en":
        "Design professional slide presentations incorporating master slides and multimedia elements.",
    "description_my":
        "မာစတာ ဆလိုက်များနှင့် မာလ်တီမီဒီယာ အစိတ်အပိုင်းများပါဝင်သော ပရော်ဖက်ရှင်နယ် ဆလိုက် တင်ဆက်မှုများကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Integration",
    "title_en": "Data Integration Across Applications",
    "title_my": "အပလီကေးရှင်းများကြား ဒေတာ ပေါင်းစပ်ခြင်း",
    "topics": [
      "Importing Spreadsheet Tables into Documents",
      "Exporting Database Data into Reports",
      "File Management and Formats",
    ],
    "description_en":
        "Seamlessly exchange data between spreadsheets, databases, and word processing documents.",
    "description_my":
        "စပရက်ရှိက်များ၊ ဒေတာဘေ့စ်များနှင့် စာရွက်စာတမ်းများကြား ဒေတာများကို ချောမွေ့စွာ ဖလှယ်ခြင်း ပြုလုပ်မည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Practical Skills",
    "title_en": "Practical Paper Strategies and File Management",
    "title_my": "လက်တွေ့ စာမေးပွဲ ဗျူဟာများနှင့် ဖိုင်စီမံခန့်ခွဲမှု",
    "topics": [
      "Evidence Document Creation",
      "Screenshot Capturing and Cropping",
      "File Naming Conventions",
    ],
    "description_en":
        "Master evidence document compilation and rigorous file management for practical examinations.",
    "description_my":
        "လက်တွေ့ စာမေးပွဲများအတွက် သက်သေပြစာရွက်စာတမ်း စုစည်းမှုနှင့် တိကျသေချာသော ဖိုင်စီမံခန့်ခွဲမှုကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Full Practical Paper Simulation Studio",
    "title_my": "လက်တွေ့စာစောင် အပြည့်အစုံ ပုံစံတူ စာမေးပွဲ အလုပ်ရုံ",
    "topics": [
      "Timed Practical Assessment (Paper 2 & 3)",
      "Integrated Multi-app Tasks",
      "Exam Review",
    ],
    "description_en":
        "Complete full-length timed practical assessment papers simulating official IGCSE ICT standards.",
    "description_my":
        "တရားဝင် IGCSE ICT စံနှုန်းများနှင့် အတူတူဖြစ်သော အချိန်ကိုက် လက်တွေ့စာမေးပွဲ စာစောင်များကို အစအဆုံး ဖြေဆိုမည်။",
  },

  // ================= TERM 9: Theory Prep and Final Graduation =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Theory) Comprehensive Review",
    "title_my": "Paper 1 (သီအိုရီ) ခြုံငုံသုံးသပ် လေ့ကျင့်ခန်း",
    "topics": [
      "Hardware and Software Revision",
      "Networks and Security Drills",
      "ICT Applications Recap",
    ],
    "description_en":
        "Intensive drilling of theoretical concepts, hardware systems, and security principles for Paper 1.",
    "description_my":
        "Paper 1 အတွက် သီအိုရီ သဘောတရားများ၊ ဟာ့ဒ်ဝဲ စနစ်များနှင့် လုံခြုံရေး မူဝါဒများကို အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 2 (Document Production & Databases) Intensive",
    "title_my":
        "Paper 2 (စာရွက်စာတမ်း ထုတ်လုပ်မှုနှင့် ဒေတာဘေ့စ်) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Advanced Word Processing Drills",
      "Complex Database Query Practice",
      "Time Management",
    ],
    "description_en":
        "Intensive practical practice focusing on high-tariff document formatting and database queries.",
    "description_my":
        "အမှတ်များသော စာရွက်စာတမ်း ဖော်မတ်ချခြင်းနှင့် ဒေတာဘေ့စ် ကွီရီများကို အဓိကထား၍ လက်တွေ့လေ့ကျင့်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 3 (Spreadsheets & Web Authoring) Intensive",
    "title_my":
        "Paper 3 (စပရက်ရှိက်နှင့် ဝဘ်ဒီဇိုင်း) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Advanced Spreadsheet Functions Drill",
      "HTML/CSS Code Optimization",
      "Full Timed Mock Test",
    ],
    "description_en":
        "Master complex spreadsheet modeling and clean web coding under timed examination conditions.",
    "description_my":
        "အချိန်ကိုက် စာမေးပွဲ အခြေအနေများအောက်တွင် ရှုပ်ထွေးသော စပရက်ရှိက် မော်ဒယ်လ်နှင့် သန့်ရှင်းသော ဝဘ်ကုဒ်ရေးသားမှုကို လေ့ကျင့်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE ICT Graduation",
    "title_my": "IGCSE ICT ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Technical Mastery",
      "Reflecting on Digital Skills",
      "Pathways to Advanced IT and Computer Science",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Information and Communication Technology and preparation for advanced computing.",
    "description_my":
        "IGCSE သတင်းအချက်အလက်နှင့် ဆက်သွယ်ရေး နည်းပညာ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး အဆင့်မြင့် ကွန်ပျူတာ ပညာရေးဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
