// File: ai_data_bridge/igcse_design_and_technology_all_terms.dart
// IGCSE Design and Technology Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseDesignAndTechnologyAllTermsData = [
  // ================= TERM 1: Design Principles and Research Methods =================
  {
    "week": 1,
    "term": 1,
    "theme": "Design Principles",
    "title_en": "The Design Process and User Needs",
    "title_my": "ဒီဇိုင်း လုပ်ငန်းစဉ်နှင့် အသုံးပြုသူ လိုအပ်ချက်များ",
    "topics": [
      "Identifying Design Needs and Problems",
      "Writing Design Briefs and Specifications",
      "Target Audience and Market Research",
    ],
    "description_en":
        "Understand the initial stages of the design process, defining client needs, and formulating design specifications.",
    "description_my":
        "ဒီဇိုင်း လုပ်ငန်းစဉ်၏ အစောပိုင်း အဆင့်များ၊ ဖောက်သည် လိုအပ်ချက်များကို သတ်မှတ်ခြင်းနှင့် ဒီဇိုင်း သတ်မှတ်ချက်များ ရေးဆွဲခြင်းကို နားလည်စေမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Research Methods",
    "title_en": "Investigative Research and Analysis",
    "title_my": "စုံစမ်းစစ်ဆေးရေး သုတေသနနှင့် ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": [
      "Product Analysis (Aesthetics, Cost, Customer, Environment, Size, Safety, Function)",
      "Deconstructing Existing Products",
      "Human Factors and Ergonomics",
    ],
    "description_en":
        "Master product analysis techniques, evaluating existing designs and ergonomic considerations.",
    "description_my":
        "လက်ရှိ ဒီဇိုင်းများကို အကဲဖြတ်ခြင်းနှင့် လူသားဆိုင်ရာ အချက်အလက်များ (Ergonomics) ကို ထည့်သွင်းစဉ်းစားသည့် ထုတ်ကုန် ခွဲခြမ်းစိတ်ဖြာမှုများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Generating Ideas",
    "title_en": "Generating and Developing Design Ideas",
    "title_my": "ဒီဇိုင်း အယူအဆများ ဖန်တီးခြင်းနှင့် တိုးတက်စေခြင်း",
    "topics": [
      "Freehand Sketching and Annotation",
      "Morphological Charts and Brainstorming",
      "Iterative Design Development",
    ],
    "description_en":
        "Explore creative ideation techniques, sketching, and iterative design development strategies.",
    "description_my":
        "ဖန်တီးမှု ရှိသော အယူအဆ ဖော်ထုတ်ရေး နည်းလမ်းများ၊ ပုံကြမ်းဆွဲခြင်းနှင့် တိုးတက်သော ဒီဇိုင်း မဟာဗျူဟာများကို စူးစမ်းမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Design Proposal and Sketchbook Studio",
    "title_my": "ဒီဇိုင်း အဆိုပြုချက်နှင့် စက္ကူမှတ်စု အလုပ်ရုံ",
    "topics": [
      "Developing Final Design Proposals",
      "Client Feedback Integration",
      "Portfolio Presentation",
    ],
    "description_en":
        "Compile professional design proposal folios meeting IGCSE standards.",
    "description_my":
        "IGCSE စံနှုန်းများနှင့် ကိုက်ညီသော ပရော်ဖက်ရှင်နယ် ဒီဇိုင်း အဆိုပြုချက် ပို့ဖိုလီယိုများကို စုစည်းမည်။",
  },

  // ================= TERM 2: Materials, Properties and Characteristics =================
  {
    "week": 5,
    "term": 2,
    "theme": "Materials - Woods",
    "title_en": "Wood-Based Materials",
    "title_my": "သစ်အခြေခံ ပစ္စည်းများ",
    "topics": [
      "Hardwoods vs Softwoods (Oak, Ash, Pine, Mahogany)",
      "Man-made Boards (MDF, Plywood, Chipboard)",
      "Working Properties and Seasoning",
    ],
    "description_en":
        "Examine hardwood, softwood, and manufactured board properties, selection, and working characteristics.",
    "description_my":
        "မာကျောသောသစ်၊ ပျော့ပျောင်းသောသစ်နှင့် လူလုပ်သစ်ပြားများ၏ ဂုဏ်သတ္တိများနှင့် ရွေးချယ်အသုံးပြုပုံကို လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Materials - Metals",
    "title_en": "Metal-Based Materials and Alloys",
    "title_my": "သတ္တုအခြေခံ ပစ္စည်းများနှင့် အလွိုင်း (Alloys) များ",
    "topics": [
      "Ferrous vs Non-Ferrous Metals (Steel, Aluminium, Copper)",
      "Alloys (Brass, Stainless Steel)",
      "Thermal and Electrical Conductivities",
    ],
    "description_en":
        "Understand ferrous and non-ferrous metal properties, alloy compositions, and applications.",
    "description_my":
        "သံပါဝင်သော/မပါဝင်သော သတ္တုများ၏ ဂုဏ်သတ္တိများ၊ အလွိုင်း ဖွဲ့စည်းပုံနှင့် အသုံးချမှုများကို နားလည်စေမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Materials - Polymers",
    "title_en": "Polymers and Smart Materials",
    "title_my": "ပိုလီမာများနှင့် စမတ် ပစ္စည်းများ",
    "topics": [
      "Thermoplastics vs Thermosetting Plastics (Acrylic, PVC, Epoxy Resin)",
      "Smart Materials (Shape Memory Alloys, Thermochromic Pigments)",
      "Composite Materials",
    ],
    "description_en":
        "Explore polymer classifications, processing characteristics, and innovative smart materials.",
    "description_my":
        "ပိုလီမာ အမျိုးအစားခွဲခြားမှုများ၊ ပြုပြင်ဖန်တီးမှု လက္ခဏာများနှင့် ဆန်းသစ်သော စမတ်ပစ္စည်းများကို စူးစမ်းမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Materials Selection Studio",
    "title_my": "ပစ္စည်းများ ရွေးချယ်ခြင်း အလုပ်ရုံ",
    "topics": [
      "Material Testing Methods",
      "Justifying Material Choices",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate material properties through rigorous testing scenarios and justify selections for specific products.",
    "description_my":
        "တင်းကျပ်သော စမ်းသပ်မှု အခြေအနေများမှတစ်ဆင့် ပစ္စည်းများ၏ ဂုဏ်သတ္တိများကို အကဲဖြတ်ပြီး ထုတ်ကုန်များအတွက် ရွေးချယ်မှုကို ရှင်းလင်းတင်ပြမည်။",
  },

  // ================= TERM 3: Practical Making Skills and Workshop Processes =================
  {
    "week": 9,
    "term": 3,
    "theme": "Workshop Safety",
    "title_en": "Workshop Safety and Tool Handling",
    "title_my": "အလုပ်ရုံ ဘေးကင်းရေးနှင့် ကိရိယာ ကိုင်တွယ်ခြင်း",
    "topics": [
      "Risk Assessments and PPE",
      "Hand Tools (Saws, Chisels, Files)",
      "Machine Safety (Pillar Drills, Band Saws, Lathes)",
    ],
    "description_en":
        "Master safe workshop practices, hand tool operations, and power machine safety protocols.",
    "description_my":
        "အလုပ်ရုံ ဘေးကင်းရေး ကျင့်စဉ်များ၊ လက်သုံးကိရိယာ အသုံးချမှုနှင့် စက်ကိရိယာ လုံခြုံရေး ပရိုတိုကောများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Making Techniques",
    "title_en": "Marking Out, Cutting, and Shaping",
    "title_my": "အမှတ်အသားပြုခြင်း၊ ဖြတ်တောက်ခြင်းနှင့် ပုံဖော်ခြင်း",
    "topics": [
      "Measuring and Marking Tools (Try Squares, Vernier Calipers)",
      "Cutting and Removing Waste Material",
      "Shaping and Planing Techniques",
    ],
    "description_en":
        "Execute precise marking out, cutting, and shaping techniques across wood, metal, and plastics.",
    "description_my":
        "သစ်၊ သတ္တုနှင့် ပလတ်စတစ်တို့တွင် တိကျသော အမှတ်အသားပြုခြင်း၊ ဖြတ်တောက်ခြင်းနှင့် ပုံဖော်ခြင်း နည်းပညာများကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Joining Techniques",
    "title_en": "Joining, Assembling, and Fastening",
    "title_my": "ချိတ်ဆက်ခြင်း၊ စုစည်းခြင်းနှင့် တပ်ဆင်ခြင်း",
    "topics": [
      "Permanent Joints (Welding, Brazing, Adhesives)",
      "Temporary Joints (Screws, Bolts, Knock-down Fittings)",
      "Wood Joints (Mortise and Tenon, Dovetail)",
    ],
    "description_en":
        "Learn permanent and temporary joining methods for diverse materials and structural stability.",
    "description_my":
        "မတူညီသော ပစ္စည်းများနှင့် တည်ဆောက်ပုံ တည်ငြိမ်မှုအတွက် အမြဲတမ်းနှင့် ယာယီ ချိတ်ဆက်သည့် နည်းလမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Surface Finishing and Quality Control",
    "title_my": "မျက်နှာပြင် တင်ဆက်မှုနှင့် အရည်အသွေး ထိန်းချုပ်ခြင်း",
    "topics": [
      "Sanding, Varnishing, Painting, and Polishing",
      "Dip Coating and Anodising",
      "Quality Assurance and Tolerances",
    ],
    "description_en":
        "Apply professional surface finishes and implement quality control checks during manufacturing.",
    "description_my":
        "ပရော်ဖက်ရှင်နယ် မျက်နှာပြင် တင်ဆက်မှုများကို အသုံးချပြီး ထုတ်လုပ်မှုအတွင်း အရည်အသွေး စစ်ဆေးမှုများကို လုပ်ဆောင်မည်။",
  },

  // ================= TERM 4: Systems and Control (Electronics, Mechanisms and Structures) =================
  {
    "week": 13,
    "term": 4,
    "theme": "Structures",
    "title_en": "Structural Forces and Reinforcement",
    "title_my": "တည်ဆောက်ပုံဆိုင်ရာ အားများနှင့် ခိုင်ခံ့အောင်ပြုလုပ်ခြင်း",
    "topics": [
      "Tension, Compression, Bending, and Torsion",
      "Triangulation and Beams",
      "Reinforcing Weak Structures",
    ],
    "description_en":
        "Analyze structural forces acting on products and design reinforced frameworks for stability.",
    "description_my":
        "ထုတ်ကုန်များအပေါ် သက်ရောက်သည့် တည်ဆောက်ပုံဆိုင်ရာ အားများကို ခွဲခြမ်းစိတ်ဖြာပြီး တည်ငြိမ်မှုအတွက် ခိုင်ခံ့သော ဘောင်များကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Mechanisms",
    "title_en": "Mechanical Systems and Motion",
    "title_my": "စက်မှု စနစ်များနှင့် ရွေ့လျားမှု",
    "topics": [
      "Types of Motion (Linear, Rotary, Reciprocating, Oscillating)",
      "Levers and Linkages",
      "Gears, Pulleys, Cams, and Followers",
    ],
    "description_en":
        "Calculate gear ratios, mechanical advantage, and design mechanical linkage systems.",
    "description_my":
        "ဂီယာ အချိုးများ၊ စက်မှု အသာစီးရမှုများကို တွက်ချက်ပြီး စက်မှု ချိတ်ဆက်မှု စနစ်များကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Electronics",
    "title_en": "Electronic Systems and Control",
    "title_my": "အီလက်ထရောနစ် စနစ်များနှင့် ထိန်းချုပ်မှု",
    "topics": [
      "Input Devices (Sensors, Switches)",
      "Processors (Microcontrollers, Logic Gates)",
      "Output Devices (LEDs, Buzzers, Motors)",
    ],
    "description_en":
        "Design simple electronic control circuits incorporating input sensors and output actuators.",
    "description_my":
        "ထည့်သွင်း ဆင်ဆာများနှင့် ထုတ်ပေးသည့် အစိတ်အပိုင်းများ ပါဝင်သော ရိုးရှင်းသော အီလက်ထရောနစ် ထိန်းချုပ် ပတ်လမ်းများကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Systems Integration Studio",
    "title_my": "စနစ်များ ပေါင်းစပ်ခြင်း အလုပ်ရုံ",
    "topics": [
      "Electromechanical System Design",
      "Circuit Testing",
      "Exam Practice",
    ],
    "description_en":
        "Integrate mechanical mechanisms and electronic controls into functioning prototype systems.",
    "description_my":
        "စက်မှု ယန္တရားများနှင့် အီလက်ထရောနစ် ထိန်းချုပ်မှုများကို အလုပ်လုပ်နိုင်သော ပုံစံတူ စနစ်များအတွင်း ပေါင်းစပ်မည်။",
  },

  // ================= TERM 5: Computer-Aided Design (CAD) and CAM =================
  {
    "week": 17,
    "term": 5,
    "theme": "CAD",
    "title_en": "Computer-Aided Design (CAD) Principles",
    "title_my": "ကွန်ပျူတာ အထောက်အကူပြု ဒီဇိုင်း (CAD) အခြေခံများ",
    "topics": [
      "2D and 3D Modeling Software",
      "Orthographic and Isometric Projections",
      "Rendering and Material Application",
    ],
    "description_en":
        "Master 3D CAD modeling software to create accurate digital prototypes and assemblies.",
    "description_my":
        "တိကျသော ဒစ်ဂျစ်တယ် ပုံစံတူများနှင့် တပ်ဆင်မှုများကို ဖန်တီးရန် 3D CAD မော်ဒယ်လ် ဆော့ဖ်ဝဲကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "CAM",
    "title_en": "Computer-Aided Manufacture (CAM)",
    "title_my": "ကွန်ပျူတာ အထောက်အကူပြု ထုတ်လုပ်မှု (CAM)",
    "topics": [
      "CNC Laser Cutters and Routers",
      "3D Printing Technologies (FDM, SLA)",
      "CAD/CAM File Preparation (DXF, STL)",
    ],
    "description_en":
        "Understand CAM machinery, file preparation, and automated digital manufacturing processes.",
    "description_my":
        "CAM စက်ယန္တရားများ၊ ဖိုင်ပြင်ဆင်မှုနှင့် အလိုအလျောက် ဒစ်ဂျစ်တယ် ထုတ်လုပ်မှု လုပ်ငန်းစဉ်များကို နားလည်စေမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Rapid Prototyping",
    "title_en": "Rapid Prototyping and Model Making",
    "title_my": "အမြန် ပုံစံတူ ထုတ်လုပ်ခြင်းနှင့် မော်ဒယ် တည်ဆောက်ခြင်း",
    "topics": [
      "Foam Board, Cardboard, and Jelutong Modeling",
      "Iterative Prototype Testing",
      "Aesthetic Evaluation",
    ],
    "description_en":
        "Construct scale models and prototypes to test ergonomics and aesthetic appeal before full production.",
    "description_my":
        "အပြည့်အဝ မထုတ်လုပ်မီ Ergonomics နှင့် အလှတရားကို စမ်းသပ်ရန် စကေး မော်ဒယ်များနှင့် ပုံစံတူများကို တည်ဆောက်မည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "CAD/CAM Prototyping Studio",
    "title_my": "CAD/CAM ပုံစံတူ ထုတ်လုပ်ရေး အလုပ်ရုံ",
    "topics": [
      "Digital Fabrication Workflow",
      "Prototype Troubleshooting",
      "Exam Practice",
    ],
    "description_en":
        "Execute a complete digital workflow from CAD design to CAM fabrication and physical prototype assembly.",
    "description_my":
        "CAD ဒီဇိုင်းမှ CAM ထုတ်လုပ်မှုနှင့် ရုပ်ပိုင်းဆိုင်ရာ ပုံစံတူ တပ်ဆင်မှုအထိ ပြီးပြည့်စုံသော ဒစ်ဂျစ်တယ် လုပ်ငန်းစဉ်ကို လုပ်ဆောင်မည်။",
  },

  // ================= TERM 6: Graphic Products and Packaging Design =================
  {
    "week": 21,
    "term": 6,
    "theme": "Graphics",
    "title_en": "Graphic Communication Techniques",
    "title_my": "ဂရပ်ဖစ် ဆက်သွယ်ရေး နည်းပညာများ",
    "topics": [
      "Perspective Drawing (1-Point and 2-Point)",
      "Rendering Techniques for Texture and Shine",
      "Exploded View Drawings",
    ],
    "description_en":
        "Master technical drawing standards, perspective sketching, and realistic product rendering.",
    "description_my":
        "နည်းပညာဆိုင်ရာ ပုံဆွဲစံနှုန်းများ၊ အမြင်ပုံကြမ်းများ (Perspective) နှင့် လက်တွေ့ဆန်သော ထုတ်ကုန် တင်ဆက်မှုများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Packaging",
    "title_en": "Packaging Design and Nets",
    "title_my": "ထုပ်ပိုးမှု ဒီဇိုင်းနှင့် ကွန်ရက်များ (Nets)",
    "topics": [
      "Net Development for Boxes and Cartons",
      "Folding, Scoring, and Tab Glueing",
      "Point of Sale Display Units",
    ],
    "description_en":
        "Design functional product packaging nets, folding patterns, and retail display structures.",
    "description_my":
        "လုပ်ဆောင်ချက်ပါရှိသော ထုပ်ပိုးမှု ကွန်ရက်များ၊ ခေါက်ပုံစံများနှင့် လက်လီပြခန်း ယူနစ်များကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Visual Communication",
    "title_en": "Commercial Printing and Typography",
    "title_my": "လုပ်ငန်းသုံး ပုံနှိပ်ခြင်းနှင့် စာလုံးဒီဇိုင်း",
    "topics": [
      "Printing Processes (Lithography, Screen Printing, Flexography)",
      "Typography and Brand Layout",
      "Environmental Labelling",
    ],
    "description_en":
        "Examine commercial printing methods and visual communication strategies in marketing.",
    "description_my":
        "စျေးကွက်ရှာဖွေရေးတွင် လုပ်ငန်းသုံး ပုံနှိပ်နည်းများနှင့် အမြင်အာရုံ ဆက်သွယ်ရေး မဟာဗျူဟာများကို လေ့လာမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Graphic Products Studio",
    "title_my": "ဂရပ်ဖစ် ထုတ်ကုန်များ အလုပ်ရုံ",
    "topics": ["Packaging Campaign Design", "Net Prototyping", "Exam Practice"],
    "description_en":
        "Design and prototype a complete commercial packaging and promotional graphic campaign.",
    "description_my":
        "ပြီးပြည့်စုံသော လုပ်ငန်းသုံး ထုပ်ပိုးမှုနှင့် ကြော်ငြာ ဂရပ်ဖစ် ကမ်ပိန်းကို ဒီဇိုင်းဆွဲ ပုံစံတူထုတ်လုပ်မည်။",
  },

  // ================= TERM 7: Environmental and Social Sustainability =================
  {
    "week": 25,
    "term": 7,
    "theme": "Sustainability",
    "title_en": "Sustainable Design and the 6Rs",
    "title_my":
        "ရေရှည်တည်တံ့သော ဒီဇိုင်းနှင့် 6Rs (Reduce, Reuse, Recycle, Rethink, Refuse, Repair)",
    "topics": [
      "The 6Rs Framework",
      "Life Cycle Assessment (LCA)",
      "Carbon Footprint in Manufacturing",
    ],
    "description_en":
        "Evaluate sustainable design strategies, environmental impact, and product life cycle assessments.",
    "description_my":
        "ရေရှည်တည်တံ့သော ဒီဇိုင်း မဟာဗျူဟာများ၊ ပတ်ဝန်းကျင် သက်ရောက်မှုနှင့် ထုတ်ကုန် သက်တမ်းစက်ဝန်း အကဲဖြတ်မှုများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Energy and Resources",
    "title_en": "Energy Consumption and Fair Trade",
    "title_my": "စွမ်းအင် သုံးစွဲမှုနှင့် တရားမျှတသော ကုန်သွယ်ရေး",
    "topics": [
      "Embodied Energy in Materials",
      "Fair Trade and Ethical Production",
      "Design for Disassembly",
    ],
    "description_en":
        "Analyze ethical sourcing, material embodied energy, and designing products for easy recycling.",
    "description_my":
        "ကျင့်ဝတ်ကျသော ရင်းမြစ်ရှာဖွေမှု၊ ပစ္စည်းများပါဝင်သည့် စွမ်းအင်နှင့် လွယ်ကူစွာ ပြန်လည်အသုံးချနိုင်ရန် ဒီဇိုင်းဆွဲခြင်းကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Social Impact",
    "title_en": "Design for Local and Global Communities",
    "title_my": "ဒေသတွင်းနှင့် ကမ္ဘာ့အသိုက်အဝန်းများအတွက် ဒီဇိုင်းဆွဲခြင်း",
    "topics": [
      "Inclusive and Accessible Design",
      "Appropriate Technology for Developing Nations",
      "Social Responsibility in Manufacturing",
    ],
    "description_en":
        "Explore inclusive design principles and appropriate technology solutions for global challenges.",
    "description_my":
        "ပါဝင်သော ဒီဇိုင်းမူဝါဒများနှင့် ကမ္ဘာ့စိန်ခေါ်မှုများအတွက် သင့်လျော်သော နည်းပညာ ဖြေရှင်းချက်များကို စူးစမ်းမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Eco-Design Innovation Studio",
    "title_my": "ဂေဟ-ဒီဇိုင်း ဆန်းသစ်တီထွင်မှု အလုပ်ရုံ",
    "topics": [
      "Redesigning Unsustainable Products",
      "Eco-Design Pitch",
      "Exam Practice",
    ],
    "description_en":
        "Redesign a commercially available unsustainable product using circular economy principles.",
    "description_my":
        "စက်ဝိုင်း စီးပွားရေး မူဝါဒများကို အသုံးပြု၍ စျေးကွက်ရှိ မရေမွန်နိုင်သော ထုတ်ကုန်တစ်ခုကို ပြန်လည်ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 8: Project Coursework Preparation & Execution =================
  {
    "week": 29,
    "term": 8,
    "theme": "Coursework",
    "title_en": "Project Portfolio: Research and Brief",
    "title_my": "ပရောဂျက် ပို့ဖိုလီယို - သုတေသနနှင့် အကျဉ်းချုပ်",
    "topics": [
      "Selecting a Project Context",
      "Primary and Secondary Investigation",
      "Formulating Detailed Design Criteria",
    ],
    "description_en":
        "Initiate the IGCSE Design and Technology Project Coursework, conducting deep contextual research.",
    "description_my":
        "IGCSE Design and Technology ပရောဂျက် လုပ်ငန်းစဉ်ကို စတင်ပြီး နက်ရှိုင်းသော ဆက်စပ်သုတေသနကို လုပ်ဆောင်မည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Coursework",
    "title_en": "Project Portfolio: Development and Modeling",
    "title_my":
        "ပရောဂျက် ပို့ဖိုလီယို - ဖွံ့ဖြိုးတိုးတက်မှုနှင့် မော်ဒယ် တည်ဆောက်ခြင်း",
    "topics": [
      "Generating Diverse Solutions",
      "CAD Modeling and Cardboard Prototyping",
      "Client Testing and Review",
    ],
    "description_en":
        "Develop multiple design ideas, test through rapid prototyping, and refine based on feedback.",
    "description_my":
        "ဒီဇိုင်း အယူအဆမျိုးစုံကို ဖန်တီးခြင်း၊ အမြန် ပုံစံတူဖြင့် စမ်းသပ်ခြင်းနှင့် တုံ့ပြန်ချက်အပေါ် မူတည်၍ ပြုပြင်မွမ်းမံမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Coursework",
    "title_en": "Project Manufacturing and Realisation",
    "title_my": "ပရောဂျက် ထုတ်လုပ်မှုနှင့် အကောင်အထည်ဖော်ခြင်း",
    "topics": [
      "Executing Final Making Plan",
      "Applying Workshop Skills and CAM",
      "Quality Control Documentation",
    ],
    "description_en":
        "Manufacture the final functional prototype adhering strictly to planned timelines and safety.",
    "description_my":
        "စီစဉ်ထားသော အချိန်ဇယားနှင့် ဘေးကင်းရေးကို တင်းကျပ်စွာ လိုက်နာလျက် နောက်ဆုံး လုပ်ဆောင်နိုင်သော ပုံစံတူကို ထုတ်လုပ်မည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Project Testing, Evaluation and Portfolio Finish",
    "title_my":
        "ပရောဂျက် စမ်းသပ်ခြင်း၊ အကဲဖြတ်ခြင်းနှင့် ပို့ဖိုလီယို ပြီးမြောက်ခြင်း",
    "topics": [
      "Rigorous Testing Against Specification",
      "Third-Party Evaluation",
      "Final Portfolio Layout and Formatting",
    ],
    "description_en":
        "Evaluate the final prototype against initial design criteria and complete the project folio.",
    "description_my":
        "မူလ ဒီဇိုင်း စံနှုန်းများနှင့် ဆန့်ကျင်၍ နောက်ဆုံး ပုံစံတူကို အကဲဖြတ်ပြီး ပရောဂျက် ဖိုလီယိုကို ပြီးမြောက်အောင် လုပ်မည်။",
  },

  // ================= TERM 9: Exam Prep & Final Graduation =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Paper 1 (Product Design Theory) Intensive",
    "title_my": "Paper 1 (ထုတ်ကုန် ဒီဇိုင်း သီအိုရီ) အထူးကြပ်မတ် လေ့ကျင့်ခန်း",
    "topics": [
      "Materials and Processes Revision",
      "Systems and Control Drills",
      "Designing in Sections Practice",
    ],
    "description_en":
        "Intensive drilling of core product design theory, manufacturing processes, and systems for Paper 1.",
    "description_my":
        "Paper 1 အတွက် အဓိက ထုတ်ကုန် ဒီဇိုင်း သီအိုရီ၊ ထုတ်လုပ်မှု လုပ်ငန်းစဉ်များနှင့် စနစ်များကို အထူးကြပ်မတ် လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Specialised Option Theory (Resistant Materials/Graphics)",
    "title_my":
        "အထူးပြု ရွေးချယ်စရာ သီအိုရီ (ခိုင်ခံ့သော ပစ္စည်းများ / ဂရပ်ဖစ်)",
    "topics": [
      "Specialist Technical Knowledge Revision",
      "Calculations and Technical Drawing Questions",
      "Exam Time Management",
    ],
    "description_en":
        "Master specialist technical option questions, calculations, and technical drawing standards.",
    "description_my":
        "အထူးပြု နည်းပညာ ရွေးချယ်စရာ မေးခွန်းများ၊ တွက်ချက်မှုများနှင့် နည်းပညာ ပုံဆွဲစံနှုန်းများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Past Paper Mock Examinations",
    "title_my": "မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အစုံအလင် ဖြေဆိုခြင်း",
    "topics": [
      "Timed Mock Paper 1",
      "Timed Mock Paper 2 (Specialist)",
      "Mark Scheme Diagnostics",
    ],
    "description_en":
        "Complete full-length past paper mock examinations under rigorous timed conditions.",
    "description_my":
        "တင်းကျပ်သော အချိန်သတ်မှတ်ချက်များအောက်တွင် မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Design and Technology Graduation",
    "title_my": "IGCSE ဒီဇိုင်းနှင့် နည်းပညာ ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Innovation and Making",
      "Reflecting on Technical Engineering",
      "Pathways to A-Level Design and Product Engineering",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Design and Technology and preparation for advanced engineering studies.",
    "description_my":
        "IGCSE ဒီဇိုင်းနှင့် နည်းပညာ ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး အဆင့်မြင့် အင်ဂျင်နီယာ ပညာရေးဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
