// File: ai_data_bridge/igcse_environmental_management_all_terms.dart
// IGCSE Environmental Management Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseEnvironmentalManagementAllTermsData = [
  // ================= TERM 1: Lithosphere and Energy Resources =================
  {
    "week": 1,
    "term": 1,
    "theme": "Lithosphere",
    "title_en": "Rocks, Minerals, and the Rock Cycle",
    "title_my": "ကျောက်တုံးများ၊ သတ္တုရိုင်းများနှင့် ကျောက်လည်ပတ်မှု စက်ဝန်း",
    "topics": [
      "Igneous, Sedimentary, and Metamorphic Rocks",
      "Formation of Mineral Ores",
      "Surface vs Underground Mining",
    ],
    "description_en":
        "Examine rock types, mineral formation processes, and extraction methods used in mining.",
    "description_my":
        "ကျောက်အမျိုးအစားများ၊ သတ္တုရိုင်း ဖြစ်ပေါ်မှု လုပ်ငန်းစဉ်များနှင့် မိုင်းဖော်ထုတ်ရေး နည်းလမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Lithosphere",
    "title_en": "Environmental Impacts of Rock and Mineral Extraction",
    "title_my":
        "ကျောက်နှင့် သတ္တုတူးဖော်ခြင်း၏ ပတ်ဝန်းကျင်အပေါ် သက်ရောက်မှုများ",
    "topics": [
      "Habitat Destruction",
      "Pollution (Water, Air, Noise)",
      "Land Restoration and Rehabilitation",
    ],
    "description_en":
        "Analyze the ecological and social degradation caused by mining and strategies for land restoration.",
    "description_my":
        "သတ္တုတူးဖော်မှုကြောင့် ဖြစ်ပေါ်လာသော ဂေဟစနစ် ပျက်စီးမှုနှင့် မြေယာပြန်လည်ထူထောင်ရေး မဟာဗျူဟာများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Energy Resources",
    "title_en": "Energy Resources and Provision",
    "title_my": "စွမ်းအင် အရင်းအမြစ်များနှင့် ထောက်ပံ့မှု",
    "topics": [
      "Fossil Fuels (Coal, Oil, Natural Gas)",
      "Nuclear Energy",
      "Energy Efficiency and Conservation",
    ],
    "description_en":
        "Compare non-renewable energy sources, nuclear power generation, and methods to improve energy efficiency.",
    "description_my":
        "ပြန်လည်ပြည့်မြောက်မှု မရှိသော စွမ်းအင်များ၊ နူကလီးယားစွမ်းအင် ထုတ်လုပ်မှုနှင့် စွမ်းအင်ထိရောက်မှု တိုးမြှင့်နည်းများကို နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Renewable Energy and Sustainable Power",
    "title_my":
        "ပြန်လည်ပြည့်မြောက်သော စွမ်းအင်နှင့် ရေရှည်တည်တံ့သော လျှပ်စစ်ဓာတ်အား",
    "topics": [
      "Solar, Wind, Geothermal, and Hydroelectric Power",
      "Biofuels and Tidal Energy",
      "Evaluating Energy Transitions",
    ],
    "description_en":
        "Evaluate renewable energy alternatives and their role in mitigating global climate change.",
    "description_my":
        "ပြန်လည်ပြည့်မြောက်သော စွမ်းအင် အစားထိုးပစ္စည်းများနှင့် ကမ္ဘာ့ရာသီဥတု ပြောင်းလဲမှုကို လျှော့ချရာတွင် ၎င်းတို့၏ အခန်းကဏ္ဍကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 2: Agriculture and Food Resources =================
  {
    "week": 5,
    "term": 2,
    "theme": "Agriculture",
    "title_en": "Agricultural Systems and Practices",
    "title_my": "စိုက်ပျိုးရေး စနစ်များနှင့် လက်တွေ့လုပ်ဆောင်မှုများ",
    "topics": [
      "Arable, Pastoral, and Mixed Farming",
      "Subsistence vs Commercial Agriculture",
      "Intensive vs Extensive Systems",
    ],
    "description_en":
        "Explore different agricultural systems, inputs, processes, and outputs across global regions.",
    "description_my":
        "ကမ္ဘာ့ဒေသအသီးသီးရှိ စိုက်ပျိုးရေးစနစ်များ၊ သွင်းအားစုများနှင့် လုပ်ငန်းစဉ်များကို စူးစမ်းမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Agriculture",
    "title_en": "Agricultural Intensification and the Green Revolution",
    "title_my":
        "စိုက်ပျိုးရေး အထွက်နှုန်းတိုးမြှင့်ခြင်းနှင့် စိမ်းလန်းသော တော်လှန်ရေး",
    "topics": [
      "Mechanisation and Chemical Fertilisers",
      "Pesticides, Herbicides, and Monocultures",
      "Genetically Modified Crops (GMOs)",
    ],
    "description_en":
        "Analyze the impacts of modern agricultural intensification on crop yields and environmental health.",
    "description_my":
        "ခေတ်မီ စိုက်ပျိုးရေး အထွက်နှုန်းတိုးမြှင့်မှုက သီးနှံထွက်နှုန်းနှင့် ပတ်ဝန်းကျင် ကျန်းမာရေးအပေါ် သက်ရောက်မှုကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Agriculture",
    "title_en": "Environmental Impacts of Agriculture",
    "title_my":
        "စိုက်ပျိုးရေးကြောင့် ဖြစ်ပေါ်လာသည့် ပတ်ဝန်းကျင်ဆိုင်ရာ သက်ရောက်မှုများ",
    "topics": [
      "Soil Erosion and Desertification",
      "Eutrophication of Water Bodies",
      "Bioaccumulation of Pesticides in Food Chains",
    ],
    "description_en":
        "Investigate soil degradation, eutrophication, and chemical accumulation in ecological food chains.",
    "description_my":
        "မြေဆီလွှာ ပျက်စီးခြင်း၊ ရေထုညစ်ညမ်းခြင်း (Eutrophication) နှင့် ဓာတုပစ္စည်းများ စုပုံလာမှုကို လေ့လာမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Sustainable Agriculture Studio",
    "title_my": "ရေရှည်တည်တံ့သော စိုက်ပျိုးရေး အလုပ်ရုံ",
    "topics": [
      "Organic Farming",
      "Crop Rotation and Terracing",
      "Managing Food Security",
    ],
    "description_en":
        "Evaluate sustainable farming practices designed to protect soil, water, and food security.",
    "description_my":
        "မြေဆီလွှာ၊ ရေနှင့် စားနပ်ရိက္ခာ လုံခြုံမှုကို ကာကွယ်ရန် ဒီဇိုင်းဆွဲထားသော ရေရှည်တည်တံ့သော စိုက်ပျိုးရေး ကျင့်စဉ်များကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 3: Water Resources and Management =================
  {
    "week": 9,
    "term": 3,
    "theme": "Water Resources",
    "title_en": "The Water Cycle and Global Water Distribution",
    "title_my": "ရေစက်ဝန်းနှင့် ကမ္ဘာ့ရေ ဖြန့်ဝေမှု",
    "topics": [
      "Evaporation, Condensation, Precipitation, and Transpiration",
      "Groundwater Aquifers",
      "Global Water Scarcity Causes",
    ],
    "description_en":
        "Examine the hydrological cycle, groundwater storage, and the causes of global water shortages.",
    "description_my":
        "ရေစက်ဝန်း၊ မြေအောက်ရေ သိုလှောင်မှုနှင့် ကမ္ဘာ့ရေရှားပါးရသည့် အကြောင်းရင်းများကို လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Water Management",
    "title_en": "Water Supply and Uses",
    "title_my": "ရေပေးဝေမှုနှင့် အသုံးပြုမှုများ",
    "topics": [
      "Domestic, Agricultural, and Industrial Water Use",
      "Dams, Reservoirs, and Desalination",
      "Water Conservation Strategies",
    ],
    "description_en":
        "Analyze water consumption patterns, large-scale supply infrastructure, and water conservation methods.",
    "description_my":
        "ရေသုံးစွဲမှု ပုံစံများ၊ ကြီးမားသော ရေပေးဝေရေး အဆောက်အအုံများနှင့် ရေထိန်းသိမ်းရေး နည်းလမ်းများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Water Pollution",
    "title_en": "Water Pollution and Wastewater Treatment",
    "title_my": "ရေထုညစ်ညမ်းမှုနှင့် မိလ္လာရေ သန့်စင်ခြင်း",
    "topics": [
      "Point and Non-Point Source Pollution",
      "Industrial Effluent and Sewage",
      "Wastewater Treatment Stages",
    ],
    "description_en":
        "Investigate water pollution sources and the multi-stage process of wastewater treatment plants.",
    "description_my":
        "ရေထုညစ်ညမ်းမှု ရင်းမြစ်များနှင့် မိလ္လာရေ သန့်စင်စက်ရုံများ၏ အဆင့်ဆင့် လုပ်ငန်းစဉ်များကို စူးစမ်းမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Water Management Case Study Studio",
    "title_my": "ရေ စီမံခန့်ခွဲမှု လက်တွေ့လေ့လာမှု အလုပ်ရုံ",
    "topics": [
      "Transboundary River Disputes",
      "Sanitation Improvements",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate complex river basin management projects and sanitation challenges in developing nations.",
    "description_my":
        "ဖွံ့ဖြိုးဆဲနိုင်ငံများရှိ ရှုပ်ထွေးသော မြစ်ဝှက်ဒေသ စီမံခန့်ခွဲမှု ပရောဂျက်များနှင့် ကျန်းမာရေး စိန်ခေါ်မှုများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 4: Oceans and Fisheries =================
  {
    "week": 13,
    "term": 4,
    "theme": "Oceans",
    "title_en": "Marine Ecosystems and Fisheries",
    "title_my": "ပင်လယ်ရေကြောင်း ဂေဟစနစ်များနှင့် ငါးဖမ်းလုပ်ငန်းများ",
    "topics": [
      "Ocean Currents and Nutrient Upwelling",
      "Commercial Marine Fisheries",
      "Food Webs in Oceans",
    ],
    "description_en":
        "Examine ocean current systems, marine food webs, and the economic importance of global fisheries.",
    "description_my":
        "ပင်လယ်ရေစီးကြောင်း စနစ်များ၊ ရေကြောင်း စားနပ်ရိက္ခာ ကွင်းဆက်များနှင့် ကမ္ဘာ့ငးဖမ်းလုပ်ငန်းများ၏ စီးပွားရေး အရေးပါမှုကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Oceans",
    "title_en": "Overfishing and Marine Depletion",
    "title_my":
        "ငါးအလွန်အမင်း ဖမ်းဆီးခြင်းနှင့် ပင်လယ်ရေကြောင်း အရင်းအမြစ် ကျဆင်းခြင်း",
    "topics": [
      "Causes of Overfishing (Trawlers, Sonar)",
      "Bycatch and Discards",
      "Collapse of Fish Stocks (e.g., Cod)",
    ],
    "description_en":
        "Analyze modern industrial fishing practices and the catastrophic decline of key fish populations.",
    "description_my":
        "ခေတ်မီ စက်မှုငါးဖမ်း လုပ်ငန်းများနှင့် အဓိက ငါးဦးရေ ကျဆင်းလာမှုကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Marine Pollution",
    "title_en": "Marine Pollution and Threats",
    "title_my": "ပင်လယ်ရေကြောင်း ညစ်ညမ်းမှုနှင့် ခြိမ်းခြောက်မှုများ",
    "topics": [
      "Plastic Pollution and Microplastics",
      "Oil Spills and Toxic Runoff",
      "Coral Reef Bleaching",
    ],
    "description_en":
        "Investigate plastic debris, oil contamination, and climate-induced coral bleaching events.",
    "description_my":
        "ပလတ်စတစ် အမှိုက်များ၊ ရေနံ စွန့်ပစ်မှုများနှင့် ရာသီဥတုကြောင့် သန္တာကျောက်တန်းများ ဖြူရော်ပျက်စီးမှုကို လေ့လာမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Sustainable Fisheries and Marine Conservation",
    "title_my":
        "ရေရှည်တည်တံ့သော ငါးဖမ်းလုပ်ငန်းနှင့် ပင်လယ်ရေကြောင်း ထိန်းသိမ်းရေး",
    "topics": [
      "Quota Systems and Net Mesh Size Limits",
      "Marine Protected Areas (MPAs)",
      "Sustainable Seafood Certification",
    ],
    "description_en":
        "Evaluate management strategies designed to restore marine ecosystems and ensure sustainable fishing.",
    "description_my":
        "ပင်လယ်ရေကြောင်း ဂေဟစနစ်များကို ပြန်လည်ထူထောင်ရန်နှင့် ရေရှည်တည်တံ့သော ငါးဖမ်းလုပ်ငန်းကို အာမခံသော စီမံခန့်ခွဲမှုများကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 5: Managing Natural Hazards =================
  {
    "week": 17,
    "term": 5,
    "theme": "Natural Hazards",
    "title_en": "Tectonic Hazards: Earthquakes and Volcanoes",
    "title_my": "မြေလွှာချပ် အန္တရာယ်များ - ငလျင်နှင့် မီးတောင်များ",
    "topics": [
      "Causes of Earthquakes and Volcanic Eruptions",
      "Primary and Secondary Impacts",
      "Predictive Monitoring and Earthquake-Proof Building",
    ],
    "description_en":
        "Analyze tectonic hazards, their physical impacts, and engineering solutions to reduce vulnerability.",
    "description_my":
        "မြေလွှာချပ် အန္တရာယ်များ၊ ၎င်းတို့၏ ရုပ်ပိုင်းဆိုင်ရာ သက်ရောက်မှုများနှင့် ထိခိုက်လွယ်မှုကို လျှော့ချရန် အင်ဂျင်နီယာ ဖြေရှင်းချက်များကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Natural Hazards",
    "title_en": "Meteorological Hazards: Tropical Cyclones and Floods",
    "title_my":
        "မိုးလေဝသ အန္တရာယ်များ - အပူပိုင်း မုန်တိုင်းများနှင့် ရေကြီးခြင်း",
    "topics": [
      "Formation of Tropical Cyclones",
      "Causes of River and Coastal Flooding",
      "Meteorological Warning Systems",
    ],
    "description_en":
        "Examine tropical cyclone formation conditions, flood triggers, and early warning meteorological systems.",
    "description_my":
        "အပူပိုင်း မုန်တိုင်းများ ဖြစ်ပေါ်သည့် အခြေအနေများ၊ ရေကြီးရသည့် အကြောင်းရင်းများနှင့် ကြိုတင်သတိပေး မိုးလေဝသ စနစ်များကို လေ့လာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Natural Hazards",
    "title_en": "Droughts and Environmental Impacts",
    "title_my": "မိုးခေါင်ရေရှားမှုနှင့် ပတ်ဝန်းကျင်ဆိုင်ရာ သက်ရောက်မှုများ",
    "topics": [
      "Meteorological vs Agricultural Drought",
      "Causes of Droughts (El Niño)",
      "Famine and Desertification Links",
    ],
    "description_en":
        "Investigate drought triggers, El Niño impacts, and links between drought and famine.",
    "description_my":
        "မိုးခေါင်ရသည့် အကြောင်းရင်းများ၊ El Niño ၏ သက်ရောက်မှုနှင့် မိုးခေါင်မှုနှင့် အငတ်ဘေးကြား ဆက်နွှယ်မှုကို စူးစမ်းမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Disaster Risk Reduction Studio",
    "title_my": "ဘေးအန္တရာယ် ဖြစ်နိုင်ခြေ လျှော့ချရေး အလုပ်ရုံ",
    "topics": [
      "Emergency Preparedness Plans",
      "Community Resilience",
      "Post-Disaster Relief Operations",
    ],
    "description_en":
        "Design a comprehensive disaster risk reduction and community emergency response plan.",
    "description_my":
        "ပြည့်စုံသော ဘေးအန္တရာယ် ဖြစ်နိုင်ခြေ လျှော့ချရေးနှင့် လူထု အရေးပေါ် တုံ့ပြန်ရေး စီမံချက်ကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 6: The Atmosphere and Human Activities =================
  {
    "week": 21,
    "term": 6,
    "theme": "The Atmosphere",
    "title_en": "Atmospheric Composition and Structure",
    "title_my": "လေထု ဖွဲ့စည်းပုံနှင့် အလွှာများ",
    "topics": [
      "Layers of the Atmosphere (Troposphere, Stratosphere)",
      "Composition of Clean Air",
      "Natural Greenhouse Effect",
    ],
    "description_en":
        "Understand atmospheric layers, gas compositions, and the natural greenhouse mechanism sustaining life.",
    "description_my":
        "လေထု အလွှာများ၊ ဓာတ်ငွေ့ ဖွဲ့စည်းပုံနှင့် အသက်ရှင်မှုကို ထိန်းသိမ်းပေးသော သဘာဝ ဖန်လုံအိမ်အာနိသင်ကို နားလည်စေမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Climate Change",
    "title_en": "Enhanced Global Warming and Climate Change",
    "title_my":
        "ဖန်လုံအိမ်အာနိသင် ပိုမိုဆိုးရွားလာခြင်းနှင့် ရာသီဥတု ပြောင်းလဲခြင်း",
    "topics": [
      "Anthropogenic Greenhouse Gas Emissions (CO2, Methane)",
      "Impacts of Climate Change (Sea Level Rise, Melting Ice Sheets)",
      "Feedback Loops",
    ],
    "description_en":
        "Analyze human-induced greenhouse gas emissions and widespread ecological impacts of global warming.",
    "description_my":
        "လူသားများကြောင့် ထွက်လာသည့် ဖန်လုံအိမ် ဓာတ်ငွေ့များနှင့် ကမ္ဘာကြီးပူနွေးလာမှု၏ ဂေဟစနစ်အပေါ် သက်ရောက်မှုကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Ozone Depletion",
    "title_en": "Ozone Layer Depletion",
    "title_my": "အိုဇုန်းလွှာ ပါးလွှာပျက်စီးခြင်း",
    "topics": [
      "Role of the Ozone Layer in Absorbing UV Radiation",
      "CFCs and Ozone Destruction Mechanism",
      "The Montreal Protocol Success",
    ],
    "description_en":
        "Examine ozone layer functions, CFC destruction cycles, and international cooperation through the Montreal Protocol.",
    "description_my":
        "အိုဇုန်းလွှာ၏ အခန်းကဏ္ဍ၊ CFCs ၏ ဖျက်ဆီးမှု စက်ဝန်းနှင့် Montreal Protocol နိုင်ငံတကာ ပူးပေါင်းဆောင်ရွက်မှုကို လေ့လာမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Climate Policy and Mitigation Studio",
    "title_my": "ရာသီဥတု မူဝါဒနှင့် လျှော့ချရေး အလုပ်ရုံ",
    "topics": [
      "Carbon Tax and Carbon Trading",
      "International Climate Summits (COP)",
      "Exam Practice",
    ],
    "description_en":
        "Evaluate global climate mitigation policies, carbon pricing mechanisms, and international agreements.",
    "description_my":
        "ကမ္ဘာ့ရာသီဥတု လျှော့ချရေး မူဝါဒများ၊ ကာဗွန်ဈေးနှုန်း သတ်မှတ်မှုနှင့် နိုင်ငံတကာ သဘောတူညီချက်များကို အကဲဖြတ်မည်။",
  },

  // ================= TERM 7: Human Population =================
  {
    "week": 25,
    "term": 7,
    "theme": "Human Population",
    "title_en": "Population Dynamics and Growth",
    "title_my": "လူဦးရေ ဒိုင်းနမစ်နှင့် တိုးတက်နှုန်းများ",
    "topics": [
      "Birth Rates, Death Rates, and Natural Increase",
      "The Demographic Transition Model (DTM)",
      "Factors Influencing Population Growth",
    ],
    "description_en":
        "Analyze demographic trends, birth/death dynamics, and stages of the Demographic Transition Model.",
    "description_my":
        "ဒီမိုဂရပ်ဖစ် ခေတ်ရေစီးကြောင်းများ၊ မွေးဖွားမှု/သေဆုံးမှု ဒိုင်းနမစ်နှင့် DTM အဆင့်များကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Human Population",
    "title_en": "Population Policies and Management",
    "title_my": "လူဦးရေ မူဝါဒများနှင့် စီမံခန့်ခွဲမှု",
    "topics": [
      "Pronatalist vs Antinatalist Policies (e.g., China's One-Child Policy)",
      "Family Planning and Healthcare",
      "Aging Populations vs Youth Bulges",
    ],
    "description_en":
        "Evaluate government population policies, family planning initiatives, and demographic challenges.",
    "description_my":
        "အစိုးရ၏ လူဦးရေ မူဝါဒများ၊ မိသားစု စီမံကိန်း အစပြုမှုများနှင့် လူဦးရေ စိန်ခေါ်မှုများကို အကဲဖြတ်မည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Urbanisation",
    "title_en": "Urbanisation and Rural-Urban Migration",
    "title_my":
        "မြို့ပြထွန်းကားလာခြင်းနှင့် ကျေးလက်မှ မြို့ပြသို့ ရွှေ့ပြောင်းခြင်း",
    "topics": [
      "Push and Pull Factors of Migration",
      "Growth of Megacities and Shantytowns",
      "Urban Environmental Problems",
    ],
    "description_en":
        "Examine migration drivers, urban expansion challenges, and informal settlement living conditions.",
    "description_my":
        "ရွှေ့ပြောင်းရခြင်း၏ တွန်းအား/ဆွဲအားများ၊ မြို့ကြီးများ ချဲ့ထွင်လာမှု စိန်ခေါ်မှုများနှင့် တရားမဝင် ရပ်ကွက်များ၏ အခြေအနေကို လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Sustainable Urban Development Studio",
    "title_my": "ရေရှည်တည်တံ့သော မြို့ပြ ဖွံ့ဖြိုးတိုးတက်မှု အလုပ်ရုံ",
    "topics": [
      "Eco-Cities and Smart Transport",
      "Slum Upgrading Projects",
      "Exam Practice",
    ],
    "description_en":
        "Design sustainable urban planning strategies to manage rapid population growth and environmental strain.",
    "description_my":
        "လူဦးရေ လျင်မြန်စွာ တိုးပွားမှုနှင့် ပတ်ဝန်းကျင် ဖိအားကို စီမံခန့်ခွဲရန် ရေရှည်တည်တံ့သော မြို့ပြ စီမံကိန်း မဟာဗျူဟာများကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 8: Natural Ecosystems and Human Impacts =================
  {
    "week": 29,
    "term": 8,
    "theme": "Ecosystems",
    "title_en": "Structure and Function of Ecosystems",
    "title_my": "ဂေဟစနစ်များ၏ ဖွဲ့စည်းပုံနှင့် လုပ်ဆောင်ချက်",
    "topics": [
      "Producers, Consumers, and Decomposers",
      "Energy Flow and Trophic Pyramids",
      "Nutrient Cycling (Carbon and Nitrogen)",
    ],
    "description_en":
        "Analyze ecological interactions, energy flow efficiencies, and biogeochemical nutrient cycles.",
    "description_my":
        "ဂေဟစနစ် အပြန်အလှန် သက်ရောက်မှုများ၊ စွမ်းအင်စီးဆင်းမှု ထိရောက်မှုနှင့် အာဟာရ စက်ဝန်းများကို ခွဲခြမ်းမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Deforestation",
    "title_en": "Deforestation and Habitat Loss",
    "title_my": "သစ်တောပြုန်းတီးမှုနှင့် နေထိုင်ရာ ပျက်စီးဆုံးရှုံးခြင်း",
    "topics": [
      "Causes of Deforestation (Logging, Agriculture, Infrastructure)",
      "Impacts on Biodiversity and Soil Stability",
      "Indigenous Communities Displaced",
    ],
    "description_en":
        "Investigate drivers of forest clearance, biodiversity loss, and socio-economic impacts on indigenous groups.",
    "description_my":
        "သစ်တောခုတ်ထွင်မှု အကြောင်းရင်းများ၊ ဇီဝမျိုးစုံမျိုးကွဲ ဆုံးရှုံးမှုနှင့် တိုင်းရင်းသား လူမျိုးစုများအပေါ် သက်ရောက်မှုကို စူးစမ်းမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Conservation",
    "title_en": "Species and Habitat Conservation",
    "title_my": "မျိုးစိတ်များနှင့် နေထိုင်ရာ ထိန်းသိမ်းခြင်း",
    "topics": [
      "Reasons for Conservation (Ethical, Ecological, Economic)",
      "National Parks and Nature Reserves",
      "Captive Breeding and Seed Banks",
    ],
    "description_en":
        "Evaluate conservation strategies, protected area management, and species preservation programs.",
    "description_my":
        "ထိန်းသိမ်းရေး မဟာဗျူဟာများ၊ ကာကွယ်ထားသော နယ်မြေ စီမံခန့်ခွဲမှုနှင့် မျိုးစိတ် ကာကွယ်ရေး အစီအစဉ်များကို အကဲဖြတ်မည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Conservation Conflict Studio",
    "title_my": "ထိန်းသိမ်းရေး ပဋိပက္ခ အလုပ်ရုံ",
    "topics": [
      "Human-Wildlife Conflicts",
      "Ecotourism Balancing",
      "Exam Practice",
    ],
    "description_en":
        "Analyze human-wildlife conflict scenarios and design balanced conservation management solutions.",
    "description_my":
        "လူနှင့် တောရိုင်းတိရစ္ဆာန် ပဋိပက္ခ အခြေအနေများကို ခွဲခြမ်းစိတ်ဖြာပြီး မျှတသော ထိန်းသိမ်းရေး စီမံခန့်ခွဲမှု ဖြေရှင်းချက်များကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 9: Pollution, Waste Management & Exam Prep =================
  {
    "week": 33,
    "term": 9,
    "theme": "Pollution",
    "title_en": "Air Pollution and Acid Rain",
    "title_my": "လေထုညစ်ညမ်းမှုနှင့် အက်ဆစ်မိုး",
    "topics": [
      "Sulfur Dioxide and Nitrogen Oxides Emissions",
      "Formation of Acid Rain",
      "Impacts on Forests, Aquatic Life, and Buildings",
    ],
    "description_en":
        "Examine air pollutant sources, acid rain chemistry, and widespread environmental degradation impacts.",
    "description_my":
        "လေထု ညစ်ညမ်းစေသော အရင်းအမြစ်များ၊ အက်ဆစ်မိုး ဖြစ်ပေါ်မှု ဓာတုဗေဒနှင့် ပတ်ဝန်းကျင် ပျက်စီးမှုများကို လေ့လာမည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Waste Management",
    "title_en": "Solid Waste Management and Recycling",
    "title_my":
        "ခဲယမ်းအမှိုက် စီမံခန့်ခွဲမှုနှင့် ပြန်လည်အသုံးချခြင်း (Recycling)",
    "topics": [
      "Landfills and Incineration",
      "The 3Rs (Reduce, Reuse, Recycle)",
      "Hazardous and E-Waste Management",
    ],
    "description_en":
        "Evaluate municipal solid waste disposal methods, recycling frameworks, and hazardous waste controls.",
    "description_my":
        "မြို့ပြ အမှိုက်စွန့်ပစ်မှု နည်းလမ်းများ၊ ပြန်လည်အသုံးချရေး မူဘောင်များနှင့် အန္တရာယ်ရှိ အမှိုက် ထိန်းချုပ်မှုကို အကဲဖြတ်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Data Response and Case Study Masterclass",
    "title_my": "ဒေတာ တုံ့ပြန်မှုနှင့် လက်တွေ့လေ့လာမှု အထူးသင်ခန်းစာ",
    "topics": [
      "Interpreting Environmental Data Tables",
      "Evaluating Case Study Evidence",
      "Structuring 6-Mark and 8-Mark Answers",
    ],
    "description_en":
        "Master data interpretation and structured essay writing for IGCSE Environmental Management exams.",
    "description_my":
        "IGCSE Environmental Management စာမေးပွဲများအတွက် ဒေတာ အဓိပ္ပာယ်ဖော်ခြင်းနှင့် ပုံစံကျ အက်ဆေး ရေးသားခြင်းကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Environmental Management Graduation",
    "title_my": "IGCSE ပတ်ဝန်းကျင် စီမံခန့်ခွဲမှု ဘွဲ့နှင်းသဘင် အထိမ်းအမှတ်",
    "topics": [
      "Celebrating Success",
      "Reflecting on Environmental Stewardship",
      "Pathways to Sustainability Careers",
    ],
    "description_en":
        "Celebrate the mastery of IGCSE Environmental Management and preparation for sustainable development studies.",
    "description_my":
        "IGCSE ပတ်ဝန်းကျင် စီမံခန့်ခွဲမှု ပြီးမြောက်မှုကို ဂုဏ်ပြုပြီး ရေရှည်တည်တံ့သော ဖွံ့ဖြိုးတိုးတက်မှု လေ့လာမှုများဆီသို့ ဆက်လက်ချီတက်ရန် အထိမ်းအမှတ်ပြုမည်။",
  },
];
