// File: ai_data_bridge/igcse_combined_science_all_terms.dart
// IGCSE Combined Science Syllabus Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> igcseCombinedScienceAllTermsData = [
  // ================= TERM 1: Biology - Cell Biology & Organisation =================
  {
    "week": 1,
    "term": 1,
    "theme": "Biology - Cells",
    "title_en": "Cell Structure and Organisation",
    "title_my": "ဆဲလ် တည်ဆောက်ပုံနှင့် ဖွဲ့စည်းပုံ",
    "topics": ["Plant and Animal Cells", "Specialised Cells", "Cell Functions"],
    "description_en":
        "Examine the ultrastructure of plant and animal cells and how specialised cells adapt for specific functions.",
    "description_my":
        "အပင်နှင့် တိရစ္ဆာန်ဆဲလ်များ၏ ဖွဲ့စည်းပုံနှင့် သီးသန့်လုပ်ဆောင်ချက်များအတွက် ဆဲလ်များ မည်သို့ လိုက်လျောညီထွေဖြစ်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Biology - Cells",
    "title_en": "Movement In and Out of Cells",
    "title_my": "ဆဲလ်အတွင်းနှင့် အပြင်သို့ ရွေ့လျားခြင်း",
    "topics": ["Diffusion", "Osmosis", "Active Transport"],
    "description_en":
        "Understand the physical and biological processes of diffusion, osmosis, and active transport across cell membranes.",
    "description_my":
        "ဆဲလ်မြှေးပါးကိုဖြတ်၍ ပျံ့နှံ့ခြင်း (Diffusion)၊ ရေစိမ့်ဝင်ခြင်း (Osmosis) နှင့် တက်ကြွစွာ သယ်ယူခြင်း (Active transport) တို့ကို လေ့လာမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Biology - Molecules",
    "title_en": "Biological Molecules and Enzymes",
    "title_my": "ဇီဝ မော်လီကျူးများနှင့် အင်ဇိုင်းများ",
    "topics": [
      "Carbohydrates, Fats, Proteins",
      "Enzyme Action",
      "Effect of Temperature and pH",
    ],
    "description_en":
        "Explore the chemical building blocks of life and how biological catalysts (enzymes) control metabolic reactions.",
    "description_my":
        "အသက်ရှင်ခြင်း၏ ဓာတုအခြေခံများနှင့် ဇီဝဓာတ်ကူပစ္စည်းများ (အင်ဇိုင်းများ) က ဇီဝဖြစ်စဉ်များကို မည်သို့ထိန်းချုပ်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Cellular Biology Practical Lab",
    "title_my": "ဆဲလ်ဇီဝဗေဒ ဓာတ်ခွဲခန်း လက်တွေ့စမ်းသပ်မှု",
    "topics": ["Osmosis Experiments", "Enzyme Testing", "Data Analysis"],
    "description_en":
        "Design and evaluate practical experiments investigating osmosis rates and enzyme activity.",
    "description_my":
        "ရေစိမ့်ဝင်နှုန်းနှင့် အင်ဇိုင်းလုပ်ဆောင်ချက်များကို စမ်းသပ်သည့် လက်တွေ့စမ်းသပ်မှုများကို ဒီဇိုင်းဆွဲ အကဲဖြတ်မည်။",
  },

  // ================= TERM 2: Chemistry - Particulate Nature & Stoichiometry =================
  {
    "week": 5,
    "term": 2,
    "theme": "Chemistry - States of Matter",
    "title_en": "The Particulate Nature of Matter",
    "title_my": "ဒြပ်ဝတ္ထု၏ အမှုန်သဘောသဘာဝ",
    "topics": ["Solid, Liquid, Gas", "Diffusion of Gases", "State Changes"],
    "description_en":
        "Understand particle theory, changes of state, and the experimental evidence for particle diffusion.",
    "description_my":
        "အမှုန်သီအိုရီ၊ အခြေအနေပြောင်းလဲမှုများနှင့် အမှုန်ပျံ့နှံ့ခြင်းအတွက် စမ်းသပ်ချက် အထောက်အထားများကို နားလည်စေမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Chemistry - Atoms",
    "title_en": "Atoms, Elements, and Compounds",
    "title_my": "အက်တမ်၊ ဒြပ်စင်နှင့် ဒြပ်ပေါင်းများ",
    "topics": ["Atomic Structure", "Isotopes", "Ionic and Covalent Bonding"],
    "description_en":
        "Explore atomic structure, electronic configurations, and how atoms bond to form compounds.",
    "description_my":
        "အက်တမ် တည်ဆောက်ပုံ၊ အီလက်ထရွန် စီစဉ်ပုံနှင့် ဒြပ်ပေါင်းများဖြစ်ပေါ်ရန် အက်တမ်များ ချိတ်ဆက်ပုံကို လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Chemistry - Stoichiometry",
    "title_en": "Chemical Equations and Calculations",
    "title_my": "ဓာတုညီမျှခြင်းများနှင့် တွက်ချက်မှုများ",
    "topics": [
      "Writing Balanced Equations",
      "Relative Atomic Mass",
      "Moles Calculations",
    ],
    "description_en":
        "Master balancing chemical equations and calculating quantities using the mole concept.",
    "description_my":
        "ဓာတုညီမျှခြင်းများကို ချိန်ညှိခြင်းနှင့် မိုးလ် (Mole) သဘောတရားကို အသုံးပြု၍ ပမာဏများကို တွက်ချက်ခြင်း ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Stoichiometry Exam Studio",
    "title_my": "စတိုင်ကျီအိုမေတြီ စာမေးပွဲ အလုပ်ရုံ",
    "topics": [
      "Moles Problem Solving",
      "Bonding Analysis",
      "Past Paper Drills",
    ],
    "description_en":
        "Solve rigorous quantitative chemistry problems mirroring IGCSE assessment standards.",
    "description_my":
        "IGCSE စာမေးပွဲ စံနှုန်းများနှင့် ကိုက်ညီသော တင်းကျပ်သည့် ပမာဏပိုင်းဆိုင်ရာ ဓာတုဗေဒ ပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 3: Physics - Motion, Forces and Energy =================
  {
    "week": 9,
    "term": 3,
    "theme": "Physics - Motion",
    "title_en": "Speed, Velocity, and Acceleration",
    "title_my": "အမြန်နှုန်း၊ အဟုန်နှင့် အရှိန်",
    "topics": [
      "Distance-Time Graphs",
      "Speed-Time Graphs",
      "Calculating Acceleration",
    ],
    "description_en":
        "Analyze motion using distance-time and speed-time graphs, calculating acceleration and distance travelled.",
    "description_my":
        "အကွာအဝေး-အချိန်နှင့် အမြန်နှုန်း-အချိန် ဂရပ်များကို အသုံးပြု၍ ရွေ့လျားမှုကို ခွဲခြမ်းစိတ်ဖြာပြီး အရှိန်ကို တွက်ချက်မည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Physics - Forces",
    "title_en": "Effects of Forces",
    "title_my": "အားများ၏ သက်ရောက်မှုများ",
    "topics": [
      "Newton's Laws of Motion",
      "F = ma",
      "Weight and Gravitational Field Strength",
    ],
    "description_en":
        "Apply Newton's laws to calculate force, mass, and acceleration, and understand terminal velocity.",
    "description_my":
        "အား၊ ထုထည်နှင့် အရှိန်ကို တွက်ချက်ရန် နယူတန်၏ နိယာမများကို အသုံးချပြီး အမြင့်ဆုံးအမြန်နှုန်း (Terminal velocity) ကို လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Physics - Energy",
    "title_en": "Energy Resources and Transfer",
    "title_my": "စွမ်းအင် အရင်းအမြစ်များနှင့် ကူးပြောင်းမှု",
    "topics": [
      "Kinetic and Potential Energy",
      "Energy Conservation",
      "Renewable vs Non-Renewable",
    ],
    "description_en":
        "Calculate gravitational potential and kinetic energy, and evaluate global energy resources.",
    "description_my":
        "ဂရာဝီတီ ပိုတန်ရှယ်နှင့် ကိုင်းနက်တစ် စွမ်းအင်များကို တွက်ချက်ပြီး ကမ္ဘာ့စွမ်းအင် အရင်းအမြစ်များကို အကဲဖြတ်မည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Forces and Energy Lab",
    "title_my": "အားနှင့် စွမ်းအင် ဓာတ်ခွဲခန်း",
    "topics": [
      "Practical Mechanics",
      "Energy Efficiency Calculations",
      "Exam Practice",
    ],
    "description_en":
        "Execute practical investigations into motion, falling objects, and energy efficiency.",
    "description_my":
        "ရွေ့လျားမှု၊ ပြုတ်ကျသော အရာဝတ္ထုများနှင့် စွမ်းအင်ထိရောက်မှုဆိုင်ရာ လက်တွေ့စမ်းသပ်မှုများကို လုပ်ဆောင်မည်။",
  },

  // ================= TERM 4: Biology - Plant and Human Nutrition =================
  {
    "week": 13,
    "term": 4,
    "theme": "Biology - Nutrition",
    "title_en": "Photosynthesis in Plants",
    "title_my": "အပင်များ၏ အလင်းမှီစုဖွဲ့ခြင်း",
    "topics": [
      "Leaf Anatomy",
      "Testing Leaves for Starch",
      "Limiting Factors of Photosynthesis",
    ],
    "description_en":
        "Investigate how plants manufacture carbohydrates through photosynthesis and the factors affecting its rate.",
    "description_my":
        "အပင်များသည် အလင်းမှီစုဖွဲ့ခြင်းဖြင့် ကာဗွန်ဟိုက်ဒရိတ် မည်သို့ထုတ်လုပ်ကြောင်းနှင့် နှုန်းကို ထိန်းချုပ်သည့် အကြောင်းရင်းများကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Biology - Nutrition",
    "title_en": "Human Diet and Digestion",
    "title_my": "လူသားတို့၏ အာဟာရနှင့် အစာခြေစနစ်",
    "topics": [
      "Balanced Diet",
      "Alimentary Canal",
      "Chemical Digestion and Absorption",
    ],
    "description_en":
        "Examine human nutritional requirements and the breakdown of food along the digestive tract.",
    "description_my":
        "လူသားတို့၏ အာဟာရ လိုအပ်ချက်များနှင့် အစာခြေလမ်းကြောင်းတစ်လျှောက် အစာခြေဖျက်မှုကို လေ့လာမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Biology - Transport",
    "title_en": "Transport in Plants and Humans",
    "title_my": "အပင်နှင့် လူသားများရှိ သယ်ယူပို့ဆောင်ရေးစနစ်",
    "topics": [
      "Xylem and Phloem",
      "Transpiration",
      "The Human Circulatory System",
    ],
    "description_en":
        "Understand water transport in plants and the mechanics of the human heart and blood vessels.",
    "description_my":
        "အပင်အတွင်း ရေသယ်ယူမှုနှင့် လူ့နှလုံးနှင့် သွေးကြောများ၏ လုပ်ဆောင်ပုံကို နားလည်စေမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Plant & Human Physiology Studio",
    "title_my": "အပင်နှင့် လူ့ဇီဝကမ္မဗေဒ အလုပ်ရုံ",
    "topics": [
      "Transpiration Rate Experiments",
      "Heart Rate Investigations",
      "Data Synthesis",
    ],
    "description_en":
        "Analyze experimental data regarding transpiration pulls and cardiovascular responses to exercise.",
    "description_my":
        "ရေငွေ့ပျံဆွဲအားနှင့် ကိုယ်လက်လှုပ်ရှားမှုအပေါ် နှုန်ခုန်နှုန်း တုံ့ပြန်မှုဆိုင်ရာ စမ်းသပ်ချက် ဒေတာများကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },

  // ================= TERM 5: Chemistry - Acids, Bases and Periodic Table =================
  {
    "week": 17,
    "term": 5,
    "theme": "Chemistry - Reactions",
    "title_en": "Acids, Bases, and Salts",
    "title_my": "အက်ဆစ်၊ ဘေ့စ်နှင့် ဆားများ",
    "topics": [
      "Properties of Acids and Alkalis",
      "Neutralisation",
      "Preparation of Salts",
    ],
    "description_en":
        "Explore the reactions of acids with metals, bases, and carbonates to produce soluble and insoluble salts.",
    "description_my":
        "ပျော်ဝင်နိုင်သောနှင့် မပျော်ဝင်သော ဆားများရရှိရန် အက်ဆစ်များ၏ သတ္တု၊ ဘေ့စ်နှင့် ကာဗွန်နိတ်တို့နှင့် ဓာတ်ပြုမှုကို လေ့လာမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Chemistry - Periodic Table",
    "title_en": "The Periodic Table",
    "title_my": "ဒြပ်စင်အလှည့်ကျဇယား (Periodic Table)",
    "topics": ["Group I Alkali Metals", "Group VII Halogens", "Noble Gases"],
    "description_en":
        "Examine trends in physical and chemical properties across periods and groups, focusing on Groups I, VII, and VIII.",
    "description_my":
        "Group I, VII နှင့် VIII တို့ကို အဓိကထားလျက် အလှည့်ကျဇယား တစ်လျှောက်ရှိ ရုပ်ပိုင်းနှင့် ဓာတုဂုဏ်သတ္တိ ပြောင်းလဲမှုများကို လေ့လာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Chemistry - Metals",
    "title_en": "Properties and Reactivity of Metals",
    "title_my": "သတ္တုများ၏ ဂုဏ်သတ္တိနှင့် ဓာတ်ပြုနိုင်စွမ်း",
    "topics": ["Reactivity Series", "Extraction of Metals", "Alloys"],
    "description_en":
        "Study the metal reactivity series and methods used to extract metals from their ores.",
    "description_my":
        "သတ္တုများ၏ ဓာတ်ပြုနိုင်စွမ်း အစဉ်နှင့် သတ္တုရိုင်းများမှ သတ္တုထုတ်ယူသည့် နည်းလမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Inorganic Chemistry Practical Lab",
    "title_my": "အဂ္ဂနီဗေဒ ဓာတ်ခွဲခန်း လက်တွေ့စမ်းသပ်မှု",
    "topics": [
      "Salt Preparation",
      "Metal Displacement Tests",
      "Identification of Ions",
    ],
    "description_en":
        "Perform chemical tests to prepare salts and identify unknown aqueous ions.",
    "description_my":
        "ဆားများပြင်ဆင်ခြင်းနှင့် အမည်မသိ အိုင်းယွန်းများကို ဖော်ထုတ်သည့် ဓာတုစမ်းသပ်မှုများ လုပ်ဆောင်မည်။",
  },

  // ================= TERM 6: Physics - Thermal Physics & Waves =================
  {
    "week": 21,
    "term": 6,
    "theme": "Physics - Thermal",
    "title_en": "Thermal Energy and Conduction",
    "title_my": "အပူစွမ်းအင်နှင့် အပူကူးပြောင်းခြင်း",
    "topics": [
      "Conduction, Convection, Radiation",
      "Thermal Insulation",
      "State Changes and Latent Heat",
    ],
    "description_en":
        "Investigate mechanisms of thermal energy transfer and the concepts of specific heat capacity.",
    "description_my":
        "အပူစွမ်းအင် ကူးပြောင်းသည့် နည်းလမ်းများနှင့် သီးသန့်အပူဆံ့နှုန်း (Specific heat capacity) သဘောတရားများကို စူးစမ်းမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Physics - Waves",
    "title_en": "General Properties of Waves",
    "title_my": "လှိုင်းများ၏ အထွေထွေ ဂုဏ်သတ္တိများ",
    "topics": [
      "Transverse and Longitudinal Waves",
      "Wave Equation (v = fλ)",
      "Reflection and Refraction",
    ],
    "description_en":
        "Master wave terminology, wave calculations, and wave behaviors including reflection and refraction.",
    "description_my":
        "လှိုင်းဝေါဟာရများ၊ လှိုင်းတွက်ချက်မှုများနှင့် အလင်းပြန်ခြင်း/ယိုင်ခြင်း အပါအဝင် လှိုင်းအမူအကျင့်များကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Physics - Light and Sound",
    "title_en": "Light and Sound Waves",
    "title_my": "အလင်းနှင့် အသံလှိုင်းများ",
    "topics": [
      "Refraction of Light",
      "Total Internal Reflection",
      "Sound Waves and Ultrasound",
    ],
    "description_en":
        "Explore optics, lenses, total internal reflection, and the nature of sound propagation.",
    "description_my":
        "အလင်းယိုင်မှန်ဘီူးများ၊ စုစုပေါင်း အတွင်းဘက်အလင်းပြန်ခြင်း (TIR) နှင့် အသံပျံ့နှံ့မှု သဘောတရားများကို လေ့လာမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Optics and Waves Practical Lab",
    "title_my": "အလင်းနှင့် လှိုင်း ဓာတ်ခွဲခန်း လက်တွေ့စမ်းသပ်မှု",
    "topics": [
      "Snell's Law Experiments",
      "Ripple Tank Wave Studies",
      "Exam Practice",
    ],
    "description_en":
        "Conduct experiments on light refraction through glass blocks and ripple tank wave phenomena.",
    "description_my":
        "ဖန်တုံးများမှတစ်ဆင့် အလင်းယိုင်ခြင်းနှင့် လှိုင်းကန် စမ်းသပ်မှုများကို လုပ်ဆောင်မည်။",
  },

  // ================= TERM 7: Biology - Coordination, Response & Reproduction =================
  {
    "week": 25,
    "term": 7,
    "theme": "Biology - Coordination",
    "title_en": "Coordination and Response",
    "title_my": "ညှိနှိုင်းဆောင်ရွက်မှုနှင့် တုံ့ပြန်ခြင်း",
    "topics": [
      "Nervous System",
      "Reflex Arcs",
      "Hormones and Endocrine System",
    ],
    "description_en":
        "Examine nervous and hormonal communication systems in humans, including reflex actions.",
    "description_my":
        "Reflex actions အပါအဝင် လူသားတို့၏ အာရုံကြောနှင့် ဟိုမုန်း ဆက်သွယ်ရေးစနစ်များကို လေ့လာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Biology - Homeostasis",
    "title_en": "Homeostasis and Excretion",
    "title_my":
        "အတွင်းပိုင်း ဟန်ချက်ညီထိန်းသိမ်းမှု (Homeostasis) နှင့် စွန့်ပစ်ခြင်း",
    "topics": [
      "Control of Blood Glucose",
      "Body Temperature Regulation",
      "Excretory Organs",
    ],
    "description_en":
        "Understand how the human body maintains a constant internal environment and excretes metabolic waste.",
    "description_my":
        "လူ့ခန္ဓာကိုယ်က အတွင်းပိုင်း ဟန်ချက်ညီမှုကို မည်သို့ထိန်းသိမ်းပြီး စွန့်ပစ်ပစ္စည်းများကို ဖယ်ရှားကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Biology - Reproduction",
    "title_en": "Reproduction in Plants and Humans",
    "title_my": "အပင်နှင့် လူသားများ၏ မျိုးပွားခြင်း",
    "topics": [
      "Asexual vs Sexual Reproduction",
      "Pollination and Fertilization",
      "Human Reproductive System",
    ],
    "description_en":
        "Compare sexual and reproductive mechanisms in flowering plants and humans.",
    "description_my":
        "ပန်းပွင့်သော အပင်များနှင့် လူသားများတွင် လိင်ပိုင်းဆိုင်ရာနှင့် လိင်မဲ့ မျိုးပွားမှုစနစ်များကို နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Coordination & Reproduction Review",
    "title_my": "ညှိနှိုင်းမှုနှင့် မျိုးပွားမှု ပြန်လည်သုံးသပ်ခြင်း",
    "topics": ["Hormonal Pathways", "Reproductive Cycles", "Case Studies"],
    "description_en":
        "Synthesize knowledge of physiological coordination and inheritance mechanisms.",
    "description_my":
        "ဇီဝကမ္မဆိုင်ရာ ညှိနှိုင်းမှုနှင့် မျိုးရိုးဗီဇ ယန္တရားများဆိုင်ရာ အသိပညာများကို ပေါင်းစပ်သုံးသပ်မည်။",
  },

  // ================= TERM 8: Chemistry - Air, Water & Organic Chemistry =================
  {
    "week": 29,
    "term": 8,
    "theme": "Chemistry - Environment",
    "title_en": "Air and Water",
    "title_my": "လေထုနှင့် ရေထု",
    "topics": [
      "Composition of Air",
      "Pollution and Greenhouse Gases",
      "Water Treatment",
    ],
    "description_en":
        "Study atmospheric composition, air pollution, greenhouse effects, and safe drinking water production.",
    "description_my":
        "လေထုဖွဲ့စည်းပုံ၊ လေထုညစ်ညမ်းမှု၊ ဖန်လုံအိမ်အာနိသင်နှင့် သောက်သုံးရေ သန့်စင်ထုတ်လုပ်မှုကို လေ့လာမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Chemistry - Organic",
    "title_en": "Introduction to Organic Chemistry",
    "title_my": "အော်ဂဲနစ် ဓာတုဗေဒ မိတ်ဆက်",
    "topics": [
      "Alkanes and Alkenes",
      "Fractional Distillation of Crude Oil",
      "Polymerisation",
    ],
    "description_en":
        "Explore hydrocarbons, fractional distillation of petroleum, and addition polymerisation.",
    "description_my":
        "ဟိုက်ဒရိုကာဘွန်များ၊ ရေနံပေါင်းခံခြင်းနှင့် ပိုလီမာဖြစ်ပေါ်ခြင်းတို့ကို စူးစမ်းမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Biology - Genetics",
    "title_en": "Inheritance, Genes, and Evolution",
    "title_my": "မျိုးရိုးလိုက်ခြင်း၊ ဂျင်းမ်များနှင့် ဆင့်ကဲဖြစ်စဉ်",
    "topics": [
      "DNA and Chromosomes",
      "Monohybrid Crosses",
      "Natural Selection",
    ],
    "description_en":
        "Examine genetic inheritance patterns, Punnett squares, and evolutionary adaptation.",
    "description_my":
        "မျိုးရိုးလိုက်ခြင်း ပုံစံများ၊ Punnett squares များနှင့် ဆင့်ကဲဖြစ်စဉ် လိုက်လျောညီထွေမှုကို လေ့လာမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Organic & Environmental Chemistry Studio",
    "title_my": "အော်ဂဲနစ်နှင့် ပတ်ဝန်းကျင် ဓာတုဗေဒ အလုပ်ရုံ",
    "topics": [
      "Organic Reactions",
      "Environmental Impact Analysis",
      "Exam Problem Solving",
    ],
    "description_en":
        "Solve multi-topic chemical and environmental application problems.",
    "description_my":
        "ဘာသာရပ်ပေါင်းစုံပါဝင်သော ဓာတုဗေဒနှင့် ပတ်ဝန်းကျင်ဆိုင်ရာ လက်တွေ့ပြဿနာများကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 9: Physics - Electricity, Magnetism & Final Prep =================
  {
    "week": 33,
    "term": 9,
    "theme": "Physics - Electricity",
    "title_en": "Electricity and Circuits",
    "title_my": "လျှပ်စစ်နှင့် ပတ်လမ်းများ",
    "topics": [
      "Current, Voltage, Resistance",
      "Ohm's Law (V = IR)",
      "Series and Parallel Circuits",
    ],
    "description_en":
        "Calculate current, voltage, and resistance in series and parallel electrical circuits.",
    "description_my":
        "အန်ကယ်၊ ဗို့အားနှင့် ခံနိုင်ရည်များကို Series နှင့် Parallel ပတ်လမ်းများတွင် တွက်ချက်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Physics - Magnetism",
    "title_en": "Electric Circuits Safety and Magnetism",
    "title_my": "လျှပ်စစ်ပတ်လမ်း လုံခြုံရေးနှင့် သံလိုက်စွမ်းပကား",
    "topics": [
      "Electrical Power and Energy",
      "Fuses and Circuit Breakers",
      "Electromagnets",
    ],
    "description_en":
        "Understand electrical safety, power equations, magnetic fields, and electromagnetic induction.",
    "description_my":
        "လျှပ်စစ်လုံခြုံရေး၊ စွမ်းအားဖော်မြူလာများ၊ သံလိုက်စက်ကွင်းများနှင့် လျှပ်စစ်သံလိုက် လှုံ့ဆော်မှုကို နားလည်စေမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Combined Science Comprehensive Revision",
    "title_my": "ပေါင်းစပ်သိပ္ပံ ခြုံငုံသုံးသပ် လေ့ကျင့်ခန်း",
    "topics": ["Biology Recap", "Chemistry Recap", "Physics Recap"],
    "description_en":
        "Review core concepts across all three sciences in preparation for IGCSE assessment papers.",
    "description_my":
        "IGCSE စာမေးပွဲအတွက် သိပ္ပံဘာသာရပ် သုံးခုလုံး၏ အဓိက သဘောတရားများကို ခြုံငုံသုံးသပ်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "IGCSE Combined Science Mock Examinations",
    "title_my": "IGCSE ပေါင်းစပ်သိပ္ပံ ပုံစံတူ စာမေးပွဲများ",
    "topics": [
      "Multiple Choice Paper",
      "Theory Paper",
      "Practical Test Simulation",
    ],
    "description_en":
        "Sit complete mock IGCSE Combined Science examination papers under strict timed conditions.",
    "description_my":
        "တင်းကျပ်သော အချိန်သတ်မှတ်ချက်ဖြင့် IGCSE ပေါင်းစပ်သိပ္ပံ ပုံစံတူ စာမေးပွဲများကို အစအဆုံး ဖြေဆိုမည်။",
  },
];
