// File: ai_data_bridge/year8_global_perspectives_all_terms.dart
// Year 8 Global Perspectives Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> year8GlobalPerspectivesAllTermsData = [
  // ================= TERM 1: Beliefs and Values =================
  {
    "week": 1,
    "term": 1,
    "theme": "Values",
    "title_en": "What Are Values?",
    "title_my": "တန်ဖိုးထားမှုများဆိုတာ ဘာလဲ?",
    "topics": ["Personal Values", "Family Values", "Cultural Differences"],
    "description_en":
        "Explore what values are and how they shape the way individuals and societies behave.",
    "description_my":
        "တန်ဖိုးထားမှုများဆိုသည်မှာ အဘယ်နည်းနှင့် ၎င်းတို့က လူတစ်ဦးချင်းစီနှင့် လူမှုအသိုင်းအဝိုင်းများ၏ အပြုအမူအပေါ် မည်သို့လွှမ်းမိုးကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Belief Systems",
    "title_en": "World Religions and Beliefs",
    "title_my": "ကမ္ဘာ့ ဘာသာတရားများနှင့် ယုံကြည်မှုများ",
    "topics": ["Major Religions", "Secular Beliefs", "Respecting Differences"],
    "description_en":
        "Investigate different belief systems around the world and the importance of mutual respect.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ မတူညီသော ယုံကြည်မှုစနစ်များနှင့် အပြန်အလှန် လေးစားမှု၏ အရေးပါပုံကို လေ့လာမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Ethics",
    "title_en": "Right and Wrong",
    "title_my": "အမှား နှင့် အမှန်",
    "topics": ["Moral Dilemmas", "Consequences", "Ethical Choices"],
    "description_en":
        "Discuss complex moral dilemmas and how different people decide what is right or wrong.",
    "description_my":
        "ရှုပ်ထွေးသော ကိုယ်ကျင့်တရားဆိုင်ရာ အကျပ်အတည်းများနှင့် လူအမျိုးမျိုးက အမှား၊ အမှန်ကို မည်သို့ဆုံးဖြတ်ကြောင်း ဆွေးနွေးမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Values in Action",
    "title_my": "တန်ဖိုးထားမှုများကို လက်တွေ့အသုံးချခြင်း",
    "topics": ["Role-play", "Debating Ethics", "Case Studies"],
    "description_en":
        "Apply your understanding of values and ethics to resolve a fictional community dispute.",
    "description_my":
        "စိတ်ကူးယဉ် လူမှုအသိုင်းအဝိုင်း အငြင်းပွားမှုတစ်ခုကို ဖြေရှင်းရန် တန်ဖိုးထားမှုနှင့် ကျင့်ဝတ်များကို လက်တွေ့အသုံးချမည်။",
  },

  // ================= TERM 2: The Digital World =================
  {
    "week": 5,
    "term": 2,
    "theme": "Technology and Society",
    "title_en": "Living Online",
    "title_my": "အွန်လိုင်းပေါ်တွင် နေထိုင်ခြင်း",
    "topics": ["Digital Citizenship", "Social Media Impact", "Online Identity"],
    "description_en":
        "Examine the positive and negative impacts of living in a hyper-connected digital world.",
    "description_my":
        "အလွန်အမင်း ချိတ်ဆက်နေသော ဒီဂျစ်တယ်ကမ္ဘာတွင် နေထိုင်ရခြင်း၏ ကောင်းကျိုးနှင့် ဆိုးကျိုးများကို လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Technology and Society",
    "title_en": "The Digital Divide",
    "title_my": "ဒီဂျစ်တယ် ကွာဟမှု",
    "topics": ["Access to Technology", "Global Inequality", "Education Gap"],
    "description_en":
        "Understand the 'digital divide' and how lack of internet access affects education and jobs globally.",
    "description_my":
        "အင်တာနက် မရရှိခြင်းက ကမ္ဘာတစ်ဝန်းရှိ ပညာရေးနှင့် အလုပ်အကိုင်များအပေါ် မည်သို့သက်ရောက်နေသည့် 'ဒီဂျစ်တယ် ကွာဟမှု' ကို နားလည်စေမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Information",
    "title_en": "The Spread of Misinformation",
    "title_my": "သတင်းမှားများ ပျံ့နှံ့ခြင်း",
    "topics": ["Fake News", "Echo Chambers", "Fact-Checking Tools"],
    "description_en":
        "Learn how false information spreads online and how to critically evaluate digital sources.",
    "description_my":
        "အွန်လိုင်းတွင် သတင်းမှားများ မည်သို့ပျံ့နှံ့ကြောင်းနှင့် ဒီဂျစ်တယ် သတင်းရင်းမြစ်များကို စဉ်းစားချင့်ချိန် အကဲဖြတ်နည်းကို လေ့လာမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Digital Awareness Campaign",
    "title_my": "ဒီဂျစ်တယ် အသိပညာပေး ကမ်ပိန်း",
    "topics": ["Designing Media", "Targeting Audiences", "Promoting Safety"],
    "description_en":
        "Create a multimedia campaign to raise awareness about digital safety or the digital divide.",
    "description_my":
        "ဒီဂျစ်တယ် လုံခြုံရေး (သို့) ဒီဂျစ်တယ် ကွာဟမှုအကြောင်း အသိပညာပေးရန် မာလ်တီမီဒီယာ ကမ်ပိန်းတစ်ခု ဖန်တီးမည်။",
  },

  // ================= TERM 3: Human Rights =================
  {
    "week": 9,
    "term": 3,
    "theme": "Rights and Responsibilities",
    "title_en": "Universal Declaration of Human Rights",
    "title_my": "ကမ္ဘာ့ကုလသမဂ္ဂ လူ့အခွင့်အရေး ကြေညာစာတမ်း",
    "topics": ["History of UDHR", "Basic Rights", "Freedom"],
    "description_en":
        "Study the Universal Declaration of Human Rights and why it was created.",
    "description_my":
        "ကမ္ဘာ့ကုလသမဂ္ဂ လူ့အခွင့်အရေး ကြေညာစာတမ်းနှင့် ၎င်းကို အဘယ်ကြောင့် ဖန်တီးခဲ့ရကြောင်း လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Rights and Responsibilities",
    "title_en": "Children's Rights",
    "title_my": "ကလေးသူငယ် အခွင့်အရေးများ",
    "topics": ["UNCRC", "Right to Play", "Protection from Harm"],
    "description_en":
        "Focus on the specific rights of children around the world and how they are protected.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ ကလေးသူငယ်များ၏ သီးခြားအခွင့်အရေးများနှင့် ၎င်းတို့ကို မည်သို့ကာကွယ်ပေးထားကြောင်း အာရုံစိုက်လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Justice",
    "title_en": "Human Rights Violations",
    "title_my": "လူ့အခွင့်အရေး ချိုးဖောက်မှုများ",
    "topics": ["Child Labor", "Discrimination", "Amnesty International"],
    "description_en":
        "Investigate real-world cases where human rights are ignored and the organizations fighting for justice.",
    "description_my":
        "လူ့အခွင့်အရေး လျစ်လျူရှုခံရသည့် လက်တွေ့ဖြစ်ရပ်များနှင့် တရားမျှတမှုအတွက် တိုက်ပွဲဝင်နေသော အဖွဲ့အစည်းများအကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Advocacy Project",
    "title_my": "အခွင့်အရေး ကာကွယ်ပြောဆိုမှု ပရောဂျက်",
    "topics": ["Writing Petitions", "Public Speaking", "Raising Awareness"],
    "description_en":
        "Choose a human rights issue and create an advocacy plan to bring attention to it.",
    "description_my":
        "လူ့အခွင့်အရေး ပြဿနာတစ်ခုကို ရွေးချယ်ပြီး အများပြည်သူ သိရှိလာစေရန် ကာကွယ်ပြောဆိုမှု အစီအစဉ်တစ်ခု ရေးဆွဲမည်။",
  },

  // ================= TERM 4: Disease and Health =================
  {
    "week": 13,
    "term": 4,
    "theme": "Global Health",
    "title_en": "Pandemics and Epidemics",
    "title_my": "ကမ္ဘာလုံးဆိုင်ရာနှင့် ဒေသတွင်း ကူးစက်ရောဂါများ",
    "topics": [
      "How Diseases Spread",
      "Historical Pandemics",
      "Global Response",
    ],
    "description_en":
        "Learn how diseases spread across borders and the global efforts required to stop them.",
    "description_my":
        "ရောဂါများ နိုင်ငံဖြတ်ကျော် မည်သို့ပျံ့နှံ့ကြောင်းနှင့် ၎င်းတို့ကို တားဆီးရန် ကမ္ဘာလုံးဆိုင်ရာ ပူးပေါင်းကြိုးပမ်းမှုများကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Global Health",
    "title_en": "Healthcare Inequality",
    "title_my": "ကျန်းမာရေးစောင့်ရှောက်မှု မညီမျှခြင်း",
    "topics": ["Access to Vaccines", "Developing Nations", "Medical Resources"],
    "description_en":
        "Analyze the unfair distribution of medical resources and vaccines between rich and poor countries.",
    "description_my":
        "ချမ်းသာသောနိုင်ငံများနှင့် ဆင်းရဲသောနိုင်ငံများအကြား ဆေးဝါးနှင့် ကာကွယ်ဆေးများ မမျှမတ ဖြန့်ဝေမှုများကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Well-being",
    "title_en": "Mental Health Globally",
    "title_my": "ကမ္ဘာလုံးဆိုင်ရာ စိတ်ကျန်းမာရေး",
    "topics": ["Cultural Views on Mental Health", "Stigma", "Support Systems"],
    "description_en":
        "Explore how different cultures view mental health and the importance of global support systems.",
    "description_my":
        "ယဉ်ကျေးမှုအမျိုးမျိုးက စိတ်ကျန်းမာရေးကို မည်သို့ရှုမြင်ကြောင်းနှင့် ကမ္ဘာလုံးဆိုင်ရာ ကူညီပံ့ပိုးမှုစနစ်များ၏ အရေးပါပုံကို စူးစမ်းမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Health Policy Proposal",
    "title_my": "ကျန်းမာရေး မူဝါဒ အဆိုပြုချက်",
    "topics": [
      "Researching Solutions",
      "Writing a Proposal",
      "Presenting to Authorities",
    ],
    "description_en":
        "Draft a policy proposal aimed at improving healthcare access for a specific vulnerable group.",
    "description_my":
        "ထိခိုက်လွယ်သော အုပ်စုတစ်စုအတွက် ကျန်းမာရေးစောင့်ရှောက်မှု ပိုမိုရရှိစေရန် ရည်ရွယ်သည့် မူဝါဒအဆိုပြုချက်တစ်ခု ရေးဆွဲမည်။",
  },

  // ================= TERM 5: Work and Employment =================
  {
    "week": 17,
    "term": 5,
    "theme": "The Economy",
    "title_en": "The World of Work",
    "title_my": "အလုပ်အကိုင် ကမ္ဘာ",
    "topics": ["Sectors of Industry", "Unemployment", "The Gig Economy"],
    "description_en":
        "Examine how employment is changing globally, including the rise of freelance and gig work.",
    "description_my":
        "အလွတ်တန်းနှင့် ယာယီအလုပ်များ (Gig economy) တိုးတက်လာခြင်း အပါအဝင် ကမ္ဘာတစ်ဝန်း အလုပ်အကိုင်အခွင့်အလမ်းများ မည်သို့ပြောင်းလဲနေကြောင်း လေ့လာမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "The Economy",
    "title_en": "Workers' Rights",
    "title_my": "အလုပ်သမား အခွင့်အရေးများ",
    "topics": ["Fair Wages", "Safe Conditions", "Trade Unions"],
    "description_en":
        "Understand the importance of workers' rights, fair pay, and safe working conditions.",
    "description_my":
        "အလုပ်သမား အခွင့်အရေးများ၊ တရားမျှတသော လုပ်အားခနှင့် ဘေးကင်းသော လုပ်ငန်းခွင် အခြေအနေများ၏ အရေးပါပုံကို နားလည်စေမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Future Focus",
    "title_en": "Jobs of the Future",
    "title_my": "အနာဂတ် အလုပ်အကိုင်များ",
    "topics": ["Automation", "New Technologies", "Skills for the Future"],
    "description_en":
        "Discuss how robots and AI might replace certain jobs and what new skills will be needed in the future.",
    "description_my":
        "စက်ရုပ်များနှင့် AI များက အလုပ်အချို့ကို မည်သို့ အစားထိုးနိုင်ကြောင်းနှင့် အနာဂတ်တွင် မည်သည့် စွမ်းရည်အသစ်များ လိုအပ်မည်ကို ဆွေးနွေးမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Career Investigation",
    "title_my": "အသက်မွေးဝမ်းကျောင်း စူးစမ်းလေ့လာမှု",
    "topics": [
      "Interviewing Professionals",
      "Mapping Career Paths",
      "Presenting",
    ],
    "description_en":
        "Research a future career, interview a professional, and present your findings on the skills required.",
    "description_my":
        "အနာဂတ် အသက်မွေးဝမ်းကျောင်းတစ်ခုကို သုတေသနပြု၍ ပညာရှင်တစ်ဦးကို အင်တာဗျူးပြီး လိုအပ်သော စွမ်းရည်များကို တင်ဆက်မည်။",
  },

  // ================= TERM 6: Sustainability and the Environment =================
  {
    "week": 21,
    "term": 6,
    "theme": "Environment",
    "title_en": "Biodiversity Loss",
    "title_my": "ဇီဝမျိုးစုံမျိုးကွဲများ ဆုံးရှုံးခြင်း",
    "topics": ["Deforestation", "Endangered Species", "Ecosystem Collapse"],
    "description_en":
        "Investigate why plant and animal species are disappearing and how it affects the planet.",
    "description_my":
        "အပင်နှင့် တိရစ္ဆာန် မျိုးစိတ်များ အဘယ်ကြောင့် ပျောက်ကွယ်နေရကြောင်းနှင့် ၎င်းက ကမ္ဘာမြေအပေါ် မည်သို့သက်ရောက်ကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Environment",
    "title_en": "Sustainable Energy",
    "title_my": "ရေရှည်တည်တံ့သော စွမ်းအင်",
    "topics": [
      "Fossil Fuels vs Renewables",
      "Solar and Wind Power",
      "Nuclear Energy",
    ],
    "description_en":
        "Compare different energy sources and debate the best ways to power our future sustainably.",
    "description_my":
        "စွမ်းအင် အရင်းအမြစ် အမျိုးမျိုးကို နှိုင်းယှဉ်ပြီး အနာဂတ်အတွက် ရေရှည်တည်တံ့သော စွမ်းအင်ရရှိရန် အကောင်းဆုံးနည်းလမ်းများကို ဆွေးနွေးမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Sustainability",
    "title_en": "The Circular Economy",
    "title_my": "စက်ဝိုင်းပုံ စီးပွားရေးစနစ်",
    "topics": [
      "Reduce, Reuse, Recycle",
      "Designing out Waste",
      "Sustainable Fashion",
    ],
    "description_en":
        "Learn about the circular economy, where products are designed to be reused and recycled, rather than thrown away.",
    "description_my":
        "ကုန်ပစ္စည်းများကို စွန့်ပစ်မည့်အစား ပြန်လည်အသုံးပြုနိုင်ရန် ဒီဇိုင်းထုတ်ထားသည့် စက်ဝိုင်းပုံ စီးပွားရေးစနစ် (Circular Economy) အကြောင်း လေ့လာမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Sustainable Business Pitch",
    "title_my": "ရေရှည်တည်တံ့သော စီးပွားရေး အဆိုပြုချက်",
    "topics": ["Eco-friendly Products", "Business Plans", "Persuasion"],
    "description_en":
        "Invent an eco-friendly product or service and pitch it to 'investors' in the classroom.",
    "description_my":
        "သဘာဝပတ်ဝန်းကျင်နှင့် ကိုက်ညီသော ထုတ်ကုန် (သို့) ဝန်ဆောင်မှုတစ်ခုကို တီထွင်ပြီး အတန်းတွင်းရှိ 'ရင်းနှီးမြှုပ်နှံသူများ' ထံ အဆိုပြု တင်ဆက်မည်။",
  },

  // ================= TERM 7: Poverty and Inequality =================
  {
    "week": 25,
    "term": 7,
    "theme": "Global Economics",
    "title_en": "Causes of Poverty",
    "title_my": "ဆင်းရဲမွဲတေမှု၏ အကြောင်းရင်းများ",
    "topics": ["War and Conflict", "Lack of Education", "Natural Disasters"],
    "description_en":
        "Analyze the complex, interconnected reasons why poverty continues to exist in the modern world.",
    "description_my":
        "ခေတ်သစ်ကမ္ဘာတွင် ဆင်းရဲမွဲတေမှု ဆက်လက်တည်ရှိနေရခြင်း၏ ရှုပ်ထွေးပြီး အပြန်အလှန်ဆက်စပ်နေသော အကြောင်းရင်းများကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Global Economics",
    "title_en": "Wealth Distribution",
    "title_my": "ဓနဥစ္စာ ခွဲဝေမှု",
    "topics": ["The 1%", "Taxation", "Economic Systems"],
    "description_en":
        "Examine how global wealth is distributed and debate whether current economic systems are fair.",
    "description_my":
        "ကမ္ဘာ့ဓနဥစ္စာများ ခွဲဝေမှုပုံစံကို လေ့လာပြီး လက်ရှိ စီးပွားရေးစနစ်များသည် တရားမျှတမှု ရှိမရှိ ဆွေးနွေးမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Solutions",
    "title_en": "Foreign Aid and Development",
    "title_my": "နိုင်ငံတကာ အကူအညီ နှင့် ဖွံ့ဖြိုးတိုးတက်ရေး",
    "topics": ["NGOs", "Charity vs Empowerment", "Microfinance"],
    "description_en":
        "Evaluate the effectiveness of foreign aid and microfinance in helping communities lift themselves out of poverty.",
    "description_my":
        "လူမှုအသိုင်းအဝိုင်းများ ဆင်းရဲတွင်းမှ လွတ်ကင်းစေရန် ကူညီရာတွင် နိုင်ငံတကာအကူအညီနှင့် အသေးစားငွေရေးကြေးရေး (Microfinance) တို့၏ ထိရောက်မှုကို အကဲဖြတ်မည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Development Action Plan",
    "title_my": "ဖွံ့ဖြိုးတိုးတက်ရေး လုပ်ငန်းစဉ်",
    "topics": ["Needs Assessment", "Budgeting", "Sustainable Solutions"],
    "description_en":
        "Design a realistic action plan to improve the infrastructure or economy of a specific developing region.",
    "description_my":
        "ဖွံ့ဖြိုးဆဲဒေသတစ်ခု၏ အခြေခံအဆောက်အအုံ (သို့) စီးပွားရေးကို တိုးတက်စေရန် လက်တွေ့ကျသော လုပ်ငန်းစဉ်တစ်ခုကို ရေးဆွဲမည်။",
  },

  // ================= TERM 8: Migration and Communities =================
  {
    "week": 29,
    "term": 8,
    "theme": "Demographics",
    "title_en": "Why People Move",
    "title_my": "လူများ အဘယ်ကြောင့် ရွှေ့ပြောင်းနေထိုင်ကြသနည်း",
    "topics": ["Push and Pull Factors", "Economic Migration", "Refugees"],
    "description_en":
        "Understand the difference between migrants and refugees, and the 'push and pull' factors that cause people to move.",
    "description_my":
        "ရွှေ့ပြောင်းလုပ်သားများနှင့် ဒုက္ခသည်များ၏ ကွာခြားချက်နှင့် လူများကို ရွှေ့ပြောင်းစေသည့် 'တွန်းအားနှင့် ဆွဲအား' (Push and Pull factors) များကို နားလည်စေမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Demographics",
    "title_en": "The Refugee Crisis",
    "title_my": "ဒုက္ခသည် အကျပ်အတည်း",
    "topics": [
      "Asylum Seekers",
      "Camps and Resettlement",
      "Global Responsibility",
    ],
    "description_en":
        "Investigate the challenges faced by refugees and the international laws designed to protect them.",
    "description_my":
        "ဒုက္ခသည်များ ရင်ဆိုင်နေရသော စိန်ခေါ်မှုများနှင့် ၎င်းတို့ကို ကာကွယ်ရန် ပြဋ္ဌာန်းထားသော နိုင်ငံတကာ ဥပဒေများကို စူးစမ်းမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Communities",
    "title_en": "Multicultural Societies",
    "title_my": "ယဉ်ကျေးမှုစုံလင်သော လူမှုအသိုင်းအဝိုင်းများ",
    "topics": ["Integration", "Cultural Exchange", "Overcoming Prejudice"],
    "description_en":
        "Explore the benefits and challenges of living in a diverse, multicultural society.",
    "description_my":
        "ကွဲပြားစုံလင်သော ယဉ်ကျေးမှုများရှိသည့် လူမှုအသိုင်းအဝိုင်းတွင် နေထိုင်ရခြင်း၏ အကျိုးကျေးဇူးများနှင့် စိန်ခေါ်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Community Integration Project",
    "title_my": "လူမှုအသိုင်းအဝိုင်း ပူးပေါင်းပါဝင်မှု ပရောဂျက်",
    "topics": [
      "Event Planning",
      "Promoting Inclusion",
      "Celebrating Diversity",
    ],
    "description_en":
        "Design a community event or initiative to help new migrants feel welcome and integrated.",
    "description_my":
        "ရွှေ့ပြောင်းလာသူအသစ်များ နွေးထွေးစွာ ကြိုဆိုခံရပြီး ပူးပေါင်းပါဝင်နိုင်စေရန် လူထုပွဲတော် (သို့) အစီအစဉ်တစ်ခုကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 9: Year Review & Global Action Project =================
  {
    "week": 33,
    "term": 9,
    "theme": "Review",
    "title_en": "Evaluating Perspectives",
    "title_my": "ရှုထောင့်အမြင်များကို အကဲဖြတ်ခြင်း",
    "topics": [
      "Critical Thinking Recap",
      "Deconstructing Arguments",
      "Forming Opinions",
    ],
    "description_en":
        "Review the crucial skill of breaking down arguments and analyzing them from multiple global perspectives.",
    "description_my":
        "အငြင်းပွားမှုများကို ခွဲခြမ်းစိတ်ဖြာခြင်းနှင့် ကမ္ဘာလုံးဆိုင်ရာ ရှုထောင့်ပေါင်းစုံမှ အကဲဖြတ်ခြင်းစသည့် အရေးကြီးစွမ်းရည်များကို ပြန်လည်သုံးသပ်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Project Preparation",
    "title_en": "Planning Global Action",
    "title_my": "ကမ္ဘာလုံးဆိုင်ရာ လှုပ်ရှားမှု စီစဉ်ခြင်း",
    "topics": [
      "Identifying Local-Global Links",
      "Setting Achievable Goals",
      "Team Roles",
    ],
    "description_en":
        "Identify a local issue with global significance and begin planning a collaborative action project.",
    "description_my":
        "ကမ္ဘာလုံးဆိုင်ရာ အရေးပါမှုရှိသော ဒေသတွင်း ပြဿနာတစ်ခုကို ဖော်ထုတ်ပြီး ပူးပေါင်းလုပ်ဆောင်ရမည့် ပရောဂျက်တစ်ခုကို စတင်စီစဉ်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Action",
    "title_en": "Executing the Project",
    "title_my": "ပရောဂျက်ကို အကောင်အထည်ဖော်ခြင်း",
    "topics": [
      "Taking Real Action",
      "Gathering Data",
      "Problem Solving on the Go",
    ],
    "description_en":
        "Put your plan into action! Run your campaign, fundraiser, or event in the school or community.",
    "description_my":
        "စီမံချက်ကို လက်တွေ့အကောင်အထည်ဖော်မည်! ကျောင်း (သို့) ရပ်ကွက်အတွင်း ကမ်ပိန်း၊ ရန်ပုံငွေရှာဖွေခြင်း သို့မဟုတ် ပွဲတစ်ခုကို ကျင်းပမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "Reflection and Presentation",
    "title_my": "သုံးသပ်ချက်နှင့် တင်ဆက်မှု",
    "topics": ["Evaluating Success", "Lessons Learned", "Final Exhibition"],
    "description_en":
        "Evaluate the success of your action project and present your findings and reflections to the class.",
    "description_my":
        "သင်၏ လှုပ်ရှားမှု ပရောဂျက် အောင်မြင်မှုကို အကဲဖြတ်ပြီး တွေ့ရှိချက်များနှင့် သုံးသပ်ချက်များကို အတန်းရှေ့တွင် တင်ဆက်မည်။",
  },
];
