// File: ai_data_bridge/year9_computing_all_terms.dart
// Year 9 Computing Terms 1 to 9 (Weeks 1-36) - IGCSE Preparatory Year
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> year9ComputingAllTermsData = [
  // ================= TERM 1: Advanced Algorithms and Python =================
  {
    "week": 1,
    "term": 1,
    "theme": "Algorithms",
    "title_en": "Searching Algorithms",
    "title_my": "ရှာဖွေရေး အယ်လဂိုရီသမ်များ (Searching Algorithms)",
    "topics": ["Linear Search", "Binary Search", "Comparing Efficiency"],
    "description_en":
        "Learn and code Linear and Binary search algorithms in Python, analyzing their speed and efficiency.",
    "description_my":
        "Python တွင် Linear နှင့် Binary ရှာဖွေရေး အယ်လဂိုရီသမ်များကို ရေးသားခြင်းနှင့် ၎င်းတို့၏ မြန်ဆန်မှုကို နှိုင်းယှဉ်လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Algorithms",
    "title_en": "Sorting Algorithms",
    "title_my": "အစဉ်လိုက် စီစဉ်သည့် အယ်လဂိုရီသမ်များ (Sorting)",
    "topics": ["Bubble Sort", "Merge Sort", "Algorithm Complexity"],
    "description_en":
        "Understand how Bubble Sort and Merge Sort arrange data in order and measure their performance.",
    "description_my":
        "Bubble Sort နှင့် Merge Sort တို့က အချက်အလက်များကို အစဉ်လိုက် မည်သို့စီစဉ်ကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Python Advanced",
    "title_en": "Error Handling and Validation",
    "title_my": "အမှားများကို ထိန်းချုပ်ခြင်းနှင့် စစ်ဆေးခြင်း",
    "topics": [
      "Try and Except Blocks",
      "Input Validation",
      "Debugging Strategies",
    ],
    "description_en":
        "Write robust Python code that gracefully handles user errors and prevents crashes.",
    "description_my":
        "အသုံးပြုသူ၏ အမှားများကို ထိန်းချုပ်ပေးပြီး ပရိုဂရမ် ရပ်တန့်သွားခြင်းမရှိစေရန် ခိုင်မာသော Python ကုဒ်များ ရေးသားမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Algorithm Performance Analyzer",
    "title_my": "အယ်လဂိုရီသမ် စွမ်းဆောင်ရည် ခွဲခြမ်းစိတ်ဖြာစက်",
    "topics": [
      "Timing Code",
      "Generating Large Datasets",
      "Performance Report",
    ],
    "description_en":
        "Build a Python program that measures how fast different sorting and searching algorithms run.",
    "description_my":
        "ရှာဖွေရေးနှင့် စီစဉ်ရေး အယ်လဂိုရီသမ်များ မည်မျှမြန်ဆန်ကြောင်း တိုင်းတာပေးသည့် Python ပရိုဂရမ်တစ်ခု တည်ဆောက်မည်။",
  },

  // ================= TERM 2: Data Structures and File Handling =================
  {
    "week": 5,
    "term": 2,
    "theme": "Data Structures",
    "title_en": "Advanced Lists and Dictionaries",
    "title_my": "အဆင့်မြင့် စာရင်းများနှင့် ဒစ်ရှင်နရီများ (Dictionaries)",
    "topics": ["2D Lists", "Key-Value Pairs", "Nested Data Structures"],
    "description_en":
        "Master 2D lists and Python dictionaries to organize complex, multi-layered data.",
    "description_my":
        "ရှုပ်ထွေးပြီး အလွှာစုံပါသော အချက်အလက်များကို စနစ်တကျ စီစဉ်ရန် 2D lists နှင့် Python dictionaries များကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "File Handling",
    "title_en": "Reading and Writing Text Files",
    "title_my": "စာသားဖိုင်များကို ဖတ်ရှုခြင်းနှင့် ရေးသားခြင်း",
    "topics": [
      "Open, Read, Write Modes",
      "With Statement",
      "Persistent Storage",
    ],
    "description_en":
        "Learn how Python can save data permanently into text files and read it back later.",
    "description_my":
        "Python သည် အချက်အလက်များကို စာသားဖိုင်များအတွင်း အမြဲတမ်း သိမ်းဆည်းရန်နှင့် ပြန်လည်ဖတ်ရှုရန် မည်သို့လုပ်ဆောင်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "File Handling",
    "title_en": "Working with CSV Files",
    "title_my": "CSV ဖိုင်များနှင့် လုပ်ဆောင်ခြင်း",
    "topics": [
      "Comma-Separated Values",
      "Parsing Data",
      "Tabular Data in Python",
    ],
    "description_en":
        "Process spreadsheet data programmatically using Python's CSV file handling capabilities.",
    "description_my":
        "Python ၏ CSV ဖိုင်စီမံခန့်ခွဲမှု စွမ်းရည်ကို အသုံးပြု၍ ဇယားကွက် အချက်အလက်များကို ပရိုဂရမ်ဖြင့် လုပ်ဆောင်မည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Console-Based Database System",
    "title_my": "ကွန်ဆိုးလ်အခြေခံ ဒေတာဘေ့စ် စနစ်",
    "topics": [
      "CRUD Operations (Create, Read, Update, Delete)",
      "File Storage",
      "User Interface",
    ],
    "description_en":
        "Build a complete data management system in Python that saves records to a file.",
    "description_my":
        "ဖိုင်တစ်ခုအတွင်း မှတ်တမ်းများကို သိမ်းဆည်းပေးပြီး အချက်အလက်များကို စီမံခန့်ခွဲပေးသည့် Python စနစ်တစ်ခု တည်ဆောက်မည်။",
  },

  // ================= TERM 3: Object-Oriented Programming (OOP) =================
  {
    "week": 9,
    "term": 3,
    "theme": "OOP Concepts",
    "title_en": "Introduction to Classes and Objects",
    "title_my": "Classes နှင့် Objects များနှင့် မိတ်ဆက်",
    "topics": [
      "Blueprint Analogy",
      "Defining Classes",
      "Instantiating Objects",
    ],
    "description_en":
        "Understand the core concepts of Object-Oriented Programming by creating custom classes and objects.",
    "description_my":
        "ကိုယ်ပိုင် Classes နှင့် Objects များကို ဖန်တီးခြင်းဖြင့် Object-Oriented Programming ၏ အဓိက သဘောတရားများကို နားလည်စေမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "OOP Concepts",
    "title_en": "Attributes and Methods",
    "title_my": "ဂုဏ်သတ္တိများနှင့် ဖန်ရှင်များ (Attributes & Methods)",
    "topics": [
      "Constructor (__init__)",
      "Instance Variables",
      "Object Functions",
    ],
    "description_en":
        "Add data attributes and behavior methods to your Python classes.",
    "description_my":
        "Python classes များတွင် အချက်အလက် ဂုဏ်သတ္တိများနှင့် လုပ်ဆောင်ချက် ဖန်ရှင်များကို ထည့်သွင်းပုံ လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "OOP Concepts",
    "title_en": "Inheritance",
    "title_my": "အမွေဆက်ခံခြင်း (Inheritance)",
    "topics": [
      "Parent and Child Classes",
      "Method Overriding",
      "Code Reusability",
    ],
    "description_en":
        "Learn how classes can inherit properties and methods from other classes to reuse code efficiently.",
    "description_my":
        "ကုဒ်များကို ထိရောက်စွာ ပြန်လည်အသုံးပြုရန် Classes များသည် အခြားသော Classes များထံမှ ဂုဏ်သတ္တိများကို မည်သို့အမွေဆက်ခံကြောင်း လေ့လာမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "OOP Game Character Engine",
    "title_my": "OOP ဂိမ်းဇာတ်ကောင် အင်ဂျင်",
    "topics": ["Character Classes", "Combat Simulation", "Object Interactions"],
    "description_en":
        "Design an object-oriented simulation where different characters battle using classes and inheritance.",
    "description_my":
        "Classes နှင့် Inheritance များကို အသုံးပြု၍ ဇာတ်ကောင်များ တိုက်ခိုက်သည့် အရာဝတ္ထုအခြေခံ ပုံစံတူ စနစ်တစ်ခု တည်ဆောက်မည်။",
  },

  // ================= TERM 4: Databases and SQL Mastery =================
  {
    "week": 13,
    "term": 4,
    "theme": "Databases",
    "title_en": "Relational Database Design",
    "title_my": "ဆက်စပ် ဒေတာဘေ့စ် ဒီဇိုင်း (Relational Database Design)",
    "topics": [
      "Entities and Attributes",
      "Primary and Foreign Keys",
      "Normalization",
    ],
    "description_en":
        "Design structured relational databases with tables linked by foreign keys.",
    "description_my":
        "Foreign keys ဖြင့် ချိတ်ဆက်ထားသော ဇယားများပါဝင်သည့် စနစ်ကျသော ဆက်စပ် ဒေတာဘေ့စ်များကို ဒီဇိုင်းဆွဲမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "SQL",
    "title_en": "Advanced SQL Queries",
    "title_my": "အဆင့်မြင့် SQL ကွီရီများ (Advanced SQL Queries)",
    "topics": ["JOIN Operations", "GROUP BY", "Aggregate Functions (SUM, AVG)"],
    "description_en":
        "Write advanced SQL statements to combine multiple tables and summarize database data.",
    "description_my":
        "ဇယားများစွာကို ပေါင်းစပ်ရန်နှင့် ဒေတာများကို အနှစ်ချုပ်ရန် အဆင့်မြင့် SQL ညွှန်ကြားချက်များ ရေးသားမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Python & SQL",
    "title_en": "Connecting Python to SQLite",
    "title_my": "Python နှင့် SQLite ချိတ်ဆက်ခြင်း",
    "topics": [
      "SQLite3 Library",
      "Executing SQL from Python",
      "Fetching Results",
    ],
    "description_en":
        "Learn how to write Python code that creates databases, inserts records, and runs queries.",
    "description_my":
        "ဒေတာဘေ့စ်များ ဖန်တီးခြင်း၊ မှတ်တမ်းများ ထည့်သွင်းခြင်းနှင့် ကွီရီများ Run ခြင်းကို Python ဖြင့် မည်သို့လုပ်ဆောင်ရမည်ကို လေ့လာမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Full-Stack Python Inventory System",
    "title_my": "Python ကုန်ပစ္စည်း စာရင်းထိန်းချုပ်ရေး စနစ်",
    "topics": ["Database Integration", "Python Interface", "Reporting"],
    "description_en":
        "Build a robust inventory management system powered by Python and an SQL database backend.",
    "description_my":
        "Python နှင့် SQL ဒေတာဘေ့စ် နောက်ခံစနစ်တို့ကို အသုံးပြု၍ ခိုင်မာသည့် ကုန်ပစ္စည်း စာရင်းထိန်းချုပ်ရေးစနစ် တည်ဆောက်မည်။",
  },

  // ================= TERM 5: Networks, Protocols and Security =================
  {
    "week": 17,
    "term": 5,
    "theme": "Networking",
    "title_en": "Network Protocols",
    "title_my": "ကွန်ရက် ပရိုတိုကောများ (Protocols)",
    "topics": ["TCP/IP Model", "HTTP and HTTPS", "FTP and SMTP"],
    "description_en":
        "Understand the communication protocols that power the internet and data transmission.",
    "description_my":
        "အင်တာနက်နှင့် အချက်အလက် ပို့လွှတ်မှုကို မောင်းနှင်ပေးသော ဆက်သွယ်ရေး ပရိုတိုကောများကို နားလည်စေမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Networking",
    "title_en": "Packet Switching",
    "title_my":
        "အချက်အလက် အထုပ်ငယ်များဖြင့် လွှဲပြောင်းခြင်း (Packet Switching)",
    "topics": ["Data Packets", "Routers and Headers", "Reassembly"],
    "description_en":
        "Trace how large files are broken into packets, routed across the internet, and reassembled.",
    "description_my":
        "ဖိုင်ကြီးများကို အထုပ်ငယ်များအဖြစ် ခွဲထုတ်ခြင်း၊ အင်တာနက်တစ်လျှောက် ပို့ဆောင်ခြင်းနှင့် ပြန်လည်စုစည်းခြင်းတို့ကို ခြေရာခံမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Security",
    "title_en": "Advanced Encryption",
    "title_my": "အဆင့်မြင့် ကုဒ်ဝှက်ခြင်းစနစ် (Encryption)",
    "topics": [
      "Symmetric Encryption",
      "Asymmetric Encryption",
      "Digital Signatures",
    ],
    "description_en":
        "Explore how public and private key encryption secures global digital communication.",
    "description_my":
        "Public နှင့် Private key ကုဒ်ဝှက်ခြင်းစနစ်များသည် ကမ္ဘာ့ဒီဂျစ်တယ် ဆက်သွယ်ရေးကို မည်သို့လုံခြုံစေကြောင်း လေ့လာမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Python Caesar Cipher Tool",
    "title_my": "Python Caesar Cipher ကုဒ်ဝှက်ကိရိယာ",
    "topics": ["String Encryption", "Decryption Logic", "User Interface"],
    "description_en":
        "Code a secure encryption and decryption tool in Python based on classical cipher algorithms.",
    "description_my":
        "ရှေးခေတ် ကုဒ်ဝှက် အယ်လဂိုရီသမ်ကို အခြေခံ၍ Python ဖြင့် လုံခြုံသော ကုဒ်ဝှက်/ကုဒ်ဖြည် ကိရိယာတစ်ခု ရေးသားမည်။",
  },

  // ================= TERM 6: Web Development and APIs =================
  {
    "week": 21,
    "term": 6,
    "theme": "Web Tech",
    "title_en": "Client-Server Architecture",
    "title_my": "Client-Server ဗိသုကာပုံစံ",
    "topics": [
      "Request and Response Cycle",
      "Web Servers",
      "Clients (Browsers)",
    ],
    "description_en":
        "Understand how web browsers interact with remote servers to load websites and apps.",
    "description_my":
        "ဝဘ်ဘရောက်ဆာများသည် ဝဘ်ဆိုက်များနှင့် အက်ပ်များကို ဖွင့်လှူရန် အဝေးရောက် ဆာဗာများနှင့် မည်သို့ချိတ်ဆက်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "APIs",
    "title_en": "Introduction to APIs",
    "title_my": "API များနှင့် မိတ်ဆက်",
    "topics": ["What is an API?", "JSON Format", "Fetching Data"],
    "description_en":
        "Learn how applications talk to each other using Application Programming Interfaces and JSON data.",
    "description_my":
        "အပလီကေးရှင်းများသည် API နှင့် JSON ဒေတာများကို သုံး၍ အချင်းချင်း မည်သို့ဆက်သွယ်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Web Development",
    "title_en": "Building a Basic Web App (Flask)",
    "title_my": "အခြေခံ ဝဘ်အက်ပ် တည်ဆောက်ခြင်း (Flask)",
    "topics": ["Python Web Frameworks", "Routing", "Rendering HTML Templates"],
    "description_en":
        "Use Python and the Flask framework to build and run your very own local web server.",
    "description_my":
        "Python နှင့် Flask ဖရိန်ဝပ်ကို အသုံးပြု၍ ဒေသတွင်း ဝဘ်ဆာဗာတစ်ခု တည်ဆောက်မောင်းနှင်မည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Live Weather Web App",
    "title_my": "အချိန်နှင့်တပြေးညီ ရာသီဥတု ဝဘ်အက်ပ်",
    "topics": ["API Integration", "Flask App", "Displaying Data"],
    "description_en":
        "Build a web application that fetches live weather data from an external API and displays it.",
    "description_my":
        "ပြင်ပ API မှ အချိန်နှင့်တပြေးညီ ရာသီဥတု အချက်အလက်များကို ဆွဲထုတ်ပြသပေးသည့် ဝဘ်အက်ပ်တစ်ခု တည်ဆောက်မည်။",
  },

  // ================= TERM 7: Software Engineering Principles =================
  {
    "week": 25,
    "term": 7,
    "theme": "Software Engineering",
    "title_en": "The Software Development Life Cycle (SDLC)",
    "title_my": "ဆော့ဖ်ဝဲ တည်ဆောက်ရေး သက်တမ်းစက်ဝန်း (SDLC)",
    "topics": [
      "Requirements Analysis",
      "Design and Coding",
      "Testing and Maintenance",
    ],
    "description_en":
        "Study the professional stages of planning, building, and maintaining large software systems.",
    "description_my":
        "ကြီးမားသော ဆော့ဖ်ဝဲစနစ်များကို စီစဉ်ခြင်း၊ တည်ဆောက်ခြင်းနှင့် ထိန်းသိမ်းခြင်းဆိုင်ရာ ပရော်ဖက်ရှင်နယ် အဆင့်များကို လေ့လာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Testing",
    "title_en": "Testing and Debugging Methodologies",
    "title_my": "စမ်းသပ်ခြင်းနှင့် အမှားရှာပြင်ဆင်ခြင်း နည်းလမ်းများ",
    "topics": [
      "White-box vs Black-box Testing",
      "Test Data (Normal, Boundary, Erroneous)",
      "Unit Testing",
    ],
    "description_en":
        "Learn rigorous software testing techniques to ensure programs work under all conditions.",
    "description_my":
        "ပရိုဂရမ်များသည် အခြေအနေအားလုံးတွင် အလုပ်လုပ်ကြောင်း သေချာစေရန် တင်းကျပ်သော ဆော့ဖ်ဝဲ စမ်းသပ်မှုနည်းလမ်းများကို လေ့လာမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Version Control",
    "title_en": "Introduction to Git and Version Control",
    "title_my": "Git နှင့် ဗားရှင်း ထိန်းချုပ်မှုစနစ် မိတ်ဆက်",
    "topics": ["Commit, Push, Pull", "Branching", "Collaborative Coding"],
    "description_en":
        "Understand how developers track code changes and collaborate using Git and GitHub.",
    "description_my":
        "ပရိုဂရမ်မာများသည် Git နှင့် GitHub ကို အသုံးပြု၍ ကုဒ်ပြောင်းလဲမှုများကို ခြေရာခံခြင်းနှင့် ပူးပေါင်းလုပ်ဆောင်ခြင်းတို့ကို လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Open Source Contribution Project",
    "title_my": "ပွင့်လင်းမြင်သာသော ပရောဂျက် ပူးပေါင်းဆောင်ရွက်မှု",
    "topics": ["Git Workflow", "Code Documentation", "Pull Requests"],
    "description_en":
        "Collaborate in teams using Git version control to build and document a Python software project.",
    "description_my":
        "Python ဆော့ဖ်ဝဲ ပရောဂျက်တစ်ခုကို တည်ဆောက်ရန် Git version control ကို သုံး၍ အဖွဲ့လိုက် ပူးပေါင်းလုပ်ဆောင်မည်။",
  },

  // ================= TERM 8: Artificial Intelligence and Data Science =================
  {
    "week": 29,
    "term": 8,
    "theme": "Artificial Intelligence",
    "title_en": "Foundations of Machine Learning",
    "title_my": "စက်သင်ယူမှု အခြေခံများ (Machine Learning)",
    "topics": [
      "Supervised vs Unsupervised Learning",
      "Training Datasets",
      "Prediction Models",
    ],
    "description_en":
        "Explore how machine learning algorithms learn from data to make automated predictions.",
    "description_my":
        "စက်သင်ယူမှု အယ်လဂိုရီသမ်များသည် အလိုအလျောက် ခန့်မှန်းချက်များပြုလုပ်ရန် အချက်အလက်များမှ မည်သို့သင်ယူကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Data Science",
    "title_en": "Data Analysis with Python",
    "title_my": "Python ဖြင့် အချက်အလက် ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": ["Data Cleaning", "Statistical Summary", "Visualizing Data"],
    "description_en":
        "Use Python libraries to clean messy datasets, calculate statistics, and generate charts.",
    "description_my":
        "ရှုပ်ထွေးနေသော အချက်အလက်စုများကို သန့်ရှင်းစင်ကြယ်စေရန်၊ စာရင်းအင်းများ တွက်ချက်ရန် Python လိုက်ဘရီများကို အသုံးပြုမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "AI Ethics",
    "title_en": "Ethics in Artificial Intelligence",
    "title_my": "ဉာဏ်ရည်တုဆိုင်ရာ ကျင့်ဝတ်များ (AI Ethics)",
    "topics": ["Algorithmic Bias", "Data Privacy", "AI Accountability"],
    "description_en":
        "Discuss the ethical challenges of AI, including bias in training data and privacy concerns.",
    "description_my":
        "သင်တန်းပေး အချက်အလက်များအတွင်း ဘက်လိုက်မှုနှင့် ကိုယ်ရေးလုံခြုံရေး အပါအဝင် AI ၏ ကျင့်ဝတ်ဆိုင်ရာ စိန်ခေါ်မှုများကို ဆွေးနွေးမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Predictive Data Model",
    "title_my": "ခန့်မှန်းချက် ထုတ်ပေးသော ဒေတာ မော်ဒယ်",
    "topics": [
      "Dataset Training",
      "Building a Predictor",
      "Evaluating Accuracy",
    ],
    "description_en":
        "Build a simple machine learning model in Python that predicts outcomes based on historical data.",
    "description_my":
        "သမိုင်းဆိုင်ရာ အချက်အလက်များကို အခြေခံ၍ ရလဒ်များကို ခန့်မှန်းပေးသည့် ရိုးရှင်းသော machine learning မော်ဒယ်တစ်ခု တည်ဆောက်မည်။",
  },

  // ================= TERM 9: IGCSE Computer Science Capstone & Review =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "IGCSE Problem-Solving Strategies",
    "title_my": "IGCSE ပြဿနာဖြေရှင်းရေး ဗျူဟာများ",
    "topics": ["Pseudocode Mastery", "Trace Tables", "System Design Questions"],
    "description_en":
        "Master writing pseudocode and interpreting trace tables for IGCSE Computer Science papers.",
    "description_my":
        "IGCSE ကွန်ပျူတာသိပ္ပံ စာမေးပွဲများအတွက် Pseudocode ရေးသားခြင်းနှင့် Trace tables များကို ဖတ်ရှုခြင်း ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Theory Revision (Systems and Networks)",
    "title_my": "သီအိုရီ ပြန်လည်လေ့ကျင့်ခြင်း (စနစ်များနှင့် ကွန်ရက်များ)",
    "topics": [
      "CPU Architecture Recap",
      "Network Topologies Review",
      "Security Recap",
    ],
    "description_en":
        "Comprehensive review of hardware, software, networks, and security theory.",
    "description_my":
        "ဟာ့ဒ်ဝဲ၊ ဆော့ဖ်ဝဲ၊ ကွန်ရက်များနှင့် လုံခြုံရေး သီအိုရီများကို ခြုံငုံသုံးသပ်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Final Project Prep",
    "title_en": "IGCSE Programming Project Planning",
    "title_my": "IGCSE ပရိုဂရမ်ရေးဆွဲရေး ပရောဂျက် စီစဉ်ခြင်း",
    "topics": ["Problem Definition", "Design Specification", "Testing Plan"],
    "description_en":
        "Plan and scope a comprehensive software programming project suitable for high school credit.",
    "description_my":
        "အထက်တန်းအဆင့် ဂုဏ်ထူးနှင့်ညီမျှသော ပြည့်စုံသည့် ဆော့ဖ်ဝဲ ပရိုဂရမ်ရေးဆွဲရေး ပရောဂျက်တစ်ခုကို စီစဉ်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "The Final Computer Science Showcase",
    "title_my": "အပြီးသတ် ကွန်ပျူတာသိပ္ပံ လက်ရာပြပွဲ",
    "topics": [
      "Code Demonstration",
      "Project Presentation",
      "Lower Secondary Completion",
    ],
    "description_en":
        "Present your major programming project, demonstrating code functionality, design, and testing.",
    "description_my":
        "ကုဒ်၏ အလုပ်လုပ်ပုံ၊ ဒီဇိုင်းနှင့် စမ်းသပ်မှုများကို ပြသလျက် သင့်၏ အဓိက ပရိုဂရမ်ရေးဆွဲရေး ပရောဂျက်ကို တင်ပြမည်။",
  },
];
