// File: ai_data_bridge/year7_computing_all_terms.dart
// Year 7 Computing Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> year7ComputingAllTermsData = [
  // ================= TERM 1: Computing Basics & E-Safety =================
  {
    "week": 1,
    "term": 1,
    "theme": "Computer Systems",
    "title_en": "Hardware and Software",
    "title_my": "ဟာ့ဒ်ဝဲ နှင့် ဆော့ဖ်ဝဲ",
    "topics": [
      "Input and Output Devices",
      "CPU and Memory",
      "Operating Systems",
    ],
    "description_en":
        "Understand the difference between physical computer parts and the programs that run them.",
    "description_my":
        "ကွန်ပျူတာ၏ ရုပ်ပိုင်းဆိုင်ရာ အစိတ်အပိုင်းများနှင့် ၎င်းတို့ကို မောင်းနှင်သော ပရိုဂရမ်များအကြား ကွာခြားချက်ကို နားလည်စေမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "E-Safety",
    "title_en": "Staying Safe Online",
    "title_my": "အွန်လိုင်းတွင် လုံခြုံစွာ နေထိုင်ခြင်း",
    "topics": ["Digital Footprint", "Cyberbullying", "Protecting Privacy"],
    "description_en":
        "Learn how to protect your personal information and behave responsibly on the internet.",
    "description_my":
        "ကိုယ်ရေးကိုယ်တာ အချက်အလက်များကို ကာကွယ်နည်းနှင့် အင်တာနက်ပေါ်တွင် တာဝန်သိစွာ ပြုမူနေထိုင်နည်းကို လေ့လာမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "E-Safety",
    "title_en": "Passwords and Security",
    "title_my": "စကားဝှက်များ နှင့် လုံခြုံရေး",
    "topics": ["Strong Passwords", "Phishing Scams", "Malware"],
    "description_en":
        "Discover how to create strong passwords and identify online threats like viruses and scams.",
    "description_my":
        "ခိုင်မာသော စကားဝှက်များ ဖန်တီးနည်းနှင့် ဗိုင်းရပ်စ်များ၊ လိမ်လည်မှုများကဲ့သို့သော အွန်လိုင်းအန္တရာယ်များကို ခွဲခြားသိမြင်နည်းကို လေ့လာမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Digital Citizen Campaign",
    "title_my": "ဒီဂျစ်တယ် နိုင်ငံသား ကမ်ပိန်း",
    "topics": ["Designing Posters", "E-Safety Rules", "Presenting Ideas"],
    "description_en":
        "Create a campaign poster to educate others about the importance of e-safety.",
    "description_my":
        "အွန်လိုင်းလုံခြုံရေး၏ အရေးပါပုံကို အခြားသူများအား ပညာပေးရန် ကမ်ပိန်းပိုစတာတစ်ခု ဖန်တီးမည်။",
  },

  // ================= TERM 2: Computational Thinking =================
  {
    "week": 5,
    "term": 2,
    "theme": "Problem Solving",
    "title_en": "What is an Algorithm?",
    "title_my": "အယ်လဂိုရီသမ် ဆိုတာ ဘာလဲ?",
    "topics": [
      "Step-by-step Instructions",
      "Everyday Algorithms",
      "Clear Instructions",
    ],
    "description_en":
        "Learn what algorithms are and how we use them in our daily lives to solve problems.",
    "description_my":
        "အယ်လဂိုရီသမ် ဆိုသည်မှာ အဘယ်နည်းနှင့် ပြဿနာများဖြေရှင်းရန် နေ့စဉ်ဘဝတွင် ၎င်းတို့ကို မည်သို့အသုံးပြုကြောင်း လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Problem Solving",
    "title_en": "Decomposition",
    "title_my": "ပြဿနာများကို ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": [
      "Breaking Down Problems",
      "Managing Complex Tasks",
      "Logical Thinking",
    ],
    "description_en":
        "Practice breaking down large, complex problems into smaller, manageable parts.",
    "description_my":
        "ကြီးမားရှုပ်ထွေးသော ပြဿနာများကို ကိုင်တွယ်ဖြေရှင်းရ လွယ်ကူစေရန် သေးငယ်သော အစိတ်အပိုင်းများအဖြစ် ခွဲခြမ်းလေ့ကျင့်မည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Problem Solving",
    "title_en": "Flowcharts",
    "title_my": "လုပ်ငန်းစဉ်ပြ ဇယားများ",
    "topics": [
      "Flowchart Symbols",
      "Decisions and Processes",
      "Visualizing Algorithms",
    ],
    "description_en":
        "Use standard symbols to draw flowcharts that represent logical algorithms visually.",
    "description_my":
        "ယုတ္တိကျသော အယ်လဂိုရီသမ်များကို ပုံဖော်ပြသရန် စံသတ်မှတ်ထားသော သင်္ကေတများဖြင့် လုပ်ငန်းစဉ်ပြဇယားများ ရေးဆွဲမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Design an Algorithm",
    "title_my": "အယ်လဂိုရီသမ် တစ်ခု ရေးဆွဲခြင်း",
    "topics": ["Pseudocode", "Testing Logic", "Fixing Errors"],
    "description_en":
        "Write and test an algorithm for a robot to complete a specific task using pseudocode.",
    "description_my":
        "စက်ရုပ်တစ်ခု လုပ်ငန်းဆောင်တာ ပြီးမြောက်စေရန် အယ်လဂိုရီသမ်တစ်ခုကို Pseudocode (ကုဒ်ကြမ်း) ဖြင့် ရေးဆွဲစမ်းသပ်မည်။",
  },

  // ================= TERM 3: Programming Basics =================
  {
    "week": 9,
    "term": 3,
    "theme": "Intro to Coding",
    "title_en": "Sequence in Programming",
    "title_my": "ပရိုဂရမ် ရေးဆွဲခြင်းရှိ အစီအစဉ်များ",
    "topics": ["Block-based Coding", "Order of Commands", "Syntax"],
    "description_en":
        "Start coding by creating simple programs where commands run in a strict order.",
    "description_my":
        "အမိန့်ပေးချက်များ အစီအစဉ်အတိုင်း အလုပ်လုပ်သော ရိုးရှင်းသည့် ပရိုဂရမ်များ ဖန်တီး၍ ကိုဒင်း (Coding) ကို စတင်မည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Intro to Coding",
    "title_en": "Using Variables",
    "title_my": "ပြောင်းလဲကိန်းများ အသုံးပြုခြင်း",
    "topics": ["Storing Data", "Naming Variables", "Updating Values"],
    "description_en":
        "Learn how to use variables as 'boxes' to store and update information in a program.",
    "description_my":
        "ပရိုဂရမ်တစ်ခုအတွင်း အချက်အလက်များ သိမ်းဆည်းရန်နှင့် ပြောင်းလဲရန် ပြောင်းလဲကိန်းများကို 'သေတ္တာ' များကဲ့သို့ မည်သို့အသုံးပြုရမည်ကို လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Intro to Coding",
    "title_en": "Inputs and Outputs",
    "title_my": "အချက်အလက် ထည့်သွင်းခြင်း နှင့် ထုတ်ပေးခြင်း",
    "topics": ["User Input", "Displaying Messages", "Interactive Programs"],
    "description_en":
        "Make your programs interactive by asking the user for input and displaying a response.",
    "description_my":
        "အသုံးပြုသူထံမှ အချက်အလက် တောင်းခံခြင်းနှင့် တုံ့ပြန်မှုများ ပြသခြင်းဖြင့် အပြန်အလှန်တုံ့ပြန်သော ပရိုဂရမ်များ ဖန်တီးမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Chatbot Project",
    "title_my": "စကားပြောစက်ရုပ် (Chatbot) ပရောဂျက်",
    "topics": ["Combining Sequence", "Variables and Input", "Debugging"],
    "description_en":
        "Code a simple interactive chatbot that asks questions and replies using variables.",
    "description_my":
        "အသုံးပြုသူကို မေးခွန်းများမေးပြီး ပြောင်းလဲကိန်းများသုံး၍ ပြန်လည်ဖြေကြားပေးနိုင်သော စကားပြောစက်ရုပ်ငယ်လေးတစ်ခု ရေးဆွဲမည်။",
  },

  // ================= TERM 4: Data Representation =================
  {
    "week": 13,
    "term": 4,
    "theme": "How Computers Think",
    "title_en": "Binary Numbers",
    "title_my": "ဘိုင်နရီ (နှစ်လီစိတ်) ကိန်းများ",
    "topics": ["Base-2 System", "Bits and Bytes", "Counting in Binary"],
    "description_en":
        "Discover how computers only understand 1s and 0s, and learn to count in binary.",
    "description_my":
        "ကွန်ပျူတာများသည် 1 နှင့် 0 ကိုသာ မည်သို့နားလည်ကြောင်း စူးစမ်းပြီး ဘိုင်နရီစနစ်ဖြင့် ရေတွက်နည်းကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "How Computers Think",
    "title_en": "Text to Binary",
    "title_my": "စာသားမှ ဘိုင်နရီသို့ ပြောင်းလဲခြင်း",
    "topics": ["ASCII Code", "Encoding", "Decoding"],
    "description_en":
        "Learn how the alphabet is translated into binary code so computers can process text.",
    "description_my":
        "ကွန်ပျူတာများ စာသားများကို လုပ်ဆောင်နိုင်ရန် အက္ခရာများကို ဘိုင်နရီကုဒ်အဖြစ် မည်သို့ပြောင်းလဲကြောင်း လေ့လာမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "How Computers Think",
    "title_en": "Images and Pixels",
    "title_my": "ပုံရိပ်များ နှင့် ပစ်ဇယ်များ",
    "topics": ["Bitmap Images", "Resolution", "Color Depth"],
    "description_en":
        "Explore how pictures are made up of tiny colored squares called pixels.",
    "description_my":
        "ဓာတ်ပုံများကို ပစ်ဇယ်ဟုခေါ်သော ရောင်စုံလေးထောင့်ကွက်ငယ်လေးများဖြင့် မည်သို့ ဖွဲ့စည်းထားကြောင်း လေ့လာမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Binary Pixel Art",
    "title_my": "ဘိုင်နရီ ပစ်ဇယ်အနုပညာ",
    "topics": ["Creating Images with 1s and 0s", "Grid Drawings", "Data Size"],
    "description_en":
        "Use binary code to design and encode your own black-and-white pixel art.",
    "description_my":
        "ဘိုင်နရီကုဒ် 1 နှင့် 0 များကို အသုံးပြု၍ ကိုယ်ပိုင် အဖြူအမည်း ပစ်ဇယ်အနုပညာကို ဒီဇိုင်းဆွဲဖန်တီးမည်။",
  },

  // ================= TERM 5: Networks & The Internet =================
  {
    "week": 17,
    "term": 5,
    "theme": "Connectivity",
    "title_en": "What is a Network?",
    "title_my": "ကွန်ရက် ဆိုတာ ဘာလဲ?",
    "topics": ["LAN vs WAN", "Servers and Clients", "Wired vs Wireless"],
    "description_en":
        "Understand how computers connect to each other to form networks and share data.",
    "description_my":
        "အချက်အလက်များ ဖလှယ်ရန် ကွန်ပျူတာများ အချင်းချင်း မည်သို့ချိတ်ဆက်၍ ကွန်ရက်များ ဖွဲ့စည်းထားကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Connectivity",
    "title_en": "How the Internet Works",
    "title_my": "အင်တာနက် အလုပ်လုပ်ပုံ",
    "topics": ["Packets", "Routers", "Global Cables"],
    "description_en":
        "Trace the journey of a message as it travels across the world through the internet.",
    "description_my":
        "မက်ဆေ့ချ်တစ်ခုသည် အင်တာနက်မှတစ်ဆင့် ကမ္ဘာတစ်ဝန်းသို့ မည်သို့ဖြတ်သန်းသွားလာကြောင်း လေ့လာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Connectivity",
    "title_en": "IP Addresses and DNS",
    "title_my": "IP လိပ်စာများ နှင့် DNS",
    "topics": ["Website Addresses", "Domain Names", "Finding Webpages"],
    "description_en":
        "Learn how the Domain Name System (DNS) acts like the phonebook of the internet.",
    "description_my":
        "အင်တာနက်၏ ဖုန်းစာအုပ်သဖွယ် လုပ်ဆောင်ပေးသော DNS စနစ်အကြောင်း လေ့လာမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Network Architect",
    "title_my": "ကွန်ရက် ဗိသုကာ",
    "topics": ["Designing a School Network", "Hardware Choices", "Security"],
    "description_en":
        "Design a basic network topology map for a small school or business.",
    "description_my":
        "ကျောင်း (သို့) လုပ်ငန်းငယ်တစ်ခုအတွက် အခြေခံ ကွန်ရက်ချိတ်ဆက်မှု မြေပုံ (Topology) တစ်ခုကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 6: Intermediate Programming =================
  {
    "week": 21,
    "term": 6,
    "theme": "Control Structures",
    "title_en": "Selection (IF Statements)",
    "title_my": "ရွေးချယ်ခြင်း (IF အမိန့်ပေးချက်များ)",
    "topics": ["Conditionals", "True or False", "Branching Paths"],
    "description_en":
        "Teach your programs to make decisions using IF/THEN statements based on conditions.",
    "description_my":
        "အခြေအနေများအပေါ် မူတည်၍ ဆုံးဖြတ်ချက်များချနိုင်ရန် ပရိုဂရမ်များကို IF/THEN အမိန့်များသုံး၍ သင်ကြားပေးမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Control Structures",
    "title_en": "Iteration (Loops)",
    "title_my": "ထပ်ော့လုပ်ဆောင်ချက်များ (Loops)",
    "topics": ["For Loops", "While Loops", "Efficiency"],
    "description_en":
        "Use loops to repeat actions in your code without having to type them out multiple times.",
    "description_my":
        "ကုဒ်များကို အကြိမ်ကြိမ် ရိုက်ထည့်စရာမလိုဘဲ လုပ်ဆောင်ချက်များ ထပ်ခါတလဲလဲ လုပ်ဆောင်ရန် Loop များကို အသုံးပြုမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Control Structures",
    "title_en": "Debugging Code",
    "title_my": "ကုဒ်အမှားများ ရှာဖွေပြင်ဆင်ခြင်း",
    "topics": ["Syntax Errors", "Logic Errors", "Testing"],
    "description_en":
        "Learn strategies for finding and fixing errors when your program doesn't work correctly.",
    "description_my":
        "ပရိုဂရမ် အလုပ်မလုပ်သောအခါ အမှားများကို ရှာဖွေပြီး ပြင်ဆင်နိုင်မည့် ဗျူဟာများကို လေ့လာမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Number Guessing Game",
    "title_my": "ဂဏန်းခန့်မှန်း ဂိမ်း",
    "topics": ["Random Numbers", "Combining Loops and IFs", "User Interface"],
    "description_en":
        "Program a complete game where the user has to guess a randomly generated number.",
    "description_my":
        "ပရိုဂရမ်က ကျပန်းရွေးချယ်ထားသော ဂဏန်းကို အသုံးပြုသူက ခန့်မှန်းရမည့် ဂိမ်းတစ်ခုကို အစအဆုံး ရေးဆွဲမည်။",
  },

  // ================= TERM 7: Web Development Basics =================
  {
    "week": 25,
    "term": 7,
    "theme": "Building the Web",
    "title_en": "Introduction to HTML",
    "title_my": "HTML နှင့် မိတ်ဆက်ခြင်း",
    "topics": [
      "Tags and Elements",
      "Webpage Structure",
      "Headings and Paragraphs",
    ],
    "description_en":
        "Learn the basic language of the web (HTML) to structure your first webpage.",
    "description_my":
        "သင်၏ ပထမဆုံး ဝဘ်စာမျက်နှာကို တည်ဆောက်ရန် ဝဘ်၏ အခြေခံဘာသာစကား (HTML) ကို လေ့လာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Building the Web",
    "title_en": "Adding Media",
    "title_my": "မီဒီယာများ ထည့်သွင်းခြင်း",
    "topics": ["Images", "Hyperlinks", "Lists"],
    "description_en":
        "Enhance your webpages by inserting pictures, lists, and links to other websites.",
    "description_my":
        "ဝဘ်စာမျက်နှာများတွင် ဓာတ်ပုံများ၊ စာရင်းများနှင့် အခြားဝဘ်ဆိုက်များသို့ လင့်ခ်များ ထည့်သွင်းနည်းကို လေ့လာမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Building the Web",
    "title_en": "Introduction to CSS",
    "title_my": "CSS နှင့် မိတ်ဆက်ခြင်း",
    "topics": ["Colors and Fonts", "Styling Text", "Basic Layout"],
    "description_en":
        "Use Cascading Style Sheets (CSS) to add colors, fonts, and style to your plain HTML.",
    "description_my":
        "ရိုးရှင်းသော HTML ကို အရောင်များ၊ ဖောင့်များနှင့် ဒီဇိုင်းများ ပြင်ဆင်ရန် CSS ကို အသုံးပြုမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Personal Portfolio Webpage",
    "title_my": "ကိုယ်ပိုင် ပရိုဖိုင် ဝဘ်စာမျက်နှာ",
    "topics": ["Coding HTML/CSS", "Designing Layout", "Publishing"],
    "description_en":
        "Code a beautifully styled, single-page website about your hobbies and interests.",
    "description_my":
        "သင်၏ ဝါသနာများနှင့် စိတ်ဝင်စားမှုများအကြောင်း ရေးသားထားသော လှပသည့် ဝဘ်စာမျက်နှာတစ်ခုကို ကိုယ်တိုင်ရေးဆွဲမည်။",
  },

  // ================= TERM 8: Data and Databases =================
  {
    "week": 29,
    "term": 8,
    "theme": "Handling Information",
    "title_en": "Introduction to Spreadsheets",
    "title_my": "Spreadsheet များနှင့် မိတ်ဆက်",
    "topics": ["Rows, Columns, Cells", "Data Entry", "Formatting"],
    "description_en":
        "Learn how to use spreadsheet software to organize and format tabular data.",
    "description_my":
        "ဇယားကွက်များအတွင်း အချက်အလက်များ စနစ်တကျ ထည့်သွင်းရန် Spreadsheet ဆော့ဖ်ဝဲလ် အသုံးပြုနည်းကို လေ့လာမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Handling Information",
    "title_en": "Formulas and Functions",
    "title_my": "ဖော်မြူလာများ နှင့် ဖန်ရှင်များ",
    "topics": ["SUM, AVERAGE", "Basic Math", "Automating Calculations"],
    "description_en":
        "Use formulas and functions to make the computer perform automatic calculations.",
    "description_my":
        "ကွန်ပျူတာမှ အလိုအလျောက် တွက်ချက်မှုများ ပြုလုပ်ပေးနိုင်ရန် ဖော်မြူလာများနှင့် ဖန်ရှင်များကို အသုံးပြုမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Handling Information",
    "title_en": "Databases Basics",
    "title_my": "ဒေတာဘေ့စ် (အချက်အလက်သိုလှောင်မှု) အခြေခံ",
    "topics": ["Fields and Records", "Searching Data", "Sorting Data"],
    "description_en":
        "Understand how flat-file databases work for storing, searching, and sorting large amounts of data.",
    "description_my":
        "အချက်အလက် အမြောက်အများကို သိမ်းဆည်းရန်၊ ရှာဖွေရန်နှင့် စီစဉ်ရန် ဒေတာဘေ့စ်များ မည်သို့အလုပ်လုပ်ကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "The Data Analyst",
    "title_my": "အချက်အလက် ခွဲခြမ်းစိတ်ဖြာသူ",
    "topics": ["Creating Charts", "Drawing Conclusions", "Presenting Data"],
    "description_en":
        "Analyze a real-world dataset, create charts, and present your findings to the class.",
    "description_my":
        "လက်တွေ့ အချက်အလက်များကို ခွဲခြမ်းစိတ်ဖြာခြင်း၊ ဇယားများဆွဲခြင်းနှင့် တွေ့ရှိချက်များကို အတန်းရှေ့တွင် တင်ပြခြင်းများ ပြုလုပ်မည်။",
  },

  // ================= TERM 9: Future Tech & Year Review =================
  {
    "week": 33,
    "term": 9,
    "theme": "Looking Ahead",
    "title_en": "Artificial Intelligence (AI)",
    "title_my": "ဉာဏ်ရည်တု (AI)",
    "topics": ["Machine Learning", "Smart Assistants", "Ethics of AI"],
    "description_en":
        "Explore what AI is, how computers learn from data, and the ethical questions it raises.",
    "description_my":
        "AI ဆိုသည်မှာ အဘယ်နည်း၊ ကွန်ပျူတာများ မည်သို့ သင်ယူကြသည်နှင့် AI ဆိုင်ရာ ကျင့်ဝတ်များကို စူးစမ်းမည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Looking Ahead",
    "title_en": "Robotics and Automation",
    "title_my": "စက်ရုပ်များ နှင့် အလိုအလျောက်စနစ်များ",
    "topics": ["Sensors and Actuators", "Real-world Robots", "Future Jobs"],
    "description_en":
        "Learn how robots interact with the physical world and how automation is changing the future.",
    "description_my":
        "စက်ရုပ်များသည် ရုပ်ပိုင်းဆိုင်ရာလောကနှင့် မည်သို့ချိတ်ဆက်လုပ်ဆောင်ကြောင်းနှင့် အလိုအလျောက်စနစ်များ၏ အနာဂတ်အကြောင်း လေ့လာမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Year 7 Review",
    "title_en": "Computing Skills Revision",
    "title_my": "Computing စွမ်းရည်များ ပြန်လည်လေ့ကျင့်ခြင်း",
    "topics": ["Programming Recap", "Data Recap", "Hardware Recap"],
    "description_en":
        "Consolidate your knowledge by reviewing the core computing topics covered in Year 7.",
    "description_my":
        "Year 7 တွင် သင်ယူခဲ့သော အဓိက ကွန်ပျူတာသိပ္ပံ အကြောင်းအရာများကို ပြန်လည်လေ့ကျင့်ခြင်းဖြင့် အသိပညာကို ခိုင်မာစေမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "Tech Innovator Presentation",
    "title_my": "နည်းပညာ တီထွင်သူ တင်ဆက်မှု",
    "topics": [
      "Designing a Future App",
      "Solving Problems with Tech",
      "Pitching Ideas",
    ],
    "description_en":
        "Invent a conceptual app or technology to solve a global problem and pitch your idea.",
    "description_my":
        "ကမ္ဘာ့ပြဿနာတစ်ခုကို ဖြေရှင်းနိုင်မည့် အက်ပ် (သို့) နည်းပညာအသစ်တစ်ခုကို စိတ်ကူးယဉ်ဖန်တီး၍ အဆိုပြု တင်ဆက်မည်။",
  },
];
