// File: ai_data_bridge/year8_computing_all_terms.dart
// Year 8 Computing Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> year8ComputingAllTermsData = [
  // ================= TERM 1: Advanced Computer Systems =================
  {
    "week": 1,
    "term": 1,
    "theme": "Inside the Computer",
    "title_en": "The CPU and Memory",
    "title_my": "CPU နှင့် မှတ်ဉာဏ် (Memory)",
    "topics": ["Fetch-Execute Cycle", "RAM vs ROM", "Cache Memory"],
    "description_en":
        "Take a deep dive into how the Central Processing Unit works and the different types of computer memory.",
    "description_my":
        "ဗဟိုလုပ်ဆောင်ချက်ယူနစ် (CPU) အလုပ်လုပ်ပုံနှင့် ကွန်ပျူတာ မှတ်ဉာဏ်အမျိုးအစားများကို အသေးစိတ် လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Inside the Computer",
    "title_en": "Storage Devices",
    "title_my": "အချက်အလက် သိုလှောင်သည့် ကိရိယာများ",
    "topics": ["Magnetic vs Solid State", "Optical Storage", "Cloud Storage"],
    "description_en":
        "Compare different ways computers store data permanently, including hard drives and the cloud.",
    "description_my":
        "Hard drives နှင့် Cloud အပါအဝင် ကွန်ပျူတာများ အချက်အလက် အမြဲတမ်းသိုလှောင်သည့် နည်းလမ်းအမျိုးမျိုးကို နှိုင်းယှဉ်မည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Networks",
    "title_en": "Network Topologies",
    "title_my": "ကွန်ရက် ချိတ်ဆက်မှု ပုံစံများ (Topologies)",
    "topics": [
      "Star, Ring, and Bus",
      "Network Hardware",
      "Switches and Routers",
    ],
    "description_en":
        "Learn the different ways computers are physically connected in a network and the hardware used.",
    "description_my":
        "ကွန်ရက်တစ်ခုအတွင်း ကွန်ပျူတာများ ချိတ်ဆက်ထားပုံ အမျိုးမျိုးနှင့် အသုံးပြုသော ဟာ့ဒ်ဝဲများကို လေ့လာမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Build a PC Project",
    "title_my": "ကွန်ပျူတာ တည်ဆောက်ခြင်း ပရောဂျက်",
    "topics": ["Choosing Components", "Understanding Specs", "Budgeting"],
    "description_en":
        "Research and select the best components to virtually 'build' a PC for a specific purpose.",
    "description_my":
        "သတ်မှတ်ထားသော ရည်ရွယ်ချက်အတွက် အကောင်းဆုံး ကွန်ပျူတာ အစိတ်အပိုင်းများကို ရွေးချယ်ပြီး ပုံစံတူ ကွန်ပျူတာ တည်ဆောက်မည်။",
  },

  // ================= TERM 2: Advanced Data Representation =================
  {
    "week": 5,
    "term": 2,
    "theme": "Binary Logic",
    "title_en": "Binary Addition",
    "title_my": "ဘိုင်နရီ (နှစ်လီစိတ်) ပေါင်းခြင်း",
    "topics": ["Adding 1s and 0s", "Overflow Errors", "Binary Math"],
    "description_en":
        "Learn the rules of binary math and how computers add numbers together.",
    "description_my":
        "ဘိုင်နရီ သင်္ချာစည်းမျဉ်းများနှင့် ကွန်ပျူတာများ ကိန်းဂဏန်းများ မည်သို့ပေါင်းကြောင်းကို လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Binary Logic",
    "title_en": "Logic Gates",
    "title_my": "လော့ဂျစ် ဂိတ်များ",
    "topics": ["AND, OR, NOT Gates", "Truth Tables", "Logic Circuits"],
    "description_en":
        "Discover the physical building blocks of processors and how they make logical decisions.",
    "description_my":
        "ပရိုဆက်ဆာများ၏ အခြေခံ ဖွဲ့စည်းပုံနှင့် ၎င်းတို့ ယုတ္တိကျကျ မည်သို့ဆုံးဖြတ်ချက်ချကြောင်းကို စူးစမ်းမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Hexadecimal",
    "title_en": "Introduction to Hexadecimal",
    "title_my": "ဟက်ဇာဒက်ဆီမယ် (Hexadecimal) နှင့် မိတ်ဆက်",
    "topics": ["Base-16 System", "Converting to Binary", "Color Codes"],
    "description_en":
        "Understand the Hexadecimal system and why programmers use it to represent colors and memory.",
    "description_my":
        "Hexadecimal (၁၆-လီစိတ်) စနစ်အကြောင်းနှင့် ပရိုဂရမ်မာများက အရောင်များနှင့် မှတ်ဉာဏ်များကို ဖော်ပြရန် ၎င်းကို အဘယ်ကြောင့်သုံးကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "The Logic Puzzle",
    "title_my": "လော့ဂျစ် ပဟေဠိ",
    "topics": ["Drawing Circuits", "Solving Truth Tables", "Applying Logic"],
    "description_en":
        "Design a complex logic circuit using AND, OR, and NOT gates to solve a specific problem.",
    "description_my":
        "သတ်မှတ်ပြဿနာတစ်ခု ဖြေရှင်းရန် AND, OR, NOT ဂိတ်များ အသုံးပြု၍ ရှုပ်ထွေးသော လော့ဂျစ်ပတ်လမ်းတစ်ခုကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 3: Introduction to Text-Based Programming (Python) =================
  {
    "week": 9,
    "term": 3,
    "theme": "Python Basics",
    "title_en": "Hello, Python!",
    "title_my": "မင်္ဂလာပါ Python!",
    "topics": ["Text-based Coding", "The Print Statement", "Syntax Errors"],
    "description_en":
        "Transition from block coding to writing real text-based code using the Python language.",
    "description_my":
        "ဘလော့ခ် (Block) ကိုဒင်းမှသည် Python ဘာသာစကားကို အသုံးပြု၍ တကယ့် စာသားအခြေခံ ကုဒ်များရေးသားခြင်းသို့ ကူးပြောင်းမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Python Basics",
    "title_en": "Variables and Data Types",
    "title_my": "ပြောင်းလဲကိန်းများ နှင့် ဒေတာအမျိုးအစားများ",
    "topics": ["Strings, Integers, Floats", "Assigning Values", "Type Casting"],
    "description_en":
        "Learn how Python stores different types of information, like text (strings) and numbers (integers).",
    "description_my":
        "Python သည် စာသားများနှင့် ကိန်းဂဏန်းများကဲ့သို့ မတူညီသော အချက်အလက်များကို မည်သို့ သိမ်းဆည်းကြောင်း လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Python Basics",
    "title_en": "Input and Math",
    "title_my": "အချက်အလက် ထည့်သွင်းခြင်း နှင့် သင်္ချာ",
    "topics": ["The Input Function", "Mathematical Operators", "Calculations"],
    "description_en":
        "Write programs that ask the user for information and perform mathematical calculations.",
    "description_my":
        "အသုံးပြုသူထံမှ အချက်အလက်များ တောင်းခံပြီး သင်္ချာတွက်ချက်မှုများ ပြုလုပ်ပေးသည့် ပရိုဂရမ်များ ရေးသားမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "The Python Calculator",
    "title_my": "Python ဂဏန်းတွက်စက်",
    "topics": ["Combining Input and Output", "Testing", "Formatting Text"],
    "description_en":
        "Code a fully functional calculator program that takes user input and displays formatted results.",
    "description_my":
        "အသုံးပြုသူထည့်သွင်းမှုကို လက်ခံပြီး ရလဒ်များကို သေသပ်စွာ ပြသပေးသော ဂဏန်းတွက်စက် ပရိုဂရမ်တစ်ခုကို အစအဆုံး ရေးဆွဲမည်။",
  },

  // ================= TERM 4: Control Structures in Python =================
  {
    "week": 13,
    "term": 4,
    "theme": "Making Decisions",
    "title_en": "If, Elif, Else",
    "title_my": "If, Elif, Else အမိန့်များ",
    "topics": ["Conditional Statements", "Comparison Operators", "Indentation"],
    "description_en":
        "Teach your Python programs to make decisions and follow different paths based on conditions.",
    "description_my":
        "အခြေအနေများအပေါ် မူတည်၍ ဆုံးဖြတ်ချက်ချကာ လမ်းကြောင်းခွဲများအတိုင်း အလုပ်လုပ်ရန် Python ပရိုဂရမ်များကို သင်ကြားပေးမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Iteration",
    "title_en": "While Loops",
    "title_my": "While Loops များ",
    "topics": ["Infinite Loops", "Condition-controlled Loops", "Counters"],
    "description_en":
        "Use While loops to keep repeating code as long as a certain condition remains true.",
    "description_my":
        "သတ်မှတ်ထားသော အခြေအနေ မှန်ကန်နေသရွေ့ ကုဒ်များကို ထပ်ခါတလဲလဲ လုပ်ဆောင်စေရန် While loops များကို အသုံးပြုမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Iteration",
    "title_en": "For Loops and Lists",
    "title_my": "For Loops များ နှင့် စာရင်းများ (Lists)",
    "topics": [
      "Count-controlled Loops",
      "Arrays/Lists",
      "Iterating through Data",
    ],
    "description_en":
        "Create lists of data and use For loops to efficiently process each item in the list.",
    "description_my":
        "အချက်အလက် စာရင်းများ ဖန်တီးပြီး စာရင်းအတွင်းရှိ အရာတစ်ခုချင်းစီကို ထိရောက်စွာ လုပ်ဆောင်ရန် For loops များကို အသုံးပြုမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Text-Based Adventure Game",
    "title_my": "စာသားအခြေခံ စွန့်စားခန်း ဂိမ်း",
    "topics": [
      "Combining Loops and Ifs",
      "Storytelling with Code",
      "Debugging",
    ],
    "description_en":
        "Program an interactive text-based adventure game with multiple choices and outcomes.",
    "description_my":
        "ရွေးချယ်စရာများနှင့် ရလဒ်အမျိုးမျိုး ပါဝင်သော အပြန်အလှန်တုံ့ပြန်မှုရှိသည့် စာသားအခြေခံ စွန့်စားခန်းဂိမ်းတစ်ခုကို ရေးဆွဲမည်။",
  },

  // ================= TERM 5: Advanced Python & Modular Programming =================
  {
    "week": 17,
    "term": 5,
    "theme": "Modular Code",
    "title_en": "Introduction to Functions",
    "title_my": "ဖန်ရှင် (Functions) များနှင့် မိတ်ဆက်",
    "topics": ["Defining Functions", "Calling Functions", "Reusing Code"],
    "description_en":
        "Learn how to group blocks of code into named functions so they can be reused easily.",
    "description_my":
        "ကုဒ်များကို အလွယ်တကူ ပြန်လည်အသုံးပြုနိုင်ရန် အမည်ပေးထားသော ဖန်ရှင်များအဖြစ် မည်သို့စုဖွဲ့ရမည်ကို လေ့လာမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Modular Code",
    "title_en": "Parameters and Arguments",
    "title_my": "ပါရာမီတာများ နှင့် အာဂူးမန့်များ",
    "topics": ["Passing Data to Functions", "Return Values", "Local Variables"],
    "description_en":
        "Make your functions more powerful by passing data into them and getting results back.",
    "description_my":
        "ဖန်ရှင်များထဲသို့ အချက်အလက်များ ထည့်သွင်းပေးခြင်းနှင့် ရလဒ်များ ပြန်လည်ရယူခြင်းဖြင့် ပိုမိုစွမ်းဆောင်ရည်မြင့်အောင် ပြုလုပ်မည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "String Manipulation",
    "title_en": "Working with Strings",
    "title_my": "စာသား (Strings) များဖြင့် လုပ်ဆောင်ခြင်း",
    "topics": ["Slicing Strings", "String Methods", "Validating Input"],
    "description_en":
        "Discover advanced ways to manipulate, cut, and check text data in Python.",
    "description_my":
        "Python တွင် စာသားအချက်အလက်များကို ပြုပြင်ခြင်း၊ ဖြတ်တောက်ခြင်းနှင့် စစ်ဆေးခြင်းဆိုင်ရာ အဆင့်မြင့်နည်းလမ်းများကို စူးစမ်းမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "The Password Generator",
    "title_my": "စကားဝှက် ထုတ်လုပ်ပေးသည့် ပရိုဂရမ်",
    "topics": ["Random Library", "Combining Functions", "String Formatting"],
    "description_en":
        "Build a program that uses functions to generate strong, random passwords for the user.",
    "description_my":
        "အသုံးပြုသူအတွက် ခိုင်မာပြီး ကျပန်းဖြစ်သော စကားဝှက်များကို ထုတ်ပေးရန် ဖန်ရှင်များအသုံးပြုသည့် ပရိုဂရမ်တစ်ခု တည်ဆောက်မည်။",
  },

  // ================= TERM 6: Cybersecurity and E-Safety =================
  {
    "week": 21,
    "term": 6,
    "theme": "Cybersecurity",
    "title_en": "Types of Cyber Threats",
    "title_my": "ဆိုက်ဘာ အန္တရာယ် အမျိုးအစားများ",
    "topics": ["Ransomware", "DDoS Attacks", "Social Engineering"],
    "description_en":
        "Understand the modern threats that target computer networks and personal data.",
    "description_my":
        "ကွန်ပျူတာ ကွန်ရက်များနှင့် ကိုယ်ရေးကိုယ်တာ အချက်အလက်များကို ပစ်မှတ်ထားသော ခေတ်သစ် ဆိုက်ဘာအန္တရာယ်များကို နားလည်စေမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Cybersecurity",
    "title_en": "Encryption Basics",
    "title_my": "ကုဒ်ဝှက်ခြင်း (Encryption) အခြေခံ",
    "topics": ["Caesar Cipher", "Public/Private Keys", "Keeping Data Safe"],
    "description_en":
        "Learn how encryption scrambles data so that hackers cannot read intercepted messages.",
    "description_my":
        "ဟက်ကာများ ဖတ်မရစေရန် အချက်အလက်များကို ကုဒ်ဝှက်စနစ်ဖြင့် မည်သို့ ပြောင်းလဲဝှက်ကွယ်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Ethics and Law",
    "title_en": "Data Protection Laws",
    "title_my": "အချက်အလက် ကာကွယ်ရေး ဥပဒေများ",
    "topics": ["Privacy Rights", "Copyright Law", "Ethical Hacking"],
    "description_en":
        "Explore the laws that protect our personal data and the ethics of being a technology user.",
    "description_my":
        "ကျွန်ုပ်တို့၏ ကိုယ်ရေးကိုယ်တာ အချက်အလက်များကို ကာကွယ်ပေးသော ဥပဒေများနှင့် နည်းပညာအသုံးပြုသူများ၏ ကျင့်ဝတ်များကို စူးစမ်းမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Cybersecurity Audit",
    "title_my": "ဆိုက်ဘာလုံခြုံရေး စစ်ဆေးမှု",
    "topics": ["Identifying Weaknesses", "Proposing Solutions", "Presentation"],
    "description_en":
        "Conduct a mock security audit for a fictional company and propose ways to protect their network.",
    "description_my":
        "စိတ်ကူးယဉ် ကုမ္ပဏီတစ်ခုအတွက် လုံခြုံရေးစစ်ဆေးမှု ပြုလုပ်ပြီး ၎င်းတို့၏ ကွန်ရက်ကို ကာကွယ်ရန် နည်းလမ်းများ အဆိုပြုမည်။",
  },

  // ================= TERM 7: Advanced Web Development =================
  {
    "week": 25,
    "term": 7,
    "theme": "Web Development",
    "title_en": "HTML5 and Structure",
    "title_my": "HTML5 နှင့် ဖွဲ့စည်းပုံ",
    "topics": ["Semantic Tags", "Forms", "Embedding Video"],
    "description_en":
        "Upgrade your web skills by using modern HTML5 tags to create structured, accessible webpages.",
    "description_my":
        "စနစ်ကျသော ဝဘ်စာမျက်နှာများ ဖန်တီးရန် ခေတ်မီ HTML5 tag များကို အသုံးပြု၍ သင်၏ ဝဘ်စွမ်းရည်ကို မြှင့်တင်မည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Web Development",
    "title_en": "CSS Layouts (Flexbox)",
    "title_my": "CSS ဒီဇိုင်းပုံစံများ (Flexbox)",
    "topics": ["Box Model", "Flexbox Basics", "Responsive Design"],
    "description_en":
        "Learn to use CSS Flexbox to easily organize and align elements on your webpage.",
    "description_my":
        "ဝဘ်စာမျက်နှာပေါ်ရှိ အစိတ်အပိုင်းများကို အလွယ်တကူ စီစဉ်နေရာချရန် CSS Flexbox အသုံးပြုနည်းကို လေ့လာမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Web Development",
    "title_en": "Introduction to JavaScript",
    "title_my": "JavaScript နှင့် မိတ်ဆက်",
    "topics": [
      "Adding Interactivity",
      "Alerts and Prompts",
      "Changing HTML Elements",
    ],
    "description_en":
        "Introduce JavaScript to make your static webpages interactive and dynamic.",
    "description_my":
        "ငြိမ်သက်နေသော ဝဘ်စာမျက်နှာများကို အသက်ဝင်လှုပ်ရှားလာစေရန် JavaScript ကို စတင်အသုံးပြုမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Interactive Web Form",
    "title_my": "အပြန်အလှန်တုံ့ပြန်သော ဝဘ်ဖောင်",
    "topics": ["HTML Forms", "CSS Styling", "JS Validation"],
    "description_en":
        "Build a styled web form that uses JavaScript to check if the user entered the right information.",
    "description_my":
        "အသုံးပြုသူ ထည့်သွင်းထားသော အချက်အလက်များ မှန်ကန်မှုရှိမရှိကို JavaScript ဖြင့် စစ်ဆေးပေးသော လှပသည့် ဝဘ်ဖောင်တစ်ခု တည်ဆောက်မည်။",
  },

  // ================= TERM 8: Introduction to Databases (SQL) =================
  {
    "week": 29,
    "term": 8,
    "theme": "Databases",
    "title_en": "Relational Databases",
    "title_my": "ဆက်စပ် ဒေတာဘေ့စ်များ (Relational Databases)",
    "topics": ["Tables and Records", "Primary Keys", "Foreign Keys"],
    "description_en":
        "Understand how large systems store data in multiple linked tables instead of a single spreadsheet.",
    "description_my":
        "စနစ်ကြီးများသည် အချက်အလက်များကို ဇယားတစ်ခုတည်းတွင် မဟုတ်ဘဲ ချိတ်ဆက်ထားသော ဇယားများစွာဖြင့် မည်သို့သိမ်းဆည်းကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Databases",
    "title_en": "Introduction to SQL",
    "title_my": "SQL နှင့် မိတ်ဆက်",
    "topics": ["What is SQL?", "SELECT Queries", "FROM Clause"],
    "description_en":
        "Learn Structured Query Language (SQL) to communicate with and retrieve data from databases.",
    "description_my":
        "ဒေတာဘေ့စ်များနှင့် ဆက်သွယ်ရန်နှင့် အချက်အလက်များ ဆွဲထုတ်ရန် SQL ဘာသာစကားကို လေ့လာမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Databases",
    "title_en": "Filtering and Sorting Data",
    "title_my": "အချက်အလက်များ စစ်ထုတ်ခြင်း နှင့် စီစဉ်ခြင်း",
    "topics": ["WHERE Clause", "ORDER BY", "Operators (AND, OR)"],
    "description_en":
        "Write advanced SQL queries to find very specific information within a large database.",
    "description_my":
        "ကြီးမားသော ဒေတာဘေ့စ်အတွင်းမှ တိကျသော အချက်အလက်များကို ရှာဖွေရန် အဆင့်မြင့် SQL ကွီရီများ ရေးသားမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "The Database Detective",
    "title_my": "ဒေတာဘေ့စ် စုံထောက်",
    "topics": ["Querying Data", "Solving Mysteries", "Data Analysis"],
    "description_en":
        "Solve a mystery by querying a database to uncover hidden clues and information.",
    "description_my":
        "လျှို့ဝှက်သဲလွန်စများနှင့် အချက်အလက်များကို ဖော်ထုတ်ရန် ဒေတာဘေ့စ်ကို SQL ဖြင့်ရှာဖွေ၍ ပဟေဠိတစ်ခုကို ဖြေရှင်းမည်။",
  },

  // ================= TERM 9: Future Technologies & Year Review =================
  {
    "week": 33,
    "term": 9,
    "theme": "Tech in Society",
    "title_en": "Impact of Technology",
    "title_my": "နည်းပညာ၏ သက်ရောက်မှု",
    "topics": ["Automation and Jobs", "Digital Divide", "E-Waste"],
    "description_en":
        "Discuss how rapidly changing technology impacts society, the environment, and future careers.",
    "description_my":
        "အလျင်အမြန် ပြောင်းလဲနေသော နည်းပညာသည် လူမှုအသိုင်းအဝိုင်း၊ သဘာဝပတ်ဝန်းကျင်နှင့် အနာဂတ် အလုပ်အကိုင်များအပေါ် မည်သို့ သက်ရောက်ကြောင်း ဆွေးနွေးမည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Tech in Society",
    "title_en": "Machine Learning and AI",
    "title_my": "စက်သင်ယူမှု နှင့် ဉာဏ်ရည်တု (AI)",
    "topics": ["Training Models", "Image Recognition", "Bias in AI"],
    "description_en":
        "Explore how Machine Learning works and the potential dangers of bias in Artificial Intelligence.",
    "description_my":
        "Machine Learning အလုပ်လုပ်ပုံနှင့် ဉာဏ်ရည်တု (AI) တွင် ပါဝင်လာနိုင်သော ဘက်လိုက်မှု အန္တရာယ်များကို စူးစမ်းမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Year Review",
    "title_en": "Year 8 Computing Review",
    "title_my": "Year 8 Computing ပြန်လည်သုံးသပ်ခြင်း",
    "topics": ["Python Recap", "Web Dev Recap", "Theory Check"],
    "description_en":
        "Consolidate your coding skills and theoretical knowledge covered throughout Year 8.",
    "description_my":
        "Year 8 တစ်နှစ်တာလုံး သင်ယူခဲ့သော ကိုဒင်းစွမ်းရည်များနှင့် သီအိုရီ အသိပညာများကို ခိုင်မာစေရန် ပြန်လည်သုံးသပ်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "The Innovation Pitch",
    "title_my": "တီထွင်ဆန်းသစ်မှု တင်ဆက်ခြင်း",
    "topics": ["Problem Solving", "Prototyping Ideas", "Presentation"],
    "description_en":
        "Propose a new software or hardware solution to a real-world problem and pitch it to the class.",
    "description_my":
        "လက်တွေ့ပြဿနာတစ်ခုကို ဖြေရှင်းနိုင်မည့် ဆော့ဖ်ဝဲလ် (သို့) ဟာ့ဒ်ဝဲလ် အသစ်တစ်ခုကို အဆိုပြု တင်ဆက်မည်။",
  },
];
