// File: ai_data_bridge/year9_global_perspectives_all_terms.dart
// Year 9 Global Perspectives Terms 1 to 9 (Weeks 1-36) - IGCSE Preparatory Year
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> year9GlobalPerspectivesAllTermsData = [
  // ================= TERM 1: Global Ethics & Moral Dilemmas =================
  {
    "week": 1,
    "term": 1,
    "theme": "Global Ethics",
    "title_en": "Moral Dilemmas in the Modern World",
    "title_my": "ခေတ်သစ်ကမ္ဘာရှိ ကိုယ်ကျင့်တရားဆိုင်ရာ အကျပ်အတည်းများ",
    "topics": [
      "Utilitarianism vs Deontology",
      "Real-world Ethical Scenarios",
      "Conflicting Values",
    ],
    "description_en":
        "Examine complex philosophical dilemmas where doing the right thing is not clear-cut.",
    "description_my":
        "မှန်ကန်သည်ကို လုပ်ဆောင်ရန်မှာ ရှင်းလင်းပြတ်သားခြင်းမရှိသော ရှုပ်ထွေးသော ဒဿနိကဗေဒဆိုင်ရာ အကျပ်အတည်းများကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Global Ethics",
    "title_en": "Animal Rights and Welfare",
    "title_my": "တိရစ္ဆာန် အခွင့်အရေးများနှင့် သုခချမ်းသာ",
    "topics": ["Testing on Animals", "Factory Farming", "Conservation Ethics"],
    "description_en":
        "Debate the ethical boundaries of human treatment of animals in science, food, and entertainment.",
    "description_my":
        "သိပ္ပံ၊ အစားအစာနှင့် ဖျော်ဖြေရေးတို့တွင် တတိရစ္ဆာန်များအပေါ် လူသားတို့၏ ဆက်ဆံမှုဆိုင်ရာ ကျင့်ဝတ်များကို ဆွေးနွေးမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Global Ethics",
    "title_en": "Censorship and Freedom of Speech",
    "title_my": "သတင်းဆင်ဆာဖြတ်ခြင်းနှင့် လွတ်လပ်စွာ ထုတ်ဖော်ပြောဆိုခွင့်",
    "topics": [
      "Information Control",
      "Hate Speech vs Free Speech",
      "Digital Censorship",
    ],
    "description_en":
        "Explore the fine line between protecting society and maintaining freedom of expression online and offline.",
    "description_my":
        "အွန်လိုင်းနှင့် အပြင်လောကတွင် လူ့အသိုင်းအဝိုင်းကို ကာကွယ်ခြင်းနှင့် ထုတ်ဖော်ပြောဆိုခွင့် လွတ်လပ်မှုအကြား နယ်နိမိတ်ကို စူးစမ်းမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "The Ethical Tribunal Project",
    "title_my": "ကျင့်ဝတ်ဆိုင်ရာ ခုံရုံး ပရောဂျက်",
    "topics": ["Mock Trials", "Defending Ethical Stances", "Peer Debate"],
    "description_en":
        "Participate in a tribunal simulation to judge and debate a major contemporary global ethical crisis.",
    "description_my":
        "ခေတ်ပြိုင် ကမ္ဘာ့ကျင့်ဝတ်ဆိုင်ရာ အကျပ်အတည်းတစ်ခုကို ဆုံးဖြတ်ရန်နှင့် ဆွေးနွေးရန် ပုံစံတူ ခုံရုံးအစည်းအဝေးတွင် ပါဝင်မည်။",
  },

  // ================= TERM 2: Geopolitics & International Relations =================
  {
    "week": 5,
    "term": 2,
    "theme": "Geopolitics",
    "title_en": "International Diplomacy",
    "title_my": "နိုင်ငံတကာ သံတမန်ရေးရာ",
    "topics": [
      "Role of the United Nations",
      "Treaties and Alliances",
      "Conflict Mediation",
    ],
    "description_en":
        "Understand how nations negotiate, form alliances, and resolve international disputes peacefully.",
    "description_my":
        "နိုင်ငံများသည် မည်သို့ညှိနှိုင်းခြင်း၊ မဟာမိတ်ဖွဲ့ခြင်းနှင့် နိုင်ငံတကာ အငြင်းပွားမှုများကို ငြိမ်းချမ်းစွာ ဖြေရှင်းခြင်းတို့ကို နားလည်စေမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Geopolitics",
    "title_en": "Global Superpowers and Trade Wars",
    "title_my": "ကမ္ဘာ့စူပါပါဝါနိုင်ငံများနှင့် ကုန်သွယ်ရေး စစ်ပွဲများ",
    "topics": [
      "Economic Sanctions",
      "Tariffs",
      "Global Supply Chain Dominance",
    ],
    "description_en":
        "Analyze how economic policies and trade disputes between superpowers impact the rest of the world.",
    "description_my":
        "စူပါပါဝါနိုင်ငံများအကြား စီးပွားရေး မူဝါဒများနှင့် ကုန်သွယ်ရေး အငြင်းပွားမှုများသည် ကျန်ကမ္ဘာပေါ်သို့ မည်သို့သက်ရောက်ကြောင်း ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Geopolitics",
    "title_en": "Water and Resource Conflicts",
    "title_my": "ရေနှင့် သဘာဝအရင်းအမြစ် ပဋိပက္ခများ",
    "topics": [
      "Transboundary Rivers",
      "Resource Scarcity",
      "Future Geopolitical Hotspots",
    ],
    "description_en":
        "Investigate how the scarcity of vital resources like fresh water can trigger future international conflicts.",
    "description_my":
        "သန့်ရှင်းသောရေကဲ့သို့သော အသက်ရှင်ရေး အရင်းအမြစ်များ ရှားပါးလာခြင်းက အနာဂတ် နိုင်ငံတကာ ပဋိပက္ခများကို မည်သို့ဖြစ်စေနိုင်ကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Model United Nations (MUN)",
    "title_my": "ပုံစံတူ ကုလသမဂ္ဂ (MUN) ညီလာခံ",
    "topics": [
      "Representing Nations",
      "Drafting Resolutions",
      "Diplomatic Negotiation",
    ],
    "description_en":
        "Represent a country in a Model United Nations summit to debate and pass a resolution on resource sharing.",
    "description_my":
        "အရင်းအမြစ် မျှဝေသုံးစွဲရေးဆိုင်ရာ ဆုံးဖြတ်ချက်ကို ဆွေးနွေးအတည်ပြုရန် MUN ညီလာခံတွင် နိုင်ငံတစ်နိုင်ငံကို ကိုယ်စားပြု တင်ပြမည်။",
  },

  // ================= TERM 3: Artificial Intelligence, Automation & Society =================
  {
    "week": 9,
    "term": 3,
    "theme": "Future Tech",
    "title_en": "The AI Revolution",
    "title_my": "ဉာဏ်ရည်တု (AI) တော်လှန်ရေး",
    "topics": [
      "Generative AI",
      "Automation of Labor",
      "Ethical AI Development",
    ],
    "description_en":
        "Examine the societal implications of artificial intelligence taking over creative and cognitive tasks.",
    "description_my":
        "ဖန်တီးမှုနှင့် ဉာဏ်ရည်သုံး လုပ်ငန်းများကို AI က နေရာယူလာခြင်း၏ လူမှုရေး သက်ရောက်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Future Tech",
    "title_en": "Surveillance Capitalism and Privacy",
    "title_my": "စောင့်ကြည့်ရေး ရင်းနှီးမြှုပ်နှံမှုနှင့် ကိုယ်ရေးလုံခြုံရေး",
    "topics": [
      "Data Harvesting",
      "Facial Recognition",
      "The Right to be Forgotten",
    ],
    "description_en":
        "Explore how big tech companies collect personal data and the threat to individual privacy.",
    "description_my":
        "နည်းပညာ ကုမ္ပဏီကြီးများသည် ကိုယ်ရေးအချက်အလက်များကို မည်သို့ကောက်ယူနေကြပြီး တစ်ဦးချင်း ကိုယ်ရေးလုံခြုံရေးအပေါ် မည်သို့ခြိမ်းခြောက်နေကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Future Tech",
    "title_en": "Transhumanism and Biotechnology",
    "title_my": "Transhumanism နှင့် ဇီဝနည်းပညာ",
    "topics": [
      "Genetic Engineering (CRISPR)",
      "Enhancing Human Limits",
      "Bioethics",
    ],
    "description_en":
        "Debate the moral limits of modifying human DNA and enhancing physical or mental capabilities.",
    "description_my":
        "လူ့ DNA ကို ပြုပြင်ခြင်းနှင့် ကိုယ်လက်စွမ်းရည်၊ ဉာဏ်ရည်များကို မြှင့်တင်ခြင်းဆိုင်ရာ ကျင့်ဝတ် ကန့်သတ်ချက်များကို ဆွေးနွေးမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Tech Regulation Policy Proposal",
    "title_my": "နည်းပညာ ထိန်းညှိမှု မူဝါဒ အဆိုပြုချက်",
    "topics": [
      "Drafting Laws",
      "Balancing Innovation and Safety",
      "Public Hearing Simulation",
    ],
    "description_en":
        "Draft a national policy framework to regulate emerging technologies safely and fairly.",
    "description_my":
        "ပေါ်ထွန်းလာသော နည်းပညာများကို ဘေးကင်းလုံခြုံစွာနှင့် တရားမျှတစွာ ထိန်းညှိရန် အမျိုးသား မူဝါဒဘောင်တစ်ခုကို ရေးဆွဲမည်။",
  },

  // ================= TERM 4: Climate Crisis & Environmental Policies =================
  {
    "week": 13,
    "term": 4,
    "theme": "Climate Crisis",
    "title_en": "Climate Refugees",
    "title_my": "ရာသီဥတု ဒုက္ခသည်များ",
    "topics": [
      "Rising Sea Levels",
      "Displacement",
      "International Legal Status",
    ],
    "description_en":
        "Investigate the plight of communities forced to relocate due to climate change and environmental destruction.",
    "description_my":
        "ရာသီဥတုပြောင်းလဲမှုနှင့် ပတ်ဝန်းကျင် ပျက်စီးမှုကြောင့် နေရာရွှေ့ပြောင်းရန် တွန်းအားပေးခံရသော လူမှုအသိုင်းအဝိုင်းများ၏ အခြေအနေကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Climate Crisis",
    "title_en": "Green Growth vs Degrowth",
    "title_my":
        "စိမ်းလန်းသော တိုးတက်မှု (Green Growth) နှင့် တိုးတက်မှုရပ်စဲရေး (Degrowth)",
    "topics": ["Economic Models", "Carbon Tax", "Sustainable Capitalism"],
    "description_en":
        "Debate whether global economic systems can be made sustainable or require fundamental restructuring.",
    "description_my":
        "ကမ္ဘာ့စီးပွားရေးစနစ်များကို ရေရှည်တည်တံ့အောင် လုပ်ဆောင်နိုင်ခြင်း ရှိမရှိ (သို့မဟုတ်) အခြေခံကျကျ ပြန်လည်ဖွဲ့စည်းရန် လိုအပ်သည်ကို ဆွေးနွေးမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Climate Crisis",
    "title_en": "Global Climate Summits (COP)",
    "title_my": "ကမ္ဘာ့ရာသီဥတု ညီလာခံများ (COP)",
    "topics": [
      "Paris Agreement",
      "Nationally Determined Contributions",
      "Enforcement Challenges",
    ],
    "description_en":
        "Analyze the successes and failures of international climate agreements and political commitments.",
    "description_my":
        "နိုင်ငံတကာ ရရာသီဥတု သဘောတူညီချက်များနှင့် နိုင်ငံရေး ကတိကဝတ်များ၏ အောင်မြင်မှုနှင့် ကျရှုံးမှုများကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "City Climate Action Plan",
    "title_my": "မြို့ပြ ရရာသီဥတု လှုပ်ရှားမှု စီမံချက်",
    "topics": [
      "Urban Planning",
      "Reducing Carbon Emissions",
      "Presenting to City Leaders",
    ],
    "description_en":
        "Design a comprehensive zero-carbon action plan for a major metropolitan city.",
    "description_my":
        "မြို့ကြီးပြကြီး တစ်ခုအတွက် ကာဗွန်ထုတ်လွှတ်မှု မရှိစေမည့် ပြည့်စုံသော လှုပ်ရှားမှုစီမံချက်တစ်ခုကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 5: Global Health & Inequality =================
  {
    "week": 17,
    "term": 5,
    "theme": "Global Health",
    "title_en": "Patent Laws and Essential Medicines",
    "title_my": "မူပိုင်ခွင့် ဥပဒေများနှင့် မရှိမဖြစ် ဆေးဝါးများ",
    "topics": ["Big Pharma Profits", "Generic Drugs", "Global Health Equity"],
    "description_en":
        "Examine the ethical conflict between pharmaceutical drug patents and saving lives in developing countries.",
    "description_my":
        "ဆေးဝါး မူပိုင်ခွင့်များနှင့် ဖွံ့ဖြိုးဆဲနိုင်ငံများတွင် အသက်ကယ်ဆယ်ရေး အကြားရှိ ကျင့်ဝတ်ဆိုင်ရာ ပဋိပက္ခကို လေ့လာမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Global Health",
    "title_en": "Mental Health as a Global Crisis",
    "title_my": "ကမ္ဘာလုံးဆိုင်ရာ အကျပ်အတည်းတစ်ခုအနေဖြင့် စိတ်ကျန်းမာရေး",
    "topics": [
      "Economic Cost of Depression",
      "Youth Mental Health",
      "Global Disparities in Care",
    ],
    "description_en":
        "Investigate mental health challenges globally and the systemic barriers to receiving psychological care.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ စိတ်ကျန်းမာရေး စိန်ခေါ်မှုများနှင့် စိတ်ပိုင်းဆိုင်ရာ ကုသမှုရရှိရန် စနစ်တကျ ရှိနေသော အတားအဆီးများကို စူးစမ်းမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Global Health",
    "title_en": "Food Security and Global Hunger",
    "title_my": "စားနပ်ရိက္ခာ လုံခြုံရေးနှင့် ကမ္ဘာ့ဆာလောင်မွတ်သိပ်မှု",
    "topics": [
      "Supply Chain Vulnerabilities",
      "Food Waste",
      "Agribusiness vs Smallholders",
    ],
    "description_en":
        "Analyze why millions face starvation in a world that produces more than enough food for everyone.",
    "description_my":
        "လူတိုင်းအတွက် လုံလောက်သည်ထက် ပိုမိုထုတ်လုပ်နိုင်သော ကမ္ဘာကြီးတွင် လူသန်းပေါင်းများစွာ အဘယ်ကြောင့် ဆာလောင်မှုကို ရင်ဆိုင်နေရကြောင်း ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Global Health Intervention Proposal",
    "title_my": "ကမ္ဘာ့ကျန်းမာရေး စွက်ဖက်မှု အဆိုပြုချက်",
    "topics": [
      "Targeted Health Campaigns",
      "Resource Allocation",
      "Impact Measurement",
    ],
    "description_en":
        "Develop an intervention strategy to tackle a specific health crisis in a designated region.",
    "description_my":
        "သတ်မှတ်ထားသော ဒေသတစ်ခုတွင် ကျန်းမာရေး အကျပ်အတည်းတစ်ခုကို ဖြေရှင်းရန် စွက်ဖက်မှု မဟာဗျူဟာတစ်ခုကို ဖန်တီးမည်။",
  },

  // ================= TERM 6: Cultural Heritage & Globalisation =================
  {
    "week": 21,
    "term": 6,
    "theme": "Cultural Identity",
    "title_en": "Cultural Imperialism vs Globalisation",
    "title_my": "ယဉ်ကျေးမှု နယ်ချဲ့ဝါဒနှင့် ကမ္ဘာ့ရွာကြီး (Globalisation)",
    "topics": [
      "Homogenisation of Culture",
      "Loss of Indigenous Languages",
      "Westernisation",
    ],
    "description_en":
        "Explore whether globalisation creates a unified global culture or destroys local heritage.",
    "description_my":
        "ကမ္ဘာ့ရွာကြီးစနစ်သည် ပေါင်းစည်းထားသော ကမ္ဘာ့ယဉ်ကျေးမှုကို ဖန်တီးသလော (သို့) ဒေသတွင်း အမွေအနှစ်များကို ဖျက်ဆီးသလောဆိုသည်ကို စူးစမ်းမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Cultural Identity",
    "title_en": "Preserving Endangered Heritage",
    "title_my":
        "မျိုးတုန်းပျောက်ကွယ်ရန် စိုးရိမ်ရသော အမွေအနှစ်များကို ထိန်းသိမ်းခြင်း",
    "topics": [
      "UNESCO World Heritage Sites",
      "Digital Archives",
      "Restitution of Artifacts",
    ],
    "description_en":
        "Investigate efforts to protect ancient artifacts, indigenous traditions, and historical sites worldwide.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ ရှေးဟောင်းပစ္စည်းများ၊ ဒေသန္တရ ဓလေ့ထုံးတမ်းများနှင့် သမိုင်းဝင်နေရာများကို ကာကွယ်ရန် ကြိုးပမ်းမှုများကို လေ့လာမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Cultural Identity",
    "title_en": "Tourism and its Impacts",
    "title_my": "ခရီးသွားလာရေးလုပ်ငန်းနှင့် ၎င်း၏ သက်ရောက်မှုများ",
    "topics": ["Overtourism", "Economic Benefits", "Cultural Commodification"],
    "description_en":
        "Evaluate the dual impact of mass tourism on local economies, environments, and cultural integrity.",
    "description_my":
        "အစုလိုက်အပြုံလိုက် ခရီးသွားလာမှုက ဒေသတွင်း စီးပွားရေး၊ ပတ်ဝန်းကျင်နှင့် ယဉ်ကျေးမှု သန့်စင်မှုအပေါ် သက်ရောက်သည့် နှစ်ဖက်စလုံးကို အကဲဖြတ်မည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Cultural Heritage Preservation Project",
    "title_my": "ယဉ်ကျေးမှု အမွေအနှစ် ထိန်းသိမ်းရေး ပရောဂျက်",
    "topics": [
      "Documenting Local Traditions",
      "Digital Storytelling",
      "Exhibition",
    ],
    "description_en":
        "Create a digital archive or showcase preserving a fading local tradition or cultural practice.",
    "description_my":
        "မှေးမှိန်ပျောက်ကွယ်သွားတော့မည့် ဒေသတွင်း ဓလေ့ထုံးတမ်း သို့မဟုတ် ယဉ်ကျေးမှုကို ထိန်းသိမ်းထားသည့် ဒီဂျစ်တယ် မှတ်တမ်းတစ်ခု ဖန်တီးမည်။",
  },

  // ================= TERM 7: Human Rights, Justice & Activism =================
  {
    "week": 25,
    "term": 7,
    "theme": "Human Rights",
    "title_en": "Modern Slavery and Human Trafficking",
    "title_my": "ခေတ်သစ် ကျွန်စနစ်နှင့် လူကုန်ကူးမှု",
    "topics": [
      "Supply Chain Exploitation",
      "Legal Frameworks",
      "Activist Movements",
    ],
    "description_en":
        "Examine the hidden forms of forced labor embedded in global clothing and tech supply chains.",
    "description_my":
        "ကမ္ဘာ့အဝတ်အထည်နှင့် နည်းပညာ ထောက်ပံ့ရေးကွင်းဆက်များအတွင်း ဖုံးကွယ်နေသော အဓမ္မခိုင်းစေမှုပုံစံများကို လေ့လာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Human Rights",
    "title_en": "Youth Activism and Global Change",
    "title_my": "လူငယ် တက်ကြွလှုပ်ရှားမှုနှင့် ကမ္ဘာ့ပြောင်းလဲမှု",
    "topics": [
      "Greta Thunberg Effect",
      "Digital Protests",
      "Impact of Youth Voices",
    ],
    "description_en":
        "Analyze how young activists use social media and global platforms to force political action.",
    "description_my":
        "လူငယ်တက်ကြွလှုပ်ရှားသူများသည် နိုင်ငံရေးအရ အရေးယူဆောင်ရွက်မှုများ ဖြစ်ပေါ်လာစေရန် ဆိုရှယ်မီဒီယာနှင့် ကမ္ဘာ့ပလက်ဖောင်းများကို မည်သို့အသုံးပြုကြောင်း ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Justice",
    "title_en": "International Justice Systems",
    "title_my": "နိုင်ငံတကာ တရားမျှတမှု စနစ်များ",
    "topics": [
      "International Criminal Court (ICC)",
      "War Crimes",
      "Universal Jurisdiction",
    ],
    "description_en":
        "Understand how international courts prosecute war crimes, genocide, and human rights abuses.",
    "description_my":
        "နိုင်ငံတကာ ခုံရုံးများသည် စစ်ရာဇဝတ်မှုများ၊ လူမျိုးတုန်းသတ်ဖြတ်မှုများနှင့် လူ့အခွင့်အရေး ချိုးဖောက်မှုများကို မည်သို့တရားစွဲဆိုကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Human Rights Campaign Strategy",
    "title_my": "လူ့အခွင့်အရေး ကမ်ပိန်း မဟာဗျူဟာ",
    "topics": ["Campaign Design", "Mobilising Support", "Media Strategy"],
    "description_en":
        "Develop a multi-channel campaign strategy to support a specific human rights advocacy group.",
    "description_my":
        "သီးခြား လူ့အခွင့်အရေး လှုပ်ရှားမှုအုပ်စုတစ်ခုကို ပံ့ပိုးရန် လမ်းကြောင်းစုံပါဝင်သော ကမ်ပိန်း မဟာဗျူဟာတစ်ခုကို ဖန်တီးမည်။",
  },

  // ================= TERM 8: Global Economics & Future Systems =================
  {
    "week": 29,
    "term": 8,
    "theme": "Global Economics",
    "title_en": "Universal Basic Income (UBI)",
    "title_my": "အများပြည်သူဆိုင်ရာ အခြေခံဝင်ငွေ (UBI)",
    "topics": [
      "Economic Feasibility",
      "Impact on Poverty",
      "Automation Countermeasure",
    ],
    "description_en":
        "Debate the pros and cons of providing every citizen with a guaranteed unconditional regular sum of money.",
    "description_my":
        "နိုင်ငံသားတိုင်းအား အခြေခံငွေကြေး ပမာဏတစ်ခုကို အခမဲ့ ပုံမှန်ထောက်ပံ့ပေးခြင်း၏ ကောင်းကျိုးနှင့် ဆိုးကျိုးများကို ဆွေးနွေးမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Global Economics",
    "title_en": "The Future of Capitalism",
    "title_my": " capitalism ၏ အနာဂတ်",
    "topics": [
      "Stakeholder Capitalism",
      "Wealth Inequality Solutions",
      "Alternative Economic Models",
    ],
    "description_en":
        "Examine reforming economic structures to prioritize environmental and social well-being over pure profit.",
    "description_my":
        "စစ်မှန်သော အမြတ်အစွန်းထက် ပတ်ဝန်းကျင်နှင့် လူမှုဖူလုံရေးကို ဦးစားပေးရန် စီးပွားရေးစနစ်များကို ပြုပြင်ပြောင်းလဲခြင်းအကြောင်း လေ့လာမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Global Systems",
    "title_en": "Megacities and Urban Futures",
    "title_my": "မြို့ကြီးပြကြီးများနှင့် မြို့ပြ အနာဂတ်",
    "topics": ["Smart Cities", "Urban Slums", "Sustainable Infrastructure"],
    "description_en":
        "Investigate how rapidly expanding megacities can be designed to be sustainable and liveable.",
    "description_my":
        "အလွန်အမင်း ကြီးထွားလာနေသော မြို့ကြီးများကို ရေရှည်တည်တံ့ပြီး နေထိုင်ကောင်းမွန်အောင် မည်သို့ ဒီဇိုင်းဆွဲနိုင်ကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "The Utopian City Design",
    "title_my": "စံပြမြို့တော် ဒီဇိုင်း ပရောဂျက်",
    "topics": [
      "Systems Integration",
      "Sustainable Technology",
      "Social Equality Planning",
    ],
    "description_en":
        "Design a conceptual futuristic city that solves modern economic, environmental, and social challenges.",
    "description_my":
        "ခေတ်သစ် စီးပွားရေး၊ ပတ်ဝန်းကျင်နှင့် လူမှုရေး စိန်ခေါ်မှုများကို ဖြေရှင်းပေးနိုင်မည့် အနာဂတ်စံပြမြို့တော်တစ်ခုကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 9: IGCSE Global Perspectives Capstone & Examination =================
  {
    "week": 33,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "IGCSE Global Perspectives Essay Structure",
    "title_my": "IGCSE Global Perspectives အက်ဆေး ဖွဲ့စည်းပုံ",
    "topics": [
      "Evaluating Arguments",
      "Perspective Synthesis",
      "Structured Reasoning",
    ],
    "description_en":
        "Master the rigorous analytical essay writing techniques required for IGCSE Global Perspectives exams.",
    "description_my":
        "IGCSE Global Perspectives စာမေးပွဲများအတွက် လိုအပ်သော တင်းကျပ်သည့် ခွဲခြမ်းစိတ်ဖြာ အက်ဆေး ရေးသားနည်းများကို ကျွမ်းကျင်အောင် လုပ်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Team Project Reflection Preparation",
    "title_my": "အဖွဲ့လိုက် ပရောဂျက် သုံးသပ်ချက် ပြင်ဆင်ခြင်း",
    "topics": [
      "Reflective Writing",
      "Collaboration Analysis",
      "Evaluating Personal Growth",
    ],
    "description_en":
        "Prepare high-level reflective journals evaluating personal and team performance on global issues.",
    "description_my":
        "ကမ္ဘာလုံးဆိုင်ရာ ပြဿနာများအပေါ် ကိုယ်ပိုင်နှင့် အဖွဲ့လိုက် စွမ်းဆောင်ရည်ကို အကဲဖြတ်သည့် အဆင့်မြင့် သုံးသပ်ချက်များကို ပြင်ဆင်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Exam Prep",
    "title_en": "Full Past-Paper Examination Simulation",
    "title_my": "ယခင်မေးခွန်းဟောင်း ပုံစံတူ စာမေးပွဲ အပြည့်အစုံ ဖြေဆိုခြင်း",
    "topics": [
      "Timed Source Analysis",
      "Constructing Arguments",
      "Exam Technique Mastery",
    ],
    "description_en":
        "Complete timed source-based paper examinations under realistic testing conditions.",
    "description_my":
        "လက်တွေ့ကျသော စာမေးပွဲ စည်းကမ်းချက်များနှင့်အညီ အရင်းအမြစ်အခြေပြု စာမေးပွဲများကို အချိန်သတ်မှတ်ချက်ဖြင့် ဖြေဆိုမည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "The Lower Secondary Global Summit & Graduation",
    "title_my": "အလယ်တန်း အဆင့် ကမ္ဘာ့ညီလာခံနှင့် ဘွဲ့နှင်းသဘင်",
    "topics": [
      "Final Presentation Showcase",
      "Lower Secondary Completion",
      "Global Citizen Celebration",
    ],
    "description_en":
        "Celebrate the completion of Lower Secondary with a grand global research symposium and project showcase.",
    "description_my":
        "ကြီးမားသော ကမ္ဘာ့သုတေသန စာတမ်းဖတ်ပွဲနှင့် ပရောဂျက်ပြပွဲတို့ဖြင့် အလယ်တန်းအဆင့် ပြီးမြောက်မှုကို ဂုဏ်ပြုကျင်းပမည်။",
  },
];
