// File: ai_data_bridge/year7_global_perspectives_all_terms.dart
// Year 7 Global Perspectives Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> year7GlobalPerspectivesAllTermsData = [
  // ================= TERM 1: Research & Information Skills =================
  {
    "week": 1,
    "term": 1,
    "theme": "Introduction to GP",
    "title_en": "What is Global Perspectives?",
    "title_my": "ကမ္ဘာ့အမြင် ဘာသာရပ်ဆိုတာ ဘာလဲ?",
    "topics": [
      "Local vs Global Issues",
      "Different Viewpoints",
      "Critical Thinking",
    ],
    "description_en":
        "Introduce the subject and learn how to look at issues from personal, local, and global viewpoints.",
    "description_my":
        "ဘာသာရပ်ကို မိတ်ဆက်ပေးပြီး ပြဿနာများကို ကိုယ်ပိုင်၊ ဒေသတွင်းနှင့် ကမ္ဘာလုံးဆိုင်ရာ ရှုထောင့်များမှ မည်သို့ကြည့်ရှုရမည်ကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Research Skills",
    "title_en": "Asking Good Questions",
    "title_my": "ကောင်းမွန်သော မေးခွန်းများ မေးမြန်းခြင်း",
    "topics": ["Open vs Closed Questions", "Research Questions", "Curiosity"],
    "description_en":
        "Learn how to formulate strong, open-ended questions to guide effective research.",
    "description_my":
        "ထိရောက်သော သုတေသနပြုလုပ်နိုင်ရန် ခိုင်မာပြီး အဖြေကျယ်ကျယ်ပြန့်ပြန့်ရနိုင်သော မေးခွန်းများ မည်သို့မေးရမည်ကို လေ့လာမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Research Skills",
    "title_en": "Fact vs. Fake News",
    "title_my": "အချက်အလက် နှင့် သတင်းတု",
    "topics": ["Evaluating Sources", "Reliability", "Identifying Bias"],
    "description_en":
        "Develop skills to check if information on the internet is true, reliable, or fake news.",
    "description_my":
        "အင်တာနက်ပေါ်ရှိ အချက်အလက်များသည် မှန်ကန်မှု၊ ယုံကြည်စိတ်ချရမှု ရှိမရှိ (သို့မဟုတ်) သတင်းတု ဟုတ်မဟုတ် စစ်ဆေးနိုင်စွမ်းကို မွေးမြူမည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Mini Research Project",
    "title_my": "သုတေသန ပရောဂျက်ငယ်",
    "topics": ["Choosing a Topic", "Gathering Facts", "Presenting Findings"],
    "description_en":
        "Apply your new research skills to investigate a global issue and present your findings.",
    "description_my":
        "ကမ္ဘာလုံးဆိုင်ရာ ပြဿနာတစ်ခုကို စုံစမ်းဖော်ထုတ်ရန် သုတေသနစွမ်းရည်များကို အသုံးချပြီး တွေ့ရှိချက်များကို တင်ပြမည်။",
  },

  // ================= TERM 2: Communication & Collaboration =================
  {
    "week": 5,
    "term": 2,
    "theme": "Communication",
    "title_en": "Effective Communication",
    "title_my": "ထိရောက်သော ဆက်သွယ်ရေး",
    "topics": ["Body Language", "Tone of Voice", "Clear Messaging"],
    "description_en":
        "Understand how words, tone, and body language affect how a message is received.",
    "description_my":
        "စကားလုံးများ၊ လေယူလေသိမ်းနှင့် ကိုယ်ဟန်အမူအရာများသည် သတင်းစကား ပေးပို့မှုအပေါ် မည်သို့သက်ရောက်ကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Collaboration",
    "title_en": "Working in a Team",
    "title_my": "အဖွဲ့လိုက် ပူးပေါင်းလုပ်ဆောင်ခြင်း",
    "topics": ["Assigning Roles", "Compromise", "Achieving Goals"],
    "description_en":
        "Learn how to collaborate effectively in groups by sharing responsibilities and compromising.",
    "description_my":
        "တာဝန်များခွဲဝေခြင်းနှင့် အပေးအယူလုပ်ခြင်းဖြင့် အဖွဲ့လိုက် ထိရောက်စွာ ပူးပေါင်းလုပ်ဆောင်နည်းကို လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Communication",
    "title_en": "Active Listening",
    "title_my": "တက်ကြွစွာ နားထောင်ခြင်း",
    "topics": ["Empathy", "Understanding Others", "Respectful Responses"],
    "description_en":
        "Practice active listening to truly understand different perspectives and show empathy.",
    "description_my":
        "ကွဲပြားသော အမြင်များကို အမှန်တကယ် နားလည်ရန်နှင့် ကိုယ်ချင်းစာတရားပြသရန် တက်ကြွစွာ နားထောင်ခြင်းကို လေ့ကျင့်မည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Group Presentation",
    "title_my": "အဖွဲ့လိုက် တင်ဆက်မှု",
    "topics": ["Planning Together", "Speaking Confidently", "Peer Feedback"],
    "description_en":
        "Work as a team to create and deliver a presentation on a global topic to the class.",
    "description_my":
        "ကမ္ဘာလုံးဆိုင်ရာ အကြောင်းအရာတစ်ခုအပေါ် အဖွဲ့လိုက် ပူးပေါင်းပြင်ဆင်၍ အတန်းရှေ့တွင် တင်ဆက်မည်။",
  },

  // ================= TERM 3: Conflict and Peace =================
  {
    "week": 9,
    "term": 3,
    "theme": "Conflict",
    "title_en": "Understanding Conflict",
    "title_my": "ပဋိပက္ခကို နားလည်ခြင်း",
    "topics": [
      "Causes of Conflict",
      "Personal vs Global Conflict",
      "Consequences",
    ],
    "description_en":
        "Explore the root causes of conflicts, from schoolyard arguments to international wars.",
    "description_my":
        "ကျောင်းတွင်း အငြင်းပွားမှုများမှသည် နိုင်ငံတကာ စစ်ပွဲများအထိ ပဋိပက္ခများ ဖြစ်ပွားရသည့် အဓိက အကြောင်းရင်းများကို စူးစမ်းမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "Conflict",
    "title_en": "Conflict Resolution",
    "title_my": "ပဋိပက္ခ ဖြေရှင်းခြင်း",
    "topics": ["Mediation", "Finding Common Ground", "Apologies"],
    "description_en":
        "Learn peaceful strategies for resolving disagreements and finding win-win solutions.",
    "description_my":
        "သဘောထားကွဲလွဲမှုများကို ဖြေရှင်းရန်နှင့် နှစ်ဦးနှစ်ဖက် အဆင်ပြေစေမည့် ငြိမ်းချမ်းသော ဗျူဟာများကို လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "Peace",
    "title_en": "Peacebuilding",
    "title_my": "ငြိမ်းချမ်းရေး တည်ဆောက်ခြင်း",
    "topics": ["Role of the UN", "Peace Treaties", "Community Harmony"],
    "description_en":
        "Investigate how international organizations and communities work together to maintain peace.",
    "description_my":
        "နိုင်ငံတကာ အဖွဲ့အစည်းများနှင့် လူမှုအသိုင်းအဝိုင်းများက ငြိမ်းချမ်းရေး ထိန်းသိမ်းရန် မည်သို့ပူးပေါင်းဆောင်ရွက်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Peace Poster Campaign",
    "title_my": "ငြိမ်းချမ်းရေး ပိုစတာ ကမ်ပိန်း",
    "topics": ["Visual Communication", "Inspiring Others", "Spreading Harmony"],
    "description_en":
        "Design a poster campaign that promotes peace and understanding in your local community.",
    "description_my":
        "ဒေသတွင်း လူမှုအသိုင်းအဝိုင်းတွင် ငြိမ်းချမ်းရေးနှင့် နားလည်မှုရှိစေရန် လှုံ့ဆော်ပေးမည့် ပိုစတာကမ်ပိန်းတစ်ခုကို ဒီဇိုင်းဆွဲမည်။",
  },

  // ================= TERM 4: Health and Well-being =================
  {
    "week": 13,
    "term": 4,
    "theme": "Global Health",
    "title_en": "Global Health Issues",
    "title_my": "ကမ္ဘာလုံးဆိုင်ရာ ကျန်းမာရေး ပြဿနာများ",
    "topics": ["Infectious Diseases", "Clean Water", "Nutrition"],
    "description_en":
        "Examine major health challenges faced by different countries around the world.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ နိုင်ငံအသီးသီးမှ ရင်ဆိုင်နေရသော အဓိက ကျန်းမာရေး စိန်ခေါ်မှုများကို လေ့လာမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Well-being",
    "title_en": "Mental Health Awareness",
    "title_my": "စိတ်ကျန်းမာရေး အသိပညာ",
    "topics": ["Stress Management", "Removing Stigma", "Supporting Friends"],
    "description_en":
        "Understand the importance of mental well-being and how to support yourself and others.",
    "description_my":
        "စိတ်ပိုင်းဆိုင်ရာ ကျန်းမာရေး၏ အရေးပါပုံနှင့် မိမိကိုယ်ကိုယ်နှင့် အခြားသူများကို မည်သို့ကူညီပံ့ပိုးရမည်ကို နားလည်စေမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Global Health",
    "title_en": "Access to Healthcare",
    "title_my": "ကျန်းမာရေးစောင့်ရှောက်မှု လက်လှမ်းမီခြင်း",
    "topics": ["Hospitals and Doctors", "Healthcare Inequality", "Charities"],
    "description_en":
        "Investigate why some parts of the world have better access to healthcare than others.",
    "description_my":
        "ကမ္ဘာ့အချို့နေရာများတွင် ကျန်းမာရေးစောင့်ရှောက်မှုကို အခြားနေရာများထက် အဘယ်ကြောင့် ပိုမိုရရှိနိုင်ကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Health Action Plan",
    "title_my": "ကျန်းမာရေး လှုပ်ရှားမှု စီမံချက်",
    "topics": ["Creating Solutions", "Promoting Hygiene", "Healthy Habits"],
    "description_en":
        "Develop a practical action plan to improve a specific health issue in your school or community.",
    "description_my":
        "ကျောင်း (သို့) ရပ်ကွက်အတွင်းရှိ ကျန်းမာရေးပြဿနာတစ်ခုကို တိုးတက်ကောင်းမွန်စေရန် လက်တွေ့ကျသော လှုပ်ရှားမှုစီမံချက်တစ်ခု ရေးဆွဲမည်။",
  },

  // ================= TERM 5: Education for All =================
  {
    "week": 17,
    "term": 5,
    "theme": "Education",
    "title_en": "The Right to Education",
    "title_my": "ပညာသင်ကြားခွင့်",
    "topics": ["Human Rights", "Importance of Learning", "Literacy Rates"],
    "description_en":
        "Discuss why education is a fundamental human right and how it changes lives.",
    "description_my":
        "ပညာရေးသည် အဘယ်ကြောင့် အခြေခံလူ့အခွင့်အရေးဖြစ်ကြောင်းနှင့် ဘဝများကို မည်သို့ပြောင်းလဲပေးကြောင်း ဆွေးနွေးမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "Education",
    "title_en": "Barriers to Learning",
    "title_my": "သင်ယူမှုဆိုင်ရာ အတားအဆီးများ",
    "topics": ["Poverty", "Gender Inequality", "Conflict Zones"],
    "description_en":
        "Analyze the reasons why millions of children around the world are unable to go to school.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ ကလေးငယ် သန်းပေါင်းများစွာ အဘယ်ကြောင့် ကျောင်းမတက်နိုင်ရသည့် အကြောင်းရင်းများကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "Education",
    "title_en": "Schools Around the World",
    "title_my": "ကမ္ဘာတစ်ဝန်းရှိ ကျောင်းများ",
    "topics": ["Different Curriculums", "School Life", "Global Classrooms"],
    "description_en":
        "Compare your own school experience with what it is like to go to school in different countries.",
    "description_my":
        "မိမိ၏ ကျောင်းအတွေ့အကြုံကို အခြားနိုင်ငံများရှိ ကျောင်းသူကျောင်းသားများ၏ အတွေ့အကြုံများနှင့် နှိုင်းယှဉ်လေ့လာမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "Ideal School Design",
    "title_my": "စံပြကျောင်း ဒီဇိုင်းဆွဲခြင်း",
    "topics": ["Inclusive Education", "Future Learning", "Blueprint"],
    "description_en":
        "Design a blueprint for the 'perfect school' that provides fair access and modern learning for everyone.",
    "description_my":
        "လူတိုင်း တန်းတူသင်ယူနိုင်ပြီး ခေတ်မီသော 'စံပြကျောင်း' တစ်ကျောင်း၏ ဒီဇိုင်းပုံစံကြမ်းကို ရေးဆွဲမည်။",
  },

  // ================= TERM 6: Environment and Sustainability =================
  {
    "week": 21,
    "term": 6,
    "theme": "Environment",
    "title_en": "Climate Change Basics",
    "title_my": "ရာသီဥတုပြောင်းလဲမှု အခြေခံ",
    "topics": ["Global Warming", "Carbon Footprint", "Extreme Weather"],
    "description_en":
        "Understand the science behind climate change and how it is impacting the planet.",
    "description_my":
        "ရာသီဥတုပြောင်းလဲမှု၏ နောက်ကွယ်ရှိ သိပ္ပံပညာနှင့် ကမ္ဘာကြီးအပေါ် မည်သို့သက်ရောက်နေကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Environment",
    "title_en": "Plastic Pollution",
    "title_my": "ပလတ်စတစ် ညစ်ညမ်းမှု",
    "topics": ["Single-Use Plastics", "Ocean Conservation", "Recycling"],
    "description_en":
        "Investigate the global problem of plastic waste and its devastating effect on marine life.",
    "description_my":
        "ကမ္ဘာလုံးဆိုင်ရာ ပလတ်စတစ်အမှိုက် ပြဿနာနှင့် ပင်လယ်တွင်း သက်ရှိများအပေါ် ဆိုးရွားသော သက်ရောက်မှုများကို စူးစမ်းမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Sustainability",
    "title_en": "Sustainable Living",
    "title_my": "ရေရှည်တည်တံ့သော နေထိုင်မှု",
    "topics": ["Renewable Energy", "Reducing Waste", "Eco-friendly Choices"],
    "description_en":
        "Learn how small changes in our daily habits can help protect the Earth for future generations.",
    "description_my":
        "နေ့စဉ်အလေ့အထများတွင် အသေးအမွှား ပြောင်းလဲမှုများပြုလုပ်ခြင်းဖြင့် အနာဂတ်မျိုးဆက်များအတွက် ကမ္ဘာမြေကို မည်သို့ကာကွယ်နိုင်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Eco-Friendly Challenge",
    "title_my": "သဘာဝပတ်ဝန်းကျင် ထိန်းသိမ်းရေး စိန်ခေါ်မှု",
    "topics": ["Taking Action", "Tracking Progress", "Environmental Impact"],
    "description_en":
        "Participate in a week-long challenge to reduce your carbon footprint and report on the results.",
    "description_my":
        "ကာဗွန်ထုတ်လွှတ်မှု လျှော့ချရေးအတွက် တစ်ပတ်ကြာ စိန်ခေါ်မှုတွင် ပါဝင်ပြီး ရလဒ်များကို တင်ပြမည်။",
  },

  // ================= TERM 7: Inequality and Poverty =================
  {
    "week": 25,
    "term": 7,
    "theme": "Economics",
    "title_en": "What is Poverty?",
    "title_my": "ဆင်းရဲမွဲတေမှု ဆိုတာ ဘာလဲ?",
    "topics": ["Basic Needs", "Causes of Poverty", "Cycle of Poverty"],
    "description_en":
        "Define what it means to live in poverty and understand the lack of access to basic needs.",
    "description_my":
        "ဆင်းရဲမွဲတေမှုဆိုသည်မှာ အဘယ်နည်းကို အဓိပ္ပာယ်ဖွင့်ဆိုပြီး အခြေခံလိုအပ်ချက်များ မရရှိခြင်းအကြောင်းကို နားလည်စေမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Inequality",
    "title_en": "Global Inequality",
    "title_my": "ကမ္ဘာလုံးဆိုင်ရာ မညီမျှမှု",
    "topics": ["Wealth Distribution", "Developed vs Developing", "Fairness"],
    "description_en":
        "Analyze the gap between the richest and poorest countries and the concept of global fairness.",
    "description_my":
        "အချမ်းသာဆုံးနှင့် အဆင်းရဲဆုံး နိုင်ငံများအကြား ကွာဟချက်နှင့် ကမ္ဘာလုံးဆိုင်ရာ တရားမျှတမှု သဘောတရားကို ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Solutions",
    "title_en": "Fair Trade",
    "title_my": "တရားမျှတသော ကုန်သွယ်မှု",
    "topics": ["Ethical Shopping", "Farmers' Rights", "Global Supply Chain"],
    "description_en":
        "Learn how buying Fair Trade products can help farmers and workers in developing countries earn a living wage.",
    "description_my":
        "တရားမျှတသော ကုန်သွယ်မှု (Fair Trade) ထုတ်ကုန်များ ဝယ်ယူခြင်းက ဖွံ့ဖြိုးဆဲနိုင်ငံများရှိ လယ်သမားများနှင့် အလုပ်သမားများကို မည်သို့ကူညီပေးနိုင်ကြောင်း လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Charity Pitch",
    "title_my": "ပရဟိတ ရန်ပုံငွေရှာဖွေခြင်း",
    "topics": ["Persuasion", "Fundraising Ideas", "Social Impact"],
    "description_en":
        "Choose a charity that fights poverty and pitch an idea to raise awareness and funds for them.",
    "description_my":
        "ဆင်းရဲမွဲတေမှုကို တိုက်ဖျက်နေသော ပရဟိတအဖွဲ့တစ်ခုကို ရွေးချယ်ပြီး ၎င်းတို့အတွက် ရန်ပုံငွေနှင့် အသိပညာပေးမည့် အကြံဉာဏ်ကို တင်ဆက်မည်။",
  },

  // ================= TERM 8: Culture and Identity =================
  {
    "week": 29,
    "term": 8,
    "theme": "Identity",
    "title_en": "Understanding Culture",
    "title_my": "ယဉ်ကျေးမှုကို နားလည်ခြင်း",
    "topics": ["Language, Food, Art", "Beliefs", "What Shapes Us"],
    "description_en":
        "Explore the different elements that make up a culture and how it shapes who we are.",
    "description_my":
        "ယဉ်ကျေးမှုတစ်ရပ်ကို ဖွဲ့စည်းထားသော အစိတ်အပိုင်းများနှင့် ၎င်းတို့က ကျွန်ုပ်တို့ကို မည်သို့ပုံဖော်ပေးကြောင်း စူးစမ်းမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Identity",
    "title_en": "Identity and Diversity",
    "title_my": "မည်သူမည်ဝါဖြစ်ကြောင်းနှင့် ကွဲပြားစုံလင်မှု",
    "topics": [
      "Personal Identity",
      "Celebrating Differences",
      "Overcoming Stereotypes",
    ],
    "description_en":
        "Discuss what makes your own identity unique and why diversity makes the world a better place.",
    "description_my":
        "မိမိ၏ ကိုယ်ပိုင်လက္ခဏာကို ထူးခြားစေသောအရာများနှင့် ကွဲပြားစုံလင်မှုက ကမ္ဘာကြီးကို အဘယ်ကြောင့် ပိုမိုကောင်းမွန်စေကြောင်း ဆွေးနွေးမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Culture",
    "title_en": "Cultural Traditions",
    "title_my": "ယဉ်ကျေးမှု ဓလေ့ထုံးတမ်းများ",
    "topics": ["Festivals", "Global Heritage", "Preserving History"],
    "description_en":
        "Investigate unique festivals and traditions from different cultures around the globe.",
    "description_my":
        "ကမ္ဘာတစ်ဝန်းရှိ မတူညီသော ယဉ်ကျေးမှုများမှ ထူးခြားသည့် ပွဲတော်များနှင့် ဓလေ့ထုံးတမ်းများကို စူးစမ်းမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Cultural Exchange Fair",
    "title_my": "ယဉ်ကျေးမှု ဖလှယ်ရေး ပွဲတော်",
    "topics": ["Showcasing Culture", "Global Citizenship", "Respect"],
    "description_en":
        "Create a display representing a specific culture to share with your classmates in a 'World Fair'.",
    "description_my":
        "'ကမ္ဘာ့ပွဲတော်' တွင် အတန်းဖော်များနှင့် မျှဝေရန် သီးခြားယဉ်ကျေးမှု တစ်ရပ်ရပ်ကို ကိုယ်စားပြုသော ပြခန်းတစ်ခု ဖန်တီးမည်။",
  },

  // ================= TERM 9: Year Review & Final Project =================
  {
    "week": 33,
    "term": 9,
    "theme": "Review",
    "title_en": "Evaluating Sources",
    "title_my": "အရင်းအမြစ်များကို အကဲဖြတ်ခြင်း",
    "topics": ["Fact-checking Recap", "Cross-referencing", "Data Accuracy"],
    "description_en":
        "Review the critical skill of evaluating information and spotting bias in research.",
    "description_my":
        "အချက်အလက်များကို အကဲဖြတ်ခြင်းနှင့် သုတေသနတွင် ဘက်လိုက်မှုများကို ရှာဖွေခြင်းစသည့် အရေးကြီးသော စွမ်းရည်များကို ပြန်လည်သုံးသပ်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Review",
    "title_en": "Reflecting on Learning",
    "title_my": "သင်ယူမှုကို ပြန်လည်သုံးသပ်ခြင်း",
    "topics": ["Self-Assessment", "Changing Viewpoints", "Global Awareness"],
    "description_en":
        "Reflect on how your perspective on global issues has grown and changed over Year 7.",
    "description_my":
        "Year 7 တစ်နှစ်တာအတွင်း ကမ္ဘာလုံးဆိုင်ရာ ပြဿနာများအပေါ် သင်၏အမြင် မည်သို့ကျယ်ပြန့် ပြောင်းလဲလာကြောင်း ပြန်လည်သုံးသပ်မည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Final Project",
    "title_en": "Planning the Final Project",
    "title_my": "နောက်ဆုံး ပရောဂျက် စီစဉ်ခြင်း",
    "topics": ["Choosing a Global Issue", "Setting Goals", "Independent Work"],
    "description_en":
        "Select a global issue you are passionate about and plan your final independent project.",
    "description_my":
        "သင်စိတ်ဝင်စားသော ကမ္ဘာလုံးဆိုင်ရာ ပြဿနာတစ်ခုကို ရွေးချယ်ပြီး နောက်ဆုံး ကိုယ်ပိုင် ပရောဂျက်ကို စီစဉ်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "Global Perspectives Exhibition",
    "title_my": "ကမ္ဘာ့အမြင် ပြပွဲ",
    "topics": [
      "Presenting Solutions",
      "Action and Reflection",
      "Year 7 Completion",
    ],
    "description_en":
        "Present your final project to the class, proposing a well-researched solution to a global problem.",
    "description_my":
        "ကမ္ဘာလုံးဆိုင်ရာ ပြဿနာတစ်ခုအတွက် သုတေသနပြုထားသော ဖြေရှင်းချက်တစ်ခုကို အဆိုပြု၍ အတန်းရှေ့တွင် နောက်ဆုံးပရောဂျက်ကို တင်ဆက်မည်။",
  },
];
