// File: ai_data_bridge/year7_english_all_terms.dart
// Year 7 English Terms 1 to 9 (Weeks 1-36)
// Generated by Gemini for Future Claude Integration

final List<Map<String, dynamic>> year7EnglishAllTermsData = [
  // ================= TERM 1: Fiction & Creative Writing =================
  {
    "week": 1,
    "term": 1,
    "theme": "Elements of Fiction",
    "title_en": "Story Structure",
    "title_my": "ပုံပြင် ဇာတ်လမ်း ဖွဲ့စည်းပုံ",
    "topics": ["Plot Mountain", "Beginnings and Endings", "Conflict"],
    "description_en":
        "Learn the core structure of storytelling, from the engaging introduction to the final resolution.",
    "description_my":
        "စိတ်ဝင်စားဖွယ် နိဒါန်းမှသည် ဇာတ်သိမ်းအထိ ပုံပြင်ဇာတ်လမ်းများ၏ အခြေခံ ဖွဲ့စည်းပုံကို လေ့လာမည်။",
  },
  {
    "week": 2,
    "term": 1,
    "theme": "Elements of Fiction",
    "title_en": "Character Development",
    "title_my": "ဇာတ်ကောင်စရိုက် ဖန်တီးခြင်း",
    "topics": ["Show, Don't Tell", "Dialogue", "Character Traits"],
    "description_en":
        "Create believable characters by describing their actions, appearance, and using dialogue.",
    "description_my":
        "ဇာတ်ကောင်များ၏ အပြုအမူ၊ အသွင်အပြင်နှင့် အပြောအဆိုများကို သရုပ်ဖော်၍ အသက်ဝင်သော ဇာတ်ကောင်များ ဖန်တီးမည်။",
  },
  {
    "week": 3,
    "term": 1,
    "theme": "Elements of Fiction",
    "title_en": "Setting the Scene",
    "title_my": "ဇာတ်ကွက် နောက်ခံတည်ဆောက်ခြင်း",
    "topics": ["Sensory Details", "Atmosphere", "Descriptive Language"],
    "description_en":
        "Use the five senses and descriptive language to build immersive and realistic settings.",
    "description_my":
        "အာရုံငါးပါးနှင့် အနုစိတ် သရုပ်ဖော်စကားလုံးများကို အသုံးပြု၍ အသက်ဝင်လှပသော ဇာတ်ကွက်နောက်ခံများ တည်ဆောက်မည်။",
  },
  {
    "week": 4,
    "term": 1,
    "theme": "Capstone",
    "title_en": "Write an Adventure",
    "title_my": "စွန့်စားခန်း ဇာတ်လမ်းရေးသားခြင်း",
    "topics": ["Planning", "Drafting", "Editing"],
    "description_en":
        "Combine your skills in plot, character, and setting to write an original adventure story.",
    "description_my":
        "ဇာတ်လမ်း၊ ဇာတ်ကောင်နှင့် နောက်ခံအပြင်အဆင် စွမ်းရည်များကို ပေါင်းစပ်၍ ကိုယ်ပိုင် စွန့်စားခန်း ဇာတ်လမ်းတစ်ပုဒ် ရေးသားမည်။",
  },

  // ================= TERM 2: Non-Fiction & Information =================
  {
    "week": 5,
    "term": 2,
    "theme": "Informational Texts",
    "title_en": "Reading Non-Fiction",
    "title_my": "သုတစာပေများ ဖတ်ရှုခြင်း",
    "topics": ["Text Features", "Main Ideas", "Skimming and Scanning"],
    "description_en":
        "Learn techniques to efficiently extract facts and main ideas from informational texts.",
    "description_my":
        "သုတစာပေများမှ အချက်အလက်များနှင့် အဓိကအကြောင်းအရာများကို ထိရောက်စွာ ထုတ်နုတ်ဖတ်ရှုနည်း လေ့လာမည်။",
  },
  {
    "week": 6,
    "term": 2,
    "theme": "Informational Texts",
    "title_en": "Biographies",
    "title_my": "အတ္ထုပ္ပတ္တိများ",
    "topics": [
      "Third-Person Perspective",
      "Chronological Order",
      "Research Skills",
    ],
    "description_en":
        "Explore how writers tell the life stories of historical and famous figures.",
    "description_my":
        "စာရေးဆရာများသည် သမိုင်းဝင် ပုဂ္ဂိုလ်ကြီးများ၏ ဘဝဇာတ်ကြောင်းများကို မည်သို့ရေးသားကြောင်း လေ့လာမည်။",
  },
  {
    "week": 7,
    "term": 2,
    "theme": "Informational Texts",
    "title_en": "Autobiographies",
    "title_my": "ကိုယ်တိုင်ရေး အတ္ထုပ္ပတ္တိများ",
    "topics": [
      "First-Person Perspective",
      "Personal Reflection",
      "Tone and Voice",
    ],
    "description_en":
        "Analyze how authors write about their own lives and share personal experiences.",
    "description_my":
        "စာရေးသူများက ၎င်းတို့၏ ကိုယ်ပိုင်ဘဝနှင့် အတွေ့အကြုံများကို မည်သို့ရေးသား ဝေမျှကြောင်း ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 8,
    "term": 2,
    "theme": "Capstone",
    "title_en": "Writing a Biography",
    "title_my": "အတ္ထုပ္ပတ္တိ ရေးသားခြင်း",
    "topics": ["Interviewing", "Structuring Facts", "Final Draft"],
    "description_en":
        "Research and write a clear, engaging biography about a person of your choice.",
    "description_my":
        "သင်နှစ်သက်ရာ ပုဂ္ဂိုလ်တစ်ဦးအကြောင်းကို သုတေသနပြု၍ ရှင်းလင်းစိတ်ဝင်စားဖွယ်ကောင်းသော အတ္ထုပ္ပတ္တိတစ်ပုဒ် ရေးသားမည်။",
  },

  // ================= TERM 3: Poetry & Figurative Language =================
  {
    "week": 9,
    "term": 3,
    "theme": "The Art of Poetry",
    "title_en": "Figurative Language",
    "title_my": "တင်စားချက် အသုံးအနှုန်းများ",
    "topics": ["Similes and Metaphors", "Personification", "Imagery"],
    "description_en":
        "Learn to use imaginative language to paint vivid pictures in the reader's mind.",
    "description_my":
        "စာဖတ်သူ၏ စိတ်ကူးထဲတွင် ပုံရိပ်များ ပေါ်လွင်စေရန် စိတ်ကူးယဉ် တင်စားချက်များ အသုံးပြုနည်းကို လေ့လာမည်။",
  },
  {
    "week": 10,
    "term": 3,
    "theme": "The Art of Poetry",
    "title_en": "Rhythm and Rhyme",
    "title_my": "ကာရန် နှင့် အသံသွားအသံလာ",
    "topics": ["Rhyme Schemes", "Meter", "Alliteration and Onomatopoeia"],
    "description_en":
        "Explore how the sound and rhythm of words create musicality in poetry.",
    "description_my":
        "စကားလုံးများ၏ အသံနှင့် ကာရန်များသည် ကဗျာများတွင် ဂီတဆန်သော သံစဉ်များ မည်သို့ဖြစ်ပေါ်စေကြောင်း လေ့လာမည်။",
  },
  {
    "week": 11,
    "term": 3,
    "theme": "The Art of Poetry",
    "title_en": "Different Poetic Forms",
    "title_my": "ကဗျာပုံစံ အမျိုးမျိုး",
    "topics": ["Haiku", "Sonnets", "Free Verse"],
    "description_en":
        "Read and analyze various forms of poetry from different cultures and eras.",
    "description_my":
        "ခေတ်အမျိုးမျိုး၊ ယဉ်ကျေးမှုအမျိုးမျိုးမှ ကဗျာပုံစံများကို ဖတ်ရှုပြီး ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 12,
    "term": 3,
    "theme": "Capstone",
    "title_en": "Poetry Anthology",
    "title_my": "ကဗျာပေါင်းချုပ်",
    "topics": ["Writing Poems", "Editing for Sound", "Performance"],
    "description_en":
        "Create your own collection of poems using the figurative language techniques learned.",
    "description_my":
        "သင်ယူခဲ့သော တင်စားချက် အသုံးအနှုန်းများကို အသုံးပြု၍ ကိုယ်ပိုင် ကဗျာပေါင်းချုပ် တစ်ခု ဖန်တီးမည်။",
  },

  // ================= TERM 4: Drama & Playscripts =================
  {
    "week": 13,
    "term": 4,
    "theme": "Exploring Drama",
    "title_en": "Reading Plays",
    "title_my": "ပြဇာတ်များ ဖတ်ရှုခြင်း",
    "topics": ["Stage Directions", "Acts and Scenes", "Cast of Characters"],
    "description_en":
        "Understand the unique format of scripts written for the stage.",
    "description_my":
        "စင်မြင့်ထက်တွင် ကပြရန် ရေးသားထားသော ပြဇာတ် ဇာတ်ညွှန်းများ၏ ထူးခြားသော ပုံစံကို နားလည်စေမည်။",
  },
  {
    "week": 14,
    "term": 4,
    "theme": "Exploring Drama",
    "title_en": "Introduction to Shakespeare",
    "title_my": "ရှိတ်စပီးယားနှင့် မိတ်ဆက်ခြင်း",
    "topics": ["Elizabethan English", "Shakespeare's World", "Classic Stories"],
    "description_en":
        "Take a beginner's look at the language and stories of William Shakespeare.",
    "description_my":
        "ဝီလျံ ရှိတ်စပီးယား၏ အင်္ဂလိပ်စာ အသုံးအနှုန်းများနှင့် ဂန္ထဝင် ဇာတ်လမ်းများကို စတင်မိတ်ဆက် လေ့လာမည်။",
  },
  {
    "week": 15,
    "term": 4,
    "theme": "Exploring Drama",
    "title_en": "Writing a Scene",
    "title_my": "ဇာတ်ကွက် ရေးသားခြင်း",
    "topics": ["Script Layout", "Dramatic Tension", "Monologues"],
    "description_en":
        "Write your own short script, focusing on formatting and dramatic dialogue.",
    "description_my":
        "ဇာတ်ညွှန်းပုံစံနှင့် အသက်ဝင်သော အပြန်အလှန်ပြောစကားများကို အာရုံစိုက်၍ ကိုယ်ပိုင် ဇာတ်လမ်းတို ရေးသားမည်။",
  },
  {
    "week": 16,
    "term": 4,
    "theme": "Capstone",
    "title_en": "Performing a Scene",
    "title_my": "ဇာတ်ကွက် သရုပ်ဆောင်ခြင်း",
    "topics": ["Voice Projection", "Body Language", "Reader's Theater"],
    "description_en":
        "Bring a script to life by performing it with expression and clear voice projection.",
    "description_my":
        "ရှင်းလင်းသော အသံထွက်၊ ခံစားချက် အပြည့်အဝဖြင့် ဇာတ်ညွှန်းတစ်ခုကို အသက်ဝင်အောင် သရုပ်ဆောင် ကပြမည်။",
  },

  // ================= TERM 5: Persuasive Writing =================
  {
    "week": 17,
    "term": 5,
    "theme": "The Art of Persuasion",
    "title_en": "Fact vs. Opinion",
    "title_my": "အချက်အလက် နှင့် ထင်မြင်ချက်",
    "topics": ["Identifying Bias", "Evidence", "Objective vs Subjective"],
    "description_en":
        "Learn to distinguish between proven facts and personal opinions in texts.",
    "description_my":
        "စာသားများတွင် ပါဝင်သော ခိုင်လုံသည့် အချက်အလက်များနှင့် ကိုယ်ပိုင် ထင်မြင်ယူဆချက်များကို ခွဲခြားသိမြင်စေမည်။",
  },
  {
    "week": 18,
    "term": 5,
    "theme": "The Art of Persuasion",
    "title_en": "Persuasive Techniques",
    "title_my": "ဆွဲဆောင်စည်းရုံးရေး နည်းဗျူဟာများ",
    "topics": ["Rhetorical Questions", "Emotive Language", "Rule of Three"],
    "description_en":
        "Master the powerful language tools writers use to convince their audience.",
    "description_my":
        "စာဖတ်သူများကို ဆွဲဆောင်စည်းရုံးရာတွင် စာရေးဆရာများ အသုံးပြုသည့် အစွမ်းထက်သော ဘာသာစကား နည်းပညာများကို ကျွမ်းကျင်အောင် လေ့လာမည်။",
  },
  {
    "week": 19,
    "term": 5,
    "theme": "The Art of Persuasion",
    "title_en": "Writing a Speech",
    "title_my": "မိန့်ခွန်း ရေးသားခြင်း",
    "topics": [
      "Structuring Arguments",
      "Engaging the Audience",
      "Strong Conclusions",
    ],
    "description_en":
        "Structure a compelling argument and write a persuasive speech on a topic you care about.",
    "description_my":
        "ခိုင်မာသော အငြင်းပွားမှုများကို တည်ဆောက်ပြီး သင်စိတ်ဝင်စားသော အကြောင်းအရာအတွက် ဆွဲဆောင်မှုရှိသော မိန့်ခွန်း ရေးသားမည်။",
  },
  {
    "week": 20,
    "term": 5,
    "theme": "Capstone",
    "title_en": "The Great Debate",
    "title_my": "စကားရည်လုပွဲ",
    "topics": ["Presenting Arguments", "Rebuttals", "Public Speaking"],
    "description_en":
        "Participate in a class debate, presenting arguments clearly and respectfully counter-arguing.",
    "description_my":
        "စကားရည်လုပွဲတွင် ပါဝင်၍ အကြောင်းပြချက်များကို ရှင်းလင်းစွာ တင်ပြခြင်းနှင့် ယဉ်ကျေးစွာ ချေပပြောဆိုခြင်းများ ပြုလုပ်မည်။",
  },

  // ================= TERM 6: Grammar & Vocabulary Mastery =================
  {
    "week": 21,
    "term": 6,
    "theme": "Advanced Grammar",
    "title_en": "Sentence Structures",
    "title_my": "ဝါကျ ဖွဲ့စည်းပုံများ",
    "topics": ["Simple, Compound, Complex", "Conjunctions", "Clauses"],
    "description_en":
        "Improve your writing flow by varying sentence lengths and using complex structures.",
    "description_my":
        "ဝါကျအရှည်အမျိုးမျိုးနှင့် ရှုပ်ထွေးသော ဖွဲ့စည်းပုံများကို အသုံးပြု၍ သင်၏ အရေးအသား အချိတ်အဆက်ကို တိုးတက်စေမည်။",
  },
  {
    "week": 22,
    "term": 6,
    "theme": "Advanced Grammar",
    "title_en": "Punctuation Power",
    "title_my": "ပုဒ်ဖြတ်ပုဒ်ရပ် စွမ်းအား",
    "topics": [
      "Commas and Apostrophes",
      "Speech Marks",
      "Colons and Semicolons",
    ],
    "description_en":
        "Master advanced punctuation to clarify meaning and add effect to your writing.",
    "description_my":
        "စာ၏ အဓိပ္ပာယ်ကို ပိုမိုရှင်းလင်းစေရန်နှင့် ထိရောက်မှုရှိစေရန် အဆင့်မြင့် ပုဒ်ဖြတ်ပုဒ်ရပ် အသုံးပြုနည်းများကို ကျွမ်းကျင်အောင် လေ့လာမည်။",
  },
  {
    "week": 23,
    "term": 6,
    "theme": "Advanced Grammar",
    "title_en": "Vocabulary Building",
    "title_my": "ဝေါဟာရ တည်ဆောက်ခြင်း",
    "topics": [
      "Synonyms and Antonyms",
      "Prefixes and Suffixes",
      "Context Clues",
    ],
    "description_en":
        "Expand your vocabulary and learn how to figure out unknown words using context.",
    "description_my":
        "ဝေါဟာရ ကြွယ်ဝစေရန်နှင့် စာပတ်ဝန်းကျင်ကိုကြည့်၍ မသိသော စကားလုံးများ၏ အဓိပ္ပာယ်ကို ကောက်ချက်ချနည်း လေ့လာမည်။",
  },
  {
    "week": 24,
    "term": 6,
    "theme": "Capstone",
    "title_en": "Grammar and Editing Challenge",
    "title_my": "သဒ္ဒါ နှင့် စာတည်းဖြတ်မှု စိန်ခေါ်ချက်",
    "topics": ["Proofreading", "Correcting Errors", "Refining Style"],
    "description_en":
        "Act as an editor to spot errors and polish written texts to a professional standard.",
    "description_my":
        "စာတည်းမှူးတစ်ဦးအနေဖြင့် အမှားများကို ရှာဖွေပြင်ဆင်ပြီး စာသားများကို အဆင့်အတန်းမီအောင် တည်းဖြတ်မည်။",
  },

  // ================= TERM 7: Media Studies & Journalism =================
  {
    "week": 25,
    "term": 7,
    "theme": "Media and Text",
    "title_en": "News Reports",
    "title_my": "သတင်း တင်ဆက်မှုများ",
    "topics": ["Headlines", "The 5 Ws", "Inverted Pyramid"],
    "description_en":
        "Analyze the structure of newspaper articles and how journalists report events.",
    "description_my":
        "သတင်းစာ ဆောင်းပါးများ၏ ဖွဲ့စည်းပုံနှင့် သတင်းထောက်များ အဖြစ်အပျက်များကို မည်သို့ တင်ဆက်ကြောင်း ခွဲခြမ်းစိတ်ဖြာမည်။",
  },
  {
    "week": 26,
    "term": 7,
    "theme": "Media and Text",
    "title_en": "The Language of Advertising",
    "title_my": "ကြော်ငြာ ဘာသာစကား",
    "topics": ["Target Audience", "Slogans", "Visual Layouts"],
    "description_en":
        "Discover how advertisers use words and images to manipulate consumers and sell products.",
    "description_my":
        "ကြော်ငြာရှင်များသည် စားသုံးသူများကို ဆွဲဆောင်ရန်နှင့် ကုန်ပစ္စည်းရောင်းချရန် စကားလုံးများနှင့် ပုံရိပ်များကို မည်သို့အသုံးပြုကြောင်း လေ့လာမည်။",
  },
  {
    "week": 27,
    "term": 7,
    "theme": "Media and Text",
    "title_en": "Conducting Interviews",
    "title_my": "အင်တာဗျူး ပြုလုပ်ခြင်း",
    "topics": ["Open vs Closed Questions", "Active Listening", "Note-taking"],
    "description_en":
        "Learn how to ask the right questions to get detailed and interesting answers.",
    "description_my":
        "အသေးစိတ်ကျပြီး စိတ်ဝင်စားဖွယ်ကောင်းသော အဖြေများရရှိရန် မှန်ကန်သော မေးခွန်းများ မည်သို့မေးမြန်းရမည်ကို လေ့လာမည်။",
  },
  {
    "week": 28,
    "term": 7,
    "theme": "Capstone",
    "title_en": "Class Newspaper",
    "title_my": "အတန်းတွင်း သတင်းစာ",
    "topics": ["Writing Articles", "Formatting", "Editorial Roles"],
    "description_en":
        "Collaborate to write, edit, and design a front page for a class newspaper.",
    "description_my":
        "အတန်းတွင်း သတင်းစာတစ်စောင်၏ မျက်နှာဖုံးအတွက် ဆောင်းပါးများရေးသားခြင်း၊ တည်းဖြတ်ခြင်းနှင့် ဒီဇိုင်းဆွဲခြင်းတို့ကို ပူးပေါင်းလုပ်ဆောင်မည်။",
  },

  // ================= TERM 8: Modern Fiction & Book Reviews =================
  {
    "week": 29,
    "term": 8,
    "theme": "Literature Study",
    "title_en": "Exploring Modern Themes",
    "title_my": "ခေတ်သစ် အကြောင်းအရာများကို စူးစမ်းခြင်း",
    "topics": ["Dystopian Fiction", "Coming of Age", "Fantasy"],
    "description_en":
        "Read excerpts from modern youth literature and discuss their underlying themes.",
    "description_my":
        "ခေတ်သစ် လူငယ်စာပေများမှ ကောက်နုတ်ချက်များကို ဖတ်ရှုပြီး ၎င်းတို့၏ အဓိက ဆိုလိုရင်းများကို ဆွေးနွေးမည်။",
  },
  {
    "week": 30,
    "term": 8,
    "theme": "Literature Study",
    "title_en": "Analyzing Plot Twists",
    "title_my": "လှည့်ကွက်များကို ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "topics": ["Foreshadowing", "Pacing", "Suspense"],
    "description_en":
        "Understand how authors build suspense and drop hints before a major plot twist.",
    "description_my":
        "စာရေးဆရာများသည် ဇာတ်လမ်းမလှည့်မီ စိတ်ဝင်စားမှုများကို မည်သို့တည်ဆောက်ပြီး အရိပ်အမြွက်များ မည်သို့ပေးကြောင်း နားလည်စေမည်။",
  },
  {
    "week": 31,
    "term": 8,
    "theme": "Literature Study",
    "title_en": "Writing a Book Review",
    "title_my": "စာအုပ် သုံးသပ်ချက် ရေးသားခြင်း",
    "topics": ["Summarizing", "Expressing Opinions", "Rating Systems"],
    "description_en":
        "Learn to write a structured review that summarizes the plot and critiques the writing.",
    "description_my":
        "ဇာတ်လမ်းကို အကျဉ်းချုပ်ပြီး အရေးအသားကို ဝေဖန်သုံးသပ်ထားသော စနစ်ကျသည့် စာအုပ်သုံးသပ်ချက် ရေးသားနည်းကို လေ့လာမည်။",
  },
  {
    "week": 32,
    "term": 8,
    "theme": "Capstone",
    "title_en": "Literary Critic",
    "title_my": "စာပေ ဝေဖန်ရေးသမား",
    "topics": [
      "Presenting Reviews",
      "Recommending Books",
      "Literary Discussions",
    ],
    "description_en":
        "Present your book review to the class and defend your critique as a literary critic.",
    "description_my":
        "သင်၏ စာအုပ်သုံးသပ်ချက်ကို အတန်းရှေ့တွင် တင်ပြပြီး စာပေဝေဖန်ရေးသမားတစ်ဦးအနေဖြင့် သင်၏အမြင်ကို ကာကွယ်ဆွေးနွေးမည်။",
  },

  // ================= TERM 9: Communication & Year 7 Project =================
  {
    "week": 33,
    "term": 9,
    "theme": "Spoken English",
    "title_en": "The Art of Storytelling",
    "title_my": "ပုံပြင်ပြောခြင်း အနုပညာ",
    "topics": ["Oral Tradition", "Pacing and Tone", "Engaging Listeners"],
    "description_en":
        "Practice the ancient art of telling stories aloud without reading from a script.",
    "description_my":
        "ဇာတ်ညွှန်းမဖတ်ဘဲ အသံထွက်၍ ပုံပြင်ပြောပြခြင်း ဟူသော ရှေးဟောင်းအနုပညာကို လေ့ကျင့်မည်။",
  },
  {
    "week": 34,
    "term": 9,
    "theme": "Spoken English",
    "title_en": "Effective Presentations",
    "title_my": "ထိရောက်သော တင်ဆက်မှုများ",
    "topics": ["Visual Aids", "Eye Contact", "Handling Questions"],
    "description_en":
        "Learn how to deliver a confident presentation using visual aids effectively.",
    "description_my":
        "အထောက်အကူပြု ပုံရိပ်များကို ထိရောက်စွာ အသုံးပြု၍ ယုံကြည်မှုရှိစွာ တင်ဆက်နည်းကို လေ့လာမည်။",
  },
  {
    "week": 35,
    "term": 9,
    "theme": "Year 7 Review",
    "title_en": "English Skills Revision",
    "title_my": "English စွမ်းရည်များ ပြန်လည်လေ့ကျင့်ခြင်း",
    "topics": ["Grammar Recap", "Writing Styles", "Comprehension Practice"],
    "description_en":
        "Review the most important reading, writing, and grammar skills learned throughout Year 7.",
    "description_my":
        "Year 7 တစ်နှစ်တာလုံး သင်ယူခဲ့သော အရေးကြီးဆုံး ဖတ်ရှုခြင်း၊ ရေးသားခြင်းနှင့် သဒ္ဒါစွမ်းရည်များကို ပြန်လည်လေ့ကျင့်မည်။",
  },
  {
    "week": 36,
    "term": 9,
    "theme": "Capstone",
    "title_en": "The Anthology Project",
    "title_my": "စာပေလက်ရာများ စုစည်းမှု ပရောဂျက်",
    "topics": ["Portfolio Assembly", "Reflection", "Final Showcase"],
    "description_en":
        "Compile your best writing from the year into a final portfolio and reflect on your progress.",
    "description_my":
        "တစ်နှစ်တာလုံး ရေးသားခဲ့သော အကောင်းဆုံး လက်ရာများကို စုစည်း၍ သင်၏ တိုးတက်မှုကို ပြန်လည်သုံးသပ် တင်ဆက်မည်။",
  },
];
